### ISSUE TITLE
 error LNK2019: "class nvinfer1::IRuntime" win10 cmake failure of TensorRT 8.6

### ISSUE THREAD

**Issue by HorseJson** [NVIDIA/TensorRT#3833] opened 2024-04-28 09:31 UTC
cmake sampleEngines.cpp，ERROR“[build] sampleEngines.obj : error LNK2019: 无法解析的外部符号 "class nvinfer1::IRuntime * __cdecl createRuntime(void)" (?createRuntime@@YAPEAVIRuntime@nvinfer1@@XZ)，函数 "public: class nvinfer1::ICudaEngine * __cdecl sample::LazilyDeserializedEngine::get(void)" (?get@LazilyDeserializedEngine@sample@@QEAAPEAVICudaEngine@nvinfer1@@XZ) 中引用了该符号 [D:\00DaittoCode\TensorRTOfficial\release_10.0\engine\build\TRT.vcxproj]”

Sure add nvinfer.lib successfully

**Comment by lix19937** [comment] 2024-04-29 15:00
make sure ld lib path , ld lib name.

**Comment by HorseJson** [comment] 2024-04-30 07:07
Thank for your assignment. The problem is solution. 
add_executable(TRT  
                samples/common/logger.cpp 
                samples/common/sampleEngines.cpp 
                samples/common/sampleInference.cpp 
                samples/common/sampleOptions.cpp 
                samples/common/sampleReporting.cpp 
                samples/common/sampleUtils.cpp 
                ) will error LNK2019: unresolved external symbol "class nvinfer1::IBuilder * __cdecl createBuilder(void)" and so on.
  add_executable(TRT  
                samples/common/logger.cpp 
                samples/common/sampleEngines.cpp 
                samples/common/sampleInference.cpp 
                samples/common/sampleOptions.cpp 
                samples/common/sampleReporting.cpp 
                samples/common/sampleUtils.cpp 

                )

**Comment by zerollzeng** [comment] 2024-05-03 13:48
I'm closing this as the problem is solved, feel free to reopen if you have any further questions.

**Comment by ttyio** [comment] 2024-07-02 16:58
closing since no activity for more than 3 weeks, pls reopen if you still have question, thanks all!

**Closed by ttyio** 2024-07-02 16:58 UTC
Labels: triaged
