### ISSUE TITLE
Tensorrt run slower than pytorch

### ISSUE THREAD

**Issue by safehumeng** [NVIDIA/TensorRT#2951] opened 2023-05-10 02:02 UTC
**TensorRT Version: 8.5.3.1:

**NVIDIA GPU Quadro: RTX 6000:

**NVIDIA Driver Version: 510.73.05

**CUDA Version: 12.1

Python Version: 3.8.10

PyTorch Version: 2.0

--------------------------------------------------
model:
--------------------------------------------------
class TestNet(nn.Module):
    def __init__(self, ):
        super(TestNet, self).__init__()
        self.query_e = torch.nn.Linear(
            768,
            3072,
            bias=True,
            dtype=torch.float16)
    def forward(self, x):
        y = self.query_e(x)
        return y
--------------------------------------------------

convert torch.nn.Linear to tensorrt, run slower than pytorch
(1)torch.nn.Linear.in_features=4096, torch.nn.Linear.out_features=3 * 16384
torch: 3ms,onnx: 33ms,trt:13ms
(2)torch.nn.Linear.in_features=4096, torch.nn.Linear.out_features=16384
torch:1ms,onnx: 8ms,trt:4ms
(3)torch.nn.Linear.in_features=768, torch.nn.Linear.out_features=3072
torch:0.4ms,onnx: 1ms,trt:0.5ms
(3)torch.nn.Linear.in_features=768, torch.nn.Linear.out_features=768
torch:0.4ms,onnx: 0.6ms,trt:0.5ms

**Comment by zerollzeng** [comment] 2023-05-11 12:31
How do you calculate the inference time of each framework? for a single os it's very unlikely that TRT will be slower than Pytorch, we've seen similar bug report before and nearly all of them caused by incorrect time calculation.

**Comment by safehumeng** [comment] 2023-05-15 00:37
> How do you calculate the inference time of each framework? for a single os it's very unlikely that TRT will be slower than Pytorch, we've seen similar bug report before and nearly all of them caused by incorrect time calculation.

import torch
import torch.nn as nn
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'

class TestNet(nn.Module):
    def __init__(self, ):
        super(TestNet, self).__init__()
        self.query_e = torch.nn.Linear(
            768,
            3072,
            bias=True,
            dtype=torch.float16)
    def forward(self, x):
        y = self.query_e(x)
        return y


if __name__ == '__main__':
    import numpy as np
    hidden_states_np = np.ones((1, 422, 768), dtype=np.float16)
    model = TestNet().cuda()
    hidden_states = torch.tensor(hidden_states_np).cuda()
    y = model(hidden_states)
    print(y)
    
    import time
    for i in range(0, 30):
        s_time = time.time()
        hidden_states = torch.tensor(hidden_states_np).cuda()
        y = model(hidden_states)
        print("torch time", time.time() - s_time)
    print("ttttttttttt")
    from torch2trt import torch2trt
    model_trt = torch2trt(model, [hidden_states])

    for i in range(0, 30):
        s_time = time.time()
        hidden_states = torch.tensor(hidden_states_np).cuda()
        y = model_trt(hidden_states)
        print("trt_time", time.time() - s_time)
    print("yyyyyyyyyyyy")

    torch.onnx.export(model,  # model being run self.model.half()
                      (hidden_states),
                      # model input (or a tuple for multiple inputs)
                      "model.onnx",  # where to save the model
                      export_params=True,  # store the trained parameter weights inside the model file
                      opset_version=13,  # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names=['hidden_states'],  # the model's input names
                      output_names=['y'],  # the model's output names
                      dynamic_axes={'hidden_states': {0: 'batch_size'},  # variable length axes
                                    'y': {0: 'batch_size'},
                                    }
                      )

    import onnxruntime as ort

    sess = ort.InferenceSession("model.onnx",
                                providers=['CUDAExecutionProvider'])
    input_names = [input_t.name for input_t in sess.get_inputs()]
    print(input_names)
    output_names = [output.name for output in sess.get_outputs()]
    print(output_names)
    input_data = {"hidden_states": hidden_states_np}
    outputs = sess.run(output_names, input_data)
    print(outputs)
    import time

    for i in range(0, 30):
        s_time = time.time()
        outputs = sess.run(output_names, input_data)
        print("onnx", time.time() - s_time)

**Comment by safehumeng** [comment] 2023-05-15 06:55
> How do you calculate the inference time of each framework? for a single os it's very unlikely that TRT will be slower than Pytorch, we've seen similar bug report before and nearly all of them caused by incorrect time calculation.

I find that fp16-model need param fp16_mode=True
use 
model_trt = torch2trt(model, [hidden_states], fp16_mode=True) 
torch 2.8ms trt 2.2ms

I do TestNet(torch.nn.Linear) test because 
convert chatglm(https://github.com/THUDM/ChatGLM-6B) to tensorrt
run slower than pytorch（num_layers set 2, torch 13ms  trt 32ms）
then find out which op caused the inference time to be abnormal 
 
use torch.onnx.export convert to onnx，
then use /usr/src/tensorrt/bin/trtexec --fp16  --onnx=./save_onnx/chatglm.onnx --saveEngine=./trt/model.plan --verbose
convert to tensorrt

**Comment by zerollzeng** [comment] 2023-05-16 15:15
Are your miss the torch.cuda.synchronize()? after each inference?
Also `print(time.time() - s_time)` calculate time in seconds.

**Comment by safehumeng** [comment] 2023-05-18 08:48
> Are your miss the torch.cuda.synchronize()? after each inference? Also `print(time.time() - s_time)` calculate time in seconds.

add torch.cuda.synchronize() 
torch time not change
Is tensorRt's effect related to model's parameter num or matrix size

**Comment by zerollzeng** [comment] 2023-05-18 10:29
> (1)torch.nn.Linear.in_features=4096, torch.nn.Linear.out_features=3 * 16384

Can you provide a reproduce code for this case? Thanks!

**Comment by safehumeng** [comment] 2023-05-18 11:42
> > (1)torch.nn.Linear.in_features=4096, torch.nn.Linear.out_features=3 * 16384
> 
> Can you provide a reproduce code for this case? Thanks!

It's usage error
need "fp16_mode=True"
use 
model_trt = torch2trt(model, [hidden_states], fp16_mode=True)
torch 2.8ms trt 2.2ms

**Comment by ttyio** [comment] 2023-06-06 04:29
closing since according to last comment, TRT is faster than torch, thanks all!

**Closed by ttyio** 2023-06-06 04:29 UTC
Labels: triaged
