### ISSUE TITLE
UffParser: Unsupported operation _GridAnchorRect_TRT

### ISSUE THREAD

**Issue by edumotya** [NVIDIA/TensorRT#807] opened 2020-09-30 07:19 UTC
## Description

I started from the container [nvcr.io/nvidia/deepstream-l4t:5.0-20.07-base](nvcr.io/nvidia/deepstream-l4t:5.0-20.07-base) and I used python to create the plugin MultipleGridAnchorGenerator with the operation GridAnchorRect_TRT for rectangular anchors. However, the uffparser complains about this operation:

`[TensorRT] ERROR: UffParser: Validator error: MultipleGridAnchorGenerator: Unsupported operation _GridAnchorRect_TRT`

I am creating the plugin node using this code:

```
PriorBox = gs.create_plugin_node(
        name="MultipleGridAnchorGenerator",
        op="GridAnchorRect_TRT",
        minSize=0.2,
        maxSize=0.95,
        aspectRatios=[1.0, 2.0, 0.5, 3.0, 0.33],
        variance=[0.1, 0.1, 0.2, 0.2],
        featureMapShapes=[40, 23, 20, 12, 10, 6, 5, 3, 3, 2, 2, 1],
        numLayers=6,
)
```

I also tried to [rebuild the TensorRT OSS components on Jetson](https://github.com/NVIDIA/TensorRT#building-the-tensorrt-oss-components) from the master branch, with no success, the error was the same.

Am I doing something wrong? Do you have any clues? 

## Environment

**TensorRT Version**: 7.1.3
**GPU Type**: Jetson TX2
**Operating System + Version**: Ubuntu 18
**Baremetal or Container (which commit + image + tag)**: nvcr.io/nvidia/deepstream-l4t:5.0-20.07-base

**Comment by bultmann-s** [comment] 2021-03-29 15:18
Are there any updates on this ? I am facing the same issue.

**Comment by DemolationPeter** [comment] 2021-04-01 16:20
I solved the issue two months back. I try to explain it but I can't remember all steps exactly. Probably you will get erros on the way.
I will try to reproduce these steps in the next couple of days.

 I think the Problem was that in this file from the TensorRT OSS package the **"GridAnchorRect_TRT"** option was missing. They fixed it but you have to install the TensorRT OSS plugin manually to get the update for TensorRT 7.1. In this file you can find the added option: https://github.com/NVIDIA/TensorRT/blob/master/plugin/gridAnchorPlugin/gridAnchorPlugin.cpp

My steps to install the fixed files are the follwing:


**1. Install newer cmake version
You have to install a more recent cmake version, because the actual version on the nano is to old to build TensorRT OSS 7.1. I used cmake 1.17.4. You can download the version form there website. 
1.1 .
Remove old cmake version: `sudo apt remove cmake`   
open folder new cmake version:
`./configure`
`make`
`sudo make install`

Know you should have the newer version

**2. Download the TensoRT OSSS 7.1 repository**
https://github.com/NVIDIA/TensorRT/tree/release/7.1

**2.1 Open the folder TensorRT inside the Terminal:**

I had a lot of trouble to install it but I got help from Nvidia. (https://forums.developer.nvidia.com/t/install-tensorrt-oss-error-make-2-waiting-for-unfinished-jobs/166956)

`mkdir -p build && cd build`
`cmake .. -DGPU_ARCHS="53"  -DTRT_LIB_DIR=/usr/lib/aarch64-linux-gnu/ -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc`
`make -j$(nproc)`

This will take quite some time and at the end you should have some foldersand files in the \build folder. 
There should be 3 important files:
libnvinfer_plugin.so
libnvinfer_plugin.so.7
libnvinfer_plugin.so.7.1.3

As far as I can remember, these files are libarys and contain the fix for rectangular bounding boxes.

**3. Copy new libarys to nano**
I copied these three files from the \build folder to \usr/lib/aarch64-linux-gnu on the Nano and replaced the current ones.

I also installed:
`sudo apt-get install python3-libnvinfer-dev`
`sudo apt-get install uff-converter-tf`
`sudo apt-get install onnx-graphsurgeon`

 I'm not sure why .exactly


**4. Start Docker image**
`sudo docker pull nvcr.io/nvidia/l4t-ml:r32.5.0-py3`

`sudo docker run -it --rm -v /home/nano/Dokumente/uff_files:/uff_files --runtime nvidia --network host nvcr.io/nvidia/l4t-ml:r32.5.0-py3`

In the -v Option you have to enter the path to the folder with the files for the uff_conversion. Know you should be able to convert the .pb files from Tensorflow. 

**5. deepstream**  

Then I cpoied from the deepstream container the \sample and  \source folders on the nano. 
Inside the /samples/configs/deepstream-app/nvdsinfer_custom_impl_ssd open the Makefile
**4.1 Chages in Makefile:** Use your own Path!!!
CFLAGS+= -I../../includes -I/usr/local/cuda-$(CUDA_VER)/include -I/home/nano-40068618/.../.../deepstream/sources/includes

LIBS:= -lnvinfer -lnvparsers -L/usr/local/cuda-$(CUDA_VER)/lib64 -lcudart -lcublas -L//home/nano-40068618/.../.../deepstream/sources/libs

Than open the folder in the Terminal and type `make`
You need these libary so that deepstream can draw the bounding boxes I think.

**Comment by bultmann-s** [comment] 2021-04-01 16:54
I also solved this issue for my setup in the meantime, by re-building TensorRT OSS from the master branch.
(in my case, I built directly on the Jetson NX).

The updated plugins become available after setting the LD_LIBRARY_PATH
`export LD_LIBRARY_PATH=/home/jetson/TensorRT/build/out:$LD_LIBRARY_PATH`
(This may be a little safer than replacing the libraries as  in @DemolationPeter's answer step 3)

However, I still needed to update two files of the GridAnchor-Plugin for rectangular input images to be handled correctly:

```
diff --git a/plugin/common/kernels/gridAnchorLayer.cu b/plugin/common/kernels/gridAnchorLayer.cu                                                                                                                                                    
index 3162b9b..7ad3baf 100644                                                                                                                                                                                                                       
--- a/plugin/common/kernels/gridAnchorLayer.cu                                                                                                                                                                                                      
+++ b/plugin/common/kernels/gridAnchorLayer.cu                                                                                                                                                                                                      
@@ -34,8 +34,10 @@ __launch_bounds__(nthdsPerCTA) __global__ void gridAnchorKernel(const GridAnchor                                                                                                                                                 
      * the image Every coordinate will go back to the pixel coordinates in the input image if being multiplied by                                                                                                                                  
      * image_input_size Here we implicitly assumes the image input and feature map are square                                                                                                                                                      
      */                                                                                                                                                                                                                                            
-    float anchorStride = (1.0 / param.H);                                                                                                                                                                                                          
-    float anchorOffset = 0.5 * anchorStride;                                                                                                                                                                                                       
+    float anchorStride_h = (1.0 / param.H);
+    float anchorOffset_h = 0.5 * anchorStride_h;
+    float anchorStride_w = (1.0 / param.W);
+    float anchorOffset_w = 0.5 * anchorStride_w;
 
     int tid = blockIdx.x * blockDim.x + threadIdx.x;
     if (tid >= dim)
@@ -47,8 +49,8 @@ __launch_bounds__(nthdsPerCTA) __global__ void gridAnchorKernel(const GridAnchor
     const int h = currIndex / param.W;
 
     // Center coordinates
-    float yC = h * anchorStride + anchorOffset;
-    float xC = w * anchorStride + anchorOffset;
+    float yC = h * anchorStride_h + anchorOffset_h;
+    float xC = w * anchorStride_w + anchorOffset_w;
 
     // x_min, y_min
     float xMin = xC - 0.5 * widths[arId];
diff --git a/plugin/gridAnchorPlugin/gridAnchorPlugin.cpp b/plugin/gridAnchorPlugin/gridAnchorPlugin.cpp
index cb52a4e..7a2ada5 100644
--- a/plugin/gridAnchorPlugin/gridAnchorPlugin.cpp
+++ b/plugin/gridAnchorPlugin/gridAnchorPlugin.cpp
@@ -109,11 +109,12 @@ GridAnchorGenerator::GridAnchorGenerator(const GridAnchorParameters* paramIn, in
 
         std::vector<float> tmpWidths;
         std::vector<float> tmpHeights;
+        float featMapAspectRatio = (float)(mParam[id].H) / (float)(mParam[id].W);
         // Calculate the width and height of the prior boxes
         for (int i = 0; i < mNumPriors[id]; i++)
         {
             float sqrt_AR = sqrt(aspect_ratios[i]);
-            tmpWidths.push_back(scales[i] * sqrt_AR);
+            tmpWidths.push_back(scales[i] * sqrt_AR * featMapAspectRatio);
             tmpHeights.push_back(scales[i] / sqrt_AR);
         }

```

**Comment by ttyio** [comment] 2021-04-30 06:21
Cool, seems the issue is solved and I will close this, thanks!

**Closed by ttyio** 2021-04-30 06:21 UTC
Labels: Component: Plugins, Component: UFF, good-reference
