### ISSUE TITLE
Can onnx parser use custom plugin?

### ISSUE THREAD

**Issue by cuijianaaa** [NVIDIA/TensorRT#112] opened 2019-09-09 11:58 UTC
Can onnx parser use custom plugin? I have found an example using caffe parser "samplePlugin" and an example using uff parser "sampleUffSSD", but dose it now support onnx parser plugin ?

**Comment by rmccorm4** [comment] 2020-01-26 00:47
Duplicate of #6, please track there. We're looking into providing samples for ONNX + plugins.

**Closed by rmccorm4** 2020-01-26 00:47 UTC
Labels: Parser: ONNX, enhancement, help wanted, plugin, sample

**Comment by cuijianaaa** [comment] 2020-01-26 03:35
Thanks!



发自我的iPhone


------------------ Original ------------------
