### ISSUE TITLE
Much lower performance after Int8 PTQ,  a point cloud detector

### ISSUE THREAD

**Issue by bigsheep2012** [NVIDIA/TensorRT#1691] opened 2021-12-27 10:05 UTC
## Description

I followed the official int8 PTQ example here: [sampleINT8](https://github.com/NVIDIA/TensorRT/tree/release/7.1/samples/opensource/sampleINT8) 

The model is a pretrained FP32 pytorch model which has been converted to an onnx file. 
But get a quite different result compared with the fp32 mode.
Specifically, the classification task works fine while the regression task works terrible (the boxes are quite smaller)

I am not sure if I miss something or the result is the best PTQ can achieve. It would be nice if there is an official int8 PTQ example with an onnx model and a detection algorithm. 

BTW, i am using batch_size =1 to create the calibration table (traverse the calibration dataset one by one), would it matter?

Illustration:
FP32 inference:
![image](https://user-images.githubusercontent.com/3154368/147460508-21abce07-6651-407a-927e-974da3365fcc.png)

INT8 inference:
![image](https://user-images.githubusercontent.com/3154368/147460816-d649b1fd-90fe-46ab-8dd5-77343b2c4b25.png)

## Environment

**TensorRT Version**: 7.1.3
**NVIDIA GPU**: Quadro P4000
**NVIDIA Driver Version**:  470.86
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.4
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.7
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.9

**Baremetal or Container (if so, version)**: 

## Relevant Files
please check the attachment for my code and data.
[demo.zip](https://github.com/NVIDIA/TensorRT/files/7779909/demo.zip)

## Steps To Reproduce
1. re-implement the batchstream.h as a customized dataloader, each time getbatch() is called, I load a pointcloud file and extract feature
2. the rest is quite similar to the original [sampleINT8](https://github.com/NVIDIA/TensorRT/tree/release/7.1/samples/opensource/sampleINT8)

**Comment by bigsheep2012** [comment] 2022-01-07 08:15
Hello @ttyio, I finally figured out how to alleviate the issue:

For the generated calibrationTable,  I just modify the word "input1" to "input" and the "output1" to "output", and everything seems fine now.  

Here is the code I used to export the onnx file:
`torch.onnx.export(model, dummy_input, "demo_op9.onnx", opset_version=9, input_names= ['input1'], output_names = ['output1'], verbose=False)`

I tried something like: change the parameters "input_names = ['input1']" to "input_names = ['input']", but still I need to change the content inside the calibration table accordingly.

May I know what is happening behind this fact?
It seems I did something wrong when I try to export a .pth file to onnx with pytorch or to generate the calibration table  
 
Thanks in advance,
LIn

**Comment by ttyio** [comment] 2022-01-07 09:52
Cool! 
Thanks @bigsheep2012 for this analysis, sounds like a 7.1 bug, have you tried 8.2 release?

**Comment by bigsheep2012** [comment] 2022-01-14 07:40
Hello @ttyio
Sorry for coming back a little bit late.

I have checked 8.2.2 release, found the followings:
1) do PTQ directly, I get the similar low performance result as mentioned in the first post.
2) do PTQ and modify the calibration table generated by trt8.2.2, cannot get the normal result anymore (like what i have done with TensorRT 7.1.3)
3) Use the correct calibration table generated by TensorRT 7.1.3 and do int8 PTQ inference with TensorRT 8.2.2, get the similar low performance result as mentioned in the first post.

The accurate TensorRT version is : TensorRT 8.2 GA Update 1(TensorRT-8.2.2.1.Linux.x86_64-gnu.cuda-10.2.cudnn8.2.tar.gz)
The download link: https://developer.nvidia.com/nvidia-tensorrt-8x-download 

Please let me know, if there is anything I can try to fix it.

**Comment by ttyio** [comment] 2022-01-20 05:04
Great @bigsheep2012 you root cause the issue , and yes, the calibration table contains `scales` used for INT8, and we will fallback to fp32 if there is no `scale`, thanks

**Comment by ttyio** [comment] 2022-03-01 01:03
I will close this issue since this is solved, thanks!

**Closed by ttyio** 2022-03-01 01:03 UTC
Labels: Samples, Release: 7.x, triaged, Topic: PTQ

**Comment by ynma-hanvo** [comment] 2023-11-29 03:47
> @ttyio well, the solution for 8.2.2 is found. After modifying the calibration table's parameters of the last several layers (need to modify more layers compared to trt7.1.3), the better result is achieved. I guess the mentioned issue is not a bug as it seems the inference go back to fp32 mode after tensorRT cannot find the modified layer's name in the calibration table. Thus, in fact, we are doing IN8 inference without the last several layers.
> 
> Could you plz help confirm whether the inference of some layer go back to fp32 mode if the calibration table's corresponding layer's name is modified or deleted?

hi, so you mean that you did run  int8 model correctly with the expected results (same as fp32)? 
but your exported names is input1,  you changed input1 to input in calib data,  that sounds the scale will be missed and default to fp32?
