### ISSUE TITLE
Convert ONNX model with INT8 mode failed.

### ISSUE THREAD

**Issue by ShawnNew** [NVIDIA/TensorRT#344] opened 2020-01-19 04:45 UTC
## Description

I tested to convert an onnx model (which was successfully converted to fp16 engine before) to int8 mode, but the conversion failed on the calibration process.
The error is mainly `Cuda Error in free: 700`.

## Environment

**TensorRT Version**: 6.0.1.5
**GPU Type**: 2080ti
**Nvidia Driver Version**: 418.56
**CUDA Version**: 10.1
**CUDNN Version**: 7
**Operating System + Version**: ubuntu 16.04
**Python Version (if applicable)**: 3.7(miniconda)
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.3.1
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

Model can be found [here](https://drive.google.com/open?id=1G1mzRDWvuIN0qQhydO7LoyXBxueWbauJ).

The implementation of IInt8EntropyCalibrator2 and stream is as following:
```python
import pycuda.driver as cuda
import pycuda.autoinit
import numpy as np
from PIL import Image
import tensorrt as trt
import os

CHANNEL = 3
HEIGHT = 800
WIDTH = 1344

__all__ = [
    'PythonEntropyCalibrator',
    'ImageBatchStream'
]

class PythonEntropyCalibrator(trt.IInt8EntropyCalibrator2):
    def __init__(self, input_layers, stream, cache_file):
        super(PythonEntropyCalibrator, self).__init__()
        # trt.infer.EntropyCalibrator.__init__(self)
        self.input_layers = input_layers
        self.stream = stream
        self.d_input = cuda.mem_alloc(self.stream.calibration_data.nbytes)
        self.cache_file = cache_file
        stream.reset()

    def get_batch_size(self):
        return self.stream.batch_size

    def get_batch(self, names):
        try:
            batch = self.stream.next_batch()
            if not batch.size:   
                return None

            cuda.memcpy_htod(self.d_input, batch)
            return [int(self.d_input)]

        except StopIteration:
            # When we're out of batches, we return either [] or None.
            # This signals to TensorRT that there is no calibration data remaining.
            return None

    def read_calibration_cache(self):
        # If there is a cache, use it instead of calibrating again. Otherwise, implicitly return None.
        if os.path.exists(self.cache_file):
            with open(self.cache_file, "rb") as f:
                return f.read()

    def write_calibration_cache(self, cache):
        # cache = ctypes.c_char_p(int(ptr))
        with open(self.cache_file, 'wb') as f:
            f.write(cache)

class ImageBatchStream():
    def __init__(self, batch_size, data_dir, data_type, calibration_files, preprocessor):
        self.data_dir = data_dir
        self.data_type = data_type
        self.batch_size = batch_size
        self.max_batches = len(calibration_files) // batch_size + \
                       (1 if len(calibration_files) % batch_size \
                        else 0)
        self.files = calibration_files
        self.calibration_data = np.zeros((batch_size, CHANNEL, HEIGHT, WIDTH), \
                                     dtype=np.float32)
        self.batch = 0
        self.preprocessor = preprocessor

    @staticmethod
    def read_image_chw(path):
        img = Image.open(path).resize((WIDTH,HEIGHT), Image.NEAREST)
        im = np.array(img, dtype=np.float32, order='C')
        im = im[:,:,::-1]
        im = im.transpose((2,0,1))
        return im
         
    def reset(self):
        self.batch = 0
     
    def next_batch(self):
        if self.batch < self.max_batches:
            imgs = []
            files_for_batch = self.files[self.batch_size * self.batch : \
                            self.batch_size * (self.batch + 1)]
            for f in files_for_batch:
                file_name = f['file_name']
                file_path = '%s/images/%s/%s'%(self.data_dir, self.data_type, file_name)
                # print("[ImageBatchStream] Processing ", file_path)
                img = ImageBatchStream.read_image_chw(file_path)
                img = self.preprocessor(img)
                imgs.append(img)
            for i in range(len(imgs)):
                self.calibration_data[i] = imgs[i]
            self.batch += 1
            print('[ImageBatchStream] Get batch done.')
            return np.ascontiguousarray(self.calibration_data, dtype=np.float32)
        else:
            return np.array([])
```

## Steps To Reproduce

* Set `builder.int8_mode = True`.
* Set `builder.int8_calibrator = int8_calibrator`, in this case int8_calibrator is an object of above `PythonEntropyCalibrator` class.

## Error log
```
[TensorRT] INFO: Starting Calibration with batch size 5.
[ImageBatchStream] Get batch done.
[TensorRT] WARNING: Explicit batch network detected and batch size specified, use execute without batch size instead.
[TensorRT] ERROR: engine.cpp (529) - Cuda Error in commonEmitTensor: 1 (invalid argument)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
[TensorRT] ERROR: engine.cpp (529) - Cuda Error in commonEmitTensor: 1 (invalid argument)
[TensorRT] ERROR: FAILED_ALLOCATION: std::exception
[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (334) - Cuda Error in execute: 1 (invalid argument)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
[TensorRT] INFO:   Calibrated batch 0 in 0.000703608 seconds.
[ImageBatchStream] Get batch done.
[TensorRT] ERROR: ../rtSafe/safeRuntime.cpp (32) - Cuda Error in free: 700 (an illegal memory access was encountered)
terminate called after throwing an instance of 'nvinfer1::CudaError'
  what():  std::exception
```

**Comment by rmccorm4** [comment] 2020-01-22 00:52
Hi @ShawnNew,

This is likely a duplicate of https://github.com/NVIDIA/TensorRT/issues/289 under the hood, please track the issue there. There was a fix internally for some TRT7 + ONNX + INT8 stuff, but not sure when it will be released yet.

**Closed by rmccorm4** 2020-01-22 00:52 UTC

**Comment by ShawnNew** [comment] 2020-01-22 03:05
Hi @rmccorm4 ,
Since TRT7 only released with cuda version 10.0+10.2, which is not compatible with my environment, I am still using TRT6 for some reason.
BTW, I encountered the same error when I run your [tensorrt-util](https://github.com/rmccorm4/tensorrt-utils/tree/master/classification/imagenet#quickstart) repo outside docker. But succeed inside docker container. So I think this issue is related to the environment.

**Comment by rmccorm4** [comment] 2020-01-22 06:27
Yes it's likely an environment issue then. I notice your CuDNN version is "7". Is that 7.0? I believe only 7.6.5 is technically supported for TRT 6/7

**Comment by le8888e** [comment] 2020-05-14 01:30
@rmccorm4  Hello, I'm doing int8 calibration on an onnx model with C++. getBatchSize(), readCalibrationCache() and writeCalibrationCache() was called, but getBatch() was not. I tried .batch and .ppm file for calibration but all failed. Coule you please tell me what's probably going wrong? And can we directly use .jpg .png file for calibration or should we implement it ourselves? Thank you.
