### ISSUE TITLE
there are some bugs in tensorrt7.0.0.11

### ISSUE THREAD

**Issue by yflv-yanxia** [NVIDIA/TensorRT#529] opened 2020-05-06 09:59 UTC
## Description
Our previous 'issues':
[previous 'issues'](https://github.com/NVIDIA/TensorRT/issues/514)
Then I changed to ONNX parser and got the same problem, so I think there may be some bugs in operation "add"("fc45") of tensorrt7.0.0.11

## Environment
TensorRT Version: 7.0.0.11
GPU Type: titan rtx
Nvidia Driver Version: 418.74
CUDA Version: libcudart.so.10.0.130
CUDNN Version: libcudnn.so.7.6.3

## Relevant Files
models, data, scripts could download from the following links:
[scripts_data_trt7model](https://github.com/yflv-yanxia/issues/blob/master/onnx_trt7_bug.zip)

## Steps To Reproduce
change the opencv path and tensorrt path in CMakeLists.txt.
cd build
cmake ..
make
./yscp

Look forward to your reply.

**Comment by rmccorm4** [comment] 2020-05-06 20:30
Hi @yflv-yanxia ,

Thanks for converting to ONNX. I verified the following:

TRT 6.0 vs. ONNX Runtime results match
TRT 7.0 vs. ONNX Runtime results **do not** match

I also verified that this regression in TRT 7.0 has already been fixed in the next release, and the results do match for your fc45.onnx model.

Please stay tuned for the next TRT release to get the fix.

**Closed by rmccorm4** 2020-05-06 20:30 UTC

**Comment by yflv-yanxia** [comment] 2020-05-07 09:32
@rmccorm4 Thank you. When will you release the new version of TRT7?

**Comment by rmccorm4** [comment] 2020-05-19 07:19
Hi @yflv-yanxia ,

I can't share those details, you'll have to wait and see. It looks like a preview version of TensorRT 7.1 was released for Jetson products via Jetpack 4.4. 

But not yet for x86
