### ISSUE TITLE
[Help]  If_534_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape.

### ISSUE THREAD

**Issue by Tian14267** [NVIDIA/TensorRT#1731] opened 2022-01-14 03:37 UTC
## Description

I covert my onnx model to TRT, and get this error:
```
Beginning ONNX file parsing
[01/14/2022-11:30:18] [TRT] [W] onnx2trt_utils.cpp:366: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[01/14/2022-11:30:19] [TRT] [E] If_534_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape.
In node 534 (parseGraph): INVALID_NODE: Invalid Node - If_534
If_534_OutputLayer: IIfConditionalOutputLayer inputs must have the same shape.
Completed parsing of ONNX file
Building an engine from file ./onnx_model/FastSpeech_out.onnx; this may take a while...
1094
[01/14/2022-11:30:19] [TRT] [E] 4: [network.cpp::validate::2633] Error Code 4: Internal Error (Network must have at least one output)
Completed creating Engine
Traceback (most recent call last):
  File "onnx2trt.py", line 105, in <module>
    engine = ONNX_build_engine_acoustic_model(onnx_file_path, write_engine)
  File "onnx2trt.py", line 91, in ONNX_build_engine_acoustic_model
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
```
I feel so confused about this error. My code is :
```
G_LOGGER = trt.Logger(trt.Logger.WARNING)
    explicit_batch = 1 << (int)(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    batch_size = 8 
    with trt.Builder(G_LOGGER) as builder, builder.create_network(explicit_batch) as network, \
            trt.OnnxParser(network, G_LOGGER) as parser:
        builder.max_batch_size = batch_size
        config = builder.create_builder_config()
        config.max_workspace_size = common.GiB(2)
        config.set_flag(trt.BuilderFlag.FP16)
        print('Loading ONNX file from path {}...'.format(onnx_file_path))
        with open(onnx_file_path, 'rb') as model:
            print('Beginning ONNX file parsing')
            parser.parse(model.read())
        print('Completed parsing of ONNX file')
        print('Building an engine from file {}; this may take a while...'.format(onnx_file_path))
        profile = builder.create_optimization_profile() 
        profile.set_shape("texts", (1, 2), (1, 50), (1, 500))
        profile.set_shape("src_lens", [1], [50], [500])   ####  Here is 
        profile.set_shape("speakers", [0], [1], [10])
        profile.set_shape("max_src_len", [1], [50], [500])
        config.add_optimization_profile(profile)

        engine = builder.build_engine(network, config)
        print("Completed creating Engine")
        if write_engine:
            engine_file_path = 'acoustic_model_efficientnet_b1.trt'
            with open(engine_file_path, "wb") as f:
                f.write(engine.serialize())
```
And my [onnx_model ](https://pan.baidu.com/s/1_h1kk_6adTU-DSkfM4q6Pg)is here.

Here is other error in other onnx model:  #1728 
The config in this error is same in #1728

**Comment by galagam** [comment] 2022-06-13 07:54
Seems like `builder.build_engine()` has failed for some reason, causing `engine` to be None. 
@Tian14267 Please supply platform and version info to help us reproduce - OS, CPU arch, TensorRT, ONNX, CUDA & CuDNN versions.

**Comment by nvpohanh** [comment] 2022-07-01 06:21
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-07-01 06:21 UTC
Labels: needs-info, triaged, starred

**Comment by philleer** [comment] 2022-11-29 07:22
Same issue. Any suggestion?
- OS: Linux 4.9.70-040970-generic, Ubuntu 16.04
- CPU: Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz x86_64
- TensorRT: 8.5.1.7
- ONNX: 1.12.0
- CUDA: 11.0
