### ISSUE TITLE
operation.cpp:3390: DCHECK(opnd->is_data()) failed.

### ISSUE THREAD

**Issue by songkq** [NVIDIA/TensorRT#2616] opened 2023-01-30 08:14 UTC
@ttyio Hi, when I use trtexec to build an engine file from a QDQ-onnx from the pytorch_quantization, it failed and said "operation.cpp:3390: DCHECK(opnd->is_data()) failed." 
`trtexec --fp16  --int8 --explicitBatch --onnx=qat.onnx  --saveEngine=qat.trt --workspace=4096`
The onnx model works well with onnxruntime. Also I'm confusing whether I can use the tensorrt api to build an engine instead. Could you please give some advices?
my envs: TensorRT-8.5.1.7; cuda11.1; RTX3090

**Comment by zerollzeng** [comment] 2023-01-31 01:43
Maybe a bug, can you share the onnx here? Thanks!

**Comment by songkq** [comment] 2023-01-31 04:26
@zerollzeng  Dose it support `where` op?

**Comment by songkq** [comment] 2023-01-31 08:03
@zerollzeng Hi, I have uploaded the onnx model[attn_170to303.onnx.zip](https://github.com/NVIDIA/TensorRT/files/10544091/attn_170to303.onnx.zip)

**Comment by songkq** [comment] 2023-02-01 09:50
@zerollzeng @ttyio Hi, do you have any progress~

**Comment by zerollzeng** [comment] 2023-02-01 13:17
Didn't met the error on 8.6. can you also check the latest 8.5 release?
```
&&&& PASSED TensorRT.trtexec [TensorRT v8600] # trtexec --fp16 --int8 --explicitBatch --onnx=attn_170to303.onnx
```

**Comment by songkq** [comment] 2023-02-02 02:29
> Didn't met the error on 8.6. can you also check the latest 8.5 release?
> 
> ```
> &&&& PASSED TensorRT.trtexec [TensorRT v8600] # trtexec --fp16 --int8 --explicitBatch --onnx=attn_170to303.onnx
> ```

@zerollzeng Thanks. Could you reproduce the error on TensorRT-8.5.1.7?  I'll try the latest 8.5 release later.

**Comment by songkq** [comment] 2023-02-02 06:33
@zerollzeng I have tried it out on TensorRT-8.5.3.1 and it failed with the same error. 
```
[02/02/2023-06:29:19] [W] [TRT] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.1.1
[02/02/2023-06:29:19] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
operation.cpp:3390: DCHECK(opnd->is_data()) failed.
```

**Comment by nvpohanh** [comment] 2023-02-02 09:49
I can confirm that TRT 8.5 has this issue but this has been fixed in TRT 8.6 (which will be released in a few weeks). 

And the issue is in the "Where" op, so could you remove that Where op for now?

**Comment by songkq** [comment] 2023-02-02 10:04
> I can confirm that TRT 8.5 has this issue but this has been fixed in TRT 8.6 (which will be released in a few weeks).
> 
> And the issue is in the "Where" op, so could you remove that Where op for now?

@nvpohanh Thanks. The uploaded onnx is a subset of my QAT model. I have attempted to remove all the isolated operations such as  `Where` or `div` or `mul` from my QAT model, but it also failed with the same error.

I'm wondering whether I can build an engine from the QAT model.pth without depending on `nvonnxparser`?

**Comment by nvpohanh** [comment] 2023-02-02 10:16
Yes, you can call TRT APIs directly to construct the network: https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Network.html#tensorrt.INetworkDefinition.add_quantize

**Comment by songkq** [comment] 2023-02-02 11:51
> Yes, you can call TRT APIs directly to construct the network: https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Network.html#tensorrt.INetworkDefinition.add_quantize

When I build the network for the QAT model, I need to add quantize and dequantize nodes, right? And I need to load the  float32 weights (instead of quantized weights) into kernels when building other nodes.

![image](https://user-images.githubusercontent.com/30183023/216314126-eb8abd00-8131-437f-8e31-88fd0ba0589b.png)

How can I obtain the `scale coefficients` needed by `add_quantize` / `add_dequantize` from the trained QAT-model? The zero points are default set to 0 by tensorrt itself, right?

**Comment by nvpohanh** [comment] 2023-02-03 02:00
Yes, zero points are always 0. For scales, you can just copy them from the Q/DQ nodes in ONNX.

**Comment by songkq** [comment] 2023-02-03 02:20
> Yes, zero points are always 0. For scales, you can just copy them from the Q/DQ nodes in ONNX.

@nvpohanh Thanks. There're still some confusions for me. 
How can I obtain the `quantized weights` of  quantized layers such as `Conv` or `Linear`? Or I just need to load the `float32` weights into their kernels when building a network?  

Moreover, I'm wondering whether I can obtain the `scales` from the `model.pth` instead of Q/DQ nodes in ONNX?

**Comment by songkq** [comment] 2023-02-03 15:36
@nvpohanh Thanks a lot. Thanks to the #1552，I have succed to build an engine using tensorrt python api from explicit quantization QDQ-onnx.  

It is worth noting that:
1、In fact, `scales` presented in the Q/DQ onnx nodes are the reciprocals of real scales for the symmetric quantization.
2、The above `scales` are exactly that needed by tensorrt api, i.e., `add_quantize` / `add_dequantize`.
3、We just need to load the `scales` and the `float32` weights into `add_quantize` when building a `QuantizeLinear`.

I wish the code snippet will be helpful beginners, enjoy it~
```
def build_network_api(network):
    """ explicit-quantization example: https://github.com/NVIDIA/TensorRT/issues/1552 """
    inputs = network.add_input(name='input', dtype=trt.DataType.FLOAT, shape=(64, 160, 512))
    MatMul_77_input_scale = network.add_constant([1], np.array(0.007991277612745762, np.float32))

    QuantizeLinear_69 = network.add_quantize(input=inputs, scale=MatMul_77_input_scale.get_output(0))
    QuantizeLinear_69.axis = 0

    DequantizeLinear_72 = network.add_dequantize(input=QuantizeLinear_69.get_output(0), scale=MatMul_77_input_scale.get_output(0))
    DequantizeLinear_72.axis = 0

    MatMul_77_weight_scale = network.add_constant([512], np.load("qdq_matmul_weights_scale.npy"))
    MatMul_77_weight_float = network.add_constant([512, 512], np.load("qdq_matmul_weights_float.npy"))
    QuantizeLinear_74 = network.add_quantize(input=MatMul_77_weight_float.get_output(0), scale=MatMul_77_weight_scale.get_output(0))
    QuantizeLinear_74.axis = 0

    DeQuantizeLinear_74 = network.add_dequantize(input=QuantizeLinear_74.get_output(0), scale=MatMul_77_weight_scale.get_output(0))
    DeQuantizeLinear_74.axis = 0

    transpose_1 = network.add_shuffle(DeQuantizeLinear_74.get_output(0))
    transpose_1.first_transpose = [1, 0]
    transpose_1.reshape_dims = [1, 512, 512]
    MatMul_77 = network.add_matrix_multiply(DequantizeLinear_72.get_output(0), trt.MatrixOperation.NONE, transpose_1.get_output(0), trt.MatrixOperation.NONE)

    MatMul_77.get_output(0).name = '192'

    network.mark_output(tensor=MatMul_77.get_output(0))

    return network

```

**Closed** 2023-02-12 09:32 UTC
Labels: triaged
