### ISSUE TITLE
Myelin error when load ONNX model, Assertion `false && "Invalid size written"' failed

### ISSUE THREAD

**Issue by Emilio66** [NVIDIA/TensorRT#1928] opened 2022-04-15 08:39 UTC
## Description
We're preparing to use Orin with TensorRT8.4 for better performance, but it failed when creating a Builder. Error occurred in myelin which is close-sourced, we've gotten stuck here for days and had no clue where to start debugging, so ask for your help:)

## Environment
**TensorRT Version**: 8400
**NVIDIA GPU**: Orin
**NVIDIA Driver Version**: 11.4
**CUDA Version**: 11.4
**Operating System**: Ubunut20.4

## Key error
It can be reproduced by just running trtexec with ONNX model, it aborted at error: 
**trtexec: /root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/cublas_impl.cpp:479: void add_heuristic_results_to_tactics(std::vector<cublasLtMatmulHeuristicResult_t>&, std::vector<myelin::ir::tactic_attribute_t>&, myelin::ir::tactic_attribute_t&, bool): Assertion `false && "Invalid size written"' failed.**

Detailed log were attached, please check:

[test_model.log](https://github.com/NVIDIA/TensorRT/files/8509418/test_model.log)

Simpilifed onnx model file for reproduction:
[test_model.tar.gz](https://github.com/NVIDIA/TensorRT/files/8509426/test_model.tar.gz)

**Comment by ttyio** [comment] 2022-04-18 09:18
Seems TRT bug, created internal issue, thanks @Emilio66 for the model

**Comment by Emilio66** [comment] 2022-04-18 11:23
> Seems TRT bug, created internal issue, thanks @Emilio66 for the model

Thanks for your quick reply!  Is it a complex bug? How long will it take to fix this?
We've gotten stuck here for almost a week and were wondering if there is any workaround if it might take you long time to fix?

**Comment by ttyio** [comment] 2022-04-18 23:36
Sorry @Emilio66 I did not have Orin in hand, and I tried 8.4 on A100 but cannot repro the failure. Maybe it is Orin specific. Have you tried disable cubalslt tacticsource since I see the error message mentioned the cublaslt? https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.TacticSource

Also I will update here ASAP when the bug has any updates, thanks!

**Comment by Emilio66** [comment] 2022-04-21 13:23
> Have you tried disable cubalslt tacticsource since I see the error message mentioned the cublaslt? https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/BuilderConfig.html#tensorrt.TacticSource
> 
> Also I will update here ASAP when the bug has any updates, thanks!

Hi @ttyio , I tried to disable CUBLAS_LT or CUBLAS in tacticSources, but it didn't work. Log said they're still required though being disabled explicitly.

command: trtexec --onnx=test_model.onnx   --tacticSources=-CUBLAS_LT,+CUDNN,+CUBLAS

Attached Log:
_[04/20/2022-06:03:53] [W] [TRT] **cuDNN, cuBLAS or cuBLASLt library is still required on networks with loop, boolean operators or transformer based architectures even if it is disabled through TacticSources APIs.**
trtexec: /root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/cublas_impl.cpp:480: void add_heuristic_results_to_tactics(std::vector<cublasLtMatmulHeuristicResult_t>&, std::vector<myelin::ir::tactic_attribute_t>&, myelin::ir::tactic_attribute_t&, bool): Assertion `false && "Invalid size written"' failed.
Aborted_

**Comment by Emilio66** [comment] 2022-04-29 00:54
are there any updates about the problem progress?

**Comment by jackwish** [comment] 2022-05-12 12:31
@Emilio66 @KeyLD Thanks for reporting this, please try if this workaround can resolve your issues:

Locate to the directory of `libcublas.so`, e.g. `/usr/local/cuda/lib64` for most cases, and create the symbol links

```sh
sudo ln -s libcublas.so.11 libcublas.so
sudo ln -s libcublasLt.so.11 libcublasLt.so
```

**Comment by KeyLD** [comment] 2022-05-15 17:06
> @Emilio66 @KeyLD Thanks for reporting this, please try if this workaround can resolve your issues:
> 
> Locate to the directory of `libcublas.so`, e.g. `/usr/local/cuda/lib64` for most cases, and create the symbol links
> 
> ```shell
> sudo ln -s libcublas.so.11 libcublas.so
> sudo ln -s libcublasLt.so.11 libcublasLt.so
> ```

Hi @jackwish, 
Thanks for reply, I'm sorry that the error still occurs after creating the symbol links. Have you succeed to convert model while using GRU layer or LSTM layer?

Any idea will help me.

**Comment by jackwish** [comment] 2022-05-18 01:30
@KeyLD Can you confirm that the symbol links `/usr/local/cuda/lib64/libcublas.so` and `/usr/local/cuda/lib64/libcublasLt.so` are newly created? I believe @Emilio66 's issue can be resolved by this workaround.

If it's not resolved still, could you share your mode and log with `trtexec --verbose ...`?

**Comment by KeyLD** [comment] 2022-05-18 02:02
Hi, @jackwish 
I confirmed the symbol links as follow.
```
nvidia@tegra-ubuntu:/usr/local/cuda-11.4/lib64$ pwd
/usr/local/cuda-11.4/lib64
nvidia@tegra-ubuntu:/usr/local/cuda-11.4/lib64$ ls -l libcublas*
lrwxrwxrwx  1 root root        15 Feb 27 12:43 libcublas.so -> libcublas.so.11
lrwxrwxrwx. 1 root root        22 Nov 15 09:07 libcublas.so.11 -> libcublas.so.11.6.5.24
-rw-r--r--. 1 root root 168021872 Nov 15 09:07 libcublas.so.11.6.5.24
lrwxrwxrwx  1 root root        17 Feb 27 12:43 libcublasLt.so -> libcublasLt.so.11
lrwxrwxrwx. 1 root root        24 Nov 15 09:07 libcublasLt.so.11 -> libcublasLt.so.11.6.5.24
-rw-r--r--. 1 root root 371525152 Nov 15 09:07 libcublasLt.so.11.6.5.24
nvidia@tegra-ubuntu:/usr/local/cuda-11.4/lib64$ date
Tue Mar  1 21:43:45 UTC 2022
```

Here is the detailed log and the simpilifed onnx model file:
[build_gru.log](https://github.com/NVIDIA/TensorRT/files/8712702/build_gru.log)
[only_gru.zip](https://github.com/NVIDIA/TensorRT/files/8712706/only_gru.zip)

**Comment by jackwish** [comment] 2022-05-18 06:30
@KeyLD I can reproduce the failre without the symbol links, and got pass with the symbol links created. Could you please check your setup?

**Comment by KeyLD** [comment] 2022-05-18 06:43
> @KeyLD I can reproduce the failre without the symbol links, and got pass with the symbol links created. Could you please check your setup?
> 
> You might need run `sudo ldconfig` or reboot. Before that your change to the libraries won't be effective.

It works! Thanks a lot!

**Comment by jackwish** [comment] 2022-05-18 06:49
Glad to hear :)

**Comment by nvpohanh** [comment] 2022-06-15 07:13
closing this issue for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-06-15 07:13 UTC
Labels: triaged, Topic: Myelin

**Comment by mpjlu** [comment] 2022-09-30 11:13
use low  version cublas may cause this issue

**Comment by lixhk** [comment] 2023-05-05 06:08
> **cuDNN, cuBLAS or cuBLASLt library is still required on networks with loop, boolean operators or transformer based architectures even if it is disabled through TacticSources APIs.**

How to solve it  if I diable  CUBLAS_LT, CUDNN, CUBLAS?

**Comment by lixhk** [comment] 2023-05-05 08:43
That is means  ` loop, boolean operators or transformer based architectures`  are native supported by TRT without CUDNN/CUBLAS/CUBLAS_LT ? @nvpohanh    

My TRT version is  TensorRT v8510

**Comment by nvpohanh** [comment] 2023-05-05 10:28
In TRT 8.5, it may or may not depend on CUDNN/CUBLAS/CUBLAS_LT. You can try enabling `PreviewFeature::kDISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805` preview flag and see if TRT throws any error
