### ISSUE TITLE
Memory leak when deleting Runtime and ICudaEngine

### ISSUE THREAD

**Issue by ReverseSystem001** [NVIDIA/TensorRT#3410] opened 2023-10-30 02:49 UTC
Env:
GPU RTX1060ti
OS, ubuntu 20.04
Cuda 11.4
TensorRT version TensorRT-8.2.5.1.Linux.x86_64-gnu.cuda-11.4.cudnn8.2/TensorRT-8.2.5.1 

examples:
void main(){
      ..........
      ..........
      sleep(10); // watch -n 1 nvidia-smi (to watch the change of GPU memory)
      context->destroy(); // **the gpu memory destroyed successfully**
      sleep(10);
       delete engine; //engine->destroy(); // both of them are not work
      sleep(10);
      delete runtime; //runtime->destroy(); // not work
}

**Comment by zerollzeng** [comment] 2023-10-31 15:38
I don't know what the issue is, please describe the expected behavior vs actual behavior.

**Comment by ReverseSystem001** [comment] 2023-10-31 15:49
thanks for your reply.
Env：Ubuntu20.04
cuda：11.4
trt version: 8.2


main{
....
....
// watch -n 1 nvidia-smi&nbsp; &nbsp;
delete context;&nbsp; // release successful
sleep(10);
delete engine;&nbsp; // GPU memory no change
sleep(10);

delete runtime;&nbsp; //&nbsp; no change
sleep(10);



}



---Original---
From: "Zero ***@***.***&gt;
Date: Tue, Oct 31, 2023 23:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA/TensorRT] Memory leak when deleting Runtime andICudaEngine (Issue #3410)




 
I don't know what the issue is, please describe the expected behavior vs actual behavior.

**Comment by ReverseSystem001** [comment] 2023-10-31 15:58
thanks for your reply.&nbsp;
Env: Ubuntu20.04
cuda :&nbsp; 11.4
Nvidia：3090
trt version:8.2


main{
....
....
//&nbsp; watch -n 1 nvidia-smi&nbsp;&nbsp;
delete context;&nbsp; //&nbsp; GPU memory release
sleep(10);

delete engine;&nbsp; //&nbsp; GPU memory no change
sleep(10);

delete runtime;&nbsp; //&nbsp; GPU memory no change




}



---Original---
From: "Zero ***@***.***&gt;
Date: Tue, Oct 31, 2023 23:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA/TensorRT] Memory leak when deleting Runtime andICudaEngine (Issue #3410)




 
I don't know what the issue is, please describe the expected behavior vs actual behavior.

**Comment by ReverseSystem001** [comment] 2023-11-02 08:07
> I don't know what the issue is, please describe the expected behavior vs actual behavior.

thanks for your reply, my expected behavior is: 
**I want to release the GPU memory,** but when I use the **delete engine and delete runtime**,   the memory of the **GPU remains unchanged**.   When I call these two delete functions, shouldn't the graphics memory be released, but I didn't release it until I jumped out of the main function. The test code is as follows
void main(){
..........
..........
sleep(10); // **watch -n 1 nvidia-smi (to watch the change of GPU memory)**
context->destroy(); // **worked successfully**
sleep(10);
**delete engine**; //engine->destroy(); **// both of them are not work**
sleep(10);
**delete runtime;** //runtime->destroy(); **// not work**
}

**Comment by ReverseSystem001** [comment] 2023-11-02 08:15
> I don't know what the issue is, please describe the expected behavior vs actual behavior.

test cpp is:   https://github.com/we0091234/yolov8-tensorrt/blob/master/yolov8.cpp
But i change the code from line 274 as following:
    // destroy the engine
    std::cout<<"averageTime:"<<(sumTime/(imagList.size()-1))<<"ms"<<std::endl;

    sleep(10);
    std::cout << "context destroy Begin" << std::endl;
    context_det->destroy();
    sleep(10);
    std::cout << "engine destroy Begin" << std::endl;
    //engine_det->destroy();
    delete engine_det;
    sleep(10);
    std::cout << "runtime destroy Begin" << std::endl;
    //runtime_det->destroy();
    delete runtime_det;
    std::cout << "runtime destroy Finished" << std::endl;
    sleep(10);
    cudaStreamDestroy(stream);
    CHECK(cudaFree(img_device));
    CHECK(cudaFreeHost(img_host));
    CHECK(cudaFree(buffers[inputIndex]));
    CHECK(cudaFree(buffers[outputIndex]));
    CHECK(cudaFree(decode_ptr_device));
    CHECK(cudaFree(affine_matrix_d2i_device));
    CHECK(cudaFreeHost(affine_matrix_d2i_host));
    CHECK(cudaFree(transpose_device));

**Comment by zerollzeng** [comment] 2023-11-04 01:08
It's expected, when you call free() or cudaFree(), the physical memory isn't recycle by the OS immediately until the program exit.

e.g. see https://stackoverflow.com/questions/21433976/free-not-freeing-memory-in-embedded-linux

**Comment by ReverseSystem001** [comment] 2023-11-04 01:17
thanks. get it



---Original---
From: "Zero ***@***.***&gt;
Date: Sat, Nov 4, 2023 09:08 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA/TensorRT] Memory leak when deleting Runtime andICudaEngine (Issue #3410)




 
It's expected, when you call free() or cudaFree(), the physical memory isn't recycle by the OS immediately until the program exit.
 
e.g. see https://stackoverflow.com/questions/21433976/free-not-freeing-memory-in-embedded-linux

**Comment by zerollzeng** [comment] 2023-11-04 01:38
I'm closing this, feel free to reopen if you have further questions.

**Closed by zerollzeng** 2023-11-04 01:38 UTC
Labels: triaged

**Comment by ReverseSystem001** [comment] 2023-11-06 01:45
Thanks
