### ISSUE TITLE
TensorRT 8.4.0.6 (EA) converts the BERT model, pthread_create failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by wanzhenchn** [NVIDIA/TensorRT#1906] opened 2022-04-06 08:32 UTC
## Description

I used the [bert4keras](https://github.com/bojone/bert4keras/blob/master/bert4keras/models.py#L410) (version: 0.10.7) package to train a bert model under tensorflow framework (version; 2.2.0), then converted it into onnx model successfully, finally I used the trtexec and script to build TensorRT(version: 8.4.0.6) engine, the convert process runs several hours and no any response, both are failed and showed:

**_runtime/cgo: pthread_create failed: Resource temporarily unavailable_**

## Environment

**TensorRT Version**: 8.4.0.6 (EA)
**NVIDIA GPU**:  Tesla T4
**NVIDIA Driver Version**: 460.91.03
**CUDA Version**: 11.6
**CUDNN Version**: 8.3
**Operating System**: unbuntu 16.04
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: 2.2.0
**PyTorch Version (if applicable)**: -
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/tensorrt:22.03-py3 (installed tensorrt 8.4.0.6 manual )

## Relevant Files

The onnx model and script used can be found here: https://drive.google.com/drive/folders/1bmYkOnFT79xudF6oiFJdlOsjjB0Ms54t?usp=sharing

## Steps To Reproduce

download the onnx model and model2trt.py and then run the following command in Docker container:
python model2trt.py --dynamic --half

**Comment by ttyio** [comment] 2022-04-07 09:09
Hello @wanzhenchn , have you checked which step did the script hang? the model to onnx or onnx to trt? You can also try trtexec to see if the failure is reproducable, thanks!

**Comment by wanzhenchn** [comment] 2022-04-08 02:47
> 

many thanks for your focus. 

The process of building trt engine (build_serialized_network(), Line 132 in model2trt.py) hangs long time and finally failed with `Resource temporarily unavailable`. The onnx model is proved to be true.

The trtexec is also tried but got the same error.

we tried  to cut the onnx model in half, the first half can be built successfully, when add the first part of last half model, the same error occurred. (the model is BERT, consists of 12 self-attention blocks)

**Comment by nvpohanh** [comment] 2022-06-15 07:42
@wanzhenchn Could you share the ONNX model? I can't find the ONNX model in https://drive.google.com/drive/folders/1bmYkOnFT79xudF6oiFJdlOsjjB0Ms54t

**Comment by nvpohanh** [comment] 2022-06-15 07:42
also, could you try TRT 8.4 GA (8.4.1) release? Thanks

**Comment by nvpohanh** [comment] 2022-07-01 06:32
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-07-01 06:32 UTC
Labels: triaged, Release: 8.x, Topic: Transformer

**Comment by zysNLP** [comment] 2022-10-16 13:30
@wanzhenchn Hey bro, have you solved the problem in this issue? I found the same questions
