### ISSUE TITLE
inference time are the same for INT8 and FP16  

### ISSUE THREAD

**Issue by alicera** [NVIDIA/TensorRT#983] opened 2020-12-25 03:22 UTC
TensorRT Version: 7.2.1
GPU Type: GTX 1660
Nvidia Driver Version: 455.38
CUDA Version: 11.1
CUDNN Version: 8.0
Operating System: ubuntu18.04

onnx-> trt 
I use the onnx model to inference trt
https://github.com/ultralytics/yolov5

Do you know the reason?

**Comment by nvpohanh** [comment] 2020-12-28 01:45
Could you attach verbose logger logs of engine building so that we can tell what the issue is? In some cases, TRT doesn't choose INT8 tactics because the dynamic ranges of some tensors are not correctly set.

**Comment by alicera** [comment] 2020-12-28 02:55
std::cout << "Building the TensorRT Engine..." << std::endl;
Engine = Builder->buildEngineWithConfig(*Network, *config);

How do I provide the information of verbose logger logs?

**Comment by nvpohanh** [comment] 2020-12-28 03:02
https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Core/Logger.html

Set the `min_severity` of the Logger to `VERBOSE` so that all messages are printed out in stdout.

**Comment by alicera** [comment] 2020-12-28 04:24
I set  trt.Logger.INFO 、trt.Logger.WARNING、trt.Logger.INTERNAL_ERROR、 trt.Logger.ERROR

the message is

> 

[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
Completed parsing of ONNX file
Building an engine; this may take a while...
[TensorRT] INFO: Reading Calibration Cache for calibrator: EntropyCalibration2
[TensorRT] INFO: Generated calibration scales using calibration cache. Make sure that calibration cache has latest scales.
[TensorRT] INFO: To regenerate calibration cache, please delete the existing one. TensorRT will generate a new calibration cache.
[TensorRT] INFO: Detected 1 inputs and 3 output network tensors.
Completed creating engine

> 


If you want to trt.Logger.VERBOSE.
The message is so many. How to save it

**Comment by nvpohanh** [comment] 2020-12-28 06:02
Are you using Linux? If so, then `<your command> 2>&1 | tee output.log` and then upload the `output.log` file.

**Comment by alicera** [comment] 2020-12-28 06:47
Thanks you. Here is the log for IN8.
[output.log](https://github.com/NVIDIA/TensorRT/files/5746152/output.log)

**Comment by nvpohanh** [comment] 2020-12-28 07:12
```
[TensorRT] VERBOSE: Layer(icudnn): Conv_41, Tactic: -6282183216199417697, Conv_41 reformatted input 0[Int8(12,320,320)] -> 208[Int8(32,320,320)]
[TensorRT] VERBOSE: Layer(PointWiseV2): PWN(PWN(PWN(209 + (Unnamed Layer* 11) [Shuffle] + Add_43, Clip_46), Mul_47), PWN(215 + (Unnamed Layer* 16) [Shuffle], Div_49)), Tactic: 4, 208[Int8(32,320,320)] -> 216[Int8(32,320,320)]
[TensorRT] VERBOSE: Layer(icudnn): Conv_50, Tactic: 4438325421691896755, 216[Int8(32,320,320)] -> 217[Int8(64,160,160)]
[TensorRT] VERBOSE: Layer(PointWiseV2): PWN(PWN(PWN(218 + (Unnamed Layer* 20) [Shuffle] + Add_52, Clip_55), Mul_56), PWN(224 + (Unnamed Layer* 25) [Shuffle], Div_58)), Tactic: 4, 217[Int8(64,160,160)] -> 225[Int8(64,160,160)]
[TensorRT] VERBOSE: Layer(icudnn): Conv_88 || Conv_59, Tactic: 4581732244273465060, 225[Int8(64,160,160)] -> Conv_88 || Conv_59[Int8(64,160,160)]
...
```
It seems that it indeed ran in INT8, but TensorCore was not utilized. Also, the INT8 TensorCore tactics (`*i8i8i32*`) were tried, but were somehow slower than normal INT8 tactics (`*int8x4_icudnn_int8x4*`). Several questions:

1. Is your GPU really RTX 3080? I can't find any `ampere_` tactics but only `volta_` and `turing_` ones, suggesting that the GPU has Turing Architecture instead of Ampere Architecture. Could you show your `nvidia-smi` output?
2. What is the Batch Size? Is it 1? Could you try a larger batch size and see if there is any runtime difference between FP16 and INT8?
3. Could you try TensorRT 7.2.2 which was just released? https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html#rel_7-2-2 It may have some optimizations for Ampere Architecture GPUs.

Thanks

**Comment by alicera** [comment] 2020-12-28 07:45
Hi, nvpohanh 

Here is my machine status, now
TensorRT Version: 7.2.1
GPU Type: GTX 1660
Nvidia Driver Version: 455.38
CUDA Version: 11.1
Operating System: ubuntu18.04

1. What is the different of ampere_ tactics, volta_ and turing_
2.  "try a larger batch size". It can speed up the speed for calib. Have it any other reason for do this?
3. I will try it with TensorRT 7.2.2, if it support.
4. What is the i8i8i32 and int8x4_icudnn_int8x4
Thanks you

**Comment by ttyio** [comment] 2021-01-11 10:21
> Hi, nvpohanh
> 
> Here is my machine status, now
> TensorRT Version: 7.2.1
> GPU Type: GTX 1660
> Nvidia Driver Version: 455.38
> CUDA Version: 11.1
> Operating System: ubuntu18.04
> 
> 1. What is the different of ampere_ tactics, volta_ and turing_
> 2. "try a larger batch size". It can speed up the speed for calib. Have it any other reason for do this?
> 3. I will try it with TensorRT 7.2.2, if it support.
> 4. What is the i8i8i32 and int8x4_icudnn_int8x4
>    Thanks you

1. they are kernels for different gpu arch, and your 1660 can run volta_  and turing_
2. to fulfill the gpu in case gpu is `hungry`
3. any update?
3. they are different instructions. i8i8i32 use tensorCore, and int8x4_icudnn_int8x4 not using tensorCore

**Comment by alicera** [comment] 2021-01-11 10:45
I try the TensorRT 7.2.2 and it is still the problem.

**Comment by nvpohanh** [comment] 2021-01-12 03:27
GTX 1660 does not have INT8 tensor cores. Is it possible that you try an RTX part?

**Comment by alicera** [comment] 2021-01-12 03:37
Do you know where is the detail message for GPU supported INT8 ？
Thanks

**Comment by nvpohanh** [comment] 2021-01-12 03:43
Support matrix is here: https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#hardware-precision-matrix

GTX 1660 does support INT8 in terms of functionality, but just not the "fast" INT8 like RTX2060/2070/2080 and so on.

**Comment by alicera** [comment] 2021-01-12 03:56
You mean RTX2060/2070/2080 support INT8 acceleration, but GTX 1660 does support INT8 acceleration, right.

Support matrix only show  "Example Device", I cant search others, like GTX 1660,RTX2060 ....

**Comment by alicera** [comment] 2021-02-01 10:48
RTX2060 meet the same problem "inference time are the same for INT8 and FP16"

**Comment by nvpohanh** [comment] 2021-02-02 03:15
@alicera Could you attach the verbose logs again? Thanks

**Comment by alicera** [comment] 2021-02-02 06:56
Thanks you. Here is the log for IN8.
[output.log](https://github.com/NVIDIA/TensorRT/files/5909241/output.log)

**Comment by nvpohanh** [comment] 2021-02-02 07:22
Thanks @alicera . I do see INT8 TensorCore already being used.

Could you let me know how you measure the inference runtime? Did you use the `trtexec` tool to measure inference time? Or something else?

**Comment by alicera** [comment] 2021-02-02 08:05
I set the timer for inference network.
Switch the INT8 and FP16 to test one image.
 
INT8:
dur/img(9.316 msec)

FP16:
dur/img(9.695 msec)

**Comment by nvpohanh** [comment] 2021-02-02 08:27
May I take a look at your inference code? Just want to know if the timing is measured correctly.

Or alternative, could you load the onnx file into `trtexec` with `trtexec --onnx=<onnx_file> --shapes=<input_tensor_name>:<input_tensor_shape> --int8 --verbose`? `trtexec` is a perf measurement tool we ship with TRT package. Thanks

**Comment by alicera** [comment] 2021-02-02 08:30
[output_fp16.log](https://github.com/NVIDIA/TensorRT/files/5909688/output_fp16.log)
[output_int8.log](https://github.com/NVIDIA/TensorRT/files/5909689/output_int8.log)

trtexec --onnx=model.onnx --shapes=input:1x3x640x640 --fp16 2>&1 | tee output_fp16.log

**Comment by nvpohanh** [comment] 2021-02-02 08:44
fp16:

```
[02/02/2021-16:20:45] [I] GPU Compute
[02/02/2021-16:20:45] [I] min: 2.08899 ms
[02/02/2021-16:20:45] [I] max: 2.19341 ms
[02/02/2021-16:20:45] [I] mean: 2.11514 ms
[02/02/2021-16:20:45] [I] median: 2.11328 ms
```

int8:

```
[02/02/2021-16:16:48] [I] GPU Compute
[02/02/2021-16:16:48] [I] min: 1.77328 ms
[02/02/2021-16:16:48] [I] max: 1.82275 ms
[02/02/2021-16:16:48] [I] mean: 1.79621 ms
[02/02/2021-16:16:48] [I] median: 1.7959 ms
```

So it seems that the INT8 is running **17.6%** faster than FP16. Could you run it again with `--dumpProfile --separateProfileRun` flags to see per-layer runtime? Thanks

**Comment by alicera** [comment] 2021-02-02 08:59
trtexec --onnx=model.onnx --shapes=input:1x3x640x640 --int8 --dumpProfile --separateProfileRun  2>&1 | tee output2_int8.log

[output2_fp16.log](https://github.com/NVIDIA/TensorRT/files/5909897/output2_fp16.log)
[output2_int8.log](https://github.com/NVIDIA/TensorRT/files/5909898/output2_int8.log)

**Comment by nvpohanh** [comment] 2021-02-02 09:06
FP16:
```
[02/02/2021-16:58:38] [I]                                                                                                                                                   Conv_41       71.36           0.0641      2.6
[02/02/2021-16:58:38] [I]                            PWN(PWN(PWN(209 + (Unnamed Layer* 11) [Shuffle] + Add_43, Clip_46), Mul_47), PWN(215 + (Unnamed Layer* 16) [Shuffle], Div_49))       78.25           0.0703      2.9
[02/02/2021-16:58:38] [I]                                                                                                                                                   Conv_50       64.81           0.0582      2.4
[02/02/2021-16:58:38] [I]                            PWN(PWN(PWN(218 + (Unnamed Layer* 20) [Shuffle] + Add_52, Clip_55), Mul_56), PWN(224 + (Unnamed Layer* 25) [Shuffle], Div_58))       45.46           0.0408      1.7
[02/02/2021-16:58:38] [I]                                                                                                                                        Conv_59 || Conv_88       32.75           0.0294      1.2
[02/02/2021-16:58:38] [I]                            PWN(PWN(PWN(227 + (Unnamed Layer* 29) [Shuffle] + Add_61, Clip_64), Mul_65), PWN(233 + (Unnamed Layer* 34) [Shuffle], Div_67))       27.64           0.0248      1.0
[02/02/2021-16:58:38] [I]                                                                                                                                                   Conv_68       13.86           0.0125      0.5
[02/02/2021-16:58:38] [I]                            PWN(PWN(PWN(236 + (Unnamed Layer* 38) [Shuffle] + Add_70, Clip_73), Mul_74), PWN(242 + (Unnamed Layer* 43) [Shuffle], Div_76))       24.72           0.0222      0.9
[02/02/2021-16:58:38] [I]                                                                                                                                                   Conv_77       30.58           0.0275      1.1
[02/02/2021-16:58:38] [I]               PWN(PWN(PWN(PWN(245 + (Unnamed Layer* 47) [Shuffle] + Add_79, Clip_82), Mul_83), PWN(251 + (Unnamed Layer* 52) [Shuffle], Div_85)), Add_86)       29.86           0.0268      1.1
```
INT8:
```
[02/02/2021-16:54:34] [I]                                                                                                                                                   Conv_41       58.86           0.0475      2.2
[02/02/2021-16:54:34] [I]                            PWN(PWN(PWN(209 + (Unnamed Layer* 11) [Shuffle] + Add_43, Clip_46), Mul_47), PWN(215 + (Unnamed Layer* 16) [Shuffle], Div_49))       95.43           0.0770      3.6
[02/02/2021-16:54:34] [I]                                                                                                                                                   Conv_50       44.65           0.0360      1.7
[02/02/2021-16:54:34] [I]                            PWN(PWN(PWN(218 + (Unnamed Layer* 20) [Shuffle] + Add_52, Clip_55), Mul_56), PWN(224 + (Unnamed Layer* 25) [Shuffle], Div_58))       47.82           0.0386      1.8
[02/02/2021-16:54:34] [I]                                                                                                                                        Conv_59 || Conv_88       20.28           0.0164      0.8
[02/02/2021-16:54:34] [I]                            PWN(PWN(PWN(227 + (Unnamed Layer* 29) [Shuffle] + Add_61, Clip_64), Mul_65), PWN(233 + (Unnamed Layer* 34) [Shuffle], Div_67))       25.84           0.0208      1.0
[02/02/2021-16:54:34] [I]                                                                                                                                                   Conv_68       13.78           0.0111      0.5
[02/02/2021-16:54:34] [I]                            PWN(PWN(PWN(236 + (Unnamed Layer* 38) [Shuffle] + Add_70, Clip_73), Mul_74), PWN(242 + (Unnamed Layer* 43) [Shuffle], Div_76))       26.62           0.0215      1.0
[02/02/2021-16:54:34] [I]                                                                                                                                                   Conv_77       26.40           0.0213      1.0
[02/02/2021-16:54:34] [I]               PWN(PWN(PWN(PWN(245 + (Unnamed Layer* 47) [Shuffle] + Add_79, Clip_82), Mul_83), PWN(251 + (Unnamed Layer* 52) [Shuffle], Div_85)), Add_86)       32.07           0.0259      1.2
```

It seems that for the convolutions, INT8 is indeed running faster than FP16. But there are many "Pointwise" layers which are basically the same speed between INT8 and FP16. May I ask what are between two convolutions? Would you be able to upload the onnx file?

Also, could you try with a larger batch sizes (like `--shapes=input:64x3x640x640`) and see if the performance difference becomes larger?

**Comment by alicera** [comment] 2021-02-02 09:34
trtexec --onnx=model.onnx --shapes=input:64x3x640x640 --int8 --dumpProfile --separateProfileRun  2>&1 | tee output3_int8.log

[output3_fp16.log](https://github.com/NVIDIA/TensorRT/files/5910048/output3_fp16.log)
[output3_int8.log](https://github.com/NVIDIA/TensorRT/files/5910049/output3_int8.log)

It will be remove after get your response. Thanks.
https://drive.google.com/file/d/1gCPQlXfN9X88nwqRCsnwRK5P3vZGkZEr/view?usp=sharing

**Comment by nvpohanh** [comment] 2021-02-02 09:46
Hi @alicera, thanks for the logs and onnx file.

Regarding the logs, it is still running at BS=1. The reason is because the ONNX file you exported has fixed input shape of 1x3x640x640. Could you re-export the ONNX file with the first dimension being a dynamic axis?

As for the ONNX file, I see a lot of this pattern: 
![2021-02-02 17_45_11-C__Users_phuan_Desktop_work_model (1) onnx - Netron](https://user-images.githubusercontent.com/53919306/106581999-764d6380-657e-11eb-8de0-41cf09ffbc94.png)
Is this some special kind of new activation? I am afraid that TensorRT might not have optimized this specific type of activation that well.

**Comment by alicera** [comment] 2021-02-02 10:04
Here is  https://github.com/ultralytics/yolov5
Your pattern is the Hardswish process.
So, it is the reson for the INT8 cant speed up .

**Comment by nvpohanh** [comment] 2021-02-03 03:23
I think there are several issues:

1. Our trtexec shows that there is a 17% performance improvement between INT8 and FP16. You may want to debug why it didn't show up in your application. (For example, you can use [Nsight Systems](https://developer.nvidia.com/nsight-systems) to check if your application is letting GPUs to sit idle for some period of time).
2. TensorRT has not optimized hard-Swish. Changing the activation to more common ones (like ReLU or Swish) may help further boost the performance.
3. Try with larger batch sizes. In some cases, batch size = 1 is too small to fully utilize the entire GPU.

I hope these suggestions help.

**Comment by alicera** [comment] 2021-02-04 02:16
The hard-Swish is compose of clip, add, Div ...
But the document show the ops have supported .
https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#supported-ops
![image](https://user-images.githubusercontent.com/59388989/106835168-cee14580-66d1-11eb-8c36-11200ff760f0.png)

**Comment by nvpohanh** [comment] 2021-02-04 03:09
Hi @alicera , yes, they are supported, and as you can tell in the logs, TRT already fuses them into one op so that we don't waste time in moving in and out from the DRAM.

That said, we have not fully optimized the performance for that fused operation, and that is why you only see 17% of perf improvements between INT8 vs FP16. Future TRT versions may optimize it further.

Another thing I would try, as I mentioned before, is to run at a much larger batch sizes and see if the performance improvements between INT8 and FP16 becomes larger.

Thanks!

**Comment by ttyio** [comment] 2021-05-21 06:39
Close since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Closed by ttyio** 2021-05-21 06:39 UTC
Labels: Precision: FP16, Precision: INT8, Runtime: Performance, triaged
