### ISSUE TITLE
Stable Diffusion XL OOM

### ISSUE THREAD

**Issue by cjt222** [NVIDIA/TensorRT#3431] opened 2023-11-07 08:59 UTC
Hello, my graphics card is 4090 with 24G of memory. I'm using torch's SD XL with a resolution of 1024 x 1024 and a batch size of 4 which consumes 21G of memory. However, when testing the demo_txt2img_xl.py script, it throws an Out of Memory (OOM) error when the batch size is set to 4. Can you help me with this issue?

PS: Please note that I have already tried to reduce the batch size to 2, but the OOM error still persists.

**Comment by zerollzeng** [comment] 2023-11-08 15:13
This is the dup of https://github.com/NVIDIA/TensorRT/issues/3421, so I'm closing that one.

**Comment by zerollzeng** [comment] 2023-11-08 15:14
Could ypu please provide the command you are using to reproduce the OOM? it's expected that tensorrt use more memory when build the engine.

**Comment by zerollzeng** [comment] 2023-11-08 15:16
Did you enable refit?

**Comment by chengzeyi** [comment] 2023-11-30 07:08
@cjt222 Hi, friend！I know you are suffering great pain from using `TRT` with `diffusers`.

So why choose my totally **open-sourced** alternative: [`stable-fast`?](https://github.com/chengzeyi/stable-fast)
It's on par with `TRT` on inference speed, faster than `torch.compile` and `AITemplate`, and is super dynamic and flexible, supporting **ALL** SD models and **LoRA** and **ControlNet** out of the box!

[![](https://mermaid.ink/img/pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1?type=png)](https://mermaid.live/edit#pako:eNpVUk2PmzAQ_SsjS1EuQGyyJMBhpZW2hx562eVQdb2HAQawBDayzTZRxH-vSapKPdh68zzye_NxY41piZVst7sprXwJt70faKJ9CfvOWHJ-v8K620l9uTYDWh_X5FFqr_xIIFmlJoKQCD1psuiV7sFoAjVhT_Bb-QHeX0EkWQSZSC_hBMDBeZpdFDLhrfoJTzznkgWJGC_KwYdkX6jVOCJ4Y5tBsigo3WHSmGlWIz2ol-8VTfOI_m9ckXbGvlVQJDwRD855rEeKO3Resk-prw8NyaYgoBw1RrdOMuAQx8-Qcs6llrpGCx8iL84RiEzwcIssj6AoRIA8LT5ZxCayE6o2NO8mNWwOt8ZJVgZYo6OtojXk4eLN-1U3rPR2oYgtcxscvyrsLU7_k99aFcpkZYejC-RosKUQ3pi_ztuUeuV8-DF47lS_8YsdAz14P7vycNiekz70fKm3Rh2careRDV_F6XBKTzmmRzqdj5gdj21TiyLv0ifRtWcuUmTrGrEZ9S9jpn8G6O7nx2NF7puy_gHMObP1)

**Comment by ttyio** [comment] 2024-05-07 18:34
closing since no activity for more than 3 weeks per our policy, thanks all!

**Closed by ttyio** 2024-05-07 18:34 UTC
Labels: triaged
