### ISSUE TITLE
On buildinig python api get the error: "void value not ignored as it ought to be"

### ISSUE THREAD

**Issue by wangxudong-cq** [NVIDIA/TensorRT#1980] opened 2022-05-13 02:45 UTC
## Description
./build.sh
```
~/TensorRT/python/build ~/TensorRT/python
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
cmake .. -DCMAKE_BUILD_TYPE=Release -DTARGET=x86_64 -DPYTHON_MAJOR_VERSION=3 -DPYTHON_MINOR_VERSION=9 -DEXT_PATH=/home/xudong/python3.9.12/external/ -DCUDA_INCLUDE_DIRS=/usr/local/cuda-10.2/include -DTENSORRT_ROOT=/home/xudong/TensorRT/ -DTENSORRT_BUILD=/home/xudong/TensorRT//build/
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
====================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xudong/TensorRT/python/build
Scanning dependencies of target tensorrt
[  8%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyGraph.cpp.o
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyFoundationalTypes.cpp.o
[ 25%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyAlgorithmSelector.cpp.o
[ 41%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o
[ 50%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyCaffe.cpp.o
[ 50%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyCore.cpp.o
[ 66%] Building CXX object CMakeFiles/tensorrt.dir/src/pyTensorRT.cpp.o
[ 66%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyUff.cpp.o
[ 75%] Building CXX object CMakeFiles/tensorrt.dir/src/parsers/pyOnnx.cpp.o
[ 83%] Building CXX object CMakeFiles/tensorrt.dir/src/utils.cpp.o
[ 91%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyPlugin.cpp.o
In file included from /home/xudong/TensorRT/python/include/ForwardDeclarations.h:30:0,
                 from /home/xudong/TensorRT/python/src/infer/pyInt8.cpp:19:
/home/xudong/TensorRT/python/src/infer/pyInt8.cpp: In member function ‘virtual const void* tensorrt::pyIInt8LegacyCalibrator::readHistogramCache(std::size_t&)’:
/home/xudong/python3.9.12/external/pybind11/include/pybind11/pybind11.h:2741:70: error: void value not ignored as it ought to be
             return pybind11::detail::cast_safe<ret_type>(std::move(o));                           \
                                                                      ^
/home/xudong/python3.9.12/external/pybind11/include/pybind11/pybind11.h:2775:9: note: in expansion of macro ‘PYBIND11_OVERRIDE_IMPL’
         PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(ret_type), PYBIND11_TYPE(cname), name, __VA_ARGS__); \
         ^~~~~~~~~~~~~~~~~~~~~~
/home/xudong/python3.9.12/external/pybind11/include/pybind11/pybind11.h:2834:5: note: in expansion of macro ‘PYBIND11_OVERRIDE_PURE_NAME’
     PYBIND11_OVERRIDE_PURE_NAME(                                                                  \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xudong/TensorRT/python/src/infer/pyInt8.cpp:136:9: note: in expansion of macro ‘PYBIND11_OVERLOAD_PURE_NAME’
         PYBIND11_OVERLOAD_PURE_NAME(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/tensorrt.dir/build.make:134: recipe for target 'CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o' failed
make[2]: *** [CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/tensorrt.dir/all' failed
make[1]: *** [CMakeFiles/tensorrt.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2
Generating python 3.9 bindings for TensorRT 8.2.4.2
~/TensorRT/python/packaging ~/TensorRT/python/build ~/TensorRT/python
~/TensorRT/python/build ~/TensorRT/python
/usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
~/TensorRT/python
```

## Environment
nvidia-smi
![image](https://user-images.githubusercontent.com/76459010/168201129-d3e77583-3609-4a2c-870b-22c76c2781ec.png)

TensorRT Version:
8.2.4

NVIDIA GPU:
GeForce GTX 1050 Ti

NVIDIA Driver Version:
hoe to check?

CUDA Version:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

CUDNN Version:
hoe to check?

Operating System:
Ubuntu 18.04.6

Python Version (if applicable):
Python 3.9.6

Tensorflow Version (if applicable): NO
PyTorch Version (if applicable): NO
Baremetal or Container (if so, version): NO

**Comment by huubvh95** [comment] 2022-05-13 12:54
I am having the same problem

**Comment by wangxudong-cq** [comment] 2022-05-16 10:49
I comment pyInt8.cpp,then excute build.sh,but there is some error for tensorrt.so which compiled by build.sh.
```
ldd -r tensorrt/tensorrt.so
        linux-vdso.so.1 (0x0000007fa7a38000)
        libnvinfer.so.7 => /usr/lib/aarch64-linux-gnu/libnvinfer.so.7 (0x0000007f9a38e000)
        libnvonnxparser.so.7 => /usr/lib/aarch64-linux-gnu/libnvonnxparser.so.7 (0x0000007f9a10e000)
        libnvparsers.so.7 => /usr/lib/aarch64-linux-gnu/libnvparsers.so.7 (0x0000007f99dcc000)
        libnvinfer_plugin.so.7 => /usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so.7 (0x0000007f99858000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f996c4000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f996a0000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f99547000)
        /lib/ld-linux-aarch64.so.1 (0x0000007fa7a0c000)
        libcublas.so.10 => /usr/lib/aarch64-linux-gnu/libcublas.so.10 (0x0000007f94869000)
        libcudart.so.10.2 => /usr/local/cuda-10.2/lib64/libcudart.so.10.2 (0x0000007f947f5000)
        libcudnn.so.8 => /usr/lib/aarch64-linux-gnu/libcudnn.so.8 (0x0000007f947b7000)
        libmyelin.so.1 => /usr/lib/aarch64-linux-gnu/libmyelin.so.1 (0x0000007f94329000)
        libnvrtc.so.10.2 => /usr/local/cuda-10.2/lib64/libnvrtc.so.10.2 (0x0000007f92ef8000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f92ee3000)
        libnvdla_compiler.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdla_compiler.so (0x0000007f92aaf000)
        libnvmedia.so => /usr/lib/aarch64-linux-gnu/tegra/libnvmedia.so (0x0000007f92a45000)
        libEGL.so.1 => /usr/lib/aarch64-linux-gnu/libEGL.so.1 (0x0000007f92a24000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f9296b000)
        libcublasLt.so.10 => /usr/lib/aarch64-linux-gnu/libcublasLt.so.10 (0x0000007f909a5000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f90979000)
        librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000007f90962000)
        libnvos.so => /usr/lib/aarch64-linux-gnu/tegra/libnvos.so (0x0000007f90944000)
        libnvrm.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm.so (0x0000007f90901000)
        libnvrm_graphics.so => /usr/lib/aarch64-linux-gnu/tegra/libnvrm_graphics.so (0x0000007f908e1000)
        libnvdc.so => /usr/lib/aarch64-linux-gnu/tegra/libnvdc.so (0x0000007f908c1000)
        libnvtvmr.so => /usr/lib/aarch64-linux-gnu/tegra/libnvtvmr.so (0x0000007f90831000)
        libnvparser.so => /usr/lib/aarch64-linux-gnu/tegra/libnvparser.so (0x0000007f907f5000)
        libGLdispatch.so.0 => /usr/lib/aarch64-linux-gnu/libGLdispatch.so.0 (0x0000007f906c9000)
        libnvimp.so => /usr/lib/aarch64-linux-gnu/tegra/libnvimp.so (0x0000007f906b4000)
undefined symbol: PyInstanceMethod_Type (tensorrt/tensorrt.so)
undefined symbol: PyExc_ValueError      (tensorrt/tensorrt.so)
undefined symbol: _Py_TrueStruct        (tensorrt/tensorrt.so)
undefined symbol: PyExc_IndexError      (tensorrt/tensorrt.so)
undefined symbol: PyCapsule_Type        (tensorrt/tensorrt.so)
undefined symbol: PyModule_Type (tensorrt/tensorrt.so)
undefined symbol: _PyObject_NextNotImplemented  (tensorrt/tensorrt.so)
undefined symbol: PySlice_Type  (tensorrt/tensorrt.so)
undefined symbol: PyMemoryView_Type     (tensorrt/tensorrt.so)
undefined symbol: _Py_NoneStruct        (tensorrt/tensorrt.so)
undefined symbol: PyExc_MemoryError     (tensorrt/tensorrt.so)
undefined symbol: PyType_Type   (tensorrt/tensorrt.so)
undefined symbol: PyByteArray_Type      (tensorrt/tensorrt.so)
undefined symbol: PyCFunction_Type      (tensorrt/tensorrt.so)
undefined symbol: PyExc_OverflowError   (tensorrt/tensorrt.so)
undefined symbol: PyProperty_Type       (tensorrt/tensorrt.so)
undefined symbol: PyExc_BufferError     (tensorrt/tensorrt.so)
undefined symbol: PyExc_DeprecationWarning      (tensorrt/tensorrt.so)
undefined symbol: PyExc_RuntimeError    (tensorrt/tensorrt.so)
undefined symbol: _Py_NotImplementedStruct      (tensorrt/tensorrt.so)
undefined symbol: PyBaseObject_Type     (tensorrt/tensorrt.so)
undefined symbol: PyExc_StopIteration   (tensorrt/tensorrt.so)
undefined symbol: PyExc_TypeError       (tensorrt/tensorrt.so)
undefined symbol: PyMethod_Type (tensorrt/tensorrt.so)
undefined symbol: _Py_FalseStruct       (tensorrt/tensorrt.so)
undefined symbol: PyDict_Type   (tensorrt/tensorrt.so)
undefined symbol: PyFloat_Type  (tensorrt/tensorrt.so)
undefined symbol: PyExc_SystemError     (tensorrt/tensorrt.so)
undefined symbol: PyExc_ImportError     (tensorrt/tensorrt.so)
undefined symbol: PyMemoryView_FromObject       (tensorrt/tensorrt.so)
undefined symbol: PyTuple_SetItem       (tensorrt/tensorrt.so)
undefined symbol: PyObject_GetBuffer    (tensorrt/tensorrt.so)
undefined symbol: PyObject_Repr (tensorrt/tensorrt.so)
undefined symbol: PyLong_AsLong (tensorrt/tensorrt.so)
undefined symbol: PyLong_FromSsize_t    (tensorrt/tensorrt.so)
undefined symbol: PyByteArray_Size      (tensorrt/tensorrt.so)
undefined symbol: PyObject_Call (tensorrt/tensorrt.so)
undefined symbol: PyNumber_And  (tensorrt/tensorrt.so)
undefined symbol: PyFrame_FastToLocals  (tensorrt/tensorrt.so)
undefined symbol: PyErr_NormalizeException      (tensorrt/tensorrt.so)
undefined symbol: PyInstanceMethod_New  (tensorrt/tensorrt.so)
undefined symbol: PyEval_AcquireThread  (tensorrt/tensorrt.so)
undefined symbol: PyObject_Str  (tensorrt/tensorrt.so)
undefined symbol: PyThreadState_DeleteCurrent   (tensorrt/tensorrt.so)
undefined symbol: PyGILState_GetThisThreadState (tensorrt/tensorrt.so)
undefined symbol: PyObject_GetAttrString        (tensorrt/tensorrt.so)
undefined symbol: PyMem_Free    (tensorrt/tensorrt.so)
undefined symbol: PyErr_Restore (tensorrt/tensorrt.so)
undefined symbol: PyType_IsSubtype      (tensorrt/tensorrt.so)
undefined symbol: PyModule_AddObject    (tensorrt/tensorrt.so)
undefined symbol: PyErr_WarnEx  (tensorrt/tensorrt.so)
undefined symbol: PyCapsule_SetPointer  (tensorrt/tensorrt.so)
undefined symbol: PyTuple_New   (tensorrt/tensorrt.so)
undefined symbol: PyObject_SetAttr      (tensorrt/tensorrt.so)
undefined symbol: PyObject_IsInstance   (tensorrt/tensorrt.so)
undefined symbol: PyEval_RestoreThread  (tensorrt/tensorrt.so)
undefined symbol: PyException_SetTraceback      (tensorrt/tensorrt.so)
undefined symbol: PyNumber_Float        (tensorrt/tensorrt.so)
undefined symbol: PyUnicode_FromFormat  (tensorrt/tensorrt.so)
undefined symbol: PyList_Append (tensorrt/tensorrt.so)
undefined symbol: PySlice_AdjustIndices (tensorrt/tensorrt.so)
undefined symbol: PyDict_Contains       (tensorrt/tensorrt.so)
undefined symbol: PyDict_Next   (tensorrt/tensorrt.so)
undefined symbol: PyList_Size   (tensorrt/tensorrt.so)
undefined symbol: PyTuple_Size  (tensorrt/tensorrt.so)
undefined symbol: PyMemoryView_FromBuffer       (tensorrt/tensorrt.so)
undefined symbol: PyNumber_Long (tensorrt/tensorrt.so)
undefined symbol: PyBuffer_Release      (tensorrt/tensorrt.so)
undefined symbol: _ZN8tensorrt8bindInt8ERN8pybind117module_E    (tensorrt/tensorrt.so)
undefined symbol: PyObject_GetIter      (tensorrt/tensorrt.so)
undefined symbol: PyErr_Format  (tensorrt/tensorrt.so)
undefined symbol: PyObject_CallObject   (tensorrt/tensorrt.so)
undefined symbol: PyFloat_FromDouble    (tensorrt/tensorrt.so)
undefined symbol: PyFloat_AsDouble      (tensorrt/tensorrt.so)
undefined symbol: PyUnicode_DecodeUTF8  (tensorrt/tensorrt.so)
undefined symbol: _Py_Dealloc   (tensorrt/tensorrt.so)
undefined symbol: PyByteArray_AsString  (tensorrt/tensorrt.so)
undefined symbol: PyCFunction_NewEx     (tensorrt/tensorrt.so)
undefined symbol: PyList_New    (tensorrt/tensorrt.so)
undefined symbol: PyImport_ImportModule (tensorrt/tensorrt.so)
undefined symbol: PyNumber_Check        (tensorrt/tensorrt.so)
undefined symbol: _PyObject_GetDictPtr  (tensorrt/tensorrt.so)
undefined symbol: PyUnicode_FromString  (tensorrt/tensorrt.so)
undefined symbol: Py_GetVersion (tensorrt/tensorrt.so)
undefined symbol: PyCapsule_SetContext  (tensorrt/tensorrt.so)
undefined symbol: PyFrame_GetLineNumber (tensorrt/tensorrt.so)
undefined symbol: PyThread_tss_get      (tensorrt/tensorrt.so)
undefined symbol: PyBytes_Size  (tensorrt/tensorrt.so)
undefined symbol: PySequence_Check      (tensorrt/tensorrt.so)
undefined symbol: PyList_GetItem        (tensorrt/tensorrt.so)
undefined symbol: PyException_SetContext        (tensorrt/tensorrt.so)
undefined symbol: PyErr_Clear   (tensorrt/tensorrt.so)
undefined symbol: PyObject_HasAttrString        (tensorrt/tensorrt.so)
undefined symbol: PyWeakref_NewRef      (tensorrt/tensorrt.so)
undefined symbol: PyDict_New    (tensorrt/tensorrt.so)
undefined symbol: PyErr_SetString       (tensorrt/tensorrt.so)
undefined symbol: PyEval_InitThreads    (tensorrt/tensorrt.so)
undefined symbol: PyCapsule_GetContext  (tensorrt/tensorrt.so)
undefined symbol: PyThreadState_Get     (tensorrt/tensorrt.so)
undefined symbol: PyObject_SetItem      (tensorrt/tensorrt.so)
undefined symbol: PySlice_Unpack        (tensorrt/tensorrt.so)
undefined symbol: PyCapsule_New (tensorrt/tensorrt.so)
undefined symbol: PyMem_Calloc  (tensorrt/tensorrt.so)
undefined symbol: PyObject_SetAttrString        (tensorrt/tensorrt.so)
undefined symbol: PyGILState_Release    (tensorrt/tensorrt.so)
undefined symbol: PyCapsule_GetPointer  (tensorrt/tensorrt.so)
undefined symbol: PyNumber_Xor  (tensorrt/tensorrt.so)
undefined symbol: PyThread_tss_alloc    (tensorrt/tensorrt.so)
undefined symbol: PyBytes_AsString      (tensorrt/tensorrt.so)
undefined symbol: PyObject_LengthHint   (tensorrt/tensorrt.so)
undefined symbol: PyDict_GetItemWithError       (tensorrt/tensorrt.so)
undefined symbol: PyThread_tss_set      (tensorrt/tensorrt.so)
undefined symbol: PyObject_GetItem      (tensorrt/tensorrt.so)
undefined symbol: PyType_Ready  (tensorrt/tensorrt.so)
undefined symbol: PyEval_SaveThread     (tensorrt/tensorrt.so)
undefined symbol: PySequence_GetItem    (tensorrt/tensorrt.so)
undefined symbol: PyNumber_Invert       (tensorrt/tensorrt.so)
undefined symbol: PyObject_ClearWeakRefs        (tensorrt/tensorrt.so)
undefined symbol: PySequence_Size       (tensorrt/tensorrt.so)
undefined symbol: PyLong_FromLong       (tensorrt/tensorrt.so)
undefined symbol: PyEval_GetBuiltins    (tensorrt/tensorrt.so)
undefined symbol: PyErr_WriteUnraisable (tensorrt/tensorrt.so)
undefined symbol: PyObject_RichCompareBool      (tensorrt/tensorrt.so)
undefined symbol: PyNumber_Or   (tensorrt/tensorrt.so)
undefined symbol: PyModule_Create2      (tensorrt/tensorrt.so)
undefined symbol: PyThread_tss_create   (tensorrt/tensorrt.so)
undefined symbol: PyLong_AsUnsignedLong (tensorrt/tensorrt.so)
undefined symbol: PyLong_FromSize_t     (tensorrt/tensorrt.so)
undefined symbol: PyErr_Occurred        (tensorrt/tensorrt.so)
undefined symbol: PyDict_Copy   (tensorrt/tensorrt.so)
undefined symbol: PyErr_Fetch   (tensorrt/tensorrt.so)
undefined symbol: PyThreadState_New     (tensorrt/tensorrt.so)
undefined symbol: _PyThreadState_UncheckedGet   (tensorrt/tensorrt.so)
undefined symbol: _PyType_Lookup        (tensorrt/tensorrt.so)
undefined symbol: PyObject_CallFunctionObjArgs  (tensorrt/tensorrt.so)
undefined symbol: PyDict_Size   (tensorrt/tensorrt.so)
undefined symbol: PyIter_Next   (tensorrt/tensorrt.so)
undefined symbol: PyCallable_Check      (tensorrt/tensorrt.so)
undefined symbol: PySequence_Tuple      (tensorrt/tensorrt.so)
undefined symbol: PyThreadState_Clear   (tensorrt/tensorrt.so)
undefined symbol: PyDict_DelItemString  (tensorrt/tensorrt.so)
undefined symbol: PyUnicode_AsUTF8AndSize       (tensorrt/tensorrt.so)
undefined symbol: PyGILState_Ensure     (tensorrt/tensorrt.so)
undefined symbol: PyObject_Malloc       (tensorrt/tensorrt.so)
undefined symbol: PyCapsule_GetName     (tensorrt/tensorrt.so)
undefined symbol: PyTuple_GetItem       (tensorrt/tensorrt.so)
undefined symbol: PyException_SetCause  (tensorrt/tensorrt.so)
undefined symbol: PyUnicode_AsUTF8String        (tensorrt/tensorrt.so)
undefined symbol: PyBytes_AsStringAndSize       (tensorrt/tensorrt.so)
```

**Comment by jstumpin** [comment] 2022-05-23 09:48
The origin of the error is actually somewhere else (at least for me). Swapping these sections resolved it for me: 
https://github.com/pybind/pybind11/blob/master/include/pybind11/cast.h#L1177-L1189
https://github.com/pybind/pybind11/blob/stable/include/pybind11/cast.h#L1180-L1189
Seems like an unreported regression issue in the latest [pybind11](https://github.com/pybind/pybind11).

**Comment by PieterBlomme** [comment] 2022-06-03 12:59
I ran into this issue aswell.  Perhaps it would be better if the README recommends
`git clone -b stable https://github.com/pybind/pybind11.git`

Instead?  

And perhaps also include
`set -e`
in build.sh because right now it will proceed to generate the wheel even if cmake fails

**Comment by nvpohanh** [comment] 2022-06-05 01:42
Maybe we should pin to stable pybind11 branch instead of master? @rajeevsrao thoughts?

**Comment by pranavm-nvidia** [comment] 2022-06-06 14:05
Yes, we should pin the version to 2.6.2, which is what we use internally.

**Comment by nvpohanh** [comment] 2022-06-08 07:38
@pranavm-nvidia Could you file an MR and a PR to fix this? Thanks

**Comment by nvpohanh** [comment] 2022-06-15 05:19
Pybind version has been pinned now: https://github.com/NVIDIA/TensorRT/blob/main/python/README.md

Closing this issue.

**Closed by nvpohanh** 2022-06-15 05:19 UTC
Labels: Component: OSS Build, triaged

**Comment by huubvh95** [comment] 2022-07-18 09:27
The problem is occurring again for this combination:
```
git clone -b stable https://github.com/pybind/pybind11.git
git clone -b release/8.2 https://github.com/NVIDIA/TensorRT.git
```

The error is the following:
```
Scanning dependencies of target tensorrt
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyAlgorithmSelector.cpp.o
[ 16%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyCore.cpp.o
[ 25%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyFoundationalTypes.cpp.o
[ 33%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyGraph.cpp.o
[ 41%] Building CXX object CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o
In file included from /home/im1/TensorRT/python/include/ForwardDeclarations.h:29,
                 from /home/im1/TensorRT/python/src/infer/pyInt8.cpp:18:
/home/im1/TensorRT/python/src/infer/pyInt8.cpp: In member function ‘virtual const void* tensorrt::pyIInt8LegacyCalibrator::readHistogramCache(std::size_t&)’:
/home/im1/pybind11/include/pybind11/pybind11.h:2760:70: error: void value not ignored as it ought to be
             return pybind11::detail::cast_safe<ret_type>(std::move(o));                           \
                                                                      ^
/home/im1/pybind11/include/pybind11/pybind11.h:2794:9: note: in expansion of macro ‘PYBIND11_OVERRIDE_IMPL’
         PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(ret_type), PYBIND11_TYPE(cname), name, __VA_ARGS__); \
         ^~~~~~~~~~~~~~~~~~~~~~
/home/im1/pybind11/include/pybind11/pybind11.h:2853:5: note: in expansion of macro ‘PYBIND11_OVERRIDE_PURE_NAME’
     PYBIND11_OVERRIDE_PURE_NAME(                                                                  \
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/im1/TensorRT/python/src/infer/pyInt8.cpp:135:9: note: in expansion of macro ‘PYBIND11_OVERLOAD_PURE_NAME’
         PYBIND11_OVERLOAD_PURE_NAME(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/tensorrt.dir/build.make:115: CMakeFiles/tensorrt.dir/src/infer/pyInt8.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/tensorrt.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```
