### ISSUE TITLE
got CUDNN_STATUS_MAPPING_ERROR when using tensorrt and pytorch together

### ISSUE THREAD

**Issue by lihaoxiang1989** [NVIDIA/TensorRT#985] opened 2020-12-28 02:45 UTC
## Description

I got this error when using Tensorrt and PyTorch together. I used PyTorch GPU calculation for the preprocessing.
`[TensorRT] ERROR: safeContext.cpp (184) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)`
`[TensorRT] ERROR: FAILED_EXECUTION: std::exception`

I also found when splitting them to different processes, the error disappears. But in my case, I have a very large image data to be used in post-process, which would add extra latency during passing it between the processes.

## Environment

**TensorRT Version**: 7.2.1
**GPU Type**: V100
**Nvidia Driver Version**: 440.64.00
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.3
**Operating System + Version**: Ubuntu 18.04.1
**Python Version (if applicable)**: python 3.7
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: pytorch1.6
**Baremetal or Container (if container which image + tag)**:

**Comment by nvpohanh** [comment] 2020-12-28 07:18
Could it be caused by this PyTorch bug in https://github.com/pytorch/pytorch/issues/32983 which caused CUDNN version mismatch? It was fixed in PyTorch 1.7 via https://github.com/pytorch/pytorch/pull/41986, so might be worth giving it a try.

**Comment by lihaoxiang1989** [comment] 2020-12-28 07:42
> Could it be caused by this PyTorch bug in [pytorch/pytorch#32983](https://github.com/pytorch/pytorch/issues/32983) which caused CUDNN version mismatch? It was fixed in PyTorch 1.7 via [pytorch/pytorch#41986](https://github.com/pytorch/pytorch/pull/41986), so might be worth giving it a try.

I just tried to upgrade PyTorch to 1.7.1, but the same Error comes out

**Comment by nvpohanh** [comment] 2020-12-28 08:15
Does this work? https://discuss.pytorch.org/t/runtimeerror-cudnn-status-mapping-error/4370/9

namely, `net.cuda()` where `net` is your PyTorch network?

**Comment by lihaoxiang1989** [comment] 2020-12-28 08:54
> Does this work? https://discuss.pytorch.org/t/runtimeerror-cudnn-status-mapping-error/4370/9
> 
> namely, `net.cuda()` where `net` is your PyTorch network?

No, I tried to use cupy instead of PyTorch and also got this error ;(

**Comment by lihaoxiang1989** [comment] 2021-01-06 07:35
I finally make this works. By adding cuda context push and pop on the two ends of doing inference

**Closed** 2021-01-06 07:52 UTC

**Comment by cyymt** [comment] 2021-04-21 08:25
@lihaoxiang1989 can you share your code?

**Comment by lihaoxiang1989** [comment] 2021-04-25 03:04
> @lihaoxiang1989 can you share your code?
you should init the cuda context manually

import pycuda.driver as cuda

...
cuda.init()
cuda_ctx = cuda.Device(gpu_id).make_context()

cuda_ctx.push()
... tensorrt inference
cuda_ctx.pop()
