### ISSUE TITLE
Mnist sample execution fails with no error message.

### ISSUE THREAD

**Issue by cipher009** [NVIDIA/TensorRT#293] opened 2019-12-23 15:29 UTC
## Description

At the execution of `sample_mnist.exe`, the run fails with no error message.
Console prints the following:

```
&&&& RUNNING TensorRT.sample_uff_mnist # sample_uff_mnist.exe
[12/23/2019-17:23:54] [I] Building and running a GPU inference engine for Uff MNIST


```
## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 2080ti
**Nvidia Driver Version**: 
**CUDA Version**: 10
**CUDNN Version**: 7.6
**Operating System + Version**: Windows10
**Python Version (if applicable)**: 3.5
**TensorFlow Version (if applicable)**: 2.0 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if container which image + tag)**:

**Comment by rmccorm4** [comment] 2019-12-23 21:37
Hi @cipher009,

Did it finish? Or it just hangs? How do you know it failed?

**Comment by cipher009** [comment] 2019-12-23 21:39
It finished with no errors and no results

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by rmccorm4** [comment] 2019-12-23 21:43
Does it happen if you run the sample multiple times repeatedly?

**Comment by cipher009** [comment] 2019-12-23 21:45
Yes tried multiple times

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by rmccorm4** [comment] 2019-12-23 21:52
It seems like calls to `gLogInfo` are producing output for you, but not `gLogger.report*` - as for that I'm not quite sure why. I would suspect it's related to running on Windows since I've seen it run successfully on Linux plenty of times. 

Maybe someone more familiar could chime in on that.

**Comment by rmccorm4** [comment] 2020-01-25 23:48
Can't reproduce, closing for now. FYI UFF parser will be deprecated in the future, perhaps try the ONNX sample: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleOnnxMNIST

**Closed by rmccorm4** 2020-01-25 23:48 UTC
Labels: Conversion: UFF, Release: 7.x, sample
