### ISSUE TITLE
[E] [TRT] ../rtSafe/coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)

### ISSUE THREAD

**Issue by hmcmmmmm** [NVIDIA/TensorRT#702] opened 2020-07-23 03:33 UTC
## Description

Found an error with T4 GPU inference with TensorRT
I double confirm the driver /cuda /tensorrt version compatibility, it's ok with nvidia description.

Could you can help me to this issue? 

ERROR INFO:
root@9bccfc2bad7b:/mnt# unzip trt7_resnet50_fp32_t4_1.zip
Archive:  trt7_resnet50_fp32_t4_1.zip
  inflating: config.pbtxt
  inflating: imagenet1k_labels.txt
  inflating: resnet50.fp32.T4.engine
root@9bccfc2bad7b:/mnt# /workspace/tensorrt/bin/trtexec --batch=128 --iterations=1000 --workspace=2048 --percentile=99 --loadEngine=resnet50.fp32.T4.engine
&&&& RUNNING TensorRT.trtexec # /workspace/tensorrt/bin/trtexec --batch=128 --iterations=1000 --workspace=2048 --percentile=99 --loadEngine=resnet50.fp32.T4.engine
[07/23/2020-03:13:28] [I] === Model Options ===
[07/23/2020-03:13:28] [I] Format: *
[07/23/2020-03:13:28] [I] Model:
[07/23/2020-03:13:28] [I] Output:
[07/23/2020-03:13:28] [I] === Build Options ===
[07/23/2020-03:13:28] [I] Max batch: 128
[07/23/2020-03:13:28] [I] Workspace: 2048 MB
[07/23/2020-03:13:28] [I] minTiming: 1
[07/23/2020-03:13:28] [I] avgTiming: 8
[07/23/2020-03:13:28] [I] Precision: FP32
[07/23/2020-03:13:28] [I] Calibration:
[07/23/2020-03:13:28] [I] Safe mode: Disabled
[07/23/2020-03:13:28] [I] Save engine:
[07/23/2020-03:13:28] [I] Load engine: resnet50.fp32.T4.engine
[07/23/2020-03:13:28] [I] Inputs format: fp32:CHW
[07/23/2020-03:13:28] [I] Outputs format: fp32:CHW
[07/23/2020-03:13:28] [I] Input build shapes: model
[07/23/2020-03:13:28] [I] === System Options ===
[07/23/2020-03:13:28] [I] Device: 0
[07/23/2020-03:13:28] [I] DLACore:
[07/23/2020-03:13:28] [I] Plugins:
[07/23/2020-03:13:28] [I] === Inference Options ===
[07/23/2020-03:13:28] [I] Batch: 128
[07/23/2020-03:13:28] [I] Iterations: 1000
[07/23/2020-03:13:28] [I] Duration: 3s (+ 200ms warm up)
[07/23/2020-03:13:28] [I] Sleep time: 0ms
[07/23/2020-03:13:28] [I] Streams: 1
[07/23/2020-03:13:28] [I] ExposeDMA: Disabled
[07/23/2020-03:13:28] [I] Spin-wait: Disabled
[07/23/2020-03:13:28] [I] Multithreading: Disabled
[07/23/2020-03:13:28] [I] CUDA Graph: Disabled
[07/23/2020-03:13:28] [I] Skip inference: Disabled
[07/23/2020-03:13:28] [I] Input inference shapes: model
[07/23/2020-03:13:28] [I] Inputs:
[07/23/2020-03:13:28] [I] === Reporting Options ===
[07/23/2020-03:13:28] [I] Verbose: Disabled
[07/23/2020-03:13:28] [I] Averages: 10 inferences
[07/23/2020-03:13:28] [I] Percentile: 99
[07/23/2020-03:13:28] [I] Dump output: Disabled
[07/23/2020-03:13:28] [I] Profile: Disabled
[07/23/2020-03:13:28] [I] Export timing to JSON file:
[07/23/2020-03:13:28] [I] Export output to JSON file:
[07/23/2020-03:13:28] [I] Export profile to JSON file:
[07/23/2020-03:13:28] [I]
[07/23/2020-03:13:28] [E] [TRT] ../rtSafe/coreReadArchive.cpp (38) - Serialization Error in verifyHeader: 0 (Version tag does not match)
[07/23/2020-03:13:28] [E] [TRT] INVALID_STATE: std::exception
[07/23/2020-03:13:28] [E] [TRT] INVALID_CONFIG: Deserialize the cuda engine failed.
[07/23/2020-03:13:28] [E] Engine creation failed
[07/23/2020-03:13:28] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # /workspace/tensorrt/bin/trtexec --batch=128 --iterations=1000 --workspace=2048 --percentile=99 --loadEngine=resnet50.fp32.T4.engine

## Environment

**TensorRT Version**: 7.0
**GPU Type**: T4
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: in docker images (nvcr.io/nvidia/tensorrt:20.01-py3)
**CUDNN Version**: in docker images (nvcr.io/nvidia/tensorrt:20.01-py3)
**Operating System + Version**: ubuntu18.04
**Python Version (if applicable)**: in docker images (nvcr.io/nvidia/tensorrt:20.01-py3)
**TensorFlow Version (if applicable)**: in docker images (nvcr.io/nvidia/tensorrt:20.01-py3)
**PyTorch Version (if applicable)**: non
**Baremetal or Container (if container which image + tag)**: container

## Steps To Reproduce
1. Install driver
2. with command enter docker
3. exec command: /workspace/tensorrt/bin/trtexec --batch=128 --iterations=1000 --workspace=2048 --percentile=99 --loadEngine=resnet50.fp32.T4.engine

**Comment by hmcmmmmm** [comment] 2020-07-23 03:36
model name for NV: trt7_resnet50_fp32_t4_1.zip

**Comment by rmccorm4** [comment] 2020-07-23 03:39
Hi @hmcmmmmm ,

I believe there's currently an issue with those pre-made trt7 engines. However, it's preferred the engines are built on the same machine they run on anyways.

So you can easily re-create the engine yourself like so:
```bash
wget https://s3.amazonaws.com/download.onnx/models/opset_8/resnet50.tar.gz
tar -xvzf resnet50.tar.gz
trtexec --explicitBatch --onnx=resnet50/model.onnx --saveEngine=resnet50.fp32.T4.engine
```

**Comment by hmcmmmmm** [comment] 2020-07-23 03:52
> Hi @hmcmmmmm ,
> 
> I believe there's currently an issue with those pre-made trt7 engines. However, it's preferred (better performance) that the engines are built on the same machine they run on anyways.
> 
> So you can easily re-create the engine yourself like so:
> 
> ```shell
> wget https://s3.amazonaws.com/download.onnx/models/opset_8/resnet50.tar.gz
> tar -xvzf resnet50.tar.gz
> trtexec --explicitBatch --onnx=resnet50/model.onnx --saveEngine=resnet50.fp32.T4.engine
> ```

Hi rmccorm4  
Thanks very much for you help , i will try soon

**Comment by hmcmmmmm** [comment] 2020-07-23 04:09
> Hi @hmcmmmmm ,
> 
> I believe there's currently an issue with those pre-made trt7 engines. However, it's preferred (better performance) that the engines are built on the same machine they run on anyways.
> 
> So you can easily re-create the engine yourself like so:
> 
> ```shell
> wget https://s3.amazonaws.com/download.onnx/models/opset_8/resnet50.tar.gz
> tar -xvzf resnet50.tar.gz
> trtexec --explicitBatch --onnx=resnet50/model.onnx --saveEngine=resnet50.fp32.T4.engine
> ```



> Hi @hmcmmmmm ,
> 
> I believe there's currently an issue with those pre-made trt7 engines. However, it's preferred (better performance) that the engines are built on the same machine they run on anyways.
> 
> So you can easily re-create the engine yourself like so:
> 
> ```shell
> wget https://s3.amazonaws.com/download.onnx/models/opset_8/resnet50.tar.gz
> tar -xvzf resnet50.tar.gz
> trtexec --explicitBatch --onnx=resnet50/model.onnx --saveEngine=resnet50.fp32.T4.engine
> ```

Hi rmccorm4 ,  
How to create fp16 and int8 engine?  THANKS

**Comment by rmccorm4** [comment] 2020-07-23 07:56
Hi, just add the `--fp16` flag for FP16 to `trtexec`. And add both `--fp16 --int8` for INT8. `trtexec` is mostly used for benchmarking performance purposes.

**Comment by hmcmmmmm** [comment] 2020-07-24 01:54
Got it, thanks rmccorm4

**Comment by depthwise** [comment] 2020-07-25 11:24
Same here, except I'm creating the engine on the jsame Jetson Xavier where I'm trying to execute it. @hmcmmmmm did you ever get this to work?

**Comment by depthwise** [comment] 2020-07-27 07:24
Also confirmed: if I don't save the engine first and use it right after conversion, it works fine.

**Comment by depthwise** [comment] 2020-07-27 09:15
And also: this only seems to be a problem on the Jetson for me. Running the exact same code on a PC, it works fine.

**Comment by depthwise** [comment] 2020-07-28 06:59
HM, never mind. I'm not sure what I did, but it seems to be load an engine on the Jetson now.

**Comment by mk-nvidia** [comment] 2020-10-27 20:53
Closing based on the comments above. Please respond here if this is still a problem.

**Closed by mk-nvidia** 2020-10-27 20:53 UTC
