### ISSUE TITLE
Assertion Error in mergeDAG: 0 (d2Inputs.size() == n2.inputs.size())

### ISSUE THREAD

**Issue by CemalAker** [NVIDIA/TensorRT#548] opened 2020-05-13 15:58 UTC
## Description

I am planning to deploy my network on a Jetson TX2 device. Hence I have exported onnx model from PyTorch and tried to deploy using TensorRT 6. While doing so, I have encountered problems about some operators etc. and TensorRT 7 was the solution for me on the PC. I have deployed the network successfully on PC. Afterwards, I have flashed the TX2 device with JetPack 4.4 DP since it includes TensorRT 7.1 and done the exact same things to deploy it. However it failed with the following error

**../builder/cudnnBuilderGraphOptimizer.cpp (3124) - Assertion Error in mergeDAG: 0 (d2Inputs.size() == n2.inputs.size())**

In order to serialize the engine, I use the following command:
**trtexec --onnx="network.onnx" --minShapes='input':1x512x8x8 --optShapes='input':1x512x64x64 --maxShapes='input':1x512x128x128 --saveEngine="net.trt" --verbose --explicitBatch**

## Environment 1

**TensorRT Version**: 7.0.0.11
**GPU Type**: GTX 1080
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5.32
**Operating System + Version**: Ubuntu 16.04

## Environment 2

**TensorRT Version**: 7.1.0 (Developer Preview)
**GPU Type**: Jetson TX2
**CUDA Version**: 10.2
**CUDNN Version**: 8.0.0 (Developer Preview)

## Relevant Files
[network.onnx](https://drive.google.com/open?id=1KQ8edWrYal6WHLf7wYcVGo2sUlaYp_KY)

## Steps To Reproduce
run the following command with correct path of trtexec

**trtexec --onnx="network.onnx" --minShapes='input':1x512x8x8 --optShapes='input':1x512x64x64 --maxShapes='input':1x512x128x128 --saveEngine="net.trt" --verbose --explicitBatch**

**Comment by rmccorm4** [comment] 2020-05-14 15:43
Hi @CemalAker ,

Can you share the ONNX model that reproduces this?

**Comment by CemalAker** [comment] 2020-05-15 14:31
> Hi @CemalAker ,
> 
> Can you share the ONNX model that reproduces this?

It has been added to the original entry.

**Comment by CemalAker** [comment] 2020-08-21 08:42
I have tested the same network with different environments. It still works on PC but **not on TX2**.

## Environment 3
**TensorRT Version**: 7.1.3.0
**GPU Type**: GTX 1080
**Nvidia Driver Version**: 440
**CUDA Version**: 10.1
**CUDNN Version**: 8.0.2
**Operating System + Version**: Ubuntu 18.04

Successful with Environment 3.

## Environment 4
**TensorRT Version**: 7.3.1 (jetpack 4.4)
**GPU Type**: Jetson TX2
**CUDA Version**: 10.2.89
**CUDNN Version**: 8.0.0 (jetpack 4.4)

**Error : 
../builder/cudnnBuilderGraphOptimizer.cpp (3127) - Assertion Error in
mergeDAG: 0 (d2Inputs.size() == n2.inputs.size())**

**Comment by a060146251** [comment] 2020-11-09 10:32
Did you solve this problem? thanks

**Comment by OronG13** [comment] 2020-12-15 18:39
Hello,
I also get this problem with my onnx model while running it on My Jetson Xavier which use JetPack 4.4.
When I run the same onnx model on my PC which include the TRT 7.2.1.6, CuDNN 8.0.4 7 CUDA 11.0 it works fine.

Anyone has any clue what is the problem source and how to fix it?
Thanks,

**Comment by NikolasMarkou** [comment] 2021-04-21 06:50
@OronG13 @CemalAker I had the same problem and fixed it.
You have to restructure your graph to avoid situations like this 
![image](https://user-images.githubusercontent.com/1175820/115509295-ee2a5080-a286-11eb-8dd2-07d7f79c4bd2.png) 
MUL node with the same input twice. You should replace this POW node and the second input a constant 2.

**Comment by ttyio** [comment] 2021-05-27 07:26
Closing since there is solution according to last comment, thanks

**Closed by ttyio** 2021-05-27 07:26 UTC
Labels: Component: ONNX, Platform: Jetson, Release: 7.x, good-reference, regression, triaged
