### ISSUE TITLE
8.6.1.6: No Myelin Error exits failure (stream_tile_size_solver.hpp:62: DCHECK(ub >= lb) failed) on GPU 3090

### ISSUE THREAD

**Issue by YUjunuuuuu** [NVIDIA/TensorRT#3411] opened 2023-10-31 01:27 UTC
## Description

I tried to convert onnx to trt,but it fails with the error below
[10/31/2023-00:27:21] [I] [TRT] Detected 5 inputs and 2 output network tensors.
[10/31/2023-00:27:28] [V] [TRT]  (foreignNode) Set user's cuda kernel library
[10/31/2023-00:27:33] [V] [TRT]  (foreignNode) Set user's cuda kernel library
stream_tile_size_solver.hpp:62: DCHECK(ub >= lb) failed. 
[10/31/2023-00:29:12] [V] [TRT] Deleting timing cache: 150 entries, served 7116 hits since creation.
[10/31/2023-00:29:12] [E] Error[1]: No Myelin Error exists
[10/31/2023-00:29:12] [E] Error[1]: [codeGenerator.cpp::compileGraph::894] Error Code 1: Myelin (No Myelin Error exists)
[10/31/2023-00:29:12] [E] Engine could not be created from network
[10/31/2023-00:29:12] [E] Building engine failed
[10/31/2023-00:29:12] [E] Failed to create engine from model or file.
[10/31/2023-00:29:12] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8601] # ./trtexec --onnx=/home/pc/Documents/eco-tr/ecotr/my_modify/entirety/mid_transformer_30_simple.onnx --minShapes=queries:1x200x2,final_corrs:1x200x2 --optShapes=queries:1x2000x2,final_corrs:1x2000x2 --maxShapes=queries:1x5000x2,final_corrs:1x5000x2 --saveEngine=/home/pc/Documents/eco-tr/ecotr/my_modify/entirety/mid_transformer1.engine --verbose

## Environment

**TensorRT Version**:
8.6.1.6
**NVIDIA GPU**:
3090
**NVIDIA Driver Version**:
11.1
**CUDA Version**:
11.1
**CUDNN Version**:

Operating System:
ubuntu 20.04
Python Version (if applicable):
3.8
Tensorflow Version (if applicable):

PyTorch Version (if applicable):
2.1
Baremetal or Container (if so, version):

## Relevant Files

**Model link**:
https://drive.google.com/file/d/1ZZMM_1uXNUnZZxL72Jd9I9FJks3eoXzI/view?usp=sharing

## Steps To Reproduce

**Commands or scripts**:
./trtexec --onnx=/home/pc/Documents/eco-tr/ecotr/my_modify/entirety/mid_transformer_30_simple.onnx --minShapes=queries:1x200x2,final_corrs:1x200x2 --optShapes=queries:1x2000x2,final_corrs:1x2000x2 --maxShapes=queries:1x5000x2,final_corrs:1x5000x2 --saveEngine=/home/pc/Documents/eco-tr/ecotr/my_modify/entirety/mid_transformer1.engine --verbose
**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**:
yes
**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):
yes

**Comment by zerollzeng** [comment] 2023-11-04 01:44
Looks like a cuda env issue, could you please try our official docker? e.g. nvcr.io/nvidia/pytorch:23.06-py3 for 8.6.1..6

**Comment by YUjunuuuuu** [comment] 2023-11-06 07:08
@zerollzeng I try the nvcr.io/nvidia/pytorch:23.06-py3 for 8.6.1..6,but it occurs the same error

**Comment by zerollzeng** [comment] 2023-11-12 14:37
I can reproduce the issue and file internal bug 4375138 for this.

**Comment by zerollzeng** [comment] 2023-11-21 06:25
@YUjunuuuuu Your model isn't a valid ONNX with specified input shapes, it can't be infer with onnxruntime
```
$ polygraphy run mid_transformer_30_simple.onnx --onnxrt --input-shapes queries:[1,2000,2] final_corrs:[1,2000,2]
[I] RUNNING | Command: /home/scratch.zeroz_sw/miniconda3/bin/polygraphy run mid_transformer_30_simple.onnx --onnxrt --input-shapes queries:[1,2000,2] final_corrs:[1,2000,2]
[I] Will generate inference input data according to provided TensorMetadata: {queries [shape=(1, 2000, 2)],
     final_corrs [shape=(1, 2000, 2)]}
[I] onnxrt-runner-N0-11/21/23-01:51:34  | Activating and starting inference
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
[I] onnxrt-runner-N0-11/21/23-01:51:34 
    ---- Inference Input(s) ----
    {mid_src [dtype=float32, shape=(1, 128, 52, 156)],
     queries [dtype=float32, shape=(1, 2000, 2)],
     final_corrs [dtype=float32, shape=(1, 2000, 2)]}
2023-11-21 01:51:59.509895208 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/mid_transformer/mid_transformer_2/Reshape_1' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:35 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,128,17,34}, requested shape:{0,128,-1}

Traceback (most recent call last):
  File "/home/scratch.zeroz_sw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 25, in <module>
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 132, in execute_runner
    outputs = active_runner.infer(feed_dict=feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/base/runner.py", line 177, in infer
    return self.infer_impl(feed_dict, *args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/util/util.py", line 694, in wrapped
    return func(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/onnxrt/runner.py", line 73, in infer_impl
    inference_outputs = self.sess.run(None, feed_dict)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'/mid_transformer/mid_transformer_2/Reshape_1' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:35 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,128,17,34}, requested shape:{0,128,-1}
```

**Comment by zerollzeng** [comment] 2023-11-29 06:33
Closed this, please reopen if you have any further questions. Thanks!

**Closed by zerollzeng** 2023-11-29 06:33 UTC
Labels: triaged, internal-bug-tracked
