### ISSUE TITLE
build failure of TensorRT 8.6.1 when running explict quantization on GPU T4

### ISSUE THREAD

**Issue by zhexinli** [NVIDIA/TensorRT#3638] opened 2024-01-29 09:38 UTC
## Description

I tried to utilize explict quantization on Stable Diffusion on GPU. I success in export the fake Q/DQ model into onnx in opset 17. but when building engine from network it fails with the error below.

```
[X] =============== Computing costs for unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv
[X] *************** Autotuning format combination: Int8(3072,3072:4,48,1) -> Float(983040,3072,48,1) ***************
[X] --------------- Timing Runner: unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv (CaskConvolution[0x80000009])
[X] CaskConvolution has no valid tactics for this config, skipping
[X] --------------- Timing Runner: unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv (CaskFlattenConvolution[0x80000036])
[X] CaskFlattenConvolution has no valid tactics for this config, skipping
[X] *************** Autotuning format combination: Int8(3072,3072:32,48,1) -> Float(983040,3072,48,1) ***************
[X] --------------- Timing Runner: unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv (CaskConvolution[0x80000009])
[X] CaskConvolution has no valid tactics for this config, skipping
[X] --------------- Timing Runner: unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv (CaskFlattenConvolution[0x80000036])
[X] CaskFlattenConvolution has no valid tactics for this config, skipping
[X] *************** Autotuning format combination: Int8(3072,3072:32,48,1) -> Float(30720,3072:32,48,1) ***************
[X] --------------- Timing Runner: unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv (CaskConvolution[0x80000009])
[X] CaskConvolution has no valid tactics for this config, skipping
[X] --------------- Timing Runner: unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv (CaskFlattenConvolution[0x80000036])
[X] CaskFlattenConvolution has no valid tactics for this config, skipping
[E] 10: Could not find any implementation for node unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv.
[E] 10: [optimizer.cpp::computeCosts::3869] Error Code 10: Internal Error (Could not find any implementation for node unet.condition_vae_latent_conv.weight + /unet/condition_vae_latent_conv/_weight_quantizer/QuantizeLinear + /unet/condition_vae_latent_conv/Conv.)
```

## Environment

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: T4

**NVIDIA Driver Version**: 525.105.17

**CUDA Version**: 11.8

**CUDNN Version**: 8.9.0

Operating System:

Python Version (if applicable): 3.9.18

PyTorch Version (if applicable): 2.0.1

Necessary Info:

Build config ( same as the TensorRT/demo/Diffuser:

```
Building engine with configuration:
    Flags                  | [INT8]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 14823.31 MiB, TACTIC_DRAM: 14928.31 MiB]
    Tactic Sources         | []
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
```

Relevent layer:
It is juct a normal weight quantizer for conv.
![image](https://github.com/NVIDIA/TensorRT/assets/44015820/72a4c69d-b7e3-4cf9-a5d2-aa8bc90ac90b)

## My try
I tried to update to the lastest tensorrt 9.2.0 but it raised the same error.

I thought maybe it is because the tactices are disabled so trt couldn't find a proper kernel. So I tried enable all Tactics like CUDNN and successed to built a plan, but it allocated to much device memory so it OOM when run inference (same input size won't cause OOM when using FP16)

**Comment by zerollzeng** [comment] 2024-01-30 01:59
Could you please provide the onnx for reproduce? Thanks!

**Comment by zhexinli** [comment] 2024-01-31 06:26
> Could you please provide the onnx for reproduce? Thanks!

I' m sorry, due to my company's policy, I couldn't provide the model in any way.

**Comment by zerollzeng** [comment] 2024-02-01 14:25
Without reproduce we can't do a further check. Have you try other newer GPU?

**Comment by zhexinli** [comment] 2024-02-04 09:50
> Without reproduce we can't do a further check. Have you try other newer GPU?

I intend to try it in A-series GPUs when available. If not succeed, I will try to reproduct the case in open-source diffusion models.

**Comment by zerollzeng** [comment] 2024-03-03 04:26
NP, I'm closing this since it works on A10. Thanks!

**Closed by zerollzeng** 2024-03-03 04:26 UTC
Labels: triaged

**Comment by ApolloRay** [comment] 2024-03-11 11:42
in V series, not work.
