### ISSUE TITLE
Unable to fallback to FP32

### ISSUE THREAD

**Issue by byjswr** [NVIDIA/TensorRT#2080] opened 2022-06-22 07:49 UTC
## Description

In a single transformer block, 3 matmuls are fused in fp16 precision, and the assigned output data type was not obeied when I can specify a matmul to fall back to fp32

## Environment

TensorRT Version: 8.4.0
NVIDIA GPU: GTX
NVIDIA Driver Version: 465.19.01
CUDA Version: 11.3
Operating System: ubuntu
Python Version: 3.8.10
PyTorch Version: 1.11.0
onnxruntime Version: 1.11.0

## Relevant Files

test script in this respository: https://github.com/byjswr/TRT2022 ,please help me solve this problem

<img width="511" alt="企业微信截图_16558840895381" src="https://user-images.githubusercontent.com/53067559/174973748-a5daa07c-d967-4b83-8301-f73a2f314de2.png">
but I have changed Matmul_14 to float32

```
    for i in range(network.num_layers):
        layer = network.get_layer(i)
        if layer.name == 'MatMul_14':
            layer.precision = trt.float32
            layer.get_output(0).dtype = trt.float32
```

**Comment by BowenFu** [comment] 2022-06-22 07:54
The issue is about horizontal merge not following output data type properly. Will try reproducing it.

**Comment by BowenFu** [comment] 2022-06-22 08:09
@byjswr can you update the description? " it fails" should be "the assigned output data type was not obeied".

**Comment by nvpohanh** [comment] 2022-06-24 05:41
@byjswr Did you set precision constraints in builder config? I didn't see that in our code. Please follow the instructions in our doc to do so: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#layer-level-control

**Comment by nvpohanh** [comment] 2022-06-24 05:41
```
config.set_flag(trt.BuilderFlag.PREFER_PRECISION_CONSTRAINTS)
```

**Comment by byjswr** [comment] 2022-06-25 06:50
> ```
> config.set_flag(trt.BuilderFlag.PREFER_PRECISION_CONSTRAINTS)
> ```
<img width="455" alt="企业微信截图_16561231411978" src="https://user-images.githubusercontent.com/53067559/175762071-422e1181-6d97-424a-901a-01d515768edc.png">
I set PREFER_PRECISION_CONSTRAINTS flag, still doesn't wok.My repo has updated, please help me to check it .

**Comment by BowenFu** [comment] 2022-06-25 07:23
We have tracked this in internal system. The issue should be fixed in next release. No action item for now.

A workaround can be to set the precision to the first node (or all nodes) of the horizontal merge.

**Comment by ttyio** [comment] 2023-11-23 00:33
Closing old issues that are inactive for long time, since there is already WAR in last comment. thanks all!

**Closed by ttyio** 2023-11-23 00:33 UTC
Labels: triaged
