### ISSUE TITLE
Build engine successfully,BUT there is a error in builder.cpp. AND no detect,the rect.x and rect.y is 0,rect.width and rect.height is -2415698....

### ISSUE THREAD

**Issue by leusbur** [NVIDIA/TensorRT#2819] opened 2023-03-28 02:31 UTC
[03/28/2023-10:26:08] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +750, GPU +318, now: CPU 1645, GPU 665 (MiB)
[03/28/2023-10:26:09] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +673, GPU +342, now: CPU 2318, GPU 1007 (MiB)
[03/28/2023-10:26:09] [W] [TRT] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.2.4
[03/28/2023-10:26:09] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[03/28/2023-10:26:40] [I] [TRT] Some tactics do not have sufficient workspace memory to run. Increasing workspace size will enable more tactics, please check verbose output for requested sizes.
[03/28/2023-10:28:43] [I] [TRT] Total Activation Memory: 179719680
[03/28/2023-10:28:43] [I] [TRT] Detected 1 inputs and 1 output network tensors.
[03/28/2023-10:28:43] [I] [TRT] Total Host Persistent Memory: 181952
[03/28/2023-10:28:43] [I] [TRT] Total Device Persistent Memory: 368640
[03/28/2023-10:28:43] [I] [TRT] Total Scratch Memory: 0
[03/28/2023-10:28:43] [I] [TRT] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 17 MiB, GPU 102 MiB
[03/28/2023-10:28:43] [I] [TRT] [BlockAssignment] Started assigning block shifts. This will take 201 steps to complete.
[03/28/2023-10:28:43] [I] [TRT] [BlockAssignment] Algorithm ShiftNTopDown took 4.86206ms to assign 6 blocks to 201 nodes requiring 16998400 bytes.
[03/28/2023-10:28:43] [I] [TRT] Total Activation Memory: 16998400
[03/28/2023-10:28:43] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 3325, GPU 1515 (MiB)
[03/28/2023-10:28:43] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 3325, GPU 1523 (MiB)
[03/28/2023-10:28:43] [W] [TRT] TensorRT was linked against cuDNN 8.6.0 but loaded cuDNN 8.2.4
[03/28/2023-10:28:43] [W] [TRT] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[03/28/2023-10:28:43] [W] [TRT] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[03/28/2023-10:28:43] [W] [TRT] Check verbose logs for the list of affected weights.
[03/28/2023-10:28:43] [W] [TRT] - 10 weights are affected by this issue: Detected FP32 infinity values and converted them to corresponding FP16 infinity.
[03/28/2023-10:28:43] [W] [TRT] - 97 weights are affected by this issue: Detected NaN values and converted them to corresponding FP16 NaN.
[03/28/2023-10:28:43] [W] [TRT] - 109 weights are affected by this issue: Detected subnormal FP16 values.
[03/28/2023-10:28:43] [W] [TRT] - 167 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
[03/28/2023-10:28:43] [W] [TRT] - 177 weights are affected by this issue: Detected finite FP32 values which would overflow in FP16 and converted them to the closest finite FP16 value.
[03/28/2023-10:28:43] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +13, GPU +14, now: CPU 13, GPU 14 (MiB)
Build engine successfully!
[03/28/2023-10:28:43] [E] [TRT] 3: [builder.cpp::~Builder::307] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builder.cpp::~Builder::307, condition: mObjectCounter.use_count() == 1. Destroying a builder object before destroying objects it created leads to undefined behavior.

**Comment by zerollzeng** [comment] 2023-03-28 06:50
Can you provide a reproduce for this? Thanks!

**Comment by ecardozog** [comment] 2023-04-02 14:03
same error

**Comment by huaiqi220** [comment] 2023-04-21 07:37
same error

**Comment by zerollzeng** [comment] 2023-04-21 10:41
> [03/28/2023-10:28:43] [E] [TRT] 3: [builder.cpp::~Builder::307] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builder.cpp::~Builder::307, condition: mObjectCounter.use_count() == 1. Destroying a builder object before destroying objects it created leads to undefined behavior.

it's because you didn't destroy the object in reverse order, e.g. if you create a IBuilder then create an ICudaEngine from the builder, you should destroy the ICudaEngine first and then IBuilder .

**Comment by ttyio** [comment] 2023-05-16 20:07
Closing since it is solved, thanks all!

**Closed by ttyio** 2023-05-16 20:07 UTC
Labels: triaged

**Comment by MargeryLab** [comment] 2023-05-27 15:11
how to solve it? i met the same error...

**Comment by FengZhiheng** [comment] 2023-10-09 01:26
I also met the same problem.

**Comment by zerollzeng** [comment] 2023-10-12 14:28
Destroy objects in reverse order.

**Comment by zerollzeng** [comment] 2023-10-12 14:29
e.g. 
```
A* a = new A().
B* b = A.createB();
```
then you should do "delete b" before "delete a"
