### ISSUE TITLE
RPROI   tensorflow

### ISSUE THREAD

**Issue by jackhelloworldly** [NVIDIA/TensorRT#543] opened 2020-05-12 07:04 UTC
I have got the results of "rpn_cls_score, conv5_3 and rpn_bbox_pred". However the result I got through the "RPROI"  didn't match the result I used the software of tensorflow. 

data_input = [rpn_cls_score.get_output(0),rpn_bbox_pred.get_output(0),  conv5_3.get_output(0), img_info]
RPROI_layer = network.add_plugin_v2(inputs=data_input, plugin=plugin)

network.mark_output(RPROI_layer.get_output(0))

----------------------------------------------------------
rois, _ = _proposal_layer(rpn_cls_prob, rpn_bbox_pred)

I compare the rois with RPROI_layer.getoutput(0).However, the results are different.

**Comment by rmccorm4** [comment] 2020-05-14 15:58
Hi @jackhelloworldly ,

Please share:

1. a complete minimal script that generates the models and reproduces this error.
2. the environment info requested by issue template

**Comment by jackhelloworldly** [comment] 2020-05-15 06:27
# tensorflow version >=2
import tensorflow as tf
import numpy as np

def mkanchors(ws, hs, x_ctr, y_ctr):
  ws = ws[:, np.newaxis]
  hs = hs[:, np.newaxis]
  anchors = np.hstack((x_ctr - 0.5 * (ws - 1),
                       y_ctr - 0.5 * (hs - 1),
                       x_ctr + 0.5 * (ws - 1),
                       y_ctr + 0.5 * (hs - 1)))
  return anchors

def whctrs(anchor):
  w = anchor[2] - anchor[0] + 1
  h = anchor[3] - anchor[1] + 1
  x_ctr = anchor[0] + 0.5 * (w - 1)
  y_ctr = anchor[1] + 0.5 * (h - 1)
  return w, h, x_ctr, y_ctr

def ratio_enum(anchor, ratios):
  w, h, x_ctr, y_ctr = whctrs(anchor)
  size = w * h
  size_ratios = size / ratios
  ws = np.round(np.sqrt(size_ratios))
  hs = np.round(ws * ratios)
  anchors = mkanchors(ws, hs, x_ctr, y_ctr)
  return anchors

def scale_enum(anchor, scales):
  w, h, x_ctr, y_ctr = whctrs(anchor)
  ws = w * scales
  hs = h * scales
  anchors = mkanchors(ws, hs, x_ctr, y_ctr)
  return anchors

def generate_anchors(base_size=16, ratios=[0.5, 1, 2], scales=2 ** np.arange(3, 6)):
  base_anchor = np.array([1, 1, base_size, base_size]) - 1
  ratio_anchors = ratio_enum(base_anchor, ratios)
  anchors = np.vstack([scale_enum(ratio_anchors[i, :], scales)
                       for i in range(ratio_anchors.shape[0])])
  return anchors

def generate_anchors_pre_tf(height, width, feat_stride=16, anchor_scales=(8, 16, 32), anchor_ratios=(0.5, 1, 2)):
    shift_x = tf.range(width) * feat_stride
    shift_y = tf.range(height) * feat_stride
    shift_x, shift_y = tf.meshgrid(shift_x, shift_y)
    sx = tf.reshape(shift_x, shape=(-1,))
    sy = tf.reshape(shift_y, shape=(-1,))
    shifts = tf.transpose(tf.stack([sx, sy, sx, sy]))
    K = tf.multiply(width, height)
    shifts = tf.transpose(tf.reshape(shifts, shape=[1, K, 4]), perm=(1, 0, 2))
    anchors = generate_anchors(ratios=np.array(anchor_ratios), scales=np.array(anchor_scales))
    S = anchors
    S1 = anchors.reshape((1, anchors.shape[0], 4))
    A = anchors.shape[0]
    anchor_constant = tf.constant(anchors.reshape((1, A, 4)), dtype=tf.int32)
    length = K * A
    anchors_tf = tf.reshape(tf.add(anchor_constant, shifts), shape=(length, 4))
    return tf.cast(anchors_tf, dtype=tf.float32), length

def bbox_transform_inv_tf(boxes, deltas):
    boxes = tf.cast(boxes, deltas.dtype)
    widths = tf.subtract(boxes[:, 2], boxes[:, 0]) + 1.0
    heights = tf.subtract(boxes[:, 3], boxes[:, 1]) + 1.0
    ctr_x = tf.add(boxes[:, 0], widths * 0.5)
    ctr_y = tf.add(boxes[:, 1], heights * 0.5)
    dx = deltas[:, 0]
    dy = deltas[:, 1]
    dw = deltas[:, 2]
    dh = deltas[:, 3]
    pred_ctr_x = tf.add(tf.multiply(dx, widths), ctr_x)
    pred_ctr_y = tf.add(tf.multiply(dy, heights), ctr_y)
    pred_w = tf.multiply(tf.exp(dw), widths)
    pred_h = tf.multiply(tf.exp(dh), heights)
    pred_boxes0 = tf.subtract(pred_ctr_x, pred_w * 0.5)
    pred_boxes1 = tf.subtract(pred_ctr_y, pred_h * 0.5)
    pred_boxes2 = tf.add(pred_ctr_x, pred_w * 0.5)
    pred_boxes3 = tf.add(pred_ctr_y, pred_h * 0.5)
    return tf.stack([pred_boxes0, pred_boxes1, pred_boxes2, pred_boxes3], axis=1)

def clip_boxes_tf(boxes, im_info):
  b0 = tf.maximum(tf.minimum(boxes[:, 0], im_info[1] - 1), 0)
  b1 = tf.maximum(tf.minimum(boxes[:, 1], im_info[0] - 1), 0)
  b2 = tf.maximum(tf.minimum(boxes[:, 2], im_info[1] - 1), 0)
  b3 = tf.maximum(tf.minimum(boxes[:, 3], im_info[0] - 1), 0)
  return tf.stack([b0, b1, b2, b3], axis=1)

def proposal_layer_tf(rpn_cls_prob, rpn_bbox_pred, im_info, cfg_key, _feat_stride, anchors, num_anchors):
  if type(cfg_key) == bytes:
    cfg_key = cfg_key.decode('utf-8')
  pre_nms_topN = 6000
  post_nms_topN = 300
  nms_thresh = 0.7
  scores = rpn_cls_prob[:, :, :, num_anchors:]
  scores = tf.reshape(scores, shape=(-1,))
  rpn_bbox_pred = tf.reshape(rpn_bbox_pred, shape=(-1, 4))

  proposals = bbox_transform_inv_tf(anchors, rpn_bbox_pred)
  proposals = clip_boxes_tf(proposals, im_info[:2])
  indices = tf.image.non_max_suppression(proposals, scores, max_output_size=post_nms_topN, iou_threshold=nms_thresh)
  boxes = tf.gather(proposals, indices)
  scores = tf.gather(scores, indices)
  scores = tf.reshape(scores, shape=(-1, 1))
  batch_inds = tf.zeros((tf.shape(indices)[0], 1), dtype=tf.float32)
  blob = tf.concat([batch_inds, boxes], 1)

  return blob, scores

def proposal_layer(rpn_cls_prob, rpn_bbox_pred):
    mode = 'TEST'
    feat_stride = 16
    num_anchors = 9
    im_info = [416, 416, 1]
    anchors, anchor_length = generate_anchors_pre_tf(26, 26, 16, [8, 16, 32], (0.5, 1, 2))
    rois, rpn_scores = proposal_layer_tf(rpn_cls_prob, rpn_bbox_pred, im_info,
                                         mode, feat_stride, anchors, num_anchors)
    return rois


if __name__ == '__main__':
    # input
    data = np.random.uniform(0, 1, size=(1, 26, 26, 2 * 9))
    rpn_cls_prob = tf.constant(data)
    data_1 = np.random.uniform(-2, 1, size=(1, 26, 26, 4 * 9))
    rpn_bbox_pred = tf.constant(data_1)
    rois = proposal_layer(rpn_cls_prob, rpn_bbox_pred)
    a = 1
Random numbers may not be suitable.
---------------------------------------------------------
# tensorrt version == 5
# If I use the tensorrt, I need to transpose some numbers.
'''
rpn_cls_prob = data.transpose(0, 3, 1, 2)     # (1, 18, 26, 26)
rpn_bbox_pred = data.transpose(0, 3, 1, 2)     # (1, 36, 26, 26)
'''

import tensorrt as trt
import numpy as np
import pycuda.driver as cuda
import pycuda.autoinit

G_LOGGER = trt.Logger(trt.Logger.WARNING)
trt.init_libnvinfer_plugins(G_LOGGER, "")
PLUGIN_CREATORS = trt.get_plugin_registry().plugin_creator_list

poolingH = trt.PluginField("poolingH", np.array([7], dtype=np.int32).data, trt.PluginFieldType.INT32) #304
poolingW = trt.PluginField("poolingW", np.array([7], dtype=np.int32).data, trt.PluginFieldType.INT32)#309
featureStride = trt.PluginField("featureStride", np.array([16], dtype=np.int32).data, trt.PluginFieldType.INT32)#314
preNmsTop = trt.PluginField("preNmsTop", np.array([6000], dtype=np.int32).data, trt.PluginFieldType.INT32)#319
nmsMaxOut = trt.PluginField("nmsMaxOut", np.array([300], dtype=np.int32).data, trt.PluginFieldType.INT32)#324
anchorsRatioCount = trt.PluginField("anchorsRatioCount", np.array([3], dtype=np.int32).data, trt.PluginFieldType.INT32)#329
anchorsScaleCount = trt.PluginField("anchorsScaleCount", np.array([3], dtype=np.int32).data, trt.PluginFieldType.INT32)#334
iouThreshold = trt.PluginField("iouThreshold", np.array([0.7], dtype=np.float32), trt.PluginFieldType.FLOAT32)
minBoxSize = trt.PluginField("minBoxSize", np.array([16], dtype=np.float32), trt.PluginFieldType.FLOAT32)
spatialScale = trt.PluginField("spatialScale", np.array([0.0625], dtype=np.float32), trt.PluginFieldType.FLOAT32)

anchorsRatios = trt.PluginField("anchorsRatios", np.array([0.5, 1.0, 2.0], dtype=np.float32), trt.PluginFieldType.FLOAT32)
anchorsScales = trt.PluginField("anchorsScales", np.array([8.0, 16.0, 32.0], dtype=np.float32), trt.PluginFieldType.FLOAT32)

field_collection = trt.PluginFieldCollection([poolingH, poolingW, featureStride, preNmsTop, nmsMaxOut,anchorsRatioCount, anchorsScaleCount, iouThreshold, minBoxSize,spatialScale, anchorsRatios, anchorsScales])


plugin = PLUGIN_CREATORS[12].create_plugin(name = "RPROI_TRT", field_collection = field_collection)

def init_tensorRT():
    with trt.Builder(G_LOGGER) as builder, builder.create_network() as network:
        builder.max_workspace_size = 1024 * 1024 * 10
        fmap = network.add_input(name="fmap", dtype=trt.float32, shape=(512, 26, 26))
        rpn_bbox_pred = network.add_input(name="deltas", dtype= trt.float32, shape=(9 * 4, 26, 26))
        rpn_cls_prob = network.add_input(name="scores", dtype= trt.float32, shape=(9 * 2, 26, 26))
        img_inf = network.add_input(name="img_inf", dtype= trt.float32, shape=(1, 1, 3))
        RPROI_layer = network.add_plugin_v2(inputs=[scores, deltas, fmap, img_inf], plugin=plugin)
        RPROI_layer.get_output(0).name = "rois"
        RPROI_layer.get_output(1).name = "pfmap"
        network.mark_output(RPROI_layer.get_output(0))
        network.mark_output(RPROI_layer.get_output(1))
        return builder.build_cuda_engine(network)


data = np.random.uniform(0, 1, size=(1, 2*9, 26, 26))
rpn_cls_prob = cuda.mem_alloc(data.nbytes)
cuda.memcpy_htod_async(rpn_cls_prob, data)

data_1 = np.random.uniform(0, 1, size=(1, 4*9, 26, 26))
rpn_bbox_pred = cuda.mem_alloc(data_1.nbytes)
cuda.memcpy_htod_async(rpn_bbox_pred, data_1)

data_2 = np.random.uniform(0, 1, size=(1, 512, 26, 26))
fmap = cuda.mem_alloc(data_2.nbytes)
cuda.memcpy_htod_async(fmap, data_2)


data_3 = np.zeros([1, 1, 1, 3], dtype=np.float32)
data_3[0][0][0][0] = 416
data_3[0][0][0][1] = 416
data_3[0][0][0][2] = 0.0625
img_inf = cuda.mem_alloc(data_3.nbytes)
cuda.memcpy_htod_async(img_inf, data_3)

output_1 = np.zeros((1, 1, 1200, 4), dtype=np.float32)
roi = cuda.mem_alloc(output_1.nbytes)
output_2 = np.zeros((1, 300, 512, 7, 7), dtype=np.float32)
rpnroi_result = cuda.mem_alloc(output_2.nbytes)
stream = cuda.Stream()
binding = [rpn_cls_prob, rpn_bbox_pred, fmap, img_inf, roi, rpnroi_result]

engine = init_tensorRT()
#
context = engine.create_execution_context()
context.execute(1, binding)

**Comment by nvpohanh** [comment] 2022-06-15 11:17
@jackhelloworldly Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, we will debug it. Thanks

**Comment by nvpohanh** [comment] 2022-07-01 05:42
Closing for now due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-07-01 05:42 UTC
Labels: Runtime: Correctness, triaged
