### ISSUE TITLE
algorithm select on some onnx has err msg 

### ISSUE THREAD

**Issue by nanbatian119** [NVIDIA/TensorRT#2073] opened 2022-06-20 07:32 UTC
algorithm select on some onnx has such err msg 

**TensorRT Version**:  8.4GA
**NVIDIA GPU**:  NVIDIA A10
**NVIDIA Driver Version**: 510.73.08
**CUDA Version**: 11.3

<img width="929" alt="企业微信截图_d47d2985-cd1c-4ac9-9c2e-babc1f184242" src="https://user-images.githubusercontent.com/20862479/174547883-fa9bf3be-e2ca-40de-b7bb-f4e02bb67522.png">

Here is my respo to reproduce

https://github.com/nanbatian119/trt-algorithm-select.git

**Comment by nanbatian119** [comment] 2022-06-20 07:48
onnx download path 

https://drive.google.com/file/d/190yzio7Imzy8gLExKnjGL5FaGOl6u0l8/view?usp=sharing

**Comment by zerollzeng** [comment] 2022-06-20 08:44
I can't reproduce it on my 8.4(internal build, maybe newer than yours). can you try to run your model with trtexec?
```
/usr/src/tensorrt/bin/trtexec --onnx=test.onnx --verbose
```

**Comment by nanbatian119** [comment] 2022-06-20 08:54
> I can't reproduce it on my 8.4(internal build, maybe newer than yours). can you try to run your model with trtexec?
> 
> ```
> /usr/src/tensorrt/bin/trtexec --onnx=test.onnx --verbose
> ```
<img width="779" alt="企业微信截图_550dfe54-774e-49ee-855c-e72776cb1b5b" src="https://user-images.githubusercontent.com/20862479/174564326-fbdd050e-d104-4eae-b1f6-3604031ed6b5.png">

It has passed.

**Comment by zerollzeng** [comment] 2022-06-20 09:06
Looks like it's related to IAlgorithmSelector. @nvpohanh can you help on here?

**Comment by BowenFu** [comment] 2022-06-21 08:41
Reproduced with latest internal TRT.
With dynamic batch, the error will appear.

**Comment by BowenFu** [comment] 2022-06-24 02:42
The error message is a little misleading. We will fix the error message.

And the actual reason why the engine building failed is that dynamic shapes may require larger workspace memory.
So removing this line in the script can work around the issue.

        config.max_workspace_size = 3 << 30

**Comment by nanbatian119** [comment] 2022-06-24 02:51
> 

thanks very much!

**Comment by nvpohanh** [comment] 2022-07-01 06:47
@BowenFu Should we close this?

**Comment by BowenFu** [comment] 2022-07-01 07:29
Yes, we can close this one. The issue has been tracked in internal system.

**Closed** 2022-07-01 07:31 UTC
Labels: triaged

**Comment by nanbatian119** [comment] 2022-10-11 09:22
邮件已收到
