### ISSUE TITLE
conv 3d dynamic shape error ? 

### ISSUE THREAD

**Issue by finnyang** [NVIDIA/TensorRT#331] opened 2020-01-13 09:25 UTC
## Description

I setup a simple network with one con3d layers. I just want test conv3d dynamic shape . 
whe I set the input dim as (-1, 1, 32, -1, -1), it work.
but whe I set the input dim as (-1, 1, -1, -1, -1), it will have "MemoryError: std::bad_alloc".
So, conv3d don't support dynamic shape when depth dimension is -1? It is bug?

## Environment

**TensorRT Version**: 7
**GPU Type**: Titan xp
**Nvidia Driver Version**:  384.130
**CUDA Version**:  9.0
**CUDNN Version**: 7.6
**Operating System + Version**: ubuntu 16.04
**Python Version (if applicable)**:  3.7
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**:  1
**Baremetal or Container (if container which image + tag)**: 

## Relevant Files

My python test script.

```
import tensorrt as trt
import numpy as np
import pycuda.driver as cuda
import pycuda.autoinit

if __name__ == '__main__':
    logger = trt.Logger(trt.Logger.WARNING)
    builder = trt.Builder(logger)
    network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
    builder.max_batch_size = 1
    builder.max_workspace_size = 1 << 30

    data = network.add_input("data", trt.float32, (-1, 1, 32, -1, -1))
    weight0 = np.ones(shape=(6, 1, 3, 3, 3), dtype=np.float32).reshape(-1)
    bias0 = np.zeros(shape=(6), dtype=np.float32).reshape(-1)

    layer0 = network.add_convolution_nd(data, 6, trt.Dims([3, 3, 3]), weight0, bias0)
    output = layer0.get_output(0)
    network.mark_output(output)

    config = builder.create_builder_config()
    profile = builder.create_optimization_profile()
    profile.set_shape(network.get_input(0).name,
                      (1, 1, 32, 32, 32),
                      (1, 1, 32, 32, 32),
                      (1, 1, 32, 32, 32))
    config.add_optimization_profile(profile)

    engine = builder.build_engine(network, config)
    context = engine.create_execution_context()
    context.set_binding_shape(0, (1, 1, 32, 32, 32))

```

## Steps To Reproduce
1、run this script， it will work。
2、replace data = network.add_input("data", trt.float32, (-1, 1, 32, -1, -1)) with data = network.add_input("data", trt.float32, (-1, 1, -1, -1, -1)) . It appears "MemoryError: std::bad_alloc".

**Comment by litaotju** [comment] 2020-01-15 02:15
This is not a bug, its knowm limitation of dynamic shape.

**Comment by finnyang** [comment] 2020-01-15 03:07
> This is not a bug, its knowm limitation of dynamic shape.

1、Will Tensor RT support dynamic shape with Depth dimension(3D input NCDHW) in the future?
2、Why can't Depth be set dynamically but Height and Width can be? Technical difficulties?

**Comment by rmccorm4** [comment] 2020-01-16 20:32
ref: https://devtalk.nvidia.com/default/topic/1069505/tensorrt/conv3d-with-dynamic-shape-error

**Comment by finnyang** [comment] 2020-01-20 02:04
> ref: https://devtalk.nvidia.com/default/topic/1069505/tensorrt/conv3d-with-dynamic-shape-error

so, how to solve this limitation.

**Comment by rmccorm4** [comment] 2020-02-15 08:31
Hi @finnyang ,

This was a bug and should be fixed for the next release.

**Closed by rmccorm4** 2020-02-15 08:31 UTC
Labels: API: Python, Release: 7.x, Topic: Dynamic Shape
