### ISSUE TITLE
graphsurgeon graph is illegal after a simple load and store

### ISSUE THREAD

**Issue by decioren** [NVIDIA/TensorRT#3079] opened 2023-06-22 06:52 UTC
## Description

[GS_ISSUE.zip](https://github.com/NVIDIA/TensorRT/files/11829753/GS_ISSUE.zip)

## Environment

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: NVIDIA RTX A5000

**NVIDIA Driver Version**: 530.30.02

**CUDA Version**: 11.2

**CUDNN Version**: 8.5.0.96

Operating System: Ubuntu 20.04.3 LTS

Python Version (if applicable): 3.11.3

PyTorch Version (if applicable): 2.0.1

## Relevant Files

https://drive.google.com/file/d/11E5GaZc4tLuwXuzQMsMkt_B56PfMzXrA/view?usp=sharing

## Steps To Reproduce
run the script below on the file in the link to reproduce these errors (alternatively use the zip attachment):

Traceback (most recent call last):
  File "C:/Users/User/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/scratch_100.py", line 13, in <module>
    onnx.checker.check_model(onnx_model)
  File "C:\Users\User\PycharmProjects\deci-algo\venv\lib\site-packages\onnx\checker.py", line 106, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Node (Split_11) has input size 2 not in range [min=1, max=1].

==> Context: Bad node spec for node. Name: Split_11 OpType: Split

**Commands or scripts**:
```
import onnx
import onnx_graphsurgeon as gs

if __name__ == '__main__':
    original_model = onnx.load("mymodel_mode2.onnx")
    onnx.checker.check_model(original_model)
    graph = gs.import_onnx(original_model)
    graph = gs.Graph(nodes=graph.nodes, inputs=graph.inputs, outputs=graph.outputs).cleanup()
    onnx.save(gs.export_onnx(graph), "mymodel_mode2_changed.onnx")

    onnx_model = onnx.load("mymodel_mode2_changed.onnx")
    onnx.checker.check_model(onnx_model)

```

**Comment by zerollzeng** [comment] 2023-06-26 02:01
> File "C:\Users\User\PycharmProjects\deci-algo\venv\lib\site-packages\onnx\checker.py", line 106, in check_model
> C.check_model(protobuf_string)

The error is emitted by the onnx package, I would suggest filing a issue in https://github.com/onnx/onnx/issues

**Comment by decioren** [comment] 2023-06-26 05:54
this is true, but the original onnx is legal. It is only the import & export of graphsurgeon which causes this problem. This makes it very unlikely that the problem is with onnx itself.

**Comment by zerollzeng** [comment] 2023-06-27 09:35
> File "C:/Users/User/AppData/Roaming/JetBrains/PyCharm2020.3/scratches/scratch_100.py", line 13, in
> onnx.checker.check_model(onnx_model)

Looks like the bug is in onnx checker.

**Comment by decioren** [comment] 2023-06-27 10:48
trying to use the onnx model (without the checker) using onnx runtime, or converting to tensorrt also fails. 
This means that the model is really problematic, don't you think?

**Comment by zerollzeng** [comment] 2023-07-02 03:11
> This means that the model is really problematic, don't you think?

Yes

**Comment by decioren** [comment] 2023-07-03 12:12
So the original model is fine. After import and export using GS it is illegal. There is a minimal code sample attached. 
Is this something you will be looking into?
We are considering putting GS to heavy use and we ran into this in our second use case.

**Comment by zerollzeng** [comment] 2023-07-04 04:17
@pranavm-nvidia Could you please help here? Thanks!

**Comment by zhiqwang** [comment] 2023-07-05 09:00
Seems that you should specify the opset manually as belows:

```python
import onnx
import onnx_graphsurgeon as gs

original_model = onnx.load("mymodel_mode1.onnx")
print(original_model.ir_version)
onnx.checker.check_model(original_model)
graph = gs.import_onnx(original_model)
opset_version = original_model.opset_import[0].version  # NOTE: Specify the opset here
graph = gs.Graph(nodes=graph.nodes, inputs=graph.inputs, outputs=graph.outputs, opset=opset_version).cleanup()
modified_model = gs.export_onnx(graph)
modified_model.ir_version = original_model.ir_version
onnx.save(modified_model, "mymodel_mode2_changed.onnx")

onnx_model = onnx.load("mymodel_mode2_changed.onnx")
onnx.checker.check_model(onnx_model)
```

**Comment by pranavm-nvidia** [comment] 2023-07-05 17:23
The problem is that you're making a copy of the graph without copying all the necessary fields, like opset information. I'd suggest using `graph.copy()` instead if you need a shallow copy.

**Comment by decioren** [comment] 2023-07-06 04:47
thank you! 
this resolves my problem and restores my faith.

**Comment by zerollzeng** [comment] 2023-07-07 05:59
I'm closing this, feel free to reopen if you have any further questions.

**Closed by zerollzeng** 2023-07-07 05:59 UTC
Labels: wontfix
