### ISSUE TITLE
pytorch fake quantization model parse failed with TensorRT 7.1.3.0

### ISSUE THREAD

**Issue by ShaneYS** [NVIDIA/TensorRT#1972] opened 2022-05-09 08:37 UTC
#1406 

> [05/09/2022-16:19:10] [E] [TRT] ../builder/cudnnBuilderGraph.cpp (902) - Assertion Error in checkSanity: 0 (!overlap(t->start, t->extent, f.first, f.second))

I want to convert fake quantization onnx model to tensorrt engine, and get the same error as in this problem.

I use TensorRT 7.1.3.0 and Xavier. The tensorrt version is bundled with Xavier, so I can't upgrade to 8.x.

How should I solve this error on tensorrt7.x ?

**Comment by galagam** [comment] 2022-05-17 07:49
Closing as this is a duplicate of #1406.

**Closed by galagam** 2022-05-17 07:49 UTC
