### ISSUE TITLE
Correct Way to Compare Speed Between ORT and TRT

### ISSUE THREAD

**Issue by WoodieDudy** [NVIDIA/TensorRT#3364] opened 2023-10-04 14:17 UTC
I am attempting to compare the performance of model running on ONNX Runtime and TensorRT.
To do that, I wrote this code:

```python
import math

import torch
import torch.utils.benchmark as tbenchmark

import tensorrt as trt
import numpy as np
import pycuda.driver as cuda
import onnxruntime as ort

import pycuda.autoinit

ALPHABET_LEN = 35
DEVICE_ID = 0


def calc_time_dim(T: int):
    sample_rate = 8000
    window_size = 0.04
    window_stride = 0.01

    win_length = int(window_size * sample_rate)
    hop_length = int(window_stride * sample_rate)
    nfft = 2 ** math.ceil(math.log2(win_length))
    freq_cutoff = nfft // 2 + 1
    pad = freq_cutoff - 1
    T_prime = (T + 2 * pad - nfft + hop_length) // hop_length
    return (T_prime + 3) // 4


class TensorRTWrapper:
    def __init__(self, engine_path: str):
        with open(engine_path, 'rb') as f:
            engine_data = f.read()

        runtime = trt.Runtime(trt.Logger(trt.Logger.WARNING))
        self.engine = runtime.deserialize_cuda_engine(engine_data)
        self.trt_ctx = self.engine.create_execution_context()

    def prepocess_inputs(self, x: np.ndarray, xlen: np.ndarray, output_shape: tuple):
        self.x = x
        self.output_shape = output_shape

        self.trt_ctx.set_input_shape("x", x.shape)
        self.trt_ctx.set_input_shape("xlen", xlen.shape)

        self.input_bindings = [
            cuda.mem_alloc(int(np.prod(x.shape)) * x.dtype.itemsize),
            cuda.mem_alloc(int(np.prod(xlen.shape)) * xlen.dtype.itemsize)
        ]
        self.output_binding = cuda.mem_alloc((int(np.prod(output_shape)) * np.float32().itemsize))
        cuda.memcpy_htod(self.input_bindings[0], x.ravel())
        cuda.memcpy_htod(self.input_bindings[1], xlen.ravel())

    def run(self):
        self.trt_ctx.execute_v2(bindings=list(map(int, self.input_bindings + [self.output_binding])))
     
    def get_outputs(self):
        h_output = np.ones(self.output_shape, dtype=np.float32)
        cuda.memcpy_dtoh(h_output, self.output_binding)
        return h_output

class ORTWrapper:
    def __init__(self, onnx_path: str):
        sess_options = ort.SessionOptions()
        sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC
        self.ort_session = ort.InferenceSession(onnx_path, providers=["CUDAExecutionProvider", "CPUExecutionProvider"], sess_options=sess_options)
        self.bindings = self.ort_session.io_binding()

    def prepocess_inputs(self, x: np.ndarray, xlen: np.ndarray, output_shape: tuple):
        device = "cuda"

        inputs = [
            ("x", x),
            ("xlen", xlen)
        ]

        for name, input_array in inputs:
            tensor = torch.from_numpy(input_array).to(f"{device}:{DEVICE_ID}")
            self.bindings.bind_input(
                name=name,
                device_type=device,
                device_id=DEVICE_ID,
                element_type=input_array.dtype,
                shape=input_array.shape,
                buffer_ptr=tensor.data_ptr(),
            )

        # for output in self.ort_session.get_outputs():
        #     print(output.name)
        #     print(output.type)
        self.output_tensor = torch.empty(output_shape, dtype=torch.float32, device=f"{device}:{DEVICE_ID}")
        self.bindings.bind_output(
            name="logits",
            device_type=device,
            device_id=DEVICE_ID,
            element_type=np.float32,
            shape=output_shape,
            buffer_ptr=self.output_tensor.data_ptr(),
        )

    def run(self):
        self.ort_session.run_with_iobinding(self.bindings)
    
    def get_outputs(self):
        return self.output_tensor.detach().cpu().numpy()


def main():
    x = np.random.rand(16, 40320).astype(np.float32)
    xlen = np.random.rand(16).astype(np.float32)
    batch, time = x.shape
    output_shape = (batch, ALPHABET_LEN, calc_time_dim(time))
    print()

    # trt_wrapper = TensorRTWrapper("engine/model_fp16_opset17_dynamicshapes.onnx.engine")
    trt_wrapper = TensorRTWrapper("engine/model_fp16_opset17_staticshapes_40320.onnx.engine")

    trt_wrapper.prepocess_inputs(x, xlen, output_shape)
    t = tbenchmark.Timer(
        stmt='model.run()',
        globals={"model": trt_wrapper}
    )
    m = t.blocked_autorange(min_run_time=2)
    trt_output = trt_wrapper.get_outputs()
    trt_mean_time = m.mean
    print(f"{trt_mean_time=}")

    # ort_wrapper = ORTWrapper("onnx/model_fp16_opset17_dynamicshapes.onnx")
    ort_wrapper = ORTWrapper("onnx/model_opset17_staticshapes_40320.onnx")
    ort_wrapper.prepocess_inputs(x, xlen, output_shape)
    t = tbenchmark.Timer(
        stmt='model.run()',
        globals={"model": ort_wrapper}
    )
    m = t.blocked_autorange(min_run_time=2)
    ort_output = ort_wrapper.get_outputs()
    ort_mean_time = m.mean
    print(f"{ort_mean_time=}")

    print(f"TRT runs {ort_mean_time/trt_mean_time} times faster than ORT")

    diff = np.abs(trt_output - ort_output)
    print(f"Mean difference: {diff.mean()}")
    print(f"Max difference: {diff.max()}")


if __name__ == '__main__':
    main()
```

**Models**
1. I have a model which I exported to ONNX format with both dynamic and static shapes.
2. I then built the TensorRT engine using both dynamic and static shapes.

For static shapes
```
trtexec --nvtxMode=verbose --buildOnly --workspace=8192 --onnx=model_staticshapes_40320.onnx --saveEngine=engine/model_staticshapes_40320.onnx.engine --fp16
```

For dynamic shapes
```
trtexec --nvtxMode=verbose --buildOnly --workspace=8192 --onnx=model_dynamicshapes.onnx --saveEngine=engine/model_dynamicshapes.onnx.engine --fp16 --minShapes=x:1x4000,xlen:1 --optShapes=x:64x40320,xlen:64 
--maxShapes=x:64x300000,xlen:64
```

**Script output**
For static shapes
```
trt_mean_time=0.01563217041984899
ort_mean_time=0.02382499598232763
TRT runs 1.5241003227597736 times faster than ORT
Mean difference: 0.12532691657543182
Max difference: 7.59375
```
For dynamic shapes
```
trt_mean_time=0.09766323465321745
ort_mean_time=0.023822454502806067
TRT runs 0.2439244879344292 times faster than ORT
Mean difference: 0.17294932901859283
Max difference: 9.5
```
#### P.S. Big max diff is a bug of my model

**Benchmark results:**
- On an A100, TRT with static shapes runs 1.5 times faster than ORT.
- With dynamic shapes, TRT runs 4 times slower than ORT.

**Questions**
1. Am I measuring the `compute` performance (without h2d, d2h transfers) correctly with this code?
3. Why is there such a discrepancy in performance between static and dynamic shapes? Specifically, why does TRT underperform with dynamic shapes compared to ORT?

**Comment by zerollzeng** [comment] 2023-10-06 10:12
FYI please take the trtexec GPU compute time as golden time for TRT.

**Comment by nvpohanh** [comment] 2023-10-06 10:53
@WoodieDudy Your benchmarking code looks correct to me. I can't tell why dynamic TRT engine would be so much slower than the static TRT engine. Is it possible to provide repro steps so that we can investigate? Also, which TRT version did you use?

**Comment by WoodieDudy** [comment] 2023-10-21 17:39
@nvpohanh 
Sorry it's taken me a while to respond
Here's [code](https://github.com/WoodieDudy/nemo-conformer-inference-benchmarks/blob/main/trt_vs_onnx_benchmark) for repro.

I use trt 8.6.1.6

**Comment by nvpohanh** [comment] 2023-10-23 02:41
@zerollzeng Could you repro and file an internal tracker? Thanks

**Comment by zerollzeng** [comment] 2023-10-30 12:59
I can reproduce the issue, will file a internal bug.
```
[10/30/2023-11:52:05] [I] GPU Compute Time: min = 28.4406 ms, max = 30.3124 ms, mean = 29.2394 ms, median = 29.2378 ms, percentile(90%) = 30.0258 ms, percentile(95%) = 30.1251 ms, percentile(99%) = 30.2909 ms
&&&& PASSED TensorRT.trtexec [TensorRT v9100] # trtexec --onnx=models/dynamic_model.onnx --minShapes=x:1x4000,xlen:1 --optShapes=x:64x40320,xlen:64 --maxShapes=x:64x300000,xlen:64 --shapes=x:16x40320,xlen:16 --verbose --fp16
[10/30/2023-11:56:47] [I] GPU Compute Time: min = 26.283 ms, max = 28.162 ms, mean = 27.0828 ms, median = 27.1708 ms, percentile(90%) = 27.6531 ms, percentile(95%) = 27.7422 ms, percentile(99%) = 27.9941 ms
&&&& PASSED TensorRT.trtexec [TensorRT v9100] # trtexec --onnx=models/dynamic_model.onnx --minShapes=x:1x4000,xlen:1 --optShapes=x:16x40320,xlen:16 --maxShapes=x:64x300000,xlen:64 --shapes=x:16x40320,xlen:16 --verbose --fp16
[10/30/2023-11:45:28] [I] GPU Compute Time: min = 22.0847 ms, max = 23.7343 ms, mean = 22.7781 ms, median = 22.7379 ms, percentile(90%) = 23.4436 ms, percentile(95%) = 23.551 ms, percentile(99%) = 23.7075 ms
&&&& PASSED TensorRT.trtexec [TensorRT v9100] # trtexec --onnx=models/static_model.onnx --verbose --fp16
```

**Comment by zerollzeng** [comment] 2023-10-30 13:08
Filed internal bug 4356314 to track this.

**Comment by WoodieDudy** [comment] 2023-10-30 13:13
Looking at your comment, I see that the compute time is almost the same everywhere. That is, there is no bug on trt v9100?

**Comment by zerollzeng** [comment] 2023-12-07 06:58
@WoodieDudy Could you please try TRT 9.2? in our test the perf has drop to <10%.

**Comment by WoodieDudy** [comment] 2023-12-14 08:23
@zerollzeng 
How can I install or download version 9.2. I have not found a [container](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-11.html) or [package](https://developer.nvidia.com/tensorrt-download). Is the only way to install 9.2 a building from source?

**Comment by zerollzeng** [comment] 2023-12-16 15:22
Check
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-11.8.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-12.2.tar.gz
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.ubuntu-22.04.aarch64-gnu.cuda-12.2.tar.gz

**Comment by ttyio** [comment] 2024-01-09 21:05
closing since this is solved, thanks all!

**Closed by ttyio** 2024-01-09 21:05 UTC
Labels: triaged
