### ISSUE TITLE
[Nonzero Operator] output of nonzero cannot to be reshape in tensorrt8.5 GA version

### ISSUE THREAD

**Issue by vanly89** [NVIDIA/TensorRT#2497] opened 2022-11-22 12:04 UTC
## Description

Hi, Experts
Thanks for your contribution in adding support for nonzero operators in the tensorrt8.5 GA version. When I tried to convert onnx model to trt model,  if I wanted to reshape the output of the nonzero operator,  I got the following error. Is there any way to avoid this problem?

11/22/2022-19:23:26] [I] Start parsing network model
[11/22/2022-19:23:26] [I] [TRT] ----------------------------------------------------------------
[11/22/2022-19:23:26] [I] [TRT] Input filename:   /home/vanly/projects/pt2trt_test/index.onnx
[11/22/2022-19:23:26] [I] [TRT] ONNX IR version:  0.0.8
[11/22/2022-19:23:26] [I] [TRT] Opset version:    16
[11/22/2022-19:23:26] [I] [TRT] Producer name:    pytorch
[11/22/2022-19:23:26] [I] [TRT] Producer version: 1.12.1
[11/22/2022-19:23:26] [I] [TRT] Domain:           
[11/22/2022-19:23:26] [I] [TRT] Model version:    0
[11/22/2022-19:23:26] [I] [TRT] Doc string:       
[11/22/2022-19:23:26] [I] [TRT] ----------------------------------------------------------------
[11/22/2022-19:23:26] [W] [TRT] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[11/22/2022-19:23:26] [I] Finish parsing network model
[11/22/2022-19:23:26] [W] [TRT] Using PreviewFeature::kFASTER_DYNAMIC_SHAPES_0805 can help improve performance and resolve potential functional issues.
[11/22/2022-19:23:26] [W] [TRT] Using PreviewFeature::kFASTER_DYNAMIC_SHAPES_0805 can help improve performance and resolve potential functional issues.
[11/22/2022-19:23:26] [W] [TRT] Using PreviewFeature::kFASTER_DYNAMIC_SHAPES_0805 can help improve performance and resolve potential functional issues.
[11/22/2022-19:23:27] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +397, GPU +166, now: CPU 1030, GPU 427 (MiB)
[11/22/2022-19:23:27] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +114, GPU +54, now: CPU 1144, GPU 481 (MiB)
[11/22/2022-19:23:27] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[11/22/2022-19:23:28] [E] Error[1]: [genericReformat.cu::executeGenericCopy::1479] Error Code 1: Internal Error (Invalid inputs to reformat)
[11/22/2022-19:23:28] [E] Error[2]: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[11/22/2022-19:23:28] [E] Engine could not be created from network
[11/22/2022-19:23:28] [E] Building engine failed
[11/22/2022-19:23:28] [E] Failed to create engine from model or file.
[11/22/2022-19:23:28] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8501] # ./trtexec --onnx=/home/vanly/projects/pt2trt_test/index.onnx --saveEngine=/home/vanly/projects/pt2trt_test/index.trt

## Environment

**TensorRT Version**: 8.5.1.7 GA
**NVIDIA GPU**: T1200
**NVIDIA Driver Version**: 515.48.07
**CUDA Version**: 11.3
**CUDNN Version**: 8.6
**Operating System**: ubuntu20.04
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.12.1
**Baremetal or Container (if so, version)**: 

## Relevant Files

https://github.com/vanly89/issue.git

## Steps To Reproduce

1. run nonzeroTest.py  in https://github.com/vanly89/issue.git to get index.onnx file.
2. go to TensorRT-8.5.1.7/bin/ directory.
3. run command ./trtexec --onnx=index.onnx --saveEngine index.trt

**Comment by vanly89** [comment] 2022-11-23 01:10
> Can you try adding `--preview=fasterDynamicShapes0805` in your trtexec commands?

Thanks for your kind answer.
I tried the command ./trtexec --onnx=index.onnx --saveEngine index.trt --preview=+fasterDynamicShapes0805,  but still got the same error as follows:

[11/23/2022-09:04:42] [I] Start parsing network model
[11/23/2022-09:04:42] [I] [TRT] ----------------------------------------------------------------
[11/23/2022-09:04:42] [I] [TRT] Input filename:   /home/vanly/projects/pt2trt_test/index.onnx
[11/23/2022-09:04:42] [I] [TRT] ONNX IR version:  0.0.8
[11/23/2022-09:04:42] [I] [TRT] Opset version:    16
[11/23/2022-09:04:42] [I] [TRT] Producer name:    pytorch
[11/23/2022-09:04:42] [I] [TRT] Producer version: 1.12.1
[11/23/2022-09:04:42] [I] [TRT] Domain:           
[11/23/2022-09:04:42] [I] [TRT] Model version:    0
[11/23/2022-09:04:42] [I] [TRT] Doc string:       
[11/23/2022-09:04:42] [I] [TRT] ----------------------------------------------------------------
[11/23/2022-09:04:42] [W] [TRT] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[11/23/2022-09:04:42] [I] Finish parsing network model
[11/23/2022-09:04:43] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +397, GPU +166, now: CPU 1030, GPU 427 (MiB)
[11/23/2022-09:04:43] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +114, GPU +54, now: CPU 1144, GPU 481 (MiB)
[11/23/2022-09:04:43] [I] [TRT] Local timing cache in use. Profiling results in this builder pass will not be stored.
[11/23/2022-09:04:43] [W] [TRT] Using kFASTER_DYNAMIC_SHAPES_0805 preview feature.
[11/23/2022-09:04:43] [W] [TRT] Skipping tactic 0x0000000000000000 due to Myelin error: Mistmatched number of elements in reshape op: Reshape_6_reshape input tensor onnx__Reshape_6' has shape [sp__mye1=0], total elements: sp__mye1=0 and specified output shape [sp__mye25=2,sp__mye27=0], total elements: __mye63=20; 
[11/23/2022-09:04:43] [E] Error[10]: [optimizer.cpp::computeCosts::3728] Error Code 10: Internal Error (Could not find any implementation for node {ForeignNode[Transpose_3...Reshape_6]}.)
[11/23/2022-09:04:43] [E] Error[2]: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[11/23/2022-09:04:43] [E] Engine could not be created from network
[11/23/2022-09:04:43] [E] Building engine failed
[11/23/2022-09:04:43] [E] Failed to create engine from model or file.
[11/23/2022-09:04:43] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8501] # ./trtexec --onnx=/home/vanly/projects/pt2trt_test/index.onnx --saveEngine=/home/vanly/projects/pt2trt_test/index.trt --preview=+fasterDynamicShapes0805

**Comment by zerollzeng** [comment] 2022-11-28 14:09
I can reproduce this and I've filed internal bug 3885648 to track this. thanks!

**Comment by zerollzeng** [comment] 2022-12-23 15:08
This will be fixed in the next release, thanks!

**Closed by zerollzeng** 2022-12-23 15:08 UTC
Labels: triaged

**Comment by slimwangyue** [comment] 2024-01-11 14:59
same bug here, is it resolved in tensorrt8.6 GA?

**Comment by zerollzeng** [comment] 2024-01-15 15:02
Should be fixed, please take a try.

**Comment by demuxin** [comment] 2024-03-20 06:59
> Can you try adding `--preview=fasterDynamicShapes0805` in your trtexec commands?

@zerollzeng , How to implement this function via C++ TensorRT api ?

**Comment by zerollzeng** [comment] 2024-03-23 07:18
See https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a78e8d461b39b52904335d005506b009e
and this flag is removed after TRT 9+ since we enable it by default.
