### ISSUE TITLE
Failing to convert from ONNX model | int8 | Jetson AGX Orin DevKit | CaskConvolution

### ISSUE THREAD

**Issue by Lucas-Steinmann** [NVIDIA/TensorRT#2787] opened 2023-03-18 16:57 UTC
## Description

I'm trying to convert a UNET-like architecutre from ONNX to TensorRT with int8-precision.

Following error is raised after about an hour:

```
[03/18/2023-01:23:30] [TRT] [V] *************** Autotuning format combination: Float(7077888,2359296,1536,1) -> Float(150994944,2359296,1536,1) ***************
[03/18/2023-01:23:30] [TRT] [V] --------------- Timing Runner: Conv_0 + Relu_1 (CudaDepthwiseConvolution)
[03/18/2023-01:23:30] [TRT] [V] CudaDepthwiseConvolution has no valid tactics for this config, skipping
[03/18/2023-01:23:30] [TRT] [V] --------------- Timing Runner: Conv_0 + Relu_1 (FusedConvActConvolution)
[03/18/2023-01:23:30] [TRT] [V] FusedConvActConvolution has no valid tactics for this config, skipping
[03/18/2023-01:23:30] [TRT] [V] --------------- Timing Runner: Conv_0 + Relu_1 (CudnnConvolution)
[03/18/2023-01:23:30] [TRT] [V] Tactic: 0x0000000000000000 Time: 39.1082
[03/18/2023-01:23:31] [TRT] [V] Tactic: 0x0000000000000001 Time: 33.2873
[03/18/2023-01:23:31] [TRT] [V] Tactic: 0x0000000000000002 Time: 44.2043
[03/18/2023-01:23:32] [TRT] [V] Tactic: 0x0000000000000005 Time: 157.736
[03/18/2023-01:23:33] [TRT] [V] Tactic: 0x0000000000000006 Time: 70.2363
[03/18/2023-01:23:33] [TRT] [V] Tactic: 0x0000000000000038 Time: 39.1251
[03/18/2023-01:23:33] [TRT] [V] Tactic: 0x0000000000000039 Time: 33.2948
[03/18/2023-01:23:34] [TRT] [V] Tactic: 0x000000000000003a Time: 44.1741
[03/18/2023-01:23:35] [TRT] [V] Tactic: 0x000000000000003d Time: 156.942
[03/18/2023-01:23:35] [TRT] [V] Tactic: 0x000000000000003e Time: 70.1369
[03/18/2023-01:23:36] [TRT] [V] Tactic: 0x0000000000000070 Time: 39.1039
[03/18/2023-01:23:36] [TRT] [V] Tactic: 0x0000000000000071 Time: 33.2924
[03/18/2023-01:23:36] [TRT] [V] Tactic: 0x0000000000000072 Time: 44.1832
[03/18/2023-01:23:37] [TRT] [V] Tactic: 0x0000000000000075 Time: 157.314
[03/18/2023-01:23:38] [TRT] [V] Tactic: 0x0000000000000076 Time: 70.3201
[03/18/2023-01:23:38] [TRT] [V] Fastest Tactic: 0x0000000000000001 Time: 33.2873
[03/18/2023-01:23:38] [TRT] [V] --------------- Timing Runner: Conv_0 + Relu_1 (CaskConvolution)
[03/18/2023-01:23:38] [TRT] [V] Conv_0 + Relu_1 Set Tactic Name: sm80_xmma_fprop_implicit_gemm_f32f32_f32f32_f32_nchwkcrs_nchw_tilesize64x128x8_stage3_warpsize1x4x1_g1_ffma_t1r3s3_aligna4_alignc4 Tactic: 0x01cf8ce2da913006
terminate called after throwing an instance of 'cask_plugin_trt::CudaDriverError'
  what():  
```

I'm using the MMDeploy+MMSegmentation library. 
So reproducing is slightly more involved. I'm not sure how to make it easier, without copying code+models from their repository.

I hope the error message is already telling enough, that it doesn't require full reproducing.

My questions are:

- **Can I turn off CaskConvolution, since it appears that CudnnConvolution was succesful?**
- **How to resolve it properly?**

## Environment

**TensorRT Version**: 8.4.1.5
**NVIDIA GPU**: Jetson AGX Orin DeviKit 
**NVIDIA Driver Version**: unknown L4T 35.1
**CUDA Version**: 11.4
**CUDNN Version**: 8.4.1.50-1+cuda11.4
**Operating System**: L4T Docker image (ubuntu based)
**Python Version (if applicable)**: 3.8.10
**Tensorflow Version (if applicable)**: n.a.
**PyTorch Version (if applicable)**: 1.12.
**Baremetal or Container (if so, version)**: nvcr.io/nvidia/l4t-tensorrt:r8.4.1.5-devel 

## Relevant Files

```bash
MMDEPLOY_ROOT=/root/mmdeploy/
MMSEG_ROOT=/root/mmsegmentation
DEPLOY_CFG_PATH="${MMDEPLOY_ROOT}/configs/mmseg/segmentation_tensorrt-int8_static-1024x1024.py"
MODEL_CFG_PATH="${MMSEG_ROOT}/configs/unet/fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes.py"
MODEL_CHECKPOINT_PATH="fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes_20211210_145204-6860854e.pth"
INPUT_IMG="/app/data/crop_1536x1536.png"
TEST_IMG=$INPUT_IMG
CALIB_DATA_CFG="/app/config/dev/datasets/calibration_dataset.py"
DEVICE="cuda"
WORK_DIR="./tensorrt/"


python ./tools/deploy.py \
    ${DEPLOY_CFG_PATH} \
    ${MODEL_CFG_PATH} \
    ${MODEL_CHECKPOINT_PATH} \
    ${INPUT_IMG} \
    --test-img ${TEST_IMG} \
    --work-dir ${WORK_DIR} \
    --calib-dataset-cfg ${CALIB_DATA_CFG} \
    --device ${DEVICE} \
    --log-level DEBUG \ # warning does not set TRT log level to VERBOSE as it should do --> fix manually in mmdeploy.backend.tensorrt.utils
    --show \
    --dump-info
```

## Steps To Reproduce

 1. Use the nvcr.io/nvidia/l4t-tensorrt:r8.4.1.5-devel on a Jetson AGX Orin DevKit
 2. Install mmsegmentation and mmdeploy according to their instructions: https://mmdeploy.readthedocs.io/en/latest/01-how-to-build/jetsons.html
 3. Create a calibration dataset (I guess it is not relevant for reproducing the error what data is in it)
 4. Create the input image (probably also irrelevant)
 5. Download the model from https://download.openmmlab.com/mmsegmentation/v0.5/unet/fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes/fcn_unet_s5-d16_4x4_512x1024_160k_cityscapes_20211210_145204-6860854e.pth
 6. run the bash script above

**Comment by zerollzeng** [comment] 2023-03-19 04:49
@nvpohanh Do you know about the error?

@Lucas-Steinmann This looks like a env issue for me, can you try running it under the raw env(not in docker, just flash a new Jetpack, I would suggest to use the latest JP version), if it still can't work, can you share the onnx model here(or upload it to GDrive and share the link here). Thanks!

**Comment by nvpohanh** [comment] 2023-03-20 01:57
This seems to be caused by driver version mismatch or driver issue... Could you share the command you used to launch the docker container?

**Comment by Lucas-Steinmann** [comment] 2023-03-20 07:14
Thanks for your quick help.

My container run command is:

```
CID=$(docker run \
        -d --rm\
        --network host \
        --ipc=host \
        --gpus all \
        <removed mounts>
        trt-remote-dev-container \
        ssh $PORT)
```

For clarification: I've added an entrypoint to the container, which starts sshd on `$PORT` enabling me to attach a remote debugger.

But I think I have some new ideas on how to solve the problem.
I've directly executed trtexec with the same model but missing most of the flags (except int8) and it worked without problems.
So now, I will try to converge the mmdeploy python API call to TensoRT builder and the trtexec command to see which flag is the problem or if it is the python api/mmdeploy itself.
I will also try what you said, and run it directly on the host.

But this will take me some time, since it always takes about an hour and it is not such high priority for me right now.
So feel free to close this issue. I will comment if there is an update.

**Comment by zerollzeng** [comment] 2023-03-21 07:59
Okay, close this for now. Feel free to reopen it if you want :-)

**Closed by zerollzeng** 2023-03-21 07:59 UTC
Labels: triaged

**Comment by shimen** [comment] 2023-06-28 12:14
@Lucas-Steinmann Have you managed to fix this?

**Comment by Lucas-Steinmann** [comment] 2023-06-28 20:52
> @Lucas-Steinmann Have you managed to fix this? I'm experiencing the same problem. Running with mmdeploy or directly with trtexec, creates different outputs.

Unfortunately, no. I optimized some preprocessing/data transfer routines, and now we are fast _enough_. If this should change, I will invest some more time.

Sorry I could not help.

**Comment by shimen** [comment] 2023-07-09 13:32
@Lucas-Steinmann If you are using old version of mmdeploy (0.13) I found out that the conversion to int8 falis.
But if you use the files generated with **python tools/deploy.py** and provide them as an input for **python tools/onnx2tensorrt.py** the conversion completes successfully
