### ISSUE TITLE
PyTorch Bert gives wrong results after converted to TensorRT

### ISSUE THREAD

**Issue by MagiaSN** [NVIDIA/TensorRT#1392] opened 2021-07-21 13:05 UTC
## Description

I convert a PyTorch (HuggingFace) Bert model to ONNX, and then to TensorRT. The PyTorch and ONNX model gives same results, but the TensorRT model not.

## Environment

**TensorRT Version**: 8.0.1.6
**NVIDIA GPU**: T4
**NVIDIA Driver Version**: 450.102.04
**CUDA Version**: 11.0
**CUDNN Version**: 
**Operating System**: CentOS 7
**Python Version (if applicable)**: 3.7.9
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.8.1+cu111
**Baremetal or Container (if so, version)**: 

## Relevant Files

I write a python script to reproduce this issue:

https://gist.github.com/MagiaSN/be8eeb36857df5b90f3991138d70aede

## Steps To Reproduce

First I dump a PyTorch Bert model to disk for testing:

```python
def save_pytorch():
    config = AutoConfig.from_pretrained("bert-base-cased")
    config.num_labels = 5
    model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", config=config)
    model.save_pretrained(PYTORCH_MODEL_PATH)
```

Then convert it to ONNX:

```python
def pytorch_to_onnx():
    model = AutoModelForSequenceClassification.from_pretrained(PYTORCH_MODEL_PATH)
    model.eval()
    model.forward = functools.partial(model.forward, return_dict=False)
    token_ids = torch.ones(2, 32, dtype=torch.long)
    attn_mask = torch.ones(2, 32, dtype=torch.long)
    torch.onnx.export(
        model,
        (token_ids, attn_mask),
        ONNX_MODEL_PATH,
        export_params=True,
        opset_version=10,
        input_names=["token_ids", "attn_mask"],
        output_names=["logits"],
        dynamic_axes={"token_ids": [0, 1], "attn_mask": [0, 1]},
    )
```

And then convert to TensorRT:

```python
def onnx_to_tensorrt():
    trt_logger = trt.Logger(trt.Logger.WARNING)
    trt_builder = trt.Builder(trt_logger)
    explicit_batch = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    trt_network = trt_builder.create_network(explicit_batch)
    trt_parser = trt.OnnxParser(trt_network, trt_logger)
    with open(ONNX_MODEL_PATH, "rb") as f:
        assert trt_parser.parse(f.read())
    trt_config = trt_builder.create_builder_config()
    trt_config.max_workspace_size = 2 * (1 << 30)
    trt_optim_profile = trt_builder.create_optimization_profile()
    trt_optim_profile.set_shape("token_ids", (2, 32), (2, 32), (2, 32))
    trt_optim_profile.set_shape("attn_mask", (2, 32), (2, 32), (2, 32))
    trt_config.add_optimization_profile(trt_optim_profile)
    trt_engine = trt_builder.build_engine(trt_network, trt_config)
    with open(TRT_MODEL_PATH, "wb") as f:
        f.write(trt_engine.serialize())
```

Run the three models:

```python
def run_pytorch():
    model = AutoModelForSequenceClassification.from_pretrained(PYTORCH_MODEL_PATH)
    model.eval()
    token_ids = torch.ones(2, 32, dtype=torch.long)
    attn_mask = torch.ones(2, 32, dtype=torch.long)
    logits = model(token_ids, attn_mask)[0].detach().numpy()
    print("pytorch")
    print(logits)


def run_onnx():
    ort_session = onnxruntime.InferenceSession(ONNX_MODEL_PATH)
    token_ids = np.ones((2, 32), dtype=np.long)
    attn_mask = np.ones((2, 32), dtype=np.long)
    inputs = {"token_ids": token_ids, "attn_mask": attn_mask}
    logits = ort_session.run(None, inputs)[0]
    print("onnx")
    print(logits)


def run_tensorrt():
    trt_logger = trt.Logger(trt.Logger.WARNING)
    trt_runtime = trt.Runtime(trt_logger)
    with open(TRT_MODEL_PATH, "rb") as f:
        trt_engine = trt_runtime.deserialize_cuda_engine(f.read())
    trt_context = trt_engine.create_execution_context()
    trt_context.set_binding_shape(0, (2, 32))
    trt_context.set_binding_shape(0, (2, 32))
    # It seems trt requires int32...
    token_ids = torch.ones((2, 32), dtype=torch.int32, device="cuda")
    attn_mask = torch.ones((2, 32), dtype=torch.int32, device="cuda")
    logits = torch.empty((2, 5), dtype=torch.float32, device="cuda")
    bindings = [token_ids.data_ptr(), attn_mask.data_ptr(), logits.data_ptr()]
    stream = torch.cuda.Stream()
    trt_context.execute_async_v2(bindings=bindings, stream_handle=stream.cuda_stream)
    print("tensorrt")
    print(logits.cpu().numpy())
```

And the TensorRT model gives different results, which is apparently wrong:

```
pytorch
[[ 0.23999208 -0.06004044  0.00191891 -0.2095247  -0.3596471 ]
 [ 0.23999208 -0.06004044  0.00191891 -0.2095247  -0.3596471 ]]
onnx
[[ 0.23999205 -0.0600413   0.00191779 -0.20952475 -0.35964683]
 [ 0.23999205 -0.0600413   0.00191779 -0.20952475 -0.35964683]]
tensorrt
[[ 0.23999813 -0.06004131  0.00191483 -0.20952295 -0.35964924]
 [-0.17394313  0.2216019   0.06454907  0.03144458 -0.5975722 ]]
```

**Comment by ttyio** [comment] 2021-08-02 09:36
@MagiaSN , have you tried 7.2, it this regression from 7.2? thanks!

**Comment by MagiaSN** [comment] 2021-08-05 08:16
> @MagiaSN , have you tried 7.2, it this regression from 7.2? thanks!

It works with 7.2, but migration to 7.2 lead me to another issue: https://github.com/NVIDIA/TensorRT/issues/1327

I hope this could be fixed in the next release

**Comment by ttyio** [comment] 2021-12-22 05:44
Closing since this is solved, thanks!

**Closed by ttyio** 2021-12-22 05:44 UTC
Labels: triaged, Release: 8.x, Models: NLP
