### ISSUE TITLE
Onnx-outputs mark all  trigger Error

### ISSUE THREAD

**Issue by Tracersboy** [NVIDIA/TensorRT#3035] opened 2023-06-04 04:55 UTC
cmd is 
 polygraphy run inference/yolov5s.onnx --onnxrt --trt --fp16 --verbose   --onnx-outputs mark all --trt-outputs mark all --atol 1e-3 --rtol 1e-3 --input-shapes 'images:[1,3,640,640]' 

but i get error

```
[V] onnxrt-runner-N0-06/04/23-12:39:59  | Input metadata is: {images [dtype=float32, shape=('batch', 3, 640, 640)]}
Traceback (most recent call last):
  File "/data/wusw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 41, in <module>
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 142, in execute_runner
    f"{active_runner.name:35}\n---- Inference Output(s) ----\n{TensorMetadata().from_feed_dict(outputs)}",
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/common/struct.py", line 93, in from_feed_dict
    meta.add(name, arr.dtype, arr.shape)
AttributeError: 'NoneType' object has no attribute 'dtype'
```
I tried to delete “-- onnx outputs mark all“, and it work
If I want to check if there are any deviations in the output of all layers of YOLOv5 between onnx and tensorrt-engine , how should I use polygraph

**Comment by zerollzeng** [comment] 2023-06-04 14:25
+ @pranavm-nvidia about the python error.

We don't suggest using `--mark all` as it will break all TRT layer fusions.

**Comment by pranavm-nvidia** [comment] 2023-06-05 16:20
@Tracersboy would you be able to share your model?

**Comment by Tracersboy** [comment] 2023-06-06 09:47
@pranavm-nvidia  sure
https://drive.google.com/file/d/1_eob6G1W8QqWCHgY0X5AFwCLvYaKIZD3/view?usp=sharing

**Comment by pranavm-nvidia** [comment] 2023-06-06 21:22
Strange, I'm not able to reproduce the error locally. Which version of Polygraphy are you using? Could you try updating?

**Comment by Tracersboy** [comment] 2023-06-07 02:24
`[I] RUNNING | Command: /data/wusw/miniconda3/bin/polygraphy run inference/yolov5s.onnx --onnxrt --trt --fp16 --verbose --onnx-outputs mark all --trt-outputs mark all --atol 1e-3 --rtol 1e-3 --input-shapes images:[1,3,640,640]
[V] Loaded Module: **polygraphy | Version: 0.47.1** | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy']
[V] Loaded extension modules: []
[V] Loaded Module: **tensorrt | Version: 8.6.1** | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/tensorrt']
[I] Will generate inference input data according to provided TensorMetadata: {images [shape=(1, 3, 640, 640)]}
[I] onnxrt-runner-N0-06/07/23-10:12:37  | Activating and starting inference
[I] Loading model: /data/wusw/tensorrt-dome1/infer/inference/yolov5s.onnx
[V] Loaded Module: **onnx | Version: 1.14.0** | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/onnx']
[V] Marking all ONNX tensors as outputs
[V] Loaded Module: onnxruntime | Version: 1.14.1 | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/onnxruntime']
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
[V] Loaded Module: numpy | Version: 1.24.1 | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/numpy']
[V] Loading inputs from data loader
[V] Generating data using numpy seed: 1
[V] Input tensor: images | Generating input data in range: [0.0, 1.0]
[I] onnxrt-runner-N0-06/07/23-10:12:37 
    ---- Inference Input(s) ----
    {images [dtype=float32, shape=(1, 3, 640, 640)]}
[V] onnxrt-runner-N0-06/07/23-10:12:37  | Input metadata is: {images [dtype=float32, shape=('batch', 3, 640, 640)]}
Traceback (most recent call last):
  File "/data/wusw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 41, in <module>
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 142, in execute_runner
    f"{active_runner.name:35}\n---- Inference Output(s) ----\n{TensorMetadata().from_feed_dict(outputs)}",
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/common/struct.py", line 93, in from_feed_dict
    meta.add(name, arr.dtype, arr.shape)
AttributeError: 'NoneType' object has no attribute 'dtype'`

I am using the latest version，If you are also the latest version, I think I can try changing the version of Python or other tools to see if it works. 

by the way，this issue has the same problem as me https://github.com/NVIDIA/TensorRT/issues/2938

**Comment by zerollzeng** [comment] 2023-06-07 15:14
Old memory just came to my mind, it may be related to numpy. could you please try numpy <=1.23? And also run it for one more time.

**Comment by Tracersboy** [comment] 2023-06-08 15:49
[I] RUNNING | Command: /data/wusw/miniconda3/bin/polygraphy run inference/yolov5s.onnx --onnxrt --trt --fp16 --verbose --onnx-outputs mark all --trt-outputs mark all --atol 1e-3 --rtol 1e-3 --input-shapes images:[1,3,640,640]
[V] Loaded Module: polygraphy | Version: 0.47.1 | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy']
[V] Loaded extension modules: []
[V] Loaded Module: tensorrt | Version: 8.6.1 | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/tensorrt']
[I] Will generate inference input data according to provided TensorMetadata: {images [shape=(1, 3, 640, 640)]}
[I] onnxrt-runner-N0-06/08/23-23:47:22  | Activating and starting inference
[I] Loading model: /data/wusw/tensorrt-dome1/infer/inference/yolov5s.onnx
[V] Loaded Module: onnx | Version: 1.14.0 | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/onnx']
[V] Marking all ONNX tensors as outputs
[V] Loaded Module: onnxruntime | Version: 1.14.1 | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/onnxruntime']
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
[V] Loaded Module: **`numpy | Version: 1.22.0`** | Path: ['/data/wusw/miniconda3/lib/python3.9/site-packages/numpy']
[V] Loading inputs from data loader
[V] Generating data using numpy seed: 1
[V] Input tensor: images | Generating input data in range: [0.0, 1.0]
[I] onnxrt-runner-N0-06/08/23-23:47:22 
    ---- Inference Input(s) ----
    {images [dtype=float32, shape=(1, 3, 640, 640)]}
[V] onnxrt-runner-N0-06/08/23-23:47:22  | Input metadata is: {images [dtype=float32, shape=('batch', 3, 640, 640)]}
Traceback (most recent call last):
  File "/data/wusw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 228, in run_impl
    exec(str(script))
  File "<string>", line 41, in <module>
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 213, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 142, in execute_runner
    f"{active_runner.name:35}\n---- Inference Output(s) ----\n{TensorMetadata().from_feed_dict(outputs)}",
  File "/data/wusw/miniconda3/lib/python3.9/site-packages/polygraphy/common/struct.py", line 93, in from_feed_dict
    meta.add(name, arr.dtype, arr.shape)
AttributeError: 'NoneType' object has no attribute 'dtype'****


If possible, could you share the version number of the environment that you can successfully work

**Comment by pranavm-nvidia** [comment] 2023-06-08 16:15
I'm currently using `1.21.6`

**Comment by Tracersboy** [comment] 2023-06-08 16:28
The same to 1.21.6，Maybe it wasn't caused by numpy ，Which version of (tensorrt, onnx ,onnxruntime,python)  are you using?This is really a tricky problem :(

**Comment by pranavm-nvidia** [comment] 2023-06-08 18:51
Ah seems to be a bug in `onnxruntime==1.14.1`. I'm able to reproduce when I downgrade just that package.

**Comment by ttyio** [comment] 2023-09-12 21:38
I will close this since there is WAR to upgrade onnxruntime to 1.15.0, thanks all!

**Closed by ttyio** 2023-09-12 21:38 UTC
Labels: triaged
