### ISSUE TITLE
ConTranspose2d layers give wrong results after being converted to TensorRT

### ISSUE THREAD

**Issue by spivakoa** [NVIDIA/TensorRT#1699] opened 2022-01-02 14:36 UTC
TensorRT Version: 8.2.0.6
GPU Type: RTX2080
Nvidia Driver Version: 470.86
CUDA Version: 11.4
CUDNN Version: 8.2.4
Operating System + Version: Ubuntu 18.04
Python Version (if applicable): 3.7.11
PyTorch Version (if applicable): 1.9.0

Hello,
I'm trying to quantize some models to int8, while  comparing the outputs of the ONNX and the quantized TensorRT engine using polygraphy tool. The ConvTranspose2d layers seems to be an issue, while trying to break the model graph into smaller subgraphs to track the problem. This is the issue I met not for the first time already, I was forced to not quantize the convtranspose2d layers to overcome this, but I really seek the problem now.

The ONNX file of the model is attached.  If I force the graph to end before the ConvTranspose_659, the onnx runtime is pretty close to tensorrt runtime, otherwise the statistics are way of.

Will appreciate if someone will take a look and explain what is the problem. 
[quantized_depthnet.zip](https://github.com/NVIDIA/TensorRT/files/7799206/quantized_depthnet.zip)

**Comment by ttyio** [comment] 2022-01-07 09:28
Thanks @spivakoa  for the model, I have created internal issue to track this.

**Comment by spivakoa** [comment] 2022-01-27 12:20
Hi @ttyio , any updates on this issue?

**Comment by ttyio** [comment] 2022-01-28 01:41
Hi @spivakoa, sorry quantization toolkit misaligned with TRT implementation for convTranspose. Could you try quant axis 0 for deconv?

     QUANT_DESC_8BIT_CONVTRANSPOSE2D_WEIGHT_PER_CHANNEL = QuantDescriptor(num_bits=8, axis=(0))

We will fix the code and document, thanks!

**Comment by spivakoa** [comment] 2022-01-31 20:11
Hi @ttyio ,  thank you for the answer. Where should I add this line inside the code?  How this QUANT_DESC_8BIT_CONVTRANSPOSE2D_WEIGHT_PER_CHANNEL  is being treated?

Thank you!

**Comment by spivakoa** [comment] 2022-02-03 12:10
Hi @ttyio , I tried your suggestion above, but unfortunately without success. When the fix to this issue is expected to be released?

Thank you!

**Comment by ttyio** [comment] 2022-02-14 09:36
Hello @spivakoa , 

Did you modify the https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/pytorch_quantization/tensor_quant.py#L229 ? 

After the modification, when you use Netron to visualize the model, you could see the quantization axis is `0` instead of `1`. 

Could you attach your ONNX again if you still see mismatch? thanks!

![image](https://user-images.githubusercontent.com/365590/153838007-f15d6802-01b8-448c-bf32-87d43ff9b3de.png)

**Comment by spivakoa** [comment] 2022-02-15 08:15
Hi @ttyio, 
I made the changes you suggested and calibrated the model. However the onnx and trt runtime still differ.
Please find attached onnx file (zipped)
[quantized_detnet.zip](https://github.com/NVIDIA/TensorRT/files/8067079/quantized_detnet.zip)

**Comment by ttyio** [comment] 2022-02-17 05:54
Hi @spivakoa , I tried your new model, but I did not obvious loss caused by convTranspose.

I tried checkout the 546 (output of relu after convTranspose) using command line: 
polygraphy run --onnxrt --trt --int8 --workspace=1G quantized_detnet.onnx --onnx-outputs=546 --trt-outputs=546

the output looks like this:
[I]         onnxrt-runner-N0-02/15/22-09:33:28: 546 | Stats: mean=0.070386, std-dev=0.12211, var=0.014911, median=0, min=0 at (0, 0, 0, 22), max=0.87536 at (0, 36, 401, 3), avg-magnitude=0.070386
[I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (0    , 0.143) |    4922564 | ########################################
                (0.143, 0.285) |     714055 | #####
                (0.285, 0.428) |     382465 | ###
                (0.428, 0.57 ) |      92765 |
                (0.57 , 0.713) |      30476 |
                (0.713, 0.856) |       1672 |
                (0.856, 0.998) |          3 |
                (0.998, 1.14 ) |          0 |
                (1.14 , 1.28 ) |          0 |
                (1.28 , 1.43 ) |          0 |
[I]         trt-runner-N0-02/15/22-09:33:28: 546 | Stats: mean=0.070436, std-dev=0.14467, var=0.02093, median=0, min=0 at (0, 0, 1, 6), max=1.4261 at (0, 36, 385, 15), avg-magnitude=0.070436
[I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (0    , 0.143) |    4960894 | ########################################
                (0.143, 0.285) |     731193 | #####
                (0.285, 0.428) |     277471 | ##
                (0.428, 0.57 ) |      82883 |
                (0.57 , 0.713) |      16573 |
                (0.713, 0.856) |      32468 |
                (0.856, 0.998) |      28462 |
                (0.998, 1.14 ) |      11851 |
                (1.14 , 1.28 ) |       2060 |
                (1.28 , 1.43 ) |        145 |


The distribution matched, and if I add option `--check-error-stat=median`, the polygraphy passed. 
How did you find the loss? thanks!

**Comment by spivakoa** [comment] 2022-02-17 06:56
Hi @ttyio , thank you for the fast response! I was testing for the node 576, which is a final convolution output and the results really differ. Using the polygraphy I just tested the input/outputs of the 3 ConvTranspose2d layers the model has. While nodes 546 and 560 were pretty much close, the output of the 3rd block node 574 fails with pretty big margins and different histograms. However the input to this ConvTranspose2d block (ConvTranspose _288), node 532 passed. 

Thank you!

**Comment by ttyio** [comment] 2022-02-22 03:21
Thanks @spivakoa , we catch a graph rewrite bug in the ConvTranspose + BN. Before the fix

    [I]         trt-runner-N0-02/22/22-03:01:36: 574 | Stats: mean=0.2286, std-dev=0.39699, var=0.1576, median=0, min=0 at (0, 0, 0, 0), max=3.6899 at (0, 54, 123, 2), avg-magnitude=0.2286
    [I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (0    , 0.512) |    5066780 | ########################################
                (0.512, 1.02 ) |     671551 | #####
                (1.02 , 1.53 ) |     321311 | ##
                (1.53 , 2.05 ) |      68641 |
                (2.05 , 2.56 ) |      12691 |
                (2.56 , 3.07 ) |       2667 |
                (3.07 , 3.58 ) |        348 |
                (3.58 , 4.09 ) |         11 |
                (4.09 , 4.6  ) |          0 |
                (4.6  , 5.12 ) |          0 |
    [I]         onnxrt-runner-N0-02/22/22-03:01:36: 574 | Stats: mean=0.53388, std-dev=0.61167, var=0.37414, median=0.35012, min=0 at (0, 0, 1, 0), max=5.1161 at (0, 3, 432, 0), avg-magnitude=0.53388
    [I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (0    , 0.512) |    3959305 | ########################################
                (0.512, 1.02 ) |    1191182 | ############
                (1.02 , 1.53 ) |     521731 | #####
                (1.53 , 2.05 ) |     265593 | ##
                (2.05 , 2.56 ) |      86342 |
                (2.56 , 3.07 ) |      85546 |
                (3.07 , 3.58 ) |      29198 |
                (3.58 , 4.09 ) |       3557 |
                (4.09 , 4.6  ) |       1160 |
                (4.6  , 5.12 ) |        386 |


After the fix 



    [I]         trt-runner-N0-02/22/22-03:11:47: 574 | Stats: mean=0.56124, std-dev=0.67005, var=0.44896, median=0.34407, min=0 at (0, 0, 1, 0), max=4.9924 at (0, 3, 376, 0), avg-magnitude=0.56124
    [I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (0    , 0.512) |    4006058 | ########################################
                (0.512, 1.02 ) |    1025605 | ##########
                (1.02 , 1.53 ) |     457572 | ####
                (1.53 , 2.05 ) |     403832 | ####
                (2.05 , 2.56 ) |     106079 | #
                (2.56 , 3.07 ) |      80764 |
                (3.07 , 3.58 ) |      54899 |
                (3.58 , 4.09 ) |       5957 |
                (4.09 , 4.6  ) |       2818 |
                (4.6  , 5.12 ) |        416 |
       [I]         onnxrt-runner-N0-02/22/22-03:11:47: 574 | Stats: mean=0.53388, std-dev=0.61167, var=0.37414, median=0.35012, min=0 at (0, 0, 1, 0), max=5.1161 at (0, 3, 432, 0), avg-magnitude=0.53388
       [I]             ---- Histogram ----
                Bin Range      |  Num Elems | Visualization
                (0    , 0.512) |    3959305 | ########################################
                (0.512, 1.02 ) |    1191182 | ############
                (1.02 , 1.53 ) |     521731 | #####
                (1.53 , 2.05 ) |     265593 | ##
                (2.05 , 2.56 ) |      86342 |
                (2.56 , 3.07 ) |      85546 |
                (3.07 , 3.58 ) |      29198 |
                (3.58 , 4.09 ) |       3557 |
                (4.09 , 4.6  ) |       1160 |
                (4.6  , 5.12 ) |        386 |

To workaround this before next major release, maybe try insert identity layer between ConvTranspose and BN? thanks

**Comment by spivakoa** [comment] 2022-02-24 18:43
Hi @ttyio , just wanted to clarify. The pytorch identity layer is a placeholder which does not appear in the graph. You meant just insert identity layer between the ConvTranspose and BN while calibrating the model?

**Comment by ttyio** [comment] 2022-02-25 05:30
Hello @spivakoa , What I want to WAR is to break the `ConvTranspose` and `BN` fusion, and if the `identity` is exposed in ONNX, then it is also exposed in TRT, stand between `ConvTranspose` and `BN`, hope it can break the fusion. So It is worth trying. Thanks!

**Comment by spivakoa** [comment] 2022-02-25 21:53
Hi @ttyio , I added an identity layer using onnx_graphsurgeon and compared the accuracy once again. The accuracy improved, however there is still an accuracy drop comparing a node before the ConvTranspose layers and after them. Is it normal? 
Additional question is if it is still worth quantizing the ConvTranspose layer followed by identity and BN as there is no fusion and it will take more time to run as the tactics are int8->fp32?
Modified onnx file is attached.

Thank you!
[modified_quantized_detnet.zip](https://github.com/NVIDIA/TensorRT/files/8145062/modified_quantized_detnet.zip)

**Comment by spivakoa** [comment] 2022-02-28 07:08
Hi @ttyio, I ran the int8 and fp16 models through TensorRT profiler and I received a slowdown for ConvTranspose layers. The slowdown rate is by factor of ~2. Moreover, the identity layer add additional 100us. I attached the 16bits onnx I used. You can compare it to the modified_quantized_detnet.onnx from above.

Thank you!
[quantized_detnet_16bits.zip](https://github.com/NVIDIA/TensorRT/files/8151271/quantized_detnet_16bits.zip)

**Comment by ttyio** [comment] 2022-03-14 05:53
Hi @spivakoa , sorry for the delay response. 

>> however there is still an accuracy drop comparing a node before the ConvTranspose layers and after them. Is it normal?
We have checked the kernel also we have some unit test , we did not find accuracy issue in it.

>>  I attached the 16bits onnx I used. You can compare it to the modified_quantized_detnet.onnx from above.
Thanks, is the PTQ accuracy enough for your model? we would suggest customer to use PTQ and enable both `--fp16` and `--int8` to get best performance, QAT usually give us more accuracy but there might be some perf gaps. Also I notice the onnx model is different, the fp16 one has single convolution in the bottom while the qat one has more slice and other ops in the bottom, not sure if there is also difference in the middle of the network.

thanks!

**Comment by spivakoa** [comment] 2022-03-14 07:27
Hi @ttyio , thank you for the answer. 
The PTQ wasn't enough and I received a big boost by QAT leading to almost the same accuracy of the original model. We use both --fp16 and --int8 as not all layers are quantized.  There are indeed some additional ops in the int8 model comparing to fp16, I exported the fp16 model assigning the output to the bottom of the convolution skipping all the slicing ops. The rest of the model is the same.
What is still problematic, is that the quantized convtranspose layers run slower than if I run them in fp16. I found this during model profiling using the Tensorrt by layer profiler. It was again seen by running the model in C++ environment on both RTX2080 and Xavier platforms.
I already raised this concern in this thread: https://github.com/NVIDIA/TensorRT/issues/1699#issuecomment-1053952809
This was the reason for attaching both quantized and original models.

Thank you!

**Comment by ttyio** [comment] 2022-03-15 07:39
thanks @spivakoa  for the explain.
I see currently  the `identity` broken the fusion of `convTranspose` and `bn` ,  the `convTranspose` run in `INT8->FP32` precision. If there is another Q/DQ after the `convTranspose`, then it can be run in `INT8->INT8` precision. 

Could you try to insert Q/DQ before the `bn` and see how the perf changes? we can reference code as example (it is not the same but demo how to insert extra Q/DQ in the model).
https://github.com/NVIDIA/TensorRT/blob/main/tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py#L107
thanks!

**Comment by spivakoa** [comment] 2022-03-15 11:07
Hi @ttyio ,  I already did this test and that's why I decided to stress this out to you. I'll show what I did and numbers I received:
The part of the graph related to the change looks as below:
![image](https://user-images.githubusercontent.com/25300810/158362724-32cca315-3340-4d3c-8c3c-1346abc89c00.png)

Now, to the numbers (in ms on my RTX2080):  
1. For 16 bits engine when the ConvTranspose layer in the engine is run as HALF->HALF the profiling is:
![image](https://user-images.githubusercontent.com/25300810/158364047-1e53a73d-c30c-4e97-9614-0f4d7e5e045a.png)

2. For 8 bits engine with the graph change the same ConvTranspose layers is run as  INT8->INT8:
![image](https://user-images.githubusercontent.com/25300810/158364101-9e029762-819d-4b57-b702-c68be5754c73.png)

So, as you can see the int8 implementation runs slower  then fp16,  the Q-DQ adds additional overhead.

**Comment by ttyio** [comment] 2022-03-19 02:44
Hi @spivakoa , is 8.4 the same? we had some new `convTranspose` kernels in 8.4. thanks!

**Comment by nvpohanh** [comment] 2022-06-15 08:18
@spivakoa Could you remove the Q/DQ between ConvTranspose and BN and try TRT 8.4.1 (8.4 GA) and see if the issue still exists? Thanks

**Comment by nvpohanh** [comment] 2022-07-01 06:20
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-07-01 06:20 UTC
Labels: Topic: QAT, triaged, Release: 8.x
