### ISSUE TITLE
Request: TF Object Detection API Faster-RCNN support

### ISSUE THREAD

**Issue by atyshka** [NVIDIA/TensorRT#254] opened 2019-12-05 19:04 UTC
Faster RCNN UFF support is appreciated in the latest release, but it's of little use to the community if it only works with the custom model provided from the TLT sample. Tensorflow Object Detection is where most of the community is right now and it would be great to be able to work with one of those models. TF-TRT is consistently mentioned, as in #120, but this is a poor solution for multiple reasons: the moment TensorRT encounters an unknown operation, it defaults back to TF for all further execution. Thus, if one of the first operations in the graph is unsupported, then Tensorflow is running the majority and we see no speed improvement. Also, for large models like faster-rcnn, creating an engine on the fly can take up to 5 minutes, and this is simply unacceptable in most runtime scenarios. I feel that the primary approach for Tensorflow users should be UFF integration and that's currently a big barrier; having support for Faster-RCNN and more models from the object detection API would be very beneficial. This has already been done for some SSD models, but Faster-RCNN is the choice for ultimate accuracy and support here is still lacking.

**Comment by rmccorm4** [comment] 2020-01-26 00:49
Closing as duplicate of #120, please track there.

**Closed by rmccorm4** 2020-01-26 00:49 UTC
Labels: enhancement
