### ISSUE TITLE
Inconsistent prediction results of the same model with different accuracy

### ISSUE THREAD

**Issue by Qiancj0605** [NVIDIA/TensorRT#790] opened 2020-09-21 06:43 UTC
TensorRT 7.1
Protobuf 3.13.0
python 3.6.10
cuda 10.2
tensorflow 1.12.0

I have a bert model in onnx format，convert onnx to trt model with 16 precision and 32 precision respectively, the infer results of the two trt models with the same input result are inconsistent。
Has any boss met？

**Comment by Qiancj0605** [comment] 2020-09-24 05:57
Has anyone encountered it?

**Comment by Semen52** [comment] 2020-09-30 14:02
Hi,
I am not sure about the root cause, but it is expected. Because Nvidia uses some optimizations for fp16 and lose something in final numbers. Also results for each engine generation using fp16 may be different due to indeterministic process.
But for fp32 the results have to be the same.

**Comment by Qiancj0605** [comment] 2020-10-08 06:38
Thanks for answering。@Semen52 
is there a way to avoid it?

**Comment by Semen52** [comment] 2020-10-08 06:46
As far as I know it will be possible with TRT 7.2. It will contains a new feature for serialization an algo type for each layer.
For example Winograd for some Conv layer and etc. In this case it will guarantee the same output for fp16 mode execution.

**Comment by Qiancj0605** [comment] 2020-10-08 07:10
Thanks, i try it。@Semen52

**Comment by ttyio** [comment] 2020-10-15 05:16
Hello @Qiancj0605 , I will close this since you already get answer, please reopen if you have more questions, thanks

**Closed by ttyio** 2020-10-15 05:16 UTC
