### ISSUE TITLE
TensorRT-7.1.3.4/samples/sample_uff_maskRCNN get error: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by brucelee78** [NVIDIA/TensorRT#788] opened 2020-09-19 08:14 UTC
## Description

when Convert the h5 model to the UFF model,according to README.md file:
`python mrcnn_to_trt_single.py -w ../data/mask_rcnn_coco.h5 -o ../data/mrcnn_nchw.uff -p ./config.py`
but i got a error:
```bash
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
WARNING:tensorflow:From /home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py:274: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

NOTE: UFF has been tested with TensorFlow 1.15.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 276, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 153, in from_tensorflow
    pre.preprocess(dynamic_graph)
  File "./config.py", line 119, in preprocess
    dynamic_graph.remove(timedistributed_remove_list)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/graphsurgeon/DynamicGraph.py", line 330, in remove
    remove_names = set(_get_node_names(nodes))
  File "/home/fh/anaconda3/lib/python3.7/site-packages/graphsurgeon/_utils.py", line 85, in _get_node_names
    return [node.name for node in nodes]
  File "/home/fh/anaconda3/lib/python3.7/site-packages/graphsurgeon/_utils.py", line 85, in <listcomp>
    return [node.name for node in nodes]
AttributeError: 'str' object has no attribute 'name'

```
so, how can i solve it ,please help me, thank you~!!

## Environment

**TensorRT Version**: 7.1.3.4
**GPU Type**: TITANRTX
**Nvidia Driver Version**: 440.110
**CUDA Version**: 10.2
**CUDNN Version**: 8.0
**Operating System + Version**: UBUNTU 18.04
**Python Version (if applicable)**: 3.7.6
**TensorFlow Version (if applicable)**: 1.14.0
**PyTorch Version (if applicable)**: 1.5.0
**Baremetal or Container (which commit + image + tag)**:

**Comment by canhld94** [comment] 2020-09-25 07:27
This error caused by `_get_node_name(nodes)` expects `nodes` is a list of graph nodes create by `gs.create_plugin_node`, but in the `config.py` file,  a list of nodes name is passed to `dynamic_graph.remove()`. You can work around this error either by one of the two following ways:
- In file `config.py`, create a list of input nodes with `gs.create_plugin_node` and pass it to `dynamic_graph.remove()`.
- In file `DynamicGraph.py`, modify line 330 `remove_names = set(_get_node_names(nodes))` to `remove_names = nodes)`

**Comment by brucelee78** [comment] 2020-09-28 08:03
> This error caused by `_get_node_name(nodes)` expects `nodes` is a list of graph nodes create by `gs.create_plugin_node`, but in the `config.py` file, a list of nodes name is passed to `dynamic_graph.remove()`. You can work around this error either by one of the two following ways:
> 
>     * In file `config.py`, create a list of input nodes with `gs.create_plugin_node` or `dynamic_graph.find_nodes_by_name()` and pass it to `dynamic_graph.remove()`.
> 
>     * In file `DynamicGraph.py`, modify line 330 `remove_names = set(_get_node_names(nodes))` to `remove_names = nodes`

hello , thank you to give a tips!
and I follow your tips, i select the second way: modify line 330 `remove_names = set(_get_node_names(nodes))` to `remove_names = nodes`

but get another problem:
`
Using output node mrcnn_detection
Using output node mrcnn_mask/Sigmoid
Converting to UFF graph
Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 276, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 225, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 141, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 126, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 94, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter_functions.py", line 87, in convert_add
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range

`

and i change to use the first way: In file` config.py,` create a list of input nodes with `gs.create_plugin_node` or `dynamic_graph.find_nodes_by_name()` and pass it to `dynamic_graph.remove()`.
i gain the below in config.py in line 122
`
    dynamic_graph.remove(fpn_p5upsampled)
    dynamic_graph.remove(fpn_p4upsampled)
    dynamic_graph.remove(fpn_p3upsampled)
    dynamic_graph.remove(roi_align_classifier)
    dynamic_graph.remove(mrcnn_detection)
    dynamic_graph.remove(roi)
    dynamic_graph.remove(roi_align_mask)
    dynamic_graph.remove(mrcnn_detection_bboxes)
`
 get the same error like above:
`
Using output node mrcnn_detection
Using output node mrcnn_mask/Sigmoid
Converting to UFF graph
Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 276, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 225, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 141, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 126, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter.py", line 94, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/home/fh/anaconda3/lib/python3.7/site-packages/uff/converters/tensorflow/converter_functions.py", line 87, in convert_add
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range

`

so, how to solve it ? thank you !

**Comment by canhld94** [comment] 2020-09-28 12:48
Actually, I haven't checked the error thoroughly. But I assume that you are using the default samples shipped with tensorRT, that's why you got the error. You can take a look at the samples in this repo, I see that they have fixed this error in `config.py` here, so it should work.

**Comment by mk-nvidia** [comment] 2020-10-14 01:05
Closing, see @canhld94 's comment above for fix details.

**Closed by mk-nvidia** 2020-10-14 01:05 UTC
