### ISSUE TITLE
TensorRT does not support in-place operations on input tensors in a prototxt file.

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [NVIDIA/TensorRT#2364] opened 2022-09-30 01:45 UTC
(base) D:\widows_mm\TensorRT-8.2.3.0\bin>trtexec.exe --deploy=detect.prototxt  --model=detect.caffemodel  --output=prob --batch=1 --saveEngine=mnist16.trt
&&&& RUNNING TensorRT.trtexec [TensorRT v8203] # trtexec.exe --deploy=detect.prototxt --model=detect.caffemodel --output=prob --batch=1 --saveEngine=mnist16.trt
[09/30/2022-09:31:39] [I] === Model Options ===
[09/30/2022-09:31:39] [I] Format: Caffe
[09/30/2022-09:31:39] [I] Model: detect.caffemodel
[09/30/2022-09:31:39] [I] Prototxt: detect.prototxt
[09/30/2022-09:31:39] [I] Output: prob
[09/30/2022-09:31:39] [I] === Build Options ===
[09/30/2022-09:31:39] [I] Max batch: 1
[09/30/2022-09:31:39] [I] Workspace: 16 MiB
[09/30/2022-09:31:39] [I] minTiming: 1
[09/30/2022-09:31:39] [I] avgTiming: 8
[09/30/2022-09:31:39] [I] Precision: FP32
[09/30/2022-09:31:39] [I] Calibration:
[09/30/2022-09:31:39] [I] Refit: Disabled
[09/30/2022-09:31:39] [I] Sparsity: Disabled
[09/30/2022-09:31:39] [I] Safe mode: Disabled
[09/30/2022-09:31:39] [I] DirectIO mode: Disabled
[09/30/2022-09:31:39] [I] Restricted mode: Disabled
[09/30/2022-09:31:39] [I] Save engine: mnist16.trt
[09/30/2022-09:31:39] [I] Load engine:
[09/30/2022-09:31:39] [I] Profiling verbosity: 0
[09/30/2022-09:31:39] [I] Tactic sources: Using default tactic sources
[09/30/2022-09:31:39] [I] timingCacheMode: local
[09/30/2022-09:31:39] [I] timingCacheFile:
[09/30/2022-09:31:39] [I] Input(s)s format: fp32:CHW
[09/30/2022-09:31:39] [I] Output(s)s format: fp32:CHW
[09/30/2022-09:31:39] [I] Input build shapes: model
[09/30/2022-09:31:39] [I] Input calibration shapes: model
[09/30/2022-09:31:39] [I] === System Options ===
[09/30/2022-09:31:39] [I] Device: 0
[09/30/2022-09:31:39] [I] DLACore:
[09/30/2022-09:31:39] [I] Plugins:
[09/30/2022-09:31:39] [I] === Inference Options ===
[09/30/2022-09:31:39] [I] Batch: 1
[09/30/2022-09:31:39] [I] Input inference shapes: model
[09/30/2022-09:31:39] [I] Iterations: 10
[09/30/2022-09:31:39] [I] Duration: 3s (+ 200ms warm up)
[09/30/2022-09:31:39] [I] Sleep time: 0ms
[09/30/2022-09:31:39] [I] Idle time: 0ms
[09/30/2022-09:31:39] [I] Streams: 1
[09/30/2022-09:31:39] [I] ExposeDMA: Disabled
[09/30/2022-09:31:39] [I] Data transfers: Enabled
[09/30/2022-09:31:39] [I] Spin-wait: Disabled
[09/30/2022-09:31:39] [I] Multithreading: Disabled
[09/30/2022-09:31:39] [I] CUDA Graph: Disabled
[09/30/2022-09:31:39] [I] Separate profiling: Disabled
[09/30/2022-09:31:39] [I] Time Deserialize: Disabled
[09/30/2022-09:31:39] [I] Time Refit: Disabled
[09/30/2022-09:31:39] [I] Skip inference: Disabled
[09/30/2022-09:31:39] [I] Inputs:
[09/30/2022-09:31:39] [I] === Reporting Options ===
[09/30/2022-09:31:39] [I] Verbose: Disabled
[09/30/2022-09:31:39] [I] Averages: 10 inferences
[09/30/2022-09:31:39] [I] Percentile: 99
[09/30/2022-09:31:39] [I] Dump refittable layers:Disabled
[09/30/2022-09:31:39] [I] Dump output: Disabled
[09/30/2022-09:31:39] [I] Profile: Disabled
[09/30/2022-09:31:39] [I] Export timing to JSON file:
[09/30/2022-09:31:39] [I] Export output to JSON file:
[09/30/2022-09:31:39] [I] Export profile to JSON file:
[09/30/2022-09:31:39] [I]
[09/30/2022-09:31:39] [I] === Device Information ===
[09/30/2022-09:31:39] [I] Selected Device: NVIDIA GeForce GTX 1650
[09/30/2022-09:31:39] [I] Compute Capability: 7.5
[09/30/2022-09:31:39] [I] SMs: 14
[09/30/2022-09:31:39] [I] Compute Clock Rate: 1.68 GHz
[09/30/2022-09:31:39] [I] Device Global Memory: 4095 MiB
[09/30/2022-09:31:39] [I] Shared Memory per SM: 64 KiB
[09/30/2022-09:31:39] [I] Memory Bus Width: 128 bits (ECC disabled)
[09/30/2022-09:31:39] [I] Memory Clock Rate: 4.001 GHz
[09/30/2022-09:31:39] [I]
[09/30/2022-09:31:39] [I] TensorRT version: 8.2.3
[09/30/2022-09:31:39] [I] [TRT] [MemUsageChange] Init CUDA: CPU +369, GPU +0, now: CPU 9231, GPU 885 (MiB)
[09/30/2022-09:31:39] [I] [TRT] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 9254 MiB, GPU 885 MiB
[09/30/2022-09:31:40] [I] [TRT] [MemUsageSnapshot] End constructing builder kernel library: CPU 9358 MiB, GPU 921 MiB
[09/30/2022-09:31:40] [I] Start parsing network model
TensorRT does not support in-place operations on input tensors in a prototxt file.
[09/30/2022-09:31:40] [E] Failed to parse caffe model or prototxt, tensors blob not found
[09/30/2022-09:31:40] [I] Finish parsing network model
[09/30/2022-09:31:40] [E] Parsing model failed
[09/30/2022-09:31:40] [E] Failed to create engine from model.
[09/30/2022-09:31:40] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8203] # trtexec.exe --deploy=detect.prototxt --model=detect.caffemodel --output=prob --batch=1 --saveEngine=mnist16.trt
Hello，when I use trtexec to convert caffemodel, the error is occured, thanks for you answers.

**Comment by jiaqizhang123-stack** [comment] 2022-09-30 03:03
TensorRT version: 8.2.3
[09/30/2022-10:36:40] [I] [TRT] [MemUsageChange] Init CUDA: CPU +383, GPU +0, now: CPU 9131, GPU 885 (MiB)
[09/30/2022-10:36:40] [I] [TRT] [MemUsageSnapshot] Begin constructing builder kernel library: CPU 9152 MiB, GPU 885 MiB
[09/30/2022-10:36:40] [I] [TRT] [MemUsageSnapshot] End constructing builder kernel library: CPU 9253 MiB, GPU 921 MiB
[09/30/2022-10:36:40] [I] Start parsing network model
[09/30/2022-10:36:40] [E] Could not find output blob 1
[09/30/2022-10:36:40] [I] Finish parsing network model
[09/30/2022-10:36:40] [E] Parsing model failed
[09/30/2022-10:36:40] [E] Failed to create engine from model.
[09/30/2022-10:36:40] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8203] # trtexec.exe --deploy=sr.prototxt --model=sr.caffemodel --output=1 --saveEngine=mnist16.engine

And when I transform another model, "Could not find output blob 1" error will occur

**Comment by jiaqizhang123-stack** [comment] 2022-09-30 04:59
![image](https://user-images.githubusercontent.com/55009436/193193693-743dfc85-4813-4305-a328-29ea8aa1127e.png)

**Comment by zerollzeng** [comment] 2022-10-06 11:01
Looks like your model doesn't have the output tensor? can you share the prototxt here?

**Comment by jiaqizhang123-stack** [comment] 2022-10-08 12:23
The prototxt is in " https://github.com/WeChatCV/opencv_3rdparty"
![08aeadbe6c15bbc249d44aaac6612c1](https://user-images.githubusercontent.com/55009436/194707270-98cd58a8-a6c6-4ae9-bf88-f759f4f156b2.png)
Is my output node wrong?

![image](https://user-images.githubusercontent.com/55009436/194707288-3fd98783-9969-43eb-a98b-d489f2941180.png)
And is this problem because there are unregistered custom operators in the model?

**Comment by zerollzeng** [comment] 2022-10-09 07:46
> Is my output node wrong?

Sry the sr.prototxt is good, I made a mistake on the netron image. I'm able to run it with TRT 8.4:
```
[10/09/2022-07:37:36] [I] === Performance summary ===
[10/09/2022-07:37:36] [I] Throughput: 858.326 qps
[10/09/2022-07:37:36] [I] Latency: min = 1.2439 ms, max = 1.27979 ms, mean = 1.2531 ms, median = 1.25214 ms, percentile(99%) = 1.26758 ms
[10/09/2022-07:37:36] [I] Enqueue Time: min = 0.556885 ms, max = 0.8974 ms, mean = 0.653554 ms, median = 0.619171 ms, percentile(99%) = 0.808105 ms
[10/09/2022-07:37:36] [I] H2D Latency: min = 0.0209961 ms, max = 0.050293 ms, mean = 0.0259898 ms, median = 0.0253906 ms, percentile(99%) = 0.0384521 ms
[10/09/2022-07:37:36] [I] GPU Compute Time: min = 1.15576 ms, max = 1.17749 ms, mean = 1.16253 ms, median = 1.16162 ms, percentile(99%) = 1.17102 ms
[10/09/2022-07:37:36] [I] D2H Latency: min = 0.0636902 ms, max = 0.0758667 ms, mean = 0.0645818 ms, median = 0.0644531 ms, percentile(99%) = 0.0678711 ms
[10/09/2022-07:37:36] [I] Total Host Walltime: 3.00352 s
[10/09/2022-07:37:36] [I] Total GPU Compute Time: 2.997 s
[10/09/2022-07:37:36] [I] Explanations of the performance metrics are printed in the verbose logs.
[10/09/2022-07:37:36] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v8401] # trtexec --deploy=sr.prototxt --output=fc
```

**Comment by zerollzeng** [comment] 2022-10-09 07:48
> And is this problem because there are unregistered custom operators in the model?

No, how can I reproduce this error on my side?

**Comment by jiaqizhang123-stack** [comment] 2022-10-09 13:14
Thank you very much.
For the detect.prototxt model, the errors will occur. I don't know why. Is it because Tensorrt doesn't support some operations in this model(detect.prototxt)? So what method should I use to convert it
![image](https://user-images.githubusercontent.com/55009436/194758556-7abb36ea-59b9-4744-872b-f667e930f0bd.png)
However, for the sr.prototxt model, the reason why I made an error at first was that the “--output” was wrong

**Comment by zerollzeng** [comment] 2022-10-10 01:49
The --output in your command is wrong, but I still met error with the correct command, I also check the prototxt, yes it has at least one custom layer that needs to be implemented as a plugin(the last layer: DetectionOutput), but that should not be the reason why it fails here. it should try to find the built-in plugin first. @ttyio correct me if I'm wrong.

BTW the caffe parser is about to be deprecated, is it important for your project?
```
[10/09/2022-18:41:01] [I] Start parsing network model
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format ditcaffe.NetParameter: 8:1: Expected identifier, got: <
[10/09/2022-18:41:01] [E] [TRT] CaffeParser: Could not parse deploy file
[10/09/2022-18:41:01] [E] Failed to parse caffe model or prototxt, tensors blob not found
[10/09/2022-18:41:01] [I] Finish parsing network model
[10/09/2022-18:41:01] [E] Parsing model failed
[10/09/2022-18:41:01] [E] Failed to create engine from model or file.
[10/09/2022-18:41:01] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8501] # trtexec --deploy=detect.prototxt --output=detection_output --verbose

```

**Comment by zerollzeng** [comment] 2022-10-10 15:07
you can refer to https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#extending. but there not much material for the caffe plugin, you might need to see the oss plugin sample before 6.0.

I would highly recommend moving to use ONNX intead.

**Comment by jiaqizhang123-stack** [comment] 2022-10-10 15:21
What is OSS plugin? 
Can I avoid the problem of custom layer by converting the caffe model to onnx and then to engine?

**Comment by zerollzeng** [comment] 2022-10-11 16:43
> What is OSS plugin?

under [plugin](https://github.com/NVIDIA/TensorRT/tree/main/plugin)

> Can I avoid the problem of custom layer by converting the caffe model to onnx and then to engine?

I think so, onnx parser is more robust and up-to-date compared to caffe parser, so I recommend using it. also implementing a plugin that's compatible with the onnx parser is easier than the caffe parser.

**Comment by ttyio** [comment] 2022-12-06 02:04
closing since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Closed by ttyio** 2022-12-06 02:04 UTC
Labels: triaged
