### ISSUE TITLE
The inference speed of the int8 quantization version of SDXL is much slower than that of fp16

### ISSUE THREAD

**Issue by theNefelibata** [NVIDIA/TensorRT#3724] opened 2024-03-19 02:59 UTC
The inference speed of the int 8 quantization version of SDXL is much slower than that of fp16. I am runing trt9.3 sdxl demo and here is the result. (I changed shape to 768x1344  manually)
fp16 : python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --version xl-1.0 --onnx-dir onnx-sdxl --engine-dir engine-sdxl --width 1344 --height 768
[I] Warming up ..
[I] Running StableDiffusionXL pipeline
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.45 ms |
|    UNet x 30    |   2616.81 ms |
|     VAE-Dec     |    222.92 ms |
|-----------------|--------------|
|    Pipeline     |   2851.01 ms |
|-----------------|--------------|
Throughput: 0.35 image/s

int8: python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --version xl-1.0 --onnx-dir onnx-sdxl --engine-dir engine-sdxl --int8 --quantization-level 3 --width 1344 --height 768
[I] Warming up ..
[I] Running StableDiffusionXL pipeline
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.39 ms |
|    UNet x 30    |   5550.13 ms |
|     VAE-Dec     |    223.70 ms |
|-----------------|--------------|
|    Pipeline     |   5785.81 ms |
|-----------------|--------------|
Throughput: 0.17 image/s

**Comment by theNefelibata** [comment] 2024-03-19 03:00
tested on A800 GPU

**Comment by ApolloRay** [comment] 2024-03-19 05:50
Have you found that the size of onnx model for int8 is much bigger than fp16 ? 
![截屏2024-03-19 13 49 45](https://github.com/NVIDIA/TensorRT/assets/36093263/0048cf7c-318d-4f07-92dc-a6b9a2f07da2)

**Comment by theNefelibata** [comment] 2024-03-19 05:59
> Have you found that the size of onnx model for int8 is much bigger than fp16 ?
> ![截屏2024-03-19 13 49 45](https://private-user-images.githubusercontent.com/36093263/313936676-0048cf7c-318d-4f07-92dc-a6b9a2f07da2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjc5NzQsIm5iZiI6MTcxMDgyNzY3NCwicGF0aCI6Ii8zNjA5MzI2My8zMTM5MzY2NzYtMDA0OGNmN2MtMzE4ZC00ZjA3LTkyZGMtYTZiOWEyZjA3ZGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MDk0YjBmN2M0MTM1ZDk0YzBlMGJiZjQwYTU2NDA3ZjE0ZTdhMjM5ZjI0ZWZhZDBiOGMwZjc0NzEyNTVhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J4f6OTJAG1q1-a8395YWyxKhI1miY6aurxDSES9to8Q)

yes, The onnx model seems to be based on fp32, but .plan file is resonable
![image](https://github.com/NVIDIA/TensorRT/assets/22743578/47d2f095-5880-4919-bfed-f9b7e7967f99)

**Comment by ApolloRay** [comment] 2024-03-19 06:02
> > Have you found that the size of onnx model for int8 is much bigger than fp16 ?
> > ![截屏2024-03-19 13 49 45](https://private-user-images.githubusercontent.com/36093263/313936676-0048cf7c-318d-4f07-92dc-a6b9a2f07da2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4Mjc5NzQsIm5iZiI6MTcxMDgyNzY3NCwicGF0aCI6Ii8zNjA5MzI2My8zMTM5MzY2NzYtMDA0OGNmN2MtMzE4ZC00ZjA3LTkyZGMtYTZiOWEyZjA3ZGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1NTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MDk0YjBmN2M0MTM1ZDk0YzBlMGJiZjQwYTU2NDA3ZjE0ZTdhMjM5ZjI0ZWZhZDBiOGMwZjc0NzEyNTVhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J4f6OTJAG1q1-a8395YWyxKhI1miY6aurxDSES9to8Q)
> 
> yes, The onnx model seems to be based on fp32, but .plan file is resonable ![image](https://private-user-images.githubusercontent.com/22743578/313938390-47d2f095-5880-4919-bfed-f9b7e7967f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MjgyNDQsIm5iZiI6MTcxMDgyNzk0NCwicGF0aCI6Ii8yMjc0MzU3OC8zMTM5MzgzOTAtNDdkMmYwOTUtNTg4MC00OTE5LWJmZWQtZjliN2U3OTY3Zjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDA1NTkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNWVlNWUyYzUzNGE3NmU3Y2E4ZWRlZGNkMTYzNDdiMzIxMzYzNzQ5YzI4NzA2OTVmOGJhNWIwZDY4NzNiNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xyiqbLkPZKpKlbJRb1YoFDPdMTjafXWOyH2hQ5zZvOg)

Me too. And during the inference, the gpu-utils is higher than the fp16. I hope it can be solved.

**Comment by theNefelibata** [comment] 2024-03-20 06:54
update pytorch 2.0, it works, but the speed improvement is very small.
[I] Running StableDiffusionXL pipeline
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.59 ms |
|    UNet x 30    |   2315.72 ms |
|     VAE-Dec     |    216.47 ms |
|-----------------|--------------|
|    Pipeline     |   2545.01 ms |
|-----------------|--------------|
Throughput: 0.39 image/s

**Comment by ApolloRay** [comment] 2024-03-20 07:01
> update pytorch 2.0, it works, but the speed improvement is very small. [I] Running StableDiffusionXL pipeline |-----------------|--------------| | Module | Latency | |-----------------|--------------| | CLIP | 2.59 ms | | UNet x 30 | 2315.72 ms | | VAE-Dec | 216.47 ms | |-----------------|--------------| | Pipeline | 2545.01 ms | |-----------------|--------------| Throughput: 0.39 image/s

This high probability is not quantified, right? After 30 times of noise reduction, the time almost didn’t change.

**Comment by theNefelibata** [comment] 2024-03-20 07:03
> > update pytorch 2.0, it works, but the speed improvement is very small. [I] Running StableDiffusionXL pipeline |-----------------|--------------| | Module | Latency | |-----------------|--------------| | CLIP | 2.59 ms | | UNet x 30 | 2315.72 ms | | VAE-Dec | 216.47 ms | |-----------------|--------------| | Pipeline | 2545.01 ms | |-----------------|--------------| Throughput: 0.39 image/s
> 
> This high probability is not quantified, right? After 30 times of noise reduction, the time almost didn’t change.

actually each step is 10ms faster...

**Comment by ApolloRay** [comment] 2024-03-20 08:14
> > > update pytorch 2.0, it works, but the speed improvement is very small. [I] Running StableDiffusionXL pipeline |-----------------|--------------| | Module | Latency | |-----------------|--------------| | CLIP | 2.59 ms | | UNet x 30 | 2315.72 ms | | VAE-Dec | 216.47 ms | |-----------------|--------------| | Pipeline | 2545.01 ms | |-----------------|--------------| Throughput: 0.39 image/s
> > 
> > 
> > This high probability is not quantified, right? After 30 times of noise reduction, the time almost didn’t change.
> 
> actually each step is 10ms faster...

for me, torch in 2.0.1, but nothing happened.

**Comment by zerollzeng** [comment] 2024-03-22 05:49
@nvpohanh is it expected?

**Comment by nvpohanh** [comment] 2024-03-22 11:53
Please try `--quantization-level 2.5` because TRT currently does not support INT8 MHA fusion for SeqLen>512 due to accuracy reason. Therefore, use `--quantization-level 2.5` instead so that the MHA part is not quantized.

**Comment by ApolloRay** [comment] 2024-03-25 03:01
> Please try `--quantization-level 2.5` because TRT currently does not support INT8 MHA fusion for SeqLen>512 due to accuracy reason. Therefore, use `--quantization-level 2.5` instead so that the MHA part is not quantized.

![Uploading 截屏2024-03-25 11.00.41.png…]()

**Comment by ApolloRay** [comment] 2024-03-25 03:01
> Please try `--quantization-level 2.5` because TRT currently does not support INT8 MHA fusion for SeqLen>512 due to accuracy reason. Therefore, use `--quantization-level 2.5` instead so that the MHA part is not quantized.

![截屏2024-03-25 11 00 41](https://github.com/NVIDIA/TensorRT/assets/36093263/22b80bf5-7daa-49eb-ab54-3ecee75d1f1b)

**Comment by theNefelibata** [comment] 2024-03-28 01:51
level 2.5 do not support, I tried level 2.
![image](https://github.com/NVIDIA/TensorRT/assets/22743578/557382f3-08df-4264-acc0-48a895d189af)

**Comment by nvpohanh** [comment] 2024-04-01 02:07
Could you remove `choices=range(1,4)` here? https://github.com/NVIDIA/TensorRT/blob/release/9.3/demo/Diffusion/utilities.py#L502

We will fix this in next version

cc @rajeevsrao

**Comment by theNefelibata** [comment] 2024-04-01 08:03
> Could you remove `choices=range(1,4)` here? https://github.com/NVIDIA/TensorRT/blob/release/9.3/demo/Diffusion/utilities.py#L502
> 
> We will fix this in next version
> 
> cc @rajeevsrao
even slower... 
python demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --version xl-1.0 --onnx-dir onnx-sdxl-int8 --engine-dir engine-sdxl-int8 --int8 --quantization-level 2.5 --width 1344 --height 768 --seed 123456
[I] Warming up ..
[I] Running StableDiffusionXL pipeline
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.60 ms |
|    UNet x 30    |   7193.33 ms |
|     VAE-Dec     |    221.53 ms |
|-----------------|--------------|
|    Pipeline     |   7427.78 ms |
|-----------------|--------------|
Throughput: 0.13 image/s

**Comment by nvpohanh** [comment] 2024-04-01 09:50
Thanks for trying. that's surprising because it doesn't match our internal measurements... Let me check internally first

**Comment by akhilg-nv** [comment] 2024-04-03 21:58
We will have an update for int8 quantization including new AMMO version and latest calibration scripts in the upcoming GA release, which should resolve this issue. Will test internally and circle back when that is released.

**Comment by theNefelibata** [comment] 2024-04-08 01:22
> We will have an update for int8 quantization including new AMMO version and latest calibration scripts in the upcoming GA release, which should resolve this issue. Will test internally and circle back when that is released.

ok, thanks. And I would like to know when the next GA version will be release.

**Comment by akhilg-nv** [comment] 2024-04-09 17:52
The release will likely be in May, but we may try to push the fix for this earlier than that.

**Comment by theNefelibata** [comment] 2024-04-11 06:11
> The release will likely be in May, but we may try to push the fix for this earlier than that.
Blog claims that the speed of FP8 is faster. How to quantinaze the model of FP8? Will you provide a demo？

**Comment by akhilg-nv** [comment] 2024-04-11 06:16
Yes, it is planned to add FP8 quantization to the demo. I'm not sure of the exact timeline for when full support will be added.

**Comment by theNefelibata** [comment] 2024-04-11 06:18
> Yes, it is planned to add FP8 quantization to the demo. I'm not sure of the exact timeline for when full support will be added.

Ok, Thank you for your reply

**Comment by akhilg-nv** [comment] 2024-04-30 19:29
Hi, please check the latest TensorRT 10.0 OSS GA release and let us know if that helps!

**Comment by ecilay** [comment] 2024-05-01 05:32
@akhilg-nv so need to use trt 10.0 to try if the quantized trt model is faster?
Agree with trt 8.6.1 see quantized trt model twice as speed of non-quantized trt model

**Comment by akhilg-nv** [comment] 2024-05-01 19:53
You can update the TRT package to 10.0 if you'd like. Great that you are seeing the perf improvement now! Which GPU are you testing on?

**Comment by ecilay** [comment] 2024-05-01 20:25
@akhilg-nv  sorry I mean the quantized trt model spend twice the time of non-quantized trt model with 8.6.1. I am on A100 80G machine

**Comment by akhilg-nv** [comment] 2024-05-01 20:30
I see, could you post the throughput summary (e.g. similar to as seen [here](https://github.com/NVIDIA/TensorRT/issues/3724#issuecomment-2008796591)) and your repro steps? 

Also, could you try the result when upgrading to TRT 10.0? As noted in the [readme](https://github.com/NVIDIA/TensorRT/tree/release/10.0/demo/Diffusion), you can do `python3 -m pip install --upgrade pip
&& pip install --pre tensorrt-cu12` to upgrade TRT package in container.

**Comment by ecilay** [comment] 2024-05-01 21:49
So I just test the trt10.0.1, and with AMMO, it turns out the quantized trt model is still slower than non-quantized trt model. I modified the code a little bit to make it quantize for `inpainting` use case, here is what I got:
Non quantized trt model perf:
```
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|     VAE-Enc     |      9.70 ms |
|      CLIP       |      2.29 ms |
|    UNet x 22    |    373.10 ms |
|     VAE-Dec     |     18.85 ms |
|-----------------|--------------|
|    Pipeline     |    411.26 ms |
|-----------------|--------------|
Throughput: 2.43 image/s
```

Quantized trt model:
```
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|     VAE-Enc     |      9.66 ms |
|      CLIP       |      2.27 ms |
|    UNet x 22    |    377.02 ms |
|     VAE-Dec     |     18.64 ms |
|-----------------|--------------|
|    Pipeline     |    414.32 ms |
|-----------------|--------------|
Throughput: 2.41 image/s
```

**Comment by ecilay** [comment] 2024-05-01 22:20
Is A100 machine a good test GPU device? What Quantization with AMMO works best on which GPUs?

**Comment by ecilay** [comment] 2024-05-01 22:25
> Please try `--quantization-level 2.5` because TRT currently does not support INT8 MHA fusion for SeqLen>512 due to accuracy reason. Therefore, use `--quantization-level 2.5` instead so that the MHA part is not quantized.

I think 2.5 is for `CNN+FFN+QKV` and 3 is for `CNN+FC`. If INT8 MHA fusion for SeqLen>512 is not available, we should use quantization-level 3?

**Comment by nvpohanh** [comment] 2024-05-02 03:25
Since INT8 MHA fusion for SeqLen>512 is not supported, adding Q/DQ before the FC after the MHA would cause an additional "Quantize" kernel which slows down the e2e perf. Therefore, the recommended quantization level for INT8 is 2.5

**Comment by akhilg-nv** [comment] 2024-05-06 21:15
@ecilay A100 should be working fine and has been tested on internally. Could you share more details about the OOM you're running into with SDXL? We're investigating such issues but it is unusual that you are experiencing this on 80GB A100. If you could share the details of which step in the pipeline is running out of memory and error logs that would be helpful, as well as any relevant modifications you've made if any. You can also try using the `--build-static-batch` flag which has resolved some memory issues on devices with less memory. 

For TRT 10.0 installation, the readme steps are specific to the provided container which already contains TRT 8.6, which causes a quirk when upgrading that requires installing twice and using `--force-reinstall` the second time. However, if you just do `python3 -m pip install --pre tensorrt` in your custom environment with an older TRT version not already present, this should work properly.

**Comment by Edwardf0t1** [comment] 2024-05-14 20:32
@ecilay Based on our internal testing, int8 vs fp16 speedup works best on RTX 6000 Ada GPU. See [here](https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/main/benchmark.md#2-ptq-for-stable-diffusion) for more data.

If interested, you could also try follow readme in TensorRT Model Optimizer diffusers https://github.com/NVIDIA/TensorRT-Model-Optimizer/tree/main/diffusers to run SDXL int8 pipeline. It includes the environment setup instructions with docker.

**Comment by ecilay** [comment] 2024-05-14 23:39
Thanks, @Edwardf0t1 , we don't have RTX6000 Ada GPU. We only have A100. Below you can find the quantized SDXL is much slower.
Original Pytorch model
```
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      3.12 ms |
|    UNet x 30    |   2701.34 ms |
|     VAE-Dec     |    338.57 ms |
|-----------------|--------------|
|    Pipeline     |   3055.21 ms |
|-----------------|--------------|
Throughput: 0.33 image/s
```

Int8 quantized on A100
```
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.90 ms |
|    UNet x 30    |   7299.95 ms |
|     VAE-Dec     |    336.11 ms |
|-----------------|--------------|
|    Pipeline     |   7648.90 ms |
|-----------------|--------------|
Throughput: 0.13 image/s
```

**Comment by ecilay** [comment] 2024-05-14 23:41
Is there a way to verify/check if tensor core is being utilized?

**Comment by Edwardf0t1** [comment] 2024-05-15 00:37
> Thanks, @Edwardf0t1 , we don't have RTX6000 Ada GPU. We only have A100. Below you can find the quantized SDXL is much slower. Original Pytorch model
> 
> ```
> |-----------------|--------------|
> |     Module      |   Latency    |
> |-----------------|--------------|
> |      CLIP       |      3.12 ms |
> |    UNet x 30    |   2701.34 ms |
> |     VAE-Dec     |    338.57 ms |
> |-----------------|--------------|
> |    Pipeline     |   3055.21 ms |
> |-----------------|--------------|
> Throughput: 0.33 image/s
> ```
> 
> Int8 quantized on A100
> 
> ```
> |-----------------|--------------|
> |     Module      |   Latency    |
> |-----------------|--------------|
> |      CLIP       |      2.90 ms |
> |    UNet x 30    |   7299.95 ms |
> |     VAE-Dec     |    336.11 ms |
> |-----------------|--------------|
> |    Pipeline     |   7648.90 ms |
> |-----------------|--------------|
> Throughput: 0.13 image/s
> ```

Thanks for reporting your benchmark on A100. We tested A100 internally as well, and observed about 1.3x speedup. May I double check that you followed the steps in [this repo](https://github.com/NVIDIA/TensorRT-Model-Optimizer/tree/main/diffusers) and built the docker as I mentioned above to get these numbers? We found the environment and workflow are quite important for accurate benchmarking.

**Comment by ecilay** [comment] 2024-05-15 03:17
Hi @Edwardf0t1 I tried this new [TensorRT-Model-Optimizer](https://github.com/NVIDIA/TensorRT-Model-Optimizer/tree/main), I quantized the SDXL model using the command
```
bash build_sdxl_8bit_engine.sh --format {FORMAT}
```
and replace the quantized model with the non_quantized model and inference with command
```
python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --version xl-1.0
```
and get below performance
```
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.69 ms |
|    UNet x 30    |   7486.83 ms |
|     VAE-Dec     |    335.80 ms |
|-----------------|--------------|
|    Pipeline     |   7837.81 ms |
|-----------------|--------------|
Throughput: 0.13 image/s
``

As for setup, I used docker image `nvcr.io/nvidia/pytorch:24.01-py3` and tensorrt 8.6.1.

**Comment by jingyu-ml** [comment] 2024-05-15 13:57
@ecilay 
Could you follow the step here to reproduce it again?

https://github.com/NVIDIA/TensorRT-Model-Optimizer/issues/3#issuecomment-2112544474

We still recommend TRT > 9.3

**Comment by Edwardf0t1** [comment] 2024-05-15 15:12
> Hi @Edwardf0t1 I just give another try with this new [TensorRT-Model-Optimizer](https://github.com/NVIDIA/TensorRT-Model-Optimizer/tree/main), I quantized the SDXL model using the command
> 
> ```
> bash build_sdxl_8bit_engine.sh --format int8
> ```
> 
> and replace and renamed the quantized model with the non_quantized model and inference with command
> 
> ```
> python3 demo_txt2img_xl.py "a photo of an astronaut riding a horse on mars" --version xl-1.0
> ```
> 
> and get below performance
> 
> ```
> |-----------------|--------------|
> |     Module      |   Latency    |
> |-----------------|--------------|
> |      CLIP       |      2.69 ms |
> |    UNet x 30    |   7486.83 ms |
> |     VAE-Dec     |    335.80 ms |
> |-----------------|--------------|
> |    Pipeline     |   7837.81 ms |
> |-----------------|--------------|
> Throughput: 0.13 image/s
> ```
> 
> As for setup, I used docker image `nvcr.io/nvidia/pytorch:24.01-py3` with default tensorrt 8.6.1 and pip installed `nvidia-modelopt`

Thanks for checking. TRT 8.6.1 does not has good support for SDXL int8 path. We use TRT 9.3 in the default docker. Here's our benchmark on a A100-PCIE-40GB:
fp16:
![image](https://github.com/NVIDIA/TensorRT/assets/24870971/e2674a69-fe77-4c1f-ae53-509fda73c609)
int8:
![image](https://github.com/NVIDIA/TensorRT/assets/24870971/2063341d-eae9-443d-891e-48a5ce635c5c)
The speedup is about 1.27x.

**Comment by ecilay** [comment] 2024-05-15 19:35
Hi @Edwardf0t1 , thanks for the tip, YES with TRT 10.0.0, I am seeing 12% faster in quantized TRT model:
Pytorch model with TRT 10
```
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.77 ms |
|    UNet x 30    |   2361.04 ms |
|     VAE-Dec     |    405.08 ms |
|-----------------|--------------|
|    Pipeline     |   2779.47 ms |
|-----------------|--------------|
Throughput: 0.36 image/s
```

Int8 Quantized TRT 10 model
```
|-----------------|--------------|
|     Module      |   Latency    |
|-----------------|--------------|
|      CLIP       |      2.48 ms |
|    UNet x 30    |   2111.89 ms |
|     VAE-Dec     |    402.42 ms |
|-----------------|--------------|
|    Pipeline     |   2526.35 ms |
|-----------------|--------------|
Throughput: 0.40 image/s
```
I used `quantization_level=2.5` based on discussion here https://github.com/NVIDIA/TensorRT/issues/3724#issuecomment-2089463800, but in your Model-Optimizer demo I see it uses 3.0 https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/main/diffusers/build_sdxl_8bit_engine.sh#L40. So which one shall I use?


Also want to confirm, for sequence length > 512, the int8 Attention is not available, only FP8 Attention available at this point, according to what I see from TRT release not, is my understanding correct?

**Comment by Edwardf0t1** [comment] 2024-05-20 22:17
> Hi @Edwardf0t1 , thanks for the tip, YES with TRT 10.0.0, I am seeing 12% faster in quantized TRT model: Pytorch model with TRT 10
> 
> ```
> |-----------------|--------------|
> |     Module      |   Latency    |
> |-----------------|--------------|
> |      CLIP       |      2.77 ms |
> |    UNet x 30    |   2361.04 ms |
> |     VAE-Dec     |    405.08 ms |
> |-----------------|--------------|
> |    Pipeline     |   2779.47 ms |
> |-----------------|--------------|
> Throughput: 0.36 image/s
> ```
> 
> Int8 Quantized TRT 10 model
> 
> ```
> |-----------------|--------------|
> |     Module      |   Latency    |
> |-----------------|--------------|
> |      CLIP       |      2.48 ms |
> |    UNet x 30    |   2111.89 ms |
> |     VAE-Dec     |    402.42 ms |
> |-----------------|--------------|
> |    Pipeline     |   2526.35 ms |
> |-----------------|--------------|
> Throughput: 0.40 image/s
> ```
> 
> I used `quantization_level=2.5` based on discussion here https://github.com/NVIDIA/TensorRT/issues/3724#issuecomment-2089463800, but in your Model-Optimizer demo I see it uses 3.0 https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/main/diffusers/build_sdxl_8bit_engine.sh#L40. So which one shall I use?
> 
> Also want to confirm, for sequence length > 512, the int8 Attention is not available, only FP8 Attention available since release 9.1, according to what I see from TRT release note, is my understanding correct?

Feel free to try quant level 3.0 with Model Optimizer and see if it brings more speedup to match our internal benchmark of 1.27x. 
Regarding TRT FP8 attention support, do you refer to FP8 MHA support for SDXL? I think it's not ready yet, and @nvpohanh may have more info.

**Comment by Edwardf0t1** [comment] 2024-06-13 00:18
@zerollzeng We may close this ticket as no ongoing discussions.

**Comment by ckolluru** [comment] 2024-09-11 18:12
Can someone please elaborate on the ```UNet x 30``` module tested here? What does the ```x 30``` mean? 

Is it safe to assume that for a FP16 TensorRT optimized U-net model, the speed up one could possibly get by moving it to INT8 is around ```1.2 to 1.3x```? This seems to be a case of post-training quantization (PTQ), is the benefit with quantization aware training (QAT) only towards improved performance accuracy?

**Comment by akhilg-nv** [comment] 2024-09-11 22:44
x30 refers to the number of iterations of the U-Net used for denoising. The speed-up you see with Int8 quantization will ultimately depend on your hardware and model, but iirc 1.2-1.3x is a reasonable expectation on Ada GPUs for SDXL. The perf gains for PTQ/QAT should be the same if the same layers are being quantized, but QAT should theoretically improve the accuracy.

Closing this issue as there has been no further discussion on the original perf discussions for >3 weeks. If you have further questions closely coupled with the issue, feel free to continue here, otherwise we welcome you to start a new one with any additional follow-ups!

**Closed by akhilg-nv** 2024-09-11 22:44 UTC
Labels: triaged
