### ISSUE TITLE
Assertion `status == myelinSuccess' failed.

### ISSUE THREAD

**Issue by ywfwyht** [NVIDIA/TensorRT#2717] opened 2023-03-01 02:23 UTC
## Description

In function split_input -- /root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/kqv_gemm_split.cpp:658 status == myelinSuccess -- assertion failed
Abort (core dumped)
/root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/kqv_gemm_split.cpp:658: std::vector<myelin::ir::operation_t*> myelin::ir::split_input(myelin::ir::graph_t*, myelin::ir::kqv_split_pattern_t&, myelin::ir::operand_t*, myelin::ir::opnd2op_t&, myelin::ir::op2bb_t&): Assertion `status == myelinSuccess' failed.

[01/01/1970-09:52:11] [V] [TRT] --------------- Timing Runner: {ForeignNode[onnx::MatMul_894 + (Unnamed Layer* 124) [Shuffle]...Reshape_322]} (Myelin)
In function split_input -- /root/gpgpu/MachineLearning/myelin/src/compiler/optimizer/kqv_gemm_split.cpp:658 status == myelinSuccess -- assertion failed
Abort (core dumped)

## Environment

**TensorRT Version**: 8.4.12
**NVIDIA GPU**: 
**NVIDIA Driver Version**: 
**CUDA Version**: 11.4
**CUDNN Version**: 
**Operating System**: qnx
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by zerollzeng** [comment] 2023-03-05 08:57
Can you try the latest TRT release first? if it will fails could you please provide a reproduce for this? Thanks!

**Comment by ywfwyht** [comment] 2023-03-07 07:23
> Can you try the latest TRT release first? if it will fails could you please provide a reproduce for this? Thanks!
https://github.com/ywfwyht/onnx_model/blob/main/submodel_part2.onnx

**Comment by zerollzeng** [comment] 2023-03-08 15:27
TRT 8.6 should fix this, which will be released soon.

```
[03/08/2023-15:27:14] [I] === Performance summary ===
[03/08/2023-15:27:14] [I] Throughput: 978.857 qps
[03/08/2023-15:27:14] [I] Latency: min = 1.11401 ms, max = 1.4388 ms, mean = 1.1455 ms, median = 1.14105 ms, percentile(90%) = 1.15631 ms, percentile(95%) = 1.16095 ms, percentile(99%) = 1.36461 ms
[03/08/2023-15:27:14] [I] Enqueue Time: min = 0.12085 ms, max = 0.28064 ms, mean = 0.190743 ms, median = 0.178711 ms, percentile(90%) = 0.241455 ms, percentile(95%) = 0.246338 ms, percentile(99%) = 0.260864 ms
[03/08/2023-15:27:14] [I] H2D Latency: min = 0.0628662 ms, max = 0.0982971 ms, mean = 0.0778077 ms, median = 0.0778809 ms, percentile(90%) = 0.0826416 ms, percentile(95%) = 0.0843506 ms, percentile(99%) = 0.0893555 ms
[03/08/2023-15:27:14] [I] GPU Compute Time: min = 0.983032 ms, max = 1.3054 ms, mean = 1.0118 ms, median = 1.00745 ms, percentile(90%) = 1.02139 ms, percentile(95%) = 1.02588 ms, percentile(99%) = 1.22878 ms
[03/08/2023-15:27:14] [I] D2H Latency: min = 0.0528564 ms, max = 0.0634766 ms, mean = 0.0558986 ms, median = 0.0556641 ms, percentile(90%) = 0.0571289 ms, percentile(95%) = 0.0576782 ms, percentile(99%) = 0.0592651 ms
[03/08/2023-15:27:14] [I] Total Host Walltime: 3.0035 s
[03/08/2023-15:27:14] [I] Total GPU Compute Time: 2.97469 s
[03/08/2023-15:27:14] [W] * GPU compute time is unstable, with coefficient of variance = 2.70597%.
[03/08/2023-15:27:14] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
[03/08/2023-15:27:14] [I] Explanations of the performance metrics are printed in the verbose logs.
[03/08/2023-15:27:14] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v8600] # trtexec --onnx=submodel_part2.onnx

```

**Comment by ttyio** [comment] 2023-04-04 04:46
Closing since no activity for more than 3 weeks, pls reopen if you still have question, thanks!

**Closed by ttyio** 2023-04-04 04:46 UTC
Labels: triaged
