### ISSUE TITLE
 nn.Linear error 

### ISSUE THREAD

**Issue by xaiocaibi** [NVIDIA/TensorRT#2663] opened 2023-02-10 09:59 UTC
TensorRT Version: TensorRT-8.5.1.7
NVIDIA GPU: [T4]
NVIDIA Driver Version:
CUDA Version: 11.8
CUDNN Version: 8.6.0.163
Operating System: 11

When I used trtexec to convert the onnx model, I found that there was an error that the operator was not implemented. In the original model, this was an nn.Linear.
Here's a screenshot of my error：
![image](https://user-images.githubusercontent.com/18330731/218061067-f1b4c4ec-d4a7-4850-bff2-2f1abdd10ef0.png)
The following figure shows the corresponding ONNX model，
![20230210-175609(WeLinkPC)](https://user-images.githubusercontent.com/18330731/218061418-74b1989b-be18-4750-af24-7ca2bcfc2a07.png)
```[tasklist]

```

**Comment by zerollzeng** [comment] 2023-02-12 03:34
Can you provide a reproduce for this? Thanks!

**Comment by xaiocaibi** [comment] 2023-02-12 03:34
已收到                                                                                                            蔡成林

**Comment by xaiocaibi** [comment] 2023-02-13 02:26
> Can you provide a reproduce for this? Thanks!

Direct supply of copies is prohibited. The error part is relatively independent, that is, multiple inputs are linearly transformed and then concatenated. The related code is as follows:
![image](https://user-images.githubusercontent.com/18330731/218352084-60eba5e1-427d-4a54-bb5a-b24e54516449.png)
self.**_linear() is nn.Linear, **_state is input . 
![截图](https://user-images.githubusercontent.com/18330731/218356706-f53cc121-d9b0-4afd-aa2a-c9a824f1daf0.PNG)
In fact, this problem occurs when you perform the steps in the figure.

**Comment by xaiocaibi** [comment] 2023-02-13 02:55
Do you need any more information? I'll try to provide it.

**Comment by zerollzeng** [comment] 2023-02-15 12:20
Can you provide part of the onnx model that can reproduce this error? or you can fill your model with random weights.

**Comment by ttyio** [comment] 2023-03-14 02:55
closing since no activitity for more than 3 weeks, thanks!

**Comment by xaiocaibi** [comment] 2023-03-14 02:56
已收到                                                                                                            蔡成林

**Closed by ttyio** 2023-03-14 02:55 UTC
Labels: triaged
