### ISSUE TITLE
Driver error when upgrade TensorRT 6 to TensorRT 7 using YoloV4 in INT8 mode

### ISSUE THREAD

**Issue by jackgao0323** [NVIDIA/TensorRT#753] opened 2020-08-28 10:12 UTC
## Description

I can using my code on TensorRT6 in INT8 and TensorRT 7 in FP32, but I getting the error like the following image when I use TensorRT 7 in INT 8.  
![image](https://user-images.githubusercontent.com/17614632/91549601-c41fc900-e959-11ea-890f-8c088c744b78.png)

This is the verbose output.

![image](https://user-images.githubusercontent.com/17614632/91549627-ceda5e00-e959-11ea-8033-c99133a210d4.png)

## Environment

**TensorRT Version**:  7.1.3
**GPU Type**: Jetson AGX iGPU
**Nvidia Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 8
**Operating System + Version**: Ubuntu 18.04

**Comment by karanjakhar** [comment] 2020-09-07 10:06
Did you find the solution?

**Comment by jackgao0323** [comment] 2020-09-07 10:15
> Did you find the solution?

No, I don't know why I get this error. 
Did you face the same issue?

**Comment by karanjakhar** [comment] 2020-09-07 10:19
yes

**Comment by karanjakhar** [comment] 2020-09-07 10:20
I am converting Yolov4 from onnx to engine format

**Comment by jackgao0323** [comment] 2020-09-07 10:45
I have posted this error on NVIDIA forum. They also didn't answer me.

**Comment by karanjakhar** [comment] 2020-09-07 11:05
I solved it. 
Just update driver.

**Comment by jackgao0323** [comment] 2020-09-07 11:08
> I solved it.
> Just update driver.

Congrats!!
But I'm using Jeston NX, it can't update the driver.  HAHA

**Comment by karanjakhar** [comment] 2020-09-07 11:09
:)

**Comment by karanjakhar** [comment] 2020-09-07 11:12
I am working v100. TX2 might be my next target. Let's see what happens then. If you solve it please let me know the solution.

**Comment by jackgao0323** [comment] 2020-09-07 11:14
> I am working v100. TX2 might be my next target. Let's see what happens then. If you solve it please let me know the solution.

I remember TX2 CANT using INT8 mode. If you want to running in INT8, you need to use Xavier or NX.

**Comment by karanjakhar** [comment] 2020-09-07 11:25
okay. Thanks

**Comment by PatrickNa** [comment] 2020-09-24 09:41
I am facing the same error message. I am running it on a RTX 2070 Super. To which driver are you referring to? CUDA, or Nvidia 
graphic driver? 

> I solved it.
> Just update driver.

**Comment by PatrickNa** [comment] 2020-09-24 13:24
Upgrading the CUDA version and all components along the way solved the problem for me. I upgraded from CUDA 11 to CUDA 11.1. A more expressive error message would be much appreciated though.

**Comment by lablabla** [comment] 2020-10-15 05:48
Thanks guys!
Updating the nvidia drivers worked for me (CUDA 10.2, upgrading to 450.80.02)

**Comment by karanjakhar** [comment] 2020-10-15 11:36
glad to know that.

**Comment by mk-nvidia** [comment] 2020-11-10 21:41
@jackgao0323 Can you please post more details about how you hit this error / your code, so we can reproduce it at our end? What

**Comment by jackgao0323** [comment] 2020-11-11 03:57
> @jackgao0323 Can you please post more details about how you hit this error / your code, so we can reproduce it at our end? What

I have post the same problem on Nvidia forum include the model and full steps.

https://forums.developer.nvidia.com/t/error-builtin-op-importers-cpp-2179-in-function-importpad-inputs-at-1-is-weights/156240

**Comment by nvpohanh** [comment] 2022-07-01 05:47
Closing this since it seems that this has been answered in https://forums.developer.nvidia.com/t/error-builtin-op-importers-cpp-2179-in-function-importpad-inputs-at-1-is-weights/156240/6 . Thanks

**Closed by nvpohanh** 2022-07-01 05:47 UTC
Labels: question, Platform: Jetson, Step: Builder, triaged
