### ISSUE TITLE
Assertion failed: convertOnnxWeights(initializer, &weights, ctx)

### ISSUE THREAD

**Issue by x-jeff** [NVIDIA/TensorRT#586] opened 2020-06-01 06:19 UTC
I used the following code to convert my pb model to onnx model:

`python -m tf2onnx.convert --input ..\frozen_model.pb --output ..\model.onnx --outputs y_pred:0 --inputs data:0 --opset11`

Then there was an error building the engine:

![image](https://user-images.githubusercontent.com/43426273/83381102-47408a00-a412-11ea-8f98-b443481af4c4.png)

if I change `--opset11` to `--opset10`, I get a different error:

![image](https://user-images.githubusercontent.com/43426273/83381220-a7cfc700-a412-11ea-8de6-699321a9c0eb.png)

Does anyone know how to solve this problem?

Thank you in advance~

**Comment by rmccorm4** [comment] 2020-06-04 17:32
Hi @x-jeff ,

This is likely fixed in the OSS master branch. Please try building ONNX parser from source with TRT 7, and try again as described in this comment: https://github.com/NVIDIA/TensorRT/issues/386#issuecomment-604183816

**Comment by x-jeff** [comment] 2020-06-05 01:11
@rmccorm4 Thank you very much for your reply.
I can only build OSS under Linux, right?Because I use windows10 now.

**Comment by deepakn94** [comment] 2020-07-29 05:43
I am seeing this same error when using the Python API.

```
[TensorRT] ERROR: [TRT]/opt/tensorrt/TensorRT/parsers/onnx/onnx2trt_utils.cpp:1312: Failed to open file:
In node -1 (parseGraph): UNSUPPORTED_NODE: Assertion failed: convertOnnxWeights(initializer, &weights, ctx)
```

Weirdly enough, `trtexec` seems to work fine on the same ONNX file. I tried rebuilding the ONNX parser from source.

This is the version of `tensorrt` I am using,

```
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt
>>> print(tensorrt.__version__)
7.1.2.8
```

I'm attaching [two ONNX files](https://github.com/NVIDIA/TensorRT/files/4992805/onnx_files.zip) -- both run into the same error. Happy to provide any other information that helps reproduce the issue!

**Comment by ttyio** [comment] 2020-09-30 06:36
Hello @x-jeff, @deepakn94 
onnx-trt support for external data feature is supported in TensorRT 7.1.3, you can also upgrade to latest TensorRT 7.2.0 to fix this. Could you take a try? thanks.

**Comment by ttyio** [comment] 2020-10-26 09:09
Close since no activity in 3 weeks, please reopen if you have more questions, thanks!

**Closed by ttyio** 2020-10-26 09:09 UTC
Labels: Component: ONNX, Conversion: tf2onnx, Release: 7.x
