### ISSUE TITLE
How to adjust memory consumption in runtime ?

### ISSUE THREAD

**Issue by Jsy0220** [NVIDIA/TensorRT#3501] opened 2023-11-30 01:59 UTC
Hi
I have a question about serialized model. I found that the memory size in runtime depends on the `maxShapes` during serialization and if it is set to be large, the memory consumption may be very large even actual input size is small in runtime. So is that possible to adjust the memory dynamically according to the input size？

**Comment by Data-Iab** [comment] 2023-11-30 08:31
did you set the `max_workspace_size`

**Comment by zerollzeng** [comment] 2023-11-30 12:09
No, it doesn't related to workspace.

@nvpohanh for more info, I can't tell the exact reason clearly too :-)

**Comment by nvpohanh** [comment] 2023-12-01 02:33
Currently, TRT allocates the memory according to the maxShapes to avoid overheads caused by re-allocation. However, we recognized that it may lead to memory usage wasting if the runtime shapes are much smaller then maxShapes.

We are currently working on add new APIs to allow users to configure TRT to allocate less memory than what's needed by maxShapes. Please stay tuned :)

**Comment by Jsy0220** [comment] 2023-12-05 01:38
@nvpohanh  ok, thanks

**Comment by zerollzeng** [comment] 2023-12-09 08:33
@Jsy0220 Any further questions? can we close this bug? Thanks!

**Comment by Jsy0220** [comment] 2023-12-14 02:34
@zerollzeng  I don't have anymore questions. Thanks!

**Closed** 2023-12-16 15:21 UTC
Labels: triaged
