### ISSUE TITLE
Model conversion from h5 to UFF in samples/sampleUffMaskRCNN/converted causes an "IndexError: list index out of range" exception

### ISSUE THREAD

**Issue by sergey-nilga** [NVIDIA/TensorRT#360] opened 2020-01-28 15:08 UTC
## Description

When I ran Mask R-CNN conversion from h5 to uff exactly as described in samples/sampleUffMaskRCNN/README.md, the conversion always ends up with  "IndexError: list index out of range" exception
## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: GeForce GT 710
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2.89
**CUDNN Version**: 7.6.5.32-1+cuda10.2 amd64
**Operating System + Version**: Ubuntu 18.04-3 LTS, amd64
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: Tensorflow-gpu 1.14.0
**PyTorch Version (if applicable)**: N/A
**Baremetal or Container (if container which image + tag)**: N/A
**UFF**: 0.6.5
**Keras**: 2.1.3

## Relevant Files

https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN

## Steps To Reproduce

1. Follow through the steps 1-7 from Section 'Prerequisites' of https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN/README.md 

2. Step 7 'Convert the h5 model to the UFF model and place it into your `/data` folder' ends up with an exception, please see the whole output attached.
[output.txt](https://github.com/NVIDIA/TensorRT/files/4123013/output.txt)

3. The conversion crashes in attempt to convert frozen graph (temp.pb) to UFF in file uff/converters/tensorflow/converter_function.py, line 40:

```
38: @tf2uff.register(["Add"])
39: def convert_add(name, tf_node, inputs, uff_graph, **kwargs):
40: uff_graph.binary(inputs[0], inputs[1], 'add', name)
41: return [tf2uff.split_node_name_and_output(inp)[0] for inp in inputs]
```

Here is backtrace info from the debugger:

```
name = {str} 'mrcnn_mask/add'
tf_node = {NodeDef} name: "mrcnn_mask/add"\nop: "Add"\ninput: "mrcnn_mask/transpose_1"\nattr {\n key: "T"\n value {\n type: DT_FLOAT\n }\n}\n
uff_graph = {Graph} <uff.model.graph.Graph object at 0x7ff47c2bda20>uff_graph = {Graph} <uff.model.graph.Graph object at 0x7ff47c2bda20>
__exception__ = {tuple: 3} (<class 'IndexError'>, IndexError('list index out of range',), <traceback object at 0x7ff47c770e88>)
inputs = {list: 1} ['mrcnn_mask/transpose_1']
kwargs = {dict: 1} {'tf_nodes': {'input_image': name: "input_image"\nop: "Placeholder"\nattr {\n key: "dtype"\n value {\n type: DT_FLOAT\n }\n}\nattr {\n key: "shape"\n value {\n shape {\n dim {\n size: -1\n }\n dim {\n size: 3\n }\n dim {\n size: 1024\n }\n dim {\n size: 1024\n }\n }\n }\n}\n, 'zero_padding2d_1/Pad/paddings': name: "zero_padding2d_1/Pad/paddings"\nop: "Const"\nattr {\n key: "dtype"\n value {\n type: DT_INT32\n }\n}\nattr {\n key: "value"\n value {\n tensor {\n dtype: DT_INT32\n tensor_shape {\n dim {\n size: 4\n }\n dim {\n size: 2\n }\n }\n tensor_content: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\003\000\000\000\003\000\000\000\003\000\000\000\003\000\000\000"\n }\n }\n}\n, 'zero_padding2d_1/Pad': name: "zero_padding2d_1/Pad"\nop: "Pad"\ninput: "input_image"\ninput: "zero_padding2d_1/Pad/paddings"\nattr {\n key: "T"\n value {\n type: DT_FLOAT\n }\n}\nattr...

```

**Comment by sergey-nilga** [comment] 2020-01-30 10:51
I've figured out that the TensorRT example works fine on the same PC running Windows 10 x64 on CUDA 10.0 +   tensorflow-gpu 1.14.0 + TensorRT 7.0.0.11 + UFF 0.6.5 + Keras 2.1.3
So the issue seems exist only in Linux (100% reproducible in my x86 PC, and Jetson Nano)

**Comment by gabrielibagon** [comment] 2020-02-15 20:28
I can confirm the same error, which occurs in the following Docker environments: `nvcr.io/nvidia/tensorrt:20.01-py3` and `nvcr.io/nvidia/tensorrt:19.03-py3`.

An additional error occurs when loading tensorflow in these containers:

```
2020-02-15 20:01:27.060652: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/tensorrt/lib:/tensorrt/lib
2020-02-15 20:01:27.060728: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/tensorrt/lib:/tensorrt/lib
2020-02-15 20:01:27.060784: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/tensorrt/lib:/tensorrt/lib
2020-02-15 20:01:27.060839: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/tensorrt/lib:/tensorrt/lib
2020-02-15 20:01:27.060891: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/tensorrt/lib:/tensorrt/lib
2020-02-15 20:01:27.060942: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/tensorrt/lib:/tensorrt/lib
```

**Workaround**
I used the environment `nvcr.io/nvidia/tensorflow:19.10-py3` and it worked correctly. 

It must be some error regarding the combination of Python version, TF version, and CUDA version. I installed tensorflow-gpu==1.14.0 in each case.

**Comment by vdevaram** [comment] 2020-02-27 06:25
1.15.2  is giving same problem and moving to 1.14.0 version is giving another problem :


_Using output node mrcnn_detection
Using output node mrcnn_mask/Sigmoid
Converting to UFF graph
Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 178, in from_tensorflow
    debug_mode=debug_mode)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/usr/lib/python3.6/dist-packages/uff/converters/tensorflow/converter_functions.py", line 40, in convert_add
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
**IndexError: list index out of range**_

**Comment by tymiao1220** [comment] 2020-03-06 19:41
Same error here, 1.15.2 is giving:
```
Traceback (most recent call last):
  File "/home/miaot2/lib/TensorRTOSS/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "/home/miaot2/lib/TensorRTOSS/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "/home/miaot2/lib/TensorRTOSS/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 178, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter_functions.py", line 307, in convert_transpose
    tf_permutation_node = kwargs["tf_nodes"][inputs[1]]
IndexError: list index out of range
```


1.14.0 gives:
```
Traceback (most recent call last):
  File "/home/miaot2/lib/TensorRTOSS/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "/home/miaot2/lib/TensorRTOSS/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "/home/miaot2/lib/TensorRTOSS/samples/opensource/sampleUffMaskRCNN/converted/mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 178, in from_tensorflow
    debug_mode=debug_mode)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/home/miaot2/env/test/lib/python3.6/site-packages/uff/converters/tensorflow/converter_functions.py", line 40, in convert_add
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range
```

**Comment by liangjiecn** [comment] 2020-03-12 13:53
I met the same problem and I can not figure out in neither linux or windows.

**Comment by sergey-nilga** [comment] 2020-05-06 09:54
The conversion also does not work in my Jetson Nano running the latest JetPack 4.4 DP, with different error though. Please see the attached log output [jetson_nano_jp44.log](https://github.com/NVIDIA/TensorRT/files/4586002/jetson_nano_jp44.log) for details. 
You can also find the list of Python modules installed in my Jetson Nano here: 
[python_modules.txt](https://github.com/NVIDIA/TensorRT/files/4586025/python_modules.txt)

**Comment by Agent-Chu** [comment] 2020-05-14 13:31
Hey! I met the same problem
I try to install UFF with pip2 to fix this , but it didn't work.
I used the environment nvcr.io/nvidia/tensorflow:19.12-py3

Traceback (most recent call last):
  File "mrcnn_to_trt_single.py", line 164, in <module>
    main()
  File "mrcnn_to_trt_single.py", line 123, in main
    text=True, list_nodes=list_nodes)
  File "mrcnn_to_trt_single.py", line 157, in convert_model
    debug_mode = False
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
    return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 178, in from_tensorflow
    debug_mode=debug_mode)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter_functions.py", line 40, in convert_add
    uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range

**Comment by Agent-Chu** [comment] 2020-05-15 02:52
Hey! I met the same problem
I tried to install UFF with pip2 to fix this , but it didn't work.
I used the environment nvcr.io/nvidia/tensorflow:19.12-py3

_Traceback (most recent call last):
File "mrcnn_to_trt_single.py", line 164, in
main()
File "mrcnn_to_trt_single.py", line 123, in main
text=True, list_nodes=list_nodes)
File "mrcnn_to_trt_single.py", line 157, in convert_model
debug_mode = False
File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 229, in from_tensorflow_frozen_model
return from_tensorflow(graphdef, output_nodes, preprocessor, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 178, in from_tensorflow
debug_mode=debug_mode)
File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
uff_graph, input_replacements, debug_mode=debug_mode)
File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/uff/converters/tensorflow/converter_functions.py", line 40, in convert_add
uff_graph.binary(inputs[0], inputs[1], 'add', name)
IndexError: list index out of range_

**Comment by XinnWang** [comment] 2020-07-29 08:23
@tymiao1220 i met the same problem. have you solved it?

**Comment by banbishan** [comment] 2020-08-28 08:39
met the same problem. any resolution?

**Comment by rajeevsrao** [comment] 2020-09-30 07:08
Please try the updated instructions from: https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN#generating-uff-model

**Comment by somekindsoffood** [comment] 2020-12-02 09:16
same problem and the instruction here https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN#generating-uff-model doesn't work.

**Comment by dr413677671** [comment] 2020-12-17 02:14
I can see the same question even though following the same docker instruction at https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN#generating-uff-model. 
I also tested the combination of CUDA 10.2 tensorflow 1.14.0 on windows and CUDA 10.1 tensorflow 2.3.0 on UBUNTU 20.04. and they failed as well.

**Comment by dr413677671** [comment] 2020-12-17 02:15
> I can see the same question even though following the same docker instruction at https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN#generating-uff-model.
> I also tested the combination of CUDA 10.2 tensorflow 1.14.0 on windows and CUDA 10.1 tensorflow 2.3.0 on UBUNTU 20.04. and they failed as well.

My uff version is 0.6.5 and the repo of MaskRCNN is 2.0.0

**Comment by charliergi** [comment] 2021-02-11 18:05
Anyone fixed it ? Or has a workaround? I don't really understand how to use ONNX format for Mask RCNN.

**Comment by Tyler-D** [comment] 2021-04-28 01:14
Could try following steps to generate uff:

nvcr.io/nvidia/tensorflow:18.12-py3
install uff, graphsugeon, keras==2.1.3
Modify uff's transpose convolution
Export:
NOTE: UFF has been tested with TensorFlow 1.14.0.
WARNING: The version of TensorFlow installed on this system is not guaranteed to work with UFF.
UFF Version 0.6.5
=== Automatically deduced input nodes ===
[name: "input_image"
op: "Placeholder"
attr {
key: "dtype"
value {
type: DT_FLOAT
}
}
attr {
key: "shape"
value {
shape {
dim {
size: -1
}
dim {
size: 3
}
dim {
size: 1024
}
dim {
size: 1024
}
}
}
}
]
=========================================
Using output node mrcnn_detection
Using output node mrcnn_mask/Sigmoid
Converting to UFF graph
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_mask_trt as custom op: PyramidROIAlign_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p5upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p4upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: ResizeNearest_TRT yet.
Converting fpn_p3upsampled as custom op: ResizeNearest_TRT
Warning: No conversion function registered for layer: SpecialSlice_TRT yet.
Converting mrcnn_detection_bboxes as custom op: SpecialSlice_TRT
Warning: No conversion function registered for layer: DetectionLayer_TRT yet.
Converting mrcnn_detection as custom op: DetectionLayer_TRT
Warning: No conversion function registered for layer: ProposalLayer_TRT yet.
Converting ROI as custom op: ProposalLayer_TRT
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: keepdims is ignored by the UFF Parser and defaults to True
Warning: No conversion function registered for layer: PyramidROIAlign_TRT yet.
Converting roi_align_classifier as custom op: PyramidROIAlign_TRT
DEBUG [/usr/local/lib/python3.5/dist-packages/uff/converters/tensorflow/converter.py:96] Marking ['mrcnn_detection', 'mrcnn_mask/Sigmoid'] as outputs
No. nodes: 3049

**Comment by ttyio** [comment] 2021-05-21 07:29
Close since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Closed by ttyio** 2021-05-21 07:29 UTC
Labels: Release: 7.x, Samples, TODO, bug, needs-repro
