### ISSUE TITLE
Maybe some bugs in tensorrt7.0.0.11

### ISSUE THREAD

**Issue by yflv-yanxia** [NVIDIA/TensorRT#396] opened 2020-02-27 08:21 UTC
## Description
I have a network on caffe as follows:
[net.prototxt](https://github.com/yflv-yanxia/issues/blob/master/knet.prototxt)

If I use tensorrt6.0.1.5 to convert model and infer, the output of network is correct.
Then I update the tensorrt from version6.0.1.5 to 7.0.0.11 to convert model and do inference, the output is not right any more. The other configures are same as tensorrt6.0.1.5.
So I guess there are some difference(bugs) in tensorrt7.0.0.11.

## Environment
tensorrt7.0.0.11
titan rtx
cuda 10.0
cudnn 7.6.3

**Comment by rmccorm4** [comment] 2020-02-27 23:30
Hi @yflv-yanxia ,

Can you please share the commands or scripts you're running to produce the different outputs so I can reproduce?

**Comment by rajeevsrao** [comment] 2020-10-18 01:55
@yflv-yanxia please provide a repro test or check if this is fixed in release 7.1

**Comment by ttyio** [comment] 2021-01-12 14:14
I will close this since no response for more than 3 weeks, please reopen if you still have question, thanks!

**Closed by ttyio** 2021-01-12 14:14 UTC
Labels: Component: Caffe, Release: 6.x, Release: 7.x, Runtime: Correctness, needs-repro, regression, triaged
