### ISSUE TITLE
ERROR: Unnamed Layer* xxx [Slice]:slice size must be positive, size=[0,0,0]

### ISSUE THREAD

**Issue by wnzhyee** [NVIDIA/TensorRT#921] opened 2020-11-20 09:29 UTC
I use onnx model in tensorrt to inferece, it reports this issue, the model can inference to the end but i cant get correct result. I check my model via onnxruntime, and the result is ok. I print the onnx node and it is like:

```
input: "LSTM__52:0"
output: "Slice__58:0"
name: "Slice__58"
op_type: "Slice"
attribute {
  name: "axes"
  ints: 1
  type: INTS
}
attribute {
  name: "ends"
  ints: 2
  type: INTS
}
attribute {
  name: "starts"
  ints: 1
  type: INTS
}
domain: ""
```

I dont know where is wrong, please help me ,thanks!

**Comment by wnzhyee** [comment] 2020-11-20 09:30
The input should be a tensor of 64x2x1x256, and the model uses 2 slice op to split them to 64x1x1x256.

**Comment by huang6886** [comment] 2020-12-15 07:11
have you find the solution for your problem?

**Comment by mk-nvidia** [comment] 2020-12-15 20:09
@wnzhyee or @huang6886, can you please attach an onnx model that reproduces you problem? It will help us figure out the problem faster. Thanks.

**Comment by wnzhyee** [comment] 2020-12-17 11:34
> have you find the solution for your problem?

我对比了一下模型的输出，这个层虽然有报错，但实际上和我的onnx模型一致性是能对上的

**Comment by whcjb** [comment] 2021-03-10 03:22
same problem，whats the cause?
`[TensorRT] VERBOSE: ModelImporter.cpp:494: Marking output1_1 as output: output1
Building an engine from file temp.pb; this may take a while...
[TensorRT] ERROR: (Unnamed Layer* 142) [Slice]: ISliceLayer size elements must be positive, but element 3 is not
[TensorRT] ERROR: Builder failed while analyzing shapes.
Completed creating Engine
Traceback (most recent call last):
  File "examples/ceshi/ceshi_rt.py", line 31, in <module>
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'`

**Comment by nvpohanh** [comment] 2022-06-15 11:06
@whcjb @wnzhyee Could you try TRT 8.2/8.4 and see if the issue still exists? If it does, please share the ONNX model and we will debug it. Thanks

**Comment by nvpohanh** [comment] 2022-07-01 05:49
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists in TRT 8.4. Thanks

**Closed by nvpohanh** 2022-07-01 05:49 UTC
Labels: Component: ONNX, triaged
