### ISSUE TITLE
TRT 7 cannot parse onnx for loop model

### ISSUE THREAD

**Issue by rtrobin** [NVIDIA/TensorRT#411] opened 2020-03-03 08:08 UTC
## Description

TRT 7 cannot parse onnx for loop model

## Environment

**TensorRT Version**: 7.0.0.11
**GPU Type**: 1080ti
**Nvidia Driver Version**: 440.33.01
**CUDA Version**: 10.2
**CUDNN Version**: 7.6.5
**Operating System + Version**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**PyTorch Version (if applicable)**: 1.4.0
**Baremetal or Container (if container which image + tag)**: ngc docker tensorrt:20.01-py3

## Relevant Files

Here is an sample code for pytorch model which can be exported to onnx model. Full test code is also uploaded to my [repo](https://github.com/rtrobin/codeMixed/blob/master/TensorRT/export.py).

``` python
class ForModel(nn.Module):
    def __init__(self):
        super().__init__()

    @staticmethod
    @torch.jit.script
    def loopFunc(x, y):
        for i in range(2):
            x = x + y
        return x

    def forward(self, x):
        # test loop export

        # Script for loop
        x = self.loopFunc(x, x)

        # Trace for loop
        # for i in range(2):
        #     x = x + x

        return x
```

## Steps To Reproduce

Upon is a sample pytorch model which can be exported to onnx model contains onnx for module. The full test code can be seen in my repo. By running `python export.py`, the onnx model can be saved to disk. Also onnxruntime  is used to check the output value. By running 'python import.py', the saved onnx model is read and parsed by trt onnx parser. It shows the error message `Segmentation fault (core dumped)`.

**Comment by rmccorm4** [comment] 2020-03-04 01:49
Hi @rtrobin ,

I don't know all the details surrounding this, but if you remove the @torch.jit.script, the model can be parsed fine:

Create simple onnx model:
```python
# repro.py
import torch
from torch import nn

class ForModel(nn.Module):
    def __init__(self):
        super().__init__()

    @staticmethod
    def loopFunc(x, y): 
        for i in range(2):
            x = x + y 
        return x

    def forward(self, x): 
        x = self.loopFunc(x, x)
        return x

model = ForModel()
batch = 10
shape = (1) 
inp = torch.randn(batch, 1)
torch.onnx.export(model, inp, "loop.onnx", verbose=True, opset_version=11)
```

Parsing succeeds:
```
$ nvidia-docker run -it -v $PWD:/mnt nvcr.io/nvidia/tensorrt:20.01-py3
$ pip install torch==1.4
$ python repro.py
$ trtexec --explicitBatch --onnx=loop.onnx
...
&&&& PASSED TensorRT.trtexec # trtexec --explicitBatch --onnx=loop.onnx
```

**Comment by rmccorm4** [comment] 2020-03-04 01:56
Seems like removing the torchscript caused PyTorch->ONNX exporter to unravel the loop.

With torchscript decorator:

![image](https://user-images.githubusercontent.com/21284872/75836934-3d0de180-5d78-11ea-8424-1d3fb3739ab7.png)


Without torchscript decorator:

![image](https://user-images.githubusercontent.com/21284872/75836902-2798b780-5d78-11ea-8b40-a2612202c821.png)

**Comment by rmccorm4** [comment] 2020-03-04 02:06
Yeah, if you increase the iterations, I don't think this scales:
```
$ ls -lh
-rw-r--r-- 1 ryan ryan  330 Mar  3 18:04 loop-jit.onnx
-rw-r--r-- 1 ryan ryan 1.9K Mar  3 18:04 loop-no-jit.onnx
```

Will need to look into why `Loop` op is causing SegFault.

**Comment by rtrobin** [comment] 2020-03-04 02:07
@rmccorm4 Yes, that is how torchscript decorator works. For more details, you could find it on [pytorch doc page](https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting).

When it comes to loops with many iterations, it will simply unroll the loop. If the nodes and operations' shape info are relatively constant, it would work fine. This issue is also related my another [issue](https://github.com/NVIDIA/TensorRT/issues/401) here.

**Comment by rtrobin** [comment] 2020-03-04 02:23
@rmccorm4 
> Unraveling won't scale to large numbers of iterations

Though the file size doesn't scale up by unravelling the iteration, the exported onnx model will contain much more nodes in it. When it comes to onnx parsing phase, the parsing time would dramatically increase from hours to days in some cases.

**Comment by rmccorm4** [comment] 2020-03-04 03:00
Right, I meant unraveling as a workaround won't scale because huge graphs will inevitably cause some kind of problem eventually, even if that's just in time spent debugging because tools like Netron crash on large models, or in increasing parse time.

**Comment by rmccorm4** [comment] 2020-03-12 21:38
Hi @rtrobin,

I think this was just fixed in OSS ONNX parser: https://github.com/onnx/onnx-tensorrt/pull/412/files

```
# Create ONNX model with loop/torch.jit.script
pip install torch==1.4 onnx==1.6
python repro.py
 
# Build latest ONNX parser and other OSS components
wget https://raw.githubusercontent.com/rmccorm4/tensorrt-utils/master/OSS/build_OSS.sh
source build_OSS.sh

# Parse model
trtexec --onnx=loop.onnx --explicitBatch
...
&&&& PASSED TensorRT.trtexec # trtexec --onnx=loop.onnx --explicitBatch
```

**Comment by rtrobin** [comment] 2020-03-13 06:22
@rmccorm4  Thanks for the support.

I have pulled the latest code and built it. For the sample code above, it could be built successfully. For my real use case, the Segmentation fault is fixed. But the engine still failed to create. The error message is shown below.

> [E] [TRT] ../builder/myelin/codeGenerator.cpp (92) - Myelin Error in addNodeToMyelinGraph: 0 (operation not supported in myelin)

I'm not sure what myelin is. I will try to locate which part of model triggers this error by adjusting my onnx exporting code in pytorch. Any help or info would be appreciated. Thanks.

**Comment by rtrobin** [comment] 2020-03-13 09:43
I will show some sample code below to illustrate my investigation by far. My code is something like this:

``` python
@torch.jit.script
def script_func(x: torch.Tensor) -> torch.Tensor:
    y = foo(x)
    for i in range(4):
        temp = bar(y)
        y = y + temp

    return y
```

Parsing by trtexec, it would show error. `[E] [TRT] ../builder/myelin/codeGenerator.cpp (92) - Myelin Error in addNodeToMyelinGraph: 0 (operation not supported in myelin)`

But if I remove the loop, and let it run only once. It could be parsed successfully. 

``` python
@torch.jit.script
def script_func(x: torch.Tensor) -> torch.Tensor:
    y = foo(x)
    # for i in range(4):
    temp = bar(y)
    y = y + temp

    return y
```

Moreover, in bar function, torch.LongTensor is used. Trt seems not working fine on some int64 operations. If I remove all LongTensor related code, the exported onnx loop model could be parsed successfully too.

I will dig this deep next week.

**Comment by rtrobin** [comment] 2020-03-18 08:33
@rmccorm4 Hi, after the research, now I extract a sample code to reproduce the error I run into. Code is as follows:

``` python

class MyelinModel(nn.Module):
    def __init__(self):
        super(MyelinModel, self).__init__()

        self.pred = torch.ones((1, 8), dtype=torch.int)
        self.trg_mask = torch.tril(torch.ones((8, 8), dtype=torch.float))
        self.mask_fn = torch.jit.trace(self.make_mask, [self.pred, self.trg_mask])

    @staticmethod
    @torch.jit.ignore
    def make_mask(tgt: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        # tgt: 1x8
        # mask: 8x8
        # return: 1x8x8
        pad_mask = (tgt != 0).unsqueeze(-1)
        return pad_mask * mask
        

    def forward(self, x):
        # x: 1x8x8
        pred = self.pred
        for i in range(4):
            # mask = self.make_mask(pred, self.trg_mask)
            mask = self.mask_fn(pred, self.trg_mask)
            out = torch.matmul(x, mask)
            prob = F.softmax(out, dim=-1)
            _, pos = torch.max(prob, dim=-1)

            pred = pred + pos.to(torch.int)

        return pred
```

You can export onnx model by code below.

``` python
    model = MyelinModel()
    model.eval()

    dummy_input = torch.randn((1, 8, 8), dtype=torch.float)
    input_names = [ "input" ]
    output_names = [ "output" ]

    my_script_module = torch.jit.script(model)

    with torch.no_grad():
        torch.onnx.export(
            my_script_module, dummy_input, "model.onnx",
            opset_version=10,
            verbose=True, input_names=input_names, output_names=output_names,
            example_outputs=torch.randint(10, (1, 8), dtype=torch.int)
        )
```

It should be exported as follows:

```
graph(%input : Float(1, 8, 8),
      %1 : Float(8, 8),
      %2 : Int(1, 8)):
  %3 : Long() = onnx::Constant[value={1}]()
  %4 : Long() = onnx::Constant[value={4}]()
  %5 : Tensor = onnx::Cast[to=9](%3)
  %output : Int(1, 8) = onnx::Loop(%4, %5, %2) # export.py:176:8
    block0(%i : Long(), %cond : bool, %pred.7 : Tensor):
      %10 : Long() = onnx::Constant[value={0}]()
      %11 : Tensor = onnx::Equal(%pred.7, %10)
      %12 : Bool(1, 8) = onnx::Not(%11) # /usr/local/lib/python3.6/dist-packages/torch/tensor.py:28:0
      %13 : Bool(1, 8, 1) = onnx::Unsqueeze[axes=[2]](%12) # export.py:169:0
      %14 : Float(1, 8, 1) = onnx::Cast[to=1](%13)
      %15 : Float(1, 8, 8) = onnx::Mul(%14, %1) # export.py:170:0
      %16 : Tensor = onnx::MatMul(%input, %15) # export.py:179:18
      %17 : Tensor = onnx::Exp(%16)
      %18 : Tensor = onnx::ReduceSum[axes=[-1]](%17)
      %19 : Tensor = onnx::Div(%17, %18) # /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1231:14
      %20 : Tensor = onnx::ArgMax[axis=-1, keepdims=0](%19) # export.py:181:21
      %21 : Tensor = onnx::Cast[to=6](%20) # export.py:183:26
      %22 : Tensor = onnx::Add(%pred.7, %21) # export.py:183:19
      %23 : Tensor = onnx::Cast[to=9](%3)
      -> (%23, %22)
  return (%output)
```

Here is the model shown in netron:
![image](https://user-images.githubusercontent.com/8224989/76940879-03230a80-6936-11ea-803e-bb39792462bc.png)

By running `trtexec --onnx=model.onnx --explicitBatch`, it will fail with error message `[E] [TRT] ../builder/myelin/codeGenerator.cpp (92) - Myelin Error in addNodeToMyelinGraph: 0 (operation not supported in myelin)`

The code above is uploaded to my [repo](https://github.com/rtrobin/codeMixed/blob/master/TensorRT/export.py) too.

**Comment by rtrobin** [comment] 2020-03-20 02:38
Hi @rmccorm4 , any update info for this issue? By the way, what is **myelin**? Is there any document or web page explaining it? Can custom plugin work for myelin? Thank you.

**Comment by rmccorm4** [comment] 2020-03-20 21:43
Hi @rtrobin ,

I believe the root cause of the issue is `Reduce` and `TopK` ops not yet being supported within a `Loop` op. This has been noted as an RFE.

**Comment by rajeevsrao** [comment] 2020-09-30 04:21
> Hi @rmccorm4 , any update info for this issue? By the way, what is **myelin**? Is there any document or web page explaining it? Can custom plugin work for myelin? Thank you.

Myelin is our graph compiler that processes subgraphs in ONNX loops. We don't yet have plugins for myelin graphs, and parsing will fail if the subgraphs can't be handled by myelin. We have filed this as an RFE as Ryan mentioned. Thanks.

**Comment by rtrobin** [comment] 2020-09-30 10:35
@rajeevsrao Thanks for the info. By the way, nvidia already released myelin recommendation framework. The myelin here in onnx parser may need a new name.

**Closed** 2021-01-12 14:23 UTC
Labels: Component: ONNX, Conversion: torch.onnx, Release: 7.x, enhancement

**Comment by rtrobin** [comment] 2021-08-03 08:02
As TensorRT 8.0 released, I run the test code above again. It seems TRT8.0 fixes unsupported op in my code. But it now gives another error info. Just let you know. Hope it helps. @rmccorm4 @ttyio 

``` bash
[08/03/2021-07:53:54] [W] [TRT] onnx2trt_utils.cpp:362: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[08/03/2021-07:53:54] [W] [TRT] Tensor DataType is determined at build time for tensors not marked as input or output.
[08/03/2021-07:53:54] [I] Finish parsing network model
[08/03/2021-07:53:54] [I] [TRT] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 257, GPU 483 (MiB)
[08/03/2021-07:53:54] [E] Error[4]: [layers.cpp::validateRecurrence::4932] Error Code 4: Internal Error ((Unnamed Layer* 31) [Recurrence]: recurrence inputs must have same type)
[08/03/2021-07:53:54] [E] Error[2]: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
Segmentation fault (core dumped)
```

**Comment by rtrobin** [comment] 2021-08-04 02:23
> As TensorRT 8.0 released, I run the test code above again. It seems TRT8.0 fixes unsupported op in my code. But it now gives another error info. Just let you know. Hope it helps. @rmccorm4 @ttyio
> 
> ```shell
> [08/03/2021-07:53:54] [W] [TRT] onnx2trt_utils.cpp:362: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
> [08/03/2021-07:53:54] [W] [TRT] Tensor DataType is determined at build time for tensors not marked as input or output.
> [08/03/2021-07:53:54] [I] Finish parsing network model
> [08/03/2021-07:53:54] [I] [TRT] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 257, GPU 483 (MiB)
> [08/03/2021-07:53:54] [E] Error[4]: [layers.cpp::validateRecurrence::4932] Error Code 4: Internal Error ((Unnamed Layer* 31) [Recurrence]: recurrence inputs must have same type)
> [08/03/2021-07:53:54] [E] Error[2]: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
> Segmentation fault (core dumped)
> ```

The onnx file led the error message above is exported py ngc `pytorch:21.06` image. I use `pytorch:20.12` exporting a new onnx file, and build the TRT engine with `TensorRT:21.07`. The error message is shown below.

``` bash
[08/04/2021-02:16:58] [W] [TRT] Convolution + generic activation fusion is disable due to incompatible driver or nvrtc
[08/04/2021-02:17:01] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +349, GPU +160, now: CPU 607, GPU 643 (MiB)
[08/04/2021-02:17:03] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +159, GPU +164, now: CPU 766, GPU 807 (MiB)
[08/04/2021-02:17:03] [W] [TRT] Detected invalid timing cache, setup a local cache instead
[08/04/2021-02:17:03] [I] [TRT] Detected 1 inputs and 1 output network tensors.
[08/04/2021-02:17:03] [I] [TRT] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 766, GPU 789 (MiB)
[08/04/2021-02:17:03] [E] Error[4]: [codeGenerator.cpp::addNodeToMyelinGraph::158] Error Code 4: Myelin (TOPK operation not supported within a loop body.)
[08/04/2021-02:17:03] [E] Error[2]: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)
Segmentation fault (core dumped)
```
