### ISSUE TITLE
Bugs in HistogramCalibrator

### ISSUE THREAD

**Issue by yuantailing** [NVIDIA/TensorRT#2757] opened 2023-03-11 18:45 UTC
### Bug 1

```python3
import pytorch_quantization.calib
import torch

torch.random.manual_seed(42)
calibrator = pytorch_quantization.calib.HistogramCalibrator(num_bits=8, axis=None, unsigned=False, torch_hist=True)
calibrator.collect(torch.arange(2048, device="cuda"))
calibrator.collect(torch.rand((1024, 1024, 1024), device="cuda"))
print(calibrator.compute_amax(method="percentile", percentile=99.99))
```

The output is 316.8452. A number less than 1 is expected.

It seems the output of `torch.histc` is clipped to 16x1024x1024. Bug 1 should be fixed by replacing `histc` with a more robust function.

### Bug 2

```python3
import pytorch_quantization.calib
import torch

torch.random.manual_seed(42)
calibrator = pytorch_quantization.calib.HistogramCalibrator(num_bits=8, axis=None, unsigned=False, torch_hist=True)
calibrator.collect(torch.rand((1024, 1024, 1024), device="cuda"))
calibrator.collect(torch.rand((1024, 1024, 1024), device="cuda"))
calibrator.collect(torch.rand((1024, 1024, 1024), device="cuda"))
print(calibrator.compute_amax(method="entropy"))
```

Output

```
Traceback (most recent call last):
  File "/home/yuan/Documents/TensorRT/a.py", line 9, in <module>
    amax = calibrator.compute_amax(method="entropy")
  File "/home/yuan/.local/lib/python3.10/site-packages/pytorch_quantization/calib/histogram.py", line 149, in compute_amax
    calib_amax = _compute_amax_entropy(
  File "/home/yuan/.local/lib/python3.10/site-packages/pytorch_quantization/calib/histogram.py", line 241, in _compute_amax_entropy
    raise RuntimeError("Count mismatch! total_counts_new={}, total_counts_old={}, total_data={}".format(
RuntimeError: Count mismatch! total_counts_new=3221225318.0, total_counts_old=-1073741978, total_data=3221225318
```

Bug 2 should be fixed by changing https://github.com/NVIDIA/TensorRT/blob/8e756f163f83d54389c7ff82235e57a518f6eb03/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L142 to
```python3
    calib_hist = self._calib_hist.to(torch.int64).cpu().numpy()
```

## Environment

**TensorRT Version**: 8.5.1.7
**NVIDIA GPU**: NVIDIA GeForce RTX 3080
**NVIDIA Driver Version**: 528.49
**CUDA Version**: 11.5
**CUDNN Version**: cudnn-linux-x86_64-8.6.0.163_cuda11
**Operating System**: Ubuntu 22.04.1 LTS (in WSL)
**Python Version (if applicable)**: 3.10.6
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.13.1+cu117
**Baremetal or Container (if so, version)**: 

pytorch_quantization version: 2.1.2

**Comment by zerollzeng** [comment] 2023-03-13 14:37
@ttyio ^ ^

**Comment by yuantailing** [comment] 2023-03-14 13:27
Bug 1 is related to https://github.com/pytorch/pytorch/issues/96613.

Here is a workaround. Change https://github.com/NVIDIA/TensorRT/blob/8e756f163f83d54389c7ff82235e57a518f6eb03/tools/pytorch-quantization/pytorch_quantization/calib/histogram.py#L77 to
```
    x = x.to(torch.float64)
```

**Comment by yuantailing** [comment] 2023-03-14 13:34
It works well now.

```python3
import pytorch_quantization.calib
import torch

torch.random.manual_seed(42)

calibrator = pytorch_quantization.calib.HistogramCalibrator(num_bits=8, axis=None, unsigned=False, torch_hist=True)
calibrator.collect(torch.arange(2048, device="cuda"))
calibrator.collect(torch.rand((512, 1024, 1024), device="cuda"))
print(calibrator.compute_amax(method="percentile", percentile=99.99))

calibrator = pytorch_quantization.calib.HistogramCalibrator(num_bits=8, axis=None, unsigned=False, torch_hist=True)
calibrator.collect(torch.rand((512, 1024, 1024), device="cuda"))
calibrator.collect(torch.rand((512, 1024, 1024), device="cuda"))
calibrator.collect(torch.rand((512, 1024, 1024), device="cuda"))
print(calibrator.compute_amax(method="entropy"))
```

Output

```
tensor(0.9995)
tensor(1.0000)
```

**Comment by zerollzeng** [comment] 2023-03-14 14:38
So it's caused by insufficient memory?

**Comment by yuantailing** [comment] 2023-03-14 14:43
> So it's caused by insufficient memory?

No, the bug is not relevent to insufficient memory.

After I fix bug 1, i.e., change `x = x.float()` to `x = x.to(torch.float64)`, I suffer insufficient memory.

**Comment by ryj0902** [comment] 2023-11-02 04:55
> With the changes (calib_hist = self._calib_hist.to(torch.int64).cpu().numpy() and x = x.to(torch.float64)), it works well now.

PERFECT SOLUTION  
@yuantailing  you really saved me a lot of time. thank you

### Environment

* TensorRT Version: 8.6.0.1
* NVIDIA GPU: NVIDIA A100-PCIE-40GB
* NVIDIA Driver Version: 535.54.03
* CUDA Version: 11.8
* Operating System: CentOS Linux release 7.9.2009 (Core)
* Python Version (if applicable): 3.10.12
* PyTorch Version (if applicable): 2.0.1+cu118
* Baremetal or Container (if so, version): Container
* model: YOLO based realtime object detector
* calibration data: custom data, total size: 6000
* evaluation metric: mAP50-95

**Calibration by 2560 data**
* percentile(0.99): 0.631
* mse: 0.631
* entropy: 0.091

**Calibration by 6000 data**
* percentile(0.99): -
* mse: 0.634
* entropy: error → **(after patch)** 0.634

**Comment by zerollzeng** [comment] 2023-11-04 01:37
bug 1 already fix in the TOT(should be also in the latest release too, if not, next version will have), I've create MR bug for bug2 . Thanks for the contribution!

**Comment by ttyio** [comment] 2023-12-19 18:08
Thanks @zerollzeng , closing since this is fixed.

**Closed by ttyio** 2023-12-19 18:08 UTC
Labels: triaged
