### ISSUE TITLE
Myelin internal error: missing offset in id2offset failure of TensorRT 8.6 when loading an engine with multiple profiles on GPU 3090

### ISSUE THREAD

**Issue by mseagrief** [NVIDIA/TensorRT#2977] opened 2023-05-16 14:36 UTC
## Description

Generating an engine with multiple profiles fails to re-load with the following internal error:
```
[MS] The main stream provided by execute/enqueue calls is the first worker stream ←[0;24;39m
myelin_session.h:303: CHECK(TI != id2offset_table_.end()) failed. Myelin internal error: missing offset in id2offset
1: [graphContext.h::nvinfer1::rt::MyelinGraphContext::MyelinGraphContext::36] Error Code 1: Myelin (No Myelin Error exists) 
```

Generating the engine with only a single optimisation profile - via the C++ API or trtexec - works successfully.

The issue is specific to the particular model linked below (Unet + mit_b1 generated by [SMP](https://github.com/qubvel/segmentation_models.pytorch)). Other engines generated with the same C++ code work correctly with single or multiple optimisation profiles.

We have a variable workload so generally generate multiple optimisation profiles to get the best performance.

## Environment

**TensorRT Version**: 8.6.1.6

**NVIDIA GPU**: 3090

**NVIDIA Driver Version**: 527.56

**CUDA Version**: 12.1

**CUDNN Version**: N/A - using the lean runtime / version compatible

Operating System: Windows 10 (21H2) 19044.2965

Python Version (if applicable): 3.11.3

Tensorflow Version (if applicable): N/A

PyTorch Version (if applicable): 2.0.0

Baremetal or Container (if so, version): Baremetal

## Relevant Files

**Model link**:
- [Unet_mit_b1_512x512_[0].onnx](https://drive.google.com/file/d/13QnLaCHrBahNtAPUxciaDeKWBwpkUqoQ/view?usp=share_link)
- [Unet_mit_b1_512x512_[0].trt](https://drive.google.com/file/d/13QHPln6NJ6VzZ-NjxL6ofr9CjhMaUoI_/view?usp=share_link)

## Steps To Reproduce

**Commands or scripts**:
Code used to generate the TRT engine:
```cpp
#include <NvInfer.h>
#include <NvOnnxParser.h>

#include <filesystem>
#include <iostream>
#include <fstream>
#include <memory>

using namespace nvinfer1;
using namespace nvonnxparser;

namespace fs = std::filesystem;

struct batches
{
    int minBatchSize{ 1 };
    int optBatchSize{ 1 };
    int maxBatchSize{ 1 };
};

class Logger : public ILogger
{
    void log(Severity severity, const char* msg) noexcept override
    {
        switch(severity)
        {
            std::cerr << msg << "\n";
        }
    }
} logger;

IOptimizationProfile* setupProfile(IBuilder* builder, INetworkDefinition* network, int minBatch, int optBatch, int maxBatch)
{
    IOptimizationProfile* profile(builder->createOptimizationProfile());

    for(int i = 0; i < network->getNbInputs(); ++i)
    {
        auto input = network->getInput(i);
        auto dims = input->getDimensions();

        auto name = input->getName();

        dims.d[0] = minBatch;
        profile->setDimensions(name, OptProfileSelector::kMIN, dims);
        dims.d[0] = optBatch;
        profile->setDimensions(name, OptProfileSelector::kOPT, dims);
        dims.d[0] = maxBatch;
        profile->setDimensions(name, OptProfileSelector::kMAX, dims);
    }

    return profile;
}

void generateTRT(const std::string& onnxPath, const std::string& trtPath, const std::string& timingCache, const std::vector<batches>& batchProfiles)
{
    std::unique_ptr<IBuilder> builder(createInferBuilder(logger));

    uint32_t flag = 1U << static_cast<uint32_t>
        (NetworkDefinitionCreationFlag::kEXPLICIT_BATCH);

    std::unique_ptr<INetworkDefinition> network(builder->createNetworkV2(flag));
    std::unique_ptr<IParser> parser(createParser(*network, logger));

    //TensorRT 8.6 requirement
    parser->setFlag(nvonnxparser::OnnxParserFlag::kNATIVE_INSTANCENORM);

    parser->parseFromFile(onnxPath.c_str(),
        static_cast<int32_t>(ILogger::Severity::kWARNING));
    for(int32_t i = 0; i < parser->getNbErrors(); ++i)
    {
        std::cerr << parser->getError(i)->desc() << "\n";
    }

    //builder options
    std::unique_ptr<IBuilderConfig> config(builder->createBuilderConfig());
    config->setFlag(BuilderFlag::kFP16);

    //dynamic batch size
    auto input = network->getInput(0);
    auto dims = input->getDimensions();

    //runtime decision for batch size
    dims.d[0] = -1;
    input->setDimensions(dims);

    //optimisaiton profiles
    for(auto& batch : batchProfiles)
    {
        //single batch
        auto optProfile0 = setupProfile(builder.get(), network.get(), batch.minBatchSize, batch.optBatchSize, batch.maxBatchSize);
        config->addOptimizationProfile(optProfile0);
    }

    config->setFlag(BuilderFlag::kVERSION_COMPATIBLE);
    std::unique_ptr<IHostMemory> serializedModel(builder->buildSerializedNetwork(*network, *config));

    std::ofstream modelFile(trtPath, std::ios::binary);
    modelFile.write(static_cast<char*>(serializedModel->data()), serializedModel->size());

    parser.reset();
    network.reset();
    //optProfile.reset();
    config.reset();
    builder.reset();

    serializedModel.reset();
}
```

Invoked as:
```cpp
generateTRT("model.onnx", "model.trt", { {1,1,1}, {2,8,8}, {9, 12, 16}});
```

Asking trtexec to benchmark the engine fails with the above error:
```
trtexec.exe --loadEngine=Unet_mit_b1_512x512.trt --useCudaGraph --vc

<snip>

[05/16/2023-15:11:35] [I] TensorRT version: 8.6.1
[05/16/2023-15:11:35] [I] Not loading standard plugins since --versionCompatible is specified.
[05/16/2023-15:11:35] [I] Engine loaded in 0.142422 sec.
[05/16/2023-15:11:36] [I] [TRT] Loaded engine size: 111 MiB
[05/16/2023-15:11:37] [I] [TRT] Loaded engine size: 111 MiB
[05/16/2023-15:11:37] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +41, now: CPU 0, GPU 41 (MiB)
[05/16/2023-15:11:37] [I] Engine deserialized in 1.69582 sec.
[05/16/2023-15:11:37] [I] [TRT] [MS] Running engine with multi stream info
[05/16/2023-15:11:37] [I] [TRT] [MS] Number of aux streams is 1
[05/16/2023-15:11:37] [I] [TRT] [MS] Number of total worker streams is 2
[05/16/2023-15:11:37] [I] [TRT] [MS] The main stream provided by execute/enqueue calls is the first worker stream
myelin_session.h:303: CHECK(TI != id2offset_table_.end()) failed. Myelin internal error: missing offset in id2offset
[05/16/2023-15:11:37] [E] Error[1]: [graphContext.h::nvinfer1::rt::MyelinGraphContext::MyelinGraphContext::36] Error Code 1: Myelin (No Myelin Error exists)
```

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: Yes

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

Yes - and as above works when using a single optimisation profile.

**Comment by zerollzeng** [comment] 2023-05-18 09:52
I can reproduce it under Linux:
```
trtexec --onnx=unet.onnx --fp16 --vc --saveEngine=unet.plan
trtexec --loadEngine=unet.plan --vc --useCudaGraph
```
@oxana-nvidia Does it relate to Windows?

**Comment by zerollzeng** [comment] 2023-05-18 09:52
```
[05/18/2023-09:51:21] [I] === Performance summary ===
[05/18/2023-09:51:21] [I] Throughput: 437.964 qps
[05/18/2023-09:51:21] [I] Latency: min = 2.45551 ms, max = 2.68213 ms, mean = 2.53707 ms, median = 2.5481 ms, percentile(90%) = 2.57654 ms, percentile(95%) = 2.58374 ms, percentile(99%) = 2.59528 ms
[05/18/2023-09:51:21] [I] Enqueue Time: min = 0.0292969 ms, max = 0.0772705 ms, mean = 0.03319 ms, median = 0.0322266 ms, percentile(90%) = 0.0345154 ms, percentile(95%) = 0.0405884 ms, percentile(99%) = 0.0508423 ms
[05/18/2023-09:51:21] [I] H2D Latency: min = 0.123779 ms, max = 0.199921 ms, mean = 0.130762 ms, median = 0.125977 ms, percentile(90%) = 0.147278 ms, percentile(95%) = 0.158966 ms, percentile(99%) = 0.161255 ms
[05/18/2023-09:51:21] [I] GPU Compute Time: min = 2.2016 ms, max = 2.34082 ms, mean = 2.27953 ms, median = 2.29785 ms, percentile(90%) = 2.31934 ms, percentile(95%) = 2.32349 ms, percentile(99%) = 2.32959 ms
[05/18/2023-09:51:21] [I] D2H Latency: min = 0.119629 ms, max = 0.231079 ms, mean = 0.126782 ms, median = 0.12793 ms, percentile(90%) = 0.129211 ms, percentile(95%) = 0.129395 ms, percentile(99%) = 0.129883 ms
[05/18/2023-09:51:21] [I] Total Host Walltime: 3.00709 s
[05/18/2023-09:51:21] [I] Total GPU Compute Time: 3.00214 s
[05/18/2023-09:51:21] [W] * GPU compute time is unstable, with coefficient of variance = 1.65542%.
[05/18/2023-09:51:21] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
[05/18/2023-09:51:21] [I] Explanations of the performance metrics are printed in the verbose logs.
[05/18/2023-09:51:21] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v8601] # trtexec --loadEngine=unet.plan --vc --useCudaGraph
```

**Comment by ttyio** [comment] 2023-07-11 16:39
@zerollzeng , do we have bug to track this? thanks!

**Comment by zerollzeng** [comment] 2023-07-13 07:06
Typo here, sorry:
I **cannot** reproduce it under Linux:

trtexec --onnx=unet.onnx --fp16 --vc --saveEngine=unet.plan
trtexec --loadEngine=unet.plan --vc --useCudaGraph
@oxana-nvidia Does it relate to Windows?

**Comment by mseagrief** [comment] 2023-07-13 14:13
I'll see if I can get a minimal reproduction working using Linux/python. I can't generate a failing engine directly using `trtexec` as it doesn't allow (I don't believe at any rate) for multiple optimisation profiles. With a single optimisation profile everything works.

**Comment by oxana-nvidia** [comment] 2023-07-13 15:40
@mseagrief Could you please clarify which profiles you are trying to use? based on the script it is `--minShapes=input:1x1x1x1 --optShapes=input:1x2x8x8 --maxShapes=input:1x9x12x16` which is not a valid profile as the model has input [-1,3,512,512]. 

Most recent (not yet public) version of TRT can run trtrexec with multiple profiles. I've tried following and it is working for me on linux. Also it is possible that the issue is fixed in most recent TRT.
```
[07/13/2023-08:24:19] [I] Finished parsing network model. Parse time: 0.182521
[07/13/2023-08:24:19] [I] Set shape of input tensor input for optimization profile 0 to: MIN=1x3x512x512 OPT=2x3x512x512 MAX=4x3x512x512
[07/13/2023-08:24:19] [I] Set shape of input tensor input for optimization profile 1 to: MIN=4x3x512x512 OPT=6x3x512x512 MAX=8x3x512x512
...
[07/13/2023-08:27:08] [I] Created engine with size: 74.9709 MiB
[07/13/2023-08:27:08] [I] Engine built in 177.23 sec.
...
[07/13/2023-08:27:09] [I] Created execution context with device memory size: 408 MiB
[07/13/2023-08:27:09] [I] Set shape of input tensor input to: 2x3x512x512
[07/13/2023-08:27:09] [I] Using random values for input input
[07/13/2023-08:27:09] [I] Input binding for input with dimensions 2x3x512x512 is created.
[07/13/2023-08:27:09] [I] Output binding for output with dimensions 2x3x512x512 is created.
[07/13/2023-08:27:09] [I] Starting inference
[07/13/2023-08:27:12] [I] Warmup completed 63 queries over 200 ms
[07/13/2023-08:27:12] [I] Timing trace has 1019 queries over 3.00794 s
...
[07/13/2023-08:27:12] [I] === Performance summary ===
[07/13/2023-08:27:12] [I] Throughput: 338.77 qps
[07/13/2023-08:27:12] [I] Latency: min = 3.93652 ms, max = 4.14297 ms, mean = 3.96713 ms, median = 3.96436 ms, percentile(90%) = 3.97253 ms, percentile(95%) = 3.97534 ms, percentile(99%) = 4.13104 ms
...
&&&& PASSED TensorRT.trtexec [TensorRT v9000] # ./trtexec --onnx=/home/okorzh/trt/Unet_mit_b1_512x512_[0].onnx --fp16 --vc --saveEngine=/tmp/unet.plan --profile=0 --minShapes=input:1x3x512x512 --optShapes=input:2x3x512x512 --maxShapes=input:4x3x512x512 --profile=1 --minShapes=input:4x3x512x512 --optShapes=input:6x3x512x512 --maxShapes=input:8x3x512x512
```

**Comment by mseagrief** [comment] 2023-07-14 11:45
The three profiles (using trtexec notation) would be:
```
--minShapes=input:1x3x512x512 --optShapes=input:1x3x512x512 --maxShapes=input:1x1x512x512
--minShapes=input:2x3x512x512 --optShapes=input:6x3x512x512 --maxShapes=input:8x1x512x512
--minShapes=input:9x3x512x512 --optShapes=input:12x3x512x512 --maxShapes=input:16x1x512x512
```

The input channels and dimensions are fixed it's just the number of batches that are varying. Using multiple profiles gave the best performance when we benchmarked the model.

**Comment by oxana-nvidia** [comment] 2023-07-14 18:01
With provided profiles also passing for me on linux with TRT Next. I'll try later with 8.6

```

[07/14/2023-08:48:47] [I] === Performance summary ===
[07/14/2023-08:48:47] [I] Throughput: 633.415 qps
[07/14/2023-08:48:47] [I] Latency: min = 2.05591 ms, max = 2.41992 ms, mean = 2.09182 ms, median = 2.08936 ms, percentile(90%) = 2.09863 ms, percentile(95%) = 2.10327 ms, percentile(99%) = 2.18445 ms
[07/14/2023-08:48:47] [I] Enqueue Time: min = 0.611084 ms, max = 1.46118 ms, mean = 1.14766 ms, median = 1.16843 ms, percentile(90%) = 1.25073 ms, percentile(95%) = 1.25781 ms, percentile(99%) = 1.27957 ms
[07/14/2023-08:48:47] [I] H2D Latency: min = 0.26709 ms, max = 0.298828 ms, mean = 0.271442 ms, median = 0.270752 ms, percentile(90%) = 0.273682 ms, percentile(95%) = 0.275757 ms, percentile(99%) = 0.282959 ms
[07/14/2023-08:48:47] [I] GPU Compute Time: min = 1.54614 ms, max = 1.90649 ms, mean = 1.57591 ms, median = 1.57388 ms, percentile(90%) = 1.58105 ms, percentile(95%) = 1.58496 ms, percentile(99%) = 1.66708 ms
[07/14/2023-08:48:47] [I] D2H Latency: min = 0.241211 ms, max = 0.261963 ms, mean = 0.244467 ms, median = 0.244141 ms, percentile(90%) = 0.24585 ms, percentile(95%) = 0.246216 ms, percentile(99%) = 0.252869 ms
[07/14/2023-08:48:47] [I] Total Host Walltime: 3.00593 s
[07/14/2023-08:48:47] [I] Total GPU Compute Time: 3.00054 s
[07/14/2023-08:48:47] [W] * GPU compute time is unstable, with coefficient of variance = 1.03521%.
[07/14/2023-08:48:47] [W]   If not already in use, locking GPU clock frequency or adding --useSpinWait may improve the stability.
[07/14/2023-08:48:47] [I] Explanations of the performance metrics are printed in the verbose logs.
[07/14/2023-08:48:47] [I]
&&&& PASSED TensorRT.trtexec [TensorRT v9000] # ./trtexec --onnx=/home/okorzh/trt/Unet_mit_b1_512x512_[0].onnx --fp16 --vc --saveEngine=/tmp/unet.plan --profile=0 --minShapes=input:1x3x512x512 --optShapes=input:1x3x512x512 --maxShapes=input:1x3x512x512 --profile=1 --minShapes=input:2x3x512x512 --optShapes=input:6x3x512x512 --maxShapes=input:8x3x512x512 --profile=2 --minShapes=input:9x3x512x512 --optShapes=input:12x3x512x512 --maxShapes=input:16x3x512x512
```

**Comment by tp-nan** [comment] 2023-09-04 08:41
I meet the same issue when i used ``swin_base_patch4_window7_224`` from timm with two profiles. The engine can be successfully genereted, but I'm unable to use the second profile.
tensorrt version: 8.6.1

**Comment by ttyio** [comment] 2024-05-07 18:38
closing since no activity for more than 3 weeks per our policy, thanks all!

**Closed by ttyio** 2024-05-07 18:38 UTC
Labels: triaged
