### ISSUE TITLE
coredump : value_info->operand()->is_tensor()

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT#2654] opened 2023-02-08 09:06 UTC
## Environment

**TensorRT Version**:  8.4.2.4
**NVIDIA GPU**:  T4
**NVIDIA Driver Version**: 510.47.03
**CUDA Version**:  11.7
**CUDNN Version**: 8.5.0
**Operating System**:  docker image : nvcr.io/nvidia/tensorrt:22.08-py3
**Python Version (if applicable)**:  3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Relevant Files

```
python3: /root/gpgpu/MachineLearning/myelin/src/compiler/kernel_gen/dag.cpp:1050: myelin::kgen::dag_t::schedule(myelin::ir::bb_t*) const::__lambda11: Assertion `value_info->operand()->is_tensor()' failed.
Aborted (core dumped)

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f0e17b29859 in __GI_abort () at abort.c:79
#2  0x00007f0e17b29729 in __assert_fail_base (fmt=0x7f0e17cbf588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f0cd9508038 "value_info->operand()->is_tensor()",
    file=0x7f0cd9507ca8 "/root/gpgpu/MachineLearning/myelin/src/compiler/kernel_gen/dag.cpp", line=1050, function=<optimized out>) at assert.c:92
#3  0x00007f0e17b3afd6 in __GI___assert_fail (assertion=0x7f0cd9508038 "value_info->operand()->is_tensor()", file=0x7f0cd9507ca8 "/root/gpgpu/MachineLearning/myelin/src/compiler/kernel_gen/dag.cpp", line=1050,
    function=0x7f0cd9899200 "myelin::kgen::dag_t::schedule(myelin::ir::bb_t*) const::__lambda11") at assert.c:101
#4  0x00007f0cd5b33708 in ?? () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.8
```

**Comment by zerollzeng** [comment] 2023-02-08 12:33
Can you try the latest release? if it still fails could you please share a reproduce or the onnx with us? Thanks!

**Comment by ttyio** [comment] 2023-03-14 02:57
closing since no activitity for more than 3 weeks, thanks!

**Closed by ttyio** 2023-03-14 02:57 UTC
Labels: triaged
