### ISSUE TITLE
PTQ quantization int8 engine is lower than fp16 engine

### ISSUE THREAD

**Issue by shuyuan-wang** [NVIDIA/TensorRT#2659] opened 2023-02-09 08:31 UTC
I'm trying to quantize yolox-l model and convert to int8. However, after I conver to int8 version onnx and conver to engine, fp16 is faster than int8 version. Can you take a look at my onnx? This onnx is generated by mmdeploy

onnx link:
https://drive.google.com/file/d/1Ro_LlkStZEDrsZIl8Ci45hWkaGbK1av_/view?usp=share_link

**Comment by zerollzeng** [comment] 2023-02-12 03:07
Met this error when try to reproduce the issue, the `TRTBatchedNMS` should be `BatchedNMS_TRT` or `BatchedNMSDynamic_TRT` according to https://github.com/NVIDIA/TensorRT/blob/b0c259a749aab1486ed3b4458e7176555b003497/plugin/batchedNMSPlugin/batchedNMSPlugin.cpp#L39. Can you provide a detailed reproduce?

```
[02/12/2023-03:01:26] [E] [TRT] parsers/onnx/ModelImporter.cpp:726: While parsing node number 1984 [TRTBatchedNMS -> "dets"]:
[02/12/2023-03:01:26] [E] [TRT] parsers/onnx/ModelImporter.cpp:727: --- Begin node ---
[02/12/2023-03:01:26] [E] [TRT] parsers/onnx/ModelImporter.cpp:728: input: "3400"
input: "3398"
output: "dets"
output: "labels"
name: "TRTBatchedNMS_1984"
op_type: "TRTBatchedNMS"
attribute {
  name: "background_label_id"
  i: -1
  type: INT
}
attribute {
  name: "clip_boxes"
  i: 0
  type: INT
}
attribute {
  name: "iou_threshold"
  f: 0.65
  type: FLOAT
}
attribute {
  name: "is_normalized"
  i: 0
  type: INT
}
attribute {
  name: "keep_topk"
  i: 100
  type: INT
}
attribute {
  name: "num_classes"
  i: 80
  type: INT
}
attribute {
  name: "return_index"
  i: 0
  type: INT
}
attribute {
  name: "score_threshold"
  f: 0.01
  type: FLOAT
}
attribute {
  name: "topk"
  i: 5000
  type: INT
}
domain: "mmdeploy"

[02/12/2023-03:01:26] [E] [TRT] parsers/onnx/ModelImporter.cpp:729: --- End node ---
[02/12/2023-03:01:26] [E] [TRT] parsers/onnx/ModelImporter.cpp:731: ERROR: parsers/onnx/builtin_op_importers.cpp:5409 In function importFallbackPluginImporter:
[8] Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
[02/12/2023-03:01:26] [E] Failed to parse onnx file
[02/12/2023-03:01:26] [I] Finish parsing network model
[02/12/2023-03:01:26] [E] Parsing model failed
[02/12/2023-03:01:26] [E] Failed to create engine from model or file.
[02/12/2023-03:01:26] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec [TensorRT v8501] # trtexec --onnx=yolox_l.onnx --int8 --verbose --profilingVerbosity=detailed --dumpLayerInfo --dumpProfile --separateProfileRun --noDataTransfers

```

**Comment by shuyuan-wang** [comment] 2023-02-13 09:35
Hi, can you try using this so file as plugin?:
https://drive.google.com/file/d/1gbPk7zg-NPF5twslQLzCy3B8cyOtS0nn/view?usp=share_link

**Comment by zerollzeng** [comment] 2023-02-15 12:23
Please provide the plugin source code, the so may not work on my env.

**Comment by ttyio** [comment] 2023-03-14 02:56
closing since no activitity for more than 3 weeks, thanks!

**Closed by ttyio** 2023-03-14 02:56 UTC
Labels: triaged
