### ISSUE TITLE
Can not Convert onnx to tensorrt with calibration on windows with tensorrt8.5.1?

### ISSUE THREAD

**Issue by monsterlyg** [NVIDIA/TensorRT#2538] opened 2022-12-09 11:23 UTC
## Environment

**TensorRT Version**:  8.5.1.7
**NVIDIA GPU**:  RTX3080
**NVIDIA Driver Version**:  512.95
**CUDA Version**:  11.4
**CUDNN Version**:  8.5.0
**Operating System**: win10
**Python Version (if applicable)**: 3.8
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**: 

## Steps To Reproduce

I used "trtexec" under Tensorrt8.5.1.7 from [here](https://developer.nvidia.com/compute/machine-learning/tensorrt/secure/8.5.1/zip/TensorRT-8.5.1.7.Windows10.x86_64.cuda-11.8.cudnn8.6.zip) to convert onnx to tensorrt file on windows10 with int8 calibration. It returned error like below:
<img width="920" alt="image" src="https://user-images.githubusercontent.com/40205682/206690706-271325f2-deff-4d2e-9eb0-8124c41185be.png">
But when i turned to linux, the onnx model could be converted to tensorrt model successfully. I have also tried with Tensorrt8.0.0.3, the same result is it worked on Linux but failed on Windows10. Another phenomenon is that when i dropped "--calib=xxx", it also succeeded on Windows. So there may be something wrong with int8 calibration on windows.

**Comment by monsterlyg** [comment] 2022-12-09 11:27
i can provide onnx and calibration file if necessary.

**Comment by zerollzeng** [comment] 2022-12-10 02:03
@oxana-nvidia did you see similar issues before? I'm not familiar with the Windows version. Thanks!

**Comment by zerollzeng** [comment] 2022-12-10 02:05
@oxana-nvidia I'm not familiar with Windows, can you kindly help here? thanks!

**Comment by oxana-nvidia** [comment] 2022-12-10 02:44
Hi @monsterlyg,
Could you please provide onnx and calibration file so we can test it internally?

**Comment by monsterlyg** [comment] 2022-12-11 11:52
> Hi @monsterlyg, Could you please provide onnx and calibration file so we can test it internally?
> 
> for options to try: may be you can consider to increase workspace?

https://drive.google.com/drive/folders/1gDxg65SaVLwrh3R1bB4HjI7IMPX1J1T9?usp=share_link

**Comment by monsterlyg** [comment] 2022-12-11 11:59
> Hi @monsterlyg, Could you please provide onnx and calibration file so we can test it internally?
> 
> for options to try: may be you can consider to increase workspace?

I have watched the memory occupied, which is under 4GB.

**Comment by oxana-nvidia** [comment] 2022-12-11 17:31
Thanks for providing data! 
I've created internal bug 3905480 to track the issue.

**Comment by oxana-nvidia** [comment] 2023-01-10 21:48
Hi @monsterlyg,
We are not able to reproduce the issue on our side. 
Could you please try if TensorRT 8.5.2 still has the issue on your side? 
Also one more suggestion from our engineers was to disable JIT_CONVOLUTIONS tactic source and see if it makes any difference.

**Comment by oxana-nvidia** [comment] 2023-01-21 03:52
closing this issue as no updates provided and on our side we can not reproduce it. Please reopen if the issue is still present.

**Closed by oxana-nvidia** 2023-01-21 03:52 UTC
Labels: triaged
