### ISSUE TITLE
Performance regression found in TensorRT 8.6.1 when running BERT on GPU T4

### ISSUE THREAD

**Issue by niuzheng168** [NVIDIA/TensorRT#3175] opened 2023-07-31 14:09 UTC
## Description

We are using TensorRT via Triton to inference a BERT classification model.
Our model is simply a BERT base + classifier.
Previous we are using TRT 8.5.2, at tail of trtexec, the log shows
`docker run --gpus=0 --rm -it --name test_trt -v /home/zhn:/home/zhn nvcr.io/nvidia/tensorrt:23.01-py3`

`trtexec --onnx=/home/zhn/triton/server/zhcn_v3/2052/1/TextAnalyzerV2.fp32.onnx --saveEngine=/home/zhn/triton/server/zhcn_v3/2052_trt/1/TextAnalyzerV2.t4.2301.trt --fp16 --memPoolSize=workspace:10000 --minShapes=input_ids:1x1,input_mask:1x1 --maxShapes=input_ids:1x512,input_mask:1x512 --optShapes=input_ids:1x64,input_mask:1x64 --device=0 --verbose`

`Average on 10 runs - GPU latency: 1.52078 ms - Host latency: 1.53953 ms (enqueue 1.5259 ms)`

But after we upgrade to TRT 8.6.1, at tail of trtexec, the log shows
`docker run --gpus=0 --rm -it --name test_trt -v /home/zhn:/home/zhn nvcr.io/nvidia/tensorrt:23.07-py3`

`trtexec --onnx=/home/zhn/triton/server/zhcn_v3/2052/1/TextAnalyzerV2.fp32.onnx --saveEngine=/home/zhn/triton/server/zhcn_v3/2052_trt/1/TextAnalyzerV2.t4.2307.trt --fp16 --memPoolSize=workspace:10000 --minShapes=input_ids:1x1,input_mask:1x1 --maxShapes=input_ids:1x512,input_mask:1x512 --optShapes=input_ids:1x64,input_mask:1x64 --device=0 --verbose --vc`

`Average on 10 runs - GPU latency: 4.13606 ms - Host latency: 4.15786 ms (enqueue 0.541821 ms)`

which shows alomost 3x latency regression, the source onnx model are same, do you know what happened?
Attached verbose log that come from trtexec

[TextAnalyzerV2.t4.2307.trt.log](https://github.com/NVIDIA/TensorRT/files/12215890/TextAnalyzerV2.t4.2307.trt.log)
[TextAnalyzerV2.t4.2301.trt.log](https://github.com/NVIDIA/TensorRT/files/12215891/TextAnalyzerV2.t4.2301.trt.log)

## Environment

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: T4

**NVIDIA Driver Version**: 525.105.17

**CUDA Version**: 12.0 

**CUDNN Version**:

Operating System: Ubuntu 20.04

Python Version (if applicable):

Tensorflow Version (if applicable):

PyTorch Version (if applicable):

Baremetal or Container (if so, version):

## Relevant Files

**Model link**:

## Steps To Reproduce

**Commands or scripts**:

**Have you tried [the latest release](https://developer.nvidia.com/tensorrt)?**: yes

**Can this model run on other frameworks?** For example run ONNX model with ONNXRuntime (`polygraphy run <model.onnx> --onnxrt`):

**Comment by cmstudyscode** [comment] 2023-08-01 08:41
same question，Have you solved it yet?

**Comment by niuzheng168** [comment] 2023-08-01 08:59
> same question，Have you solved it yet?

not yet.

**Comment by pranavm-nvidia** [comment] 2023-08-01 18:17
Can you try without the version compatibility option (`--vc`)?

**Comment by niuzheng168** [comment] 2023-08-02 02:32
> Can you try without the version compatibility option (`--vc`)?

tried and got same result. the perf regression still not mitigated.

**Comment by niuzheng168** [comment] 2023-08-02 04:49
@WeiHaocheng @pranavm-nvidia 
I have followed up the suggestion by @WeiHaocheng. If I removed the classifier, the latency go back to normal.
So I believe the classifier triggered some bug that caused the perf regression. @pranavm-nvidia  can you take a look?

**Comment by zerollzeng** [comment] 2023-08-03 03:48
@niuzheng168 Could you please provide a reproduce? Thanks!

**Comment by niuzheng168** [comment] 2023-08-03 08:09
> @niuzheng168 Could you please provide a reproduce? Thanks!

you can easily repro by a model with bert encoder + Linear + argmax:
https://drive.google.com/file/d/1oNxYzoL2qcY3u_ZiAEKi1CA7qxiLZsKY/view?usp=drive_link

repro steps:
1. start docker: docker run --gpus=0 --rm -it --name test_trt1 -v /home/zhn:/home/zhn [nvcr.io/nvidia/tensorrt:23.07-py3](http://nvcr.io/nvidia/tensorrt:23.07-py3)
2. run trt exec: trtexec --onnx=model.onnx --saveEngine=model.861.trt --fp16 --memPoolSize=workspace:10000 --minShapes=input_ids:1x1,input_mask:1x1 --maxShapes=input_ids:1x512,input_mask:1x512 --optShapes=input_ids:1x64,input_mask:1x64 --device=0

**Comment by zerollzeng** [comment] 2023-08-07 14:21
Thanks, I cannot find a T4 now, will check it later.

**Comment by zerollzeng** [comment] 2023-08-13 12:42
File internal bug 4239772 to track this. cc @nvpohanh

**Comment by zerollzeng** [comment] 2023-09-07 03:13
This bug has been fixed in 9.0.1.4, please download it from devzone. Thanks!

**Comment by zerollzeng** [comment] 2023-09-07 04:25
The bug has been fixed in 9.0GA

**Comment by ttyio** [comment] 2023-10-10 20:15
closing since 9.0 is released, thanks all!

**Closed by ttyio** 2023-10-10 20:15 UTC
Labels: triaged
