### ISSUE TITLE
Engine build failure (launch timeout)

### ISSUE THREAD

**Issue by itmo153277** [NVIDIA/TensorRT#2478] opened 2022-11-12 17:33 UTC
## Description

TensorRT 8.5.1.7.fails to build an engine for a model that works perfectly fine with 8.4.0.6.

<details>
<summary>Log</summary>

```
[11/12/2022-17:24:28] [TRT] [I] [MemUsageChange] Init CUDA: CPU +202, GPU +0, now: CPU 250, GPU 437 (MiB)
[11/12/2022-17:24:32] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +118, GPU +21, now: CPU 423, GPU 458 (MiB)
[11/12/2022-17:24:32] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage. See `CUDA_MODULE_LOADING` in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars
[11/12/2022-17:24:32] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +181, GPU +72, now: CPU 606, GPU 530 (MiB)
[11/12/2022-17:24:33] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +111, GPU +43, now: CPU 717, GPU 573 (MiB)
[11/12/2022-17:24:33] [TRT] [I] Local timing cache in use. Profiling results in this builder pass will not be stored.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] Caught cuda error during timing, format rejected.
[11/12/2022-17:24:54] [TRT] [W] GPU error during getBestTactic: ConstantFolding/final/full/preprocess/truediv_recip:0 + (Unnamed Layer* 1) [Shuffle] + final/full/preprocess/truediv : the launch timed out and was terminated
[11/12/2022-17:24:54] [TRT] [E] 1: [virtualMemoryBuffer.cpp::~StdVirtualMemoryBufferImpl::105] Error Code 1: Cuda Runtime (the launch timed out and was terminated)
[11/12/2022-17:24:54] [TRT] [E] 10: [optimizer.cpp::computeCosts::3728] Error Code 10: Internal Error (Could not find any implementation for node ConstantFolding/final/full/preprocess/truediv_recip:0 + (Unnamed Layer* 1) [Shuffle] + final/full/preprocess/truediv.)
[11/12/2022-17:24:54] [TRT] [E] 2: [builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
```
</details>

(basically it fails on the very first layer)

Please let me know if you need the model.

## Environment

**TensorRT Version**:  8.5
**NVIDIA GPU**:   GTX 960M (compute capability 5.0)
**NVIDIA Driver Version**:  526.86
**CUDA Version**: 11.8
**CUDNN Version**:  8.6.0
**Operating System**:  Windows 10 (19044.2251) WSL2 (10.0.19041.1566) + docker ubuntu 20.04
**Container**:  based on `nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04`

**Comment by itmo153277** [comment] 2022-11-13 06:02
After looking deeper into the issue, I found that kernel launch timeout is an unrecoverable CUDA error which is caused by GPU scheduler timeout. It happens during optimizations for `ConvTranspose`. All next CUDA calls fail because the error is unrecoverable.

Workaround:
If I disable WDDM TDR, the engine can be built successfully.

[trtexec.log](https://github.com/NVIDIA/TensorRT/files/9996560/trtexec.log)
[model-trt.zip](https://github.com/NVIDIA/TensorRT/files/9996561/model-trt.zip)

**Comment by zerollzeng** [comment] 2022-11-14 15:54
```
[11/14/2022-07:51:02] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +40, now: CPU 0, GPU 40 (MiB)
[11/14/2022-07:51:02] [I] Engine built in 50.3953 sec.
[11/14/2022-07:51:02] [I] [TRT] Loaded engine size: 40 MiB
[11/14/2022-07:51:02] [V] [TRT] Trying to load shared library libcudnn.so.8
[11/14/2022-07:51:02] [V] [TRT] Loaded shared library libcudnn.so.8
[11/14/2022-07:51:02] [V] [TRT] Using cuDNN as plugin tactic source
[11/14/2022-07:51:02] [V] [TRT] Using cuDNN as core library tactic source
[11/14/2022-07:51:02] [I] [TRT] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 1746, GPU 856 (MiB)
[11/14/2022-07:51:02] [V] [TRT] Deserialization required 15351 microseconds.
[11/14/2022-07:51:02] [I] [TRT] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +40, now: CPU 0, GPU 40 (MiB)
[11/14/2022-07:51:02] [I] Engine deserialized in 0.0156102 sec.
[11/14/2022-07:51:02] [I] Skipped inference phase since --buildOnly is added.
&&&& PASSED TensorRT.trtexec [TensorRT v8501] # trtexec --onnx=model-trt.onnx --verbose --buildOnly
```
I cannot reproduce it under Linux, TRT 8.5.1.7, RTX8000, it might be due to the old 960M GPU or the WSL, could you please test it under linux environment first? many thanks!

**Comment by itmo153277** [comment] 2022-11-15 15:10
@zerollzeng 
It works on linux although it appeared to be stuck for some time at the same point where it crashed on windows.

Windows (WSL):

```
[11/13/2022-05:26:56] [V] [TRT] --------------- Timing Runner: Optimizer Reformat(final/full/generator/conv_trans_2/BiasAdd:0 -> <out>) (Reformat)
[11/13/2022-05:26:57] [V] [TRT] Tactic: 0x00000000000003e8 Time: 97.0699
[11/13/2022-05:26:59] [W] [TRT] Caught cuda error during timing, format rejected.
```

Linux:

```
[11/15/2022-14:47:26] [V] [TRT] --------------- Timing Runner: Optimizer Reformat(final/full/generator/conv_trans_2/BiasAdd:0 -> <out>) (Reformat)
[11/15/2022-14:47:27] [V] [TRT] Tactic: 0x00000000000003e8 Time: 97.0001
[11/15/2022-14:47:47] [V] [TRT] Tactic: 0x00000000000003ea Time: 2597.11
[11/15/2022-14:47:48] [V] [TRT] Tactic: 0x0000000000000000 Time: 96.9788
[11/15/2022-14:47:48] [V] [TRT] Fastest Tactic: 0x0000000000000000 Time: 96.9788
```

This tactic seem to take a very long time and triggers WDDM TDR protection on Windows. This did not happen with TensorRT 8.4 (maybe the tactic was not present in the older versions?).

In the end I am not entirely sure who is at fault here: is it TensorRT which tries to launch a kernel too heavy for the GPU, or is it  the driver which becomes unresponsive during kernel launch and gets killed by WDDM TDR.

WDDM TDR had been mentioned in known issues for TensorRT 5, but I have never had such problems with TensorRT 7 and 8 until TensorRT 8.5. 

[tensorrt-linux.log](https://github.com/NVIDIA/TensorRT/files/10013648/tensorrt-linux.log)

**Comment by zerollzeng** [comment] 2022-11-16 15:20
@oxana-nvidia @nvpohanh @pranavm-nvidia  Do you have any suggestions?  I know little about Windows.

**Comment by oxana-nvidia** [comment] 2022-11-16 17:26
I've created an internal ticket to investigate the issue: 3872585

@itmo153277 Please try to use Algorithm Selector as a WAR to disable that tactic.

**Comment by ttyio** [comment] 2023-03-01 08:50
Sorry we need close this since maxwell support is droped.

**Closed by ttyio** 2023-03-01 08:50 UTC
Labels: triaged
