### ISSUE TITLE
Stalling/memory-leak failure of TensorRT 8.6.1 when running tensorrt.Builder.build_serialized_network on GPU NVIDIA GeForce RTX 3060

### ISSUE THREAD

**Issue by dspyz-matician** [NVIDIA/TensorRT#3729] opened 2024-03-21 20:49 UTC
## Description

Creating a saved tensorrt engine from my simple onnx model eventually (multiple hours) uses up all the memory on my 64g machine. Code is below, onnx file is attached:

```
import torch
import torch.nn as nn
import torch.onnx

MAX_TRAV = 21


class Traversability(nn.Module):
    def forward(self, untraversable: torch.Tensor) -> torch.Tensor:
        device = untraversable.device
        sq_distances = torch.where(untraversable > 0, 0, MAX_TRAV**2)
        extra_col = torch.full((sq_distances.shape[0], 1), MAX_TRAV**2, device=device)
        for d in range(1, MAX_TRAV * 2 + 1, 2):
            sq_distances = torch.minimum(
                sq_distances,
                torch.minimum(
                    torch.cat([sq_distances[:, 1:] + d, extra_col], 1),
                    torch.cat([extra_col, sq_distances[:, :-1] + d], 1),
                ),
            )
        extra_row = torch.full((1, sq_distances.shape[1]), MAX_TRAV**2, device=device)
        for d in range(1, MAX_TRAV * 2 + 1, 2):
            sq_distances = torch.minimum(
                sq_distances,
                torch.minimum(
                    torch.cat([sq_distances[1:, :] + d, extra_row], 0),
                    torch.cat([extra_row, sq_distances[:-1, :] + d], 0),
                ),
            )
        return sq_distances.sqrt()
```

## Environment

**TensorRT Version**: 8.6.1

**NVIDIA GPU**: NVIDIA GeForce RTX 3060

**NVIDIA Driver Version**: 550.54.14

**CUDA Version**: 12.4

**CUDNN Version**: 8.9.7

Operating System: Debian 11

Python Version (if applicable): 3.9.2

PyTorch Version (if applicable): 2.2.1+cu121

## Relevant Files

**Model link**:

[traversability.zip](https://github.com/NVIDIA/TensorRT/files/14707037/traversability.zip)

## Steps To Reproduce

**Commands or scripts**:

Generating the onnx model:
```
    # Set the model to evaluation mode
    model.eval()

    # Define the input shape
    dummy_input = torch.randint(0, 2, (224, 224), dtype=torch.bool)

    # Specify the output file path
    onnx_file_path = "traversability.onnx"

    # Convert the model to ONNX format
    torch.onnx.export(
        model,
        dummy_input,
        onnx_file_path,
        input_names=["input"],
        output_names=["output"],
    )
```

Converting the onnx model:
```
import tensorrt as trt

# Create a TensorRT logger
logger = trt.Logger(trt.Logger.WARNING)

# Create a TensorRT builder
builder = trt.Builder(logger)

# Create a network
network = builder.create_network(
    1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
)

# Parse the ONNX model
parser = trt.OnnxParser(network, logger)
parser.parse_from_file("traversability.onnx")

success = parser.parse_from_file("traversability.onnx")
if not success:
    print("Failed to parse the ONNX model.")
    exit(1)

# Configure the builder
config = builder.create_builder_config()
config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, 1 << 30)  # Adjust the workspace size as needed
config.set_flag(trt.BuilderFlag.FP16)  # Enable FP16 precision if desired

# Create an engine
engine = builder.build_serialized_network(network, config)
```

**Can this model run on other frameworks?**:

If I remove the `> 0` and change it to `torch.where(untraversable, ...)` it works, but it still takes like 10 minutes and 1.5 gigs to compile

**Comment by lix19937** [comment] 2024-03-23 01:33
You can see which modules are causing the most time consumption by trtexec layer info profile, two `for loop` maybe need improve.

**Comment by zerollzeng** [comment] 2024-03-23 07:59
Please fix #3728 first.

**Comment by zerollzeng** [comment] 2024-03-23 08:10
@lix19937 I saw you name in several issues and BIG THANKS for helping other users :-)

Looks like you are working in Bilibili now, if you are interested in any position in Nvidia, I can do a little favor :-)

**Comment by lix19937** [comment] 2024-03-23 09:30
@zerollzeng  Thanks a lot. NV is a great and nice company, maybe i need to improve myself even more, if I am ready, i think i will contact you in the future. Thanks again !

**Comment by dspyz-matician** [comment] 2024-04-03 23:42
@zerollzeng Sorry for the late reply. I realize the code is similar, but I think this issue is unrelated to #3278

It's an entirely separate bug I hit while shotgunning through trying to get something that works. Could you please take another look?

**Comment by zerollzeng** [comment] 2024-04-06 17:08
@dspyz-matician the model in [traversability.zip](https://github.com/NVIDIA/TensorRT/files/14707037/traversability.zip) is not a valid onnx model, could you please fix this first?
```
$ polygraphy run traversability.onnx --onnxrt
[I] RUNNING | Command: /home/scratch.zeroz_sw/miniconda3/bin/polygraphy run traversability.onnx --onnxrt
[I] onnxrt-runner-N0-04/06/24-17:06:54  | Activating and starting inference
[I] Creating ONNX-Runtime Inference Session with providers: ['CPUExecutionProvider']
Traceback (most recent call last):
  File "/home/scratch.zeroz_sw/miniconda3/bin/polygraphy", line 8, in <module>
    sys.exit(main())
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/_main.py", line 70, in main
    status = selected_tool.run(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/base/tool.py", line 171, in run
    status = self.run_impl(args)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/tools/run/run.py", line 226, in run_impl
    exec(str(script))
  File "<string>", line 21, in <module>
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 211, in run
    run_results.append((runner.name, execute_runner(runner, loader_cache)))
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/comparator/comparator.py", line 96, in execute_runner
    with runner as active_runner:
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/base/runner.py", line 62, in __enter__
    self.activate()
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/base/runner.py", line 97, in activate
    self.activate_impl()
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/onnxrt/runner.py", line 43, in activate_impl
    self.sess, _ = util.invoke_if_callable(self._sess)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/util/util.py", line 678, in invoke_if_callable
    ret = func(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/base/loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/util/util.py", line 710, in wrapped
    return func(*args, **kwargs)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/polygraphy/backend/onnxrt/loader.py", line 68, in call_impl
    return onnxrt.InferenceSession(model_bytes, providers=providers)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/scratch.zeroz_sw/miniconda3/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 472, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /home/scratch.zeroz_sw/github_bug/3729/traversability.onnx failed:Type Error: Type parameter (T) of Optype (Where) bound to different types (tensor(int64) and tensor(int32) in node (/Where).
```

**Comment by zerollzeng** [comment] 2024-04-06 17:09
Ask this because I try to reproduce the issue on TRT 10, but now it fails when parsing, so I double-check with onnxruntime.

**Comment by zerollzeng** [comment] 2024-04-06 17:10
please provide a new model for you issue. Looks like you've fix it according to https://github.com/NVIDIA/TensorRT/issues/3728#issuecomment-2037635392

**Comment by dspyz-matician** [comment] 2024-04-08 14:54
Yeah, somehow I mixed up the models. Sorry about that. But the PyTorch code I gave to reproduce the issue is correct. Here it is again. This is a zip file. You have to unzip it (`unzip zipped_model.zip`). GitHub doesn't allow uploading raw onnx models so I zipped it into a zip file: 
[zipped_model.zip](https://github.com/NVIDIA/TensorRT/files/14907177/zipped_model.zip)

**Comment by dspyz-matician** [comment] 2024-04-08 14:58
Yeah, somehow I mixed up the models. Sorry about that. I've fixed the PyTorch code. Here it is again. This is a zip file. You have to unzip it (`unzip zipped_model.zip`). GitHub doesn't allow uploading raw onnx models so I zipped it into a zip file: 
[zipped_model.zip](https://github.com/NVIDIA/TensorRT/files/14907232/zipped_model.zip)

**Comment by zerollzeng** [comment] 2024-04-13 01:58
I can repro the issue and filed internal bug 4601836 to track.

**Comment by akhilg-nv** [comment] 2024-08-30 20:56
The bug has been fixed and should be included in the latest minor release. Closing this issue.

**Closed by akhilg-nv** 2024-08-30 20:56 UTC
Labels: triaged, internal-bug-tracked
