### ISSUE TITLE
[08/18/2019-20:58:10] [E] [TRT] UffParser: Validator error: mrcnn_mask_deconv/add_1: Unsupported operation _AddV2 &&&& FAILED TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN -d 

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/TensorRT#125] opened 2019-09-18 12:58 UTC
```
[08/18/2019-20:58:10] [E] [TRT] UffParser: Validator error: mrcnn_mask_deconv/add_1: Unsupported operation _AddV2
&&&& FAILED TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN -d ~/data
```

ubuntu16.04
TensorRT 6.x (build source from git branch release/6.0)
following tutorial converts matterport maskrcnn model successfully to uff, inference got this result.

**Comment by xiaoniu1235** [comment] 2019-09-19 08:34
Running up, I got the error：
[08/19/2019-16:29:24] [I] Building and running a GPU inference engine for Mask RCNN
[08/19/2019-16:29:34] [E] [TRT] UffParser: Validator error: fpn_p3upsampled: Unsupported operation _ResizeNearest_TRT

windows 10
TensorRT 6.x zip install

**Comment by jinfagang** [comment] 2019-09-19 08:37
Well, why so many errors

**Comment by xiaoniu1235** [comment] 2019-09-19 10:14
可能是新代码，所以bug比较多。
而且有个比较恶心的bug，因为修改了mask rcnn代码，使用修改后的代码训练，会出错！
只能是用原mask rcnn训练，然后用修改后的代码转模型文件格式。

**Comment by jinfagang** [comment] 2019-09-19 13:29
先别想着训练了，能跑通实例就不错了。。。。。

don't think about training.... thanks to God if they can even run....

**Comment by Tyler-D** [comment] 2019-09-20 08:47
> Running up, I got the error：
> [08/19/2019-16:29:24] [I] Building and running a GPU inference engine for Mask RCNN
> [08/19/2019-16:29:34] [E] [TRT] UffParser: Validator error: fpn_p3upsampled: Unsupported operation _ResizeNearest_TRT
> 
> windows 10
> TensorRT 6.x zip install

Hi @xiaoniu1235 , Can you check if your excution program linked to the correct plugin library ?

**Comment by Tyler-D** [comment] 2019-09-20 08:48
> ```
> [08/18/2019-20:58:10] [E] [TRT] UffParser: Validator error: mrcnn_mask_deconv/add_1: Unsupported operation _AddV2
> &&&& FAILED TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN -d ~/data
> ```
> 
> ubuntu16.04
> TensorRT 6.x (build source from git branch release/6.0)
> following tutorial converts matterport maskrcnn model successfully to uff, inference got this result.

@jinfagang What's the version of your tensorflow when you do the conversion?

**Comment by xiaoniu1235** [comment] 2019-09-21 01:05
> > Running up, I got the error：
> > [08/19/2019-16:29:24] [I] Building and running a GPU inference engine for Mask RCNN
> > [08/19/2019-16:29:34] [E] [TRT] UffParser: Validator error: fpn_p3upsampled: Unsupported operation _ResizeNearest_TRT
> > windows 10
> > TensorRT 6.x zip install
> 
> Hi @xiaoniu1235 , Can you check if your excution program linked to the correct plugin library ?

Sorry,i can't generate a build system for CMake, so i use tensorrt zip! windows 10.
I copied the build runtime environment for sampleFasterRCNN, but I didn't see the use of plugin in sampleUffMaskRCNN.cpp and mrcnn_config.h.

**Comment by Tyler-D** [comment] 2019-09-21 01:14
@xiaoniu1235 , So that's the point. UffMaskRCNN uses some plugin layers provided in this repo including this `_ResizeNearest_TRT` in your error msg.

**Comment by jinfagang** [comment] 2019-09-21 01:34
What does this error mean:  ` mrcnn_mask_deconv/add_1: Unsupported operation _AddV2`?

**Comment by xiaoniu1235** [comment] 2019-09-21 01:38
@Tyler-D 
I tracked the code and the parse mrcnn_nchw.uff file went wrong!
Parser is created using nvuffparser::createUffParser(), it seems that there is no plugin, compare the sampleFasterRCNN.cpp code

sampleUffMaskRCNN.cpp
	auto parser = SampleUniquePtr<nvuffparser::IUffParser>(nvuffparser::createUffParser());
	if (!parser)
    {
        return false;
    }

    auto constructed = constructNetwork(builder, network, parser);
    if (!constructed)
    {
        return false;
    }
	...
	
sampleFasterRCNN.cpp
	auto parser = SampleUniquePtr<nvcaffeparser1::ICaffeParser>(nvcaffeparser1::createCaffeParser());
    if (!parser)
    {
        return false;
    }

    FRCNNPluginFactory pluginFactory;
    parser->setPluginFactoryV2(&pluginFactory);
    constructNetwork(parser, builder, network, config);
	
sampleFasterRCNN can clearly see the call of plugin, but sampleUffMaskRCNN I did not find the corresponding code, is I wrong?

**Comment by Tyler-D** [comment] 2019-09-21 01:48
@jinfagang No operation called "AddV2" supported in TensorRT. https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html You can check the supported layers here. I noticed tensoflow has updated to 1.15 recently. So it is possible it adds some computation nodes that TensorRT uff cannot handle right now. You may downgrade to 1.14 and I guess this node will become "Add" and compatible with UFF parser.

**Comment by Tyler-D** [comment] 2019-09-21 01:59
@xiaoniu1235 The schema to use plugin layer has changed a little with version updating.  Now we use https://github.com/NVIDIA/TensorRT/blob/07ed9b57b1ff7c24664388e5564b17f7ce2873e5/samples/opensource/sampleUffMaskRCNN/sampleUffMaskRCNN.cpp#L352 instead of plugin factory to initialize plugin layers.

**Comment by jinfagang** [comment] 2019-09-21 07:40
@Tyler-D  I installed tensorflow 1.14 build from source. And I traced uff model succesffuly.
How Nvidia can traced a model with unsupported node name? Haven't they check available nodes like ONNX converts does? I don't think this is an tensorflow version issue here. Maybe it's uff version issue? I simply install uff from TensorRT6.0 tar file.

**Comment by guods** [comment] 2019-09-27 07:01
@xiaoniu1235 Did you build the TensorRT6 succesffuly ? I meet the problems when I build, such as RT_LIB_NOTFOUND and uff , I don't know what is the RT_LIB; Nvidia don't open uff code, do you know the complied binaries about UFF ?

**Comment by dssdyx** [comment] 2019-10-07 08:56
> @Tyler-D I installed tensorflow 1.14 build from source. And I traced uff model succesffuly.
> How Nvidia can traced a model with unsupported node name? Haven't they check available nodes like ONNX converts does? I don't think this is an tensorflow version issue here. Maybe it's uff version issue? I simply install uff from TensorRT6.0 tar file.
Have you solved this problem?

**Comment by dssdyx** [comment] 2019-10-07 15:09
> @jinfagang No operation called "AddV2" supported in TensorRT. https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html You can check the supported layers here. I noticed tensoflow has updated to 1.15 recently. So it is possible it adds some computation nodes that TensorRT uff cannot handle right now. You may downgrade to 1.14 and I guess this node will become "Add" and compatible with UFF parser.

Maybe you are right. I use tf1.15.0-rc2 there are some ops changed from Add to AddV2

**Comment by dssdyx** [comment] 2019-10-08 01:30
> @Tyler-D I installed tensorflow 1.14 build from source. And I traced uff model succesffuly.
> How Nvidia can traced a model with unsupported node name? Haven't they check available nodes like ONNX converts does? I don't think this is an tensorflow version issue here. Maybe it's uff version issue? I simply install uff from TensorRT6.0 tar file.

I use tf1.9 now and the problem with AddV2 disappears, so I think it's version conflict. But now when I run sample_uff_maskRCNN, it shows that "[E] [TRT] UffParser: Validator error: mrcnn_detection_bboxes: Unsupported operation _SpecialSlice_TRT" which I think it's because that the plugins were not correctly installed. I plan to rewrite relative plugins like these are released in TensorRT6.0.1.

**Comment by jinfagang** [comment] 2019-10-08 03:37
@dssdyx Or maybe tf1.9 to low

**Comment by dssdyx** [comment] 2019-10-08 03:51
@jinfagang Yes, you can also try other versions.

**Comment by dssdyx** [comment] 2019-10-09 01:04
@jinfagang  the performance is 350ms/frame in 1050Ti

**Comment by jinfagang** [comment] 2019-10-09 02:20
@dssdyx  That is too slow. 2.8 fps..

Can u have a test on GTX1080ti or RTX2080ti? Would that able up to 20 fps?

**Comment by dssdyx** [comment] 2019-10-10 01:18
@jinfagang I don't have better device.

**Comment by guods** [comment] 2019-10-11 07:41
“mrcnn_mask_deconv/add_1: Unsupported operation _AddV2”，did you solved the preblem?

**Comment by guods** [comment] 2019-10-11 07:42
“mrcnn_mask_deconv/add_1: Unsupported operation _AddV2”，did you solved the preblem?

**Comment by dssdyx** [comment] 2019-10-11 11:22
> “mrcnn_mask_deconv/add_1: Unsupported operation _AddV2”，did you solved the preblem?

Install lower verison tf such as tf1.9

**Comment by jinfagang** [comment] 2019-10-11 12:05
@dssdyx Would u like share a uff to test on more decent gpus for the performance checking? I am currently only have tensorflow 2.0 with cuda10.1 installed.

**Comment by rtrobin** [comment] 2019-10-14 12:50
> @xiaoniu1235 , So that's the point. UffMaskRCNN uses some plugin layers provided in this repo including this `_ResizeNearest_TRT` in your error msg.

Hi @xiaoniu1235 . I'm facing a similar problem here. I found the plugin layers needed for MaskRCNN were provided in this repo, plugin sub-folder. Do you have any idea how to link the custom plugins in this repo to the MaskRCNN sample?

**Comment by dssdyx** [comment] 2019-10-16 09:31
> @dssdyx Would u like share a uff to test on more decent gpus for the performance checking? I am currently only have tensorflow 2.0 with cuda10.1 installed.

I don't think it will work in your env.

**Comment by gemmit** [comment] 2019-10-30 12:11
@dssdyx Did it work for you only by reinstalling a different version of TensorFlow or did you do further changes?

**Comment by gemmit** [comment] 2019-10-31 15:05
> @dssdyx Did it work for you only by reinstalling a different version of TensorFlow or did you do further changes?

Works for me now. I am able to convert the model and also run the maskrcnn example.
Thanks

**Comment by rmccorm4** [comment] 2019-10-31 16:00
Just sharing this here for visibility - @gemmit was able to run the sample with the following configuration:

```
TensorRT: 6.0.1.5
CUDA: 9.0
CuDNN: 7.6.3
python: 3.6.5
Tensorflow-gpu==1.9.0
Keras: 2.1.3

I was able to convert the model using uff-converter and run the mask-rcnn example as mentioned here

Thanks
```

If anyone is able to run it successfully with a more recent version of `tensorflow-gpu`, please share your full environment configuration so others can get it working as well!

**Closed** 2019-10-31 16:00 UTC
Labels: UFF, sample, unsupported-op

**Comment by doomb007** [comment] 2019-11-12 06:35
> ```
> [08/18/2019-20:58:10] [E] [TRT] UffParser: Validator error: mrcnn_mask_deconv/add_1: Unsupported operation _AddV2
> &&&& FAILED TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN -d ~/data
> ```
> 
> ubuntu16.04
> TensorRT 6.x (build source from git branch release/6.0)
> following tutorial converts matterport maskrcnn model successfully to uff, inference got this result.

Hi @jinfagang, I have the same problem as you now. 

If the command '**./sample_uff_maskRCNN**' was used, the terminal display:
&&&& RUNNING TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN
[10/12/2019-14:16:43] [I] Building and running a GPU inference engine for Mask RCNN
[10/12/2019-14:16:43] [E] [TRT] UffParser: Validator error: mrcnn_mask_deconv/add_1: Unsupported operation _AddV2
&&&& FAILED TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN

And if the command '**sudo ./sample_uff_maskRCNN**' was used, the terminal display: 
./sample_uff_maskRCNN: error while loading shared libraries: libnvparsers.so.6: cannot open shared object file: No such file or directory

The strange thing is that: the scripts **./sample_googlenet** and **./sample_uff_mnist** can run successfully, which proves that my software environment should be suitable.

Is your problem solved? Can you share your experience? thank you.

**Comment by rmccorm4** [comment] 2019-11-12 06:42
The `error while loading shared libraries: libnvparsers.so.6: cannot open shared object file: No such file or directory` error when running with `sudo` is somewhat expected, because when you run as `sudo`, your environment variables are not the same as your regular user. So things like `LD_LIBRARY*` won't be set correctly. I think that can be fixed with the `-E` or `--preserve-env` flag, although I don't think you need to be running the command with `sudo`.

I'm starting to get confused about that AddV2, error. I was messing around with this a week or two ago, and confirmed for myself that this only happened with `tensorflow >= 1.15`. So if you're using `tensorflow <= 1.14`, you shouldn't get this error. Is this not true for you? Can you share the output of `pip freeze` from the environment you're getting this error in?

**Comment by jinfagang** [comment] 2019-11-12 07:06
@rmccorm4  Yeah, Nvidia guys written a bounch of steps but not specific exactly version of tensorflow they were using and assuming all tensorflow under 1.19 were same behavior, obviously this is not tensorflow style, it always changes a lot ....

**Comment by doomb007** [comment] 2019-11-12 07:46
@rmccorm4 

1. Got it!

2. Actually, I'm using Tensorflow-gpu1.14.0 at the moment(Before that, I used Tensorflow-gpu1.15.0 and Tensorflow-gpu2.0.0), don't know what I missed. the output of `pip freeze`  is  as follow:

absl-py==0.8.1
 #alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.3
asn1crypto==0.24.0
astor==0.8.0
astroid==2.2.5
astropy==3.2.1
atomicwrites==1.3.0
   ###attrs==19.1.0
Babel==2.7.0
backcall==0.1.0
backports.functools-lru-cache==1.5
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.7.1
bitarray==0.9.3
bkcharts==0.2
bleach==3.1.0
bokeh==1.2.0
boto==2.49.0
Bottleneck==1.2.1
cachetools==3.1.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloudpickle==1.2.1
clyent==1.2.2
colorama==0.4.1
conda==4.7.12
conda-build==3.18.8
conda-package-handling==1.3.11
conda-verify==3.4.2
contextlib2==0.5.5
cryptography==2.7
cycler==0.10.0
Cython==0.29.12
cytoolz==0.10.0
dask==2.1.0
decorator==4.4.0
defusedxml==0.6.0
distributed==2.1.0
docutils==0.14
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
Flask==1.1.1
future==0.17.1
gast==0.2.2
gevent==1.4.0
glob2==0.7
gmpy2==2.0.8
google-auth==1.6.3
google-auth-oauthlib==0.4.1
google-pasta==0.1.7
graphsurgeon==0.4.1
greenlet==0.4.15
grpcio==1.24.3
h5py==2.9.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.8
imageio==2.5.0
imagesize==1.1.0
importlib-metadata==0.17
ipykernel==5.1.1
ipython==7.6.1
ipython-genutils==0.2.0
ipywidgets==7.5.0
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.13.3
jeepney==0.4
Jinja2==2.10.1
joblib==0.13.2
json5==0.8.4
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
jupyterlab==1.0.2
jupyterlab-server==1.0.0
Keras==2.1.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==18.0.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.1
libarchive-c==2.8
lief==0.9.0
llvmlite==0.29.0
locket==0.2.0
lxml==4.3.4
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.0
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
more-itertools==7.0.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
navigator-updater==0.2.1
nbconvert==5.5.0
nbformat==4.4.0
networkx==2.3
nltk==3.4.4
nose==1.3.7
notebook==6.0.0
numba==0.44.1
numexpr==2.6.9
numpy==1.16.4
numpydoc==0.9.1
oauthlib==3.1.0
olefile==0.46
openpyxl==2.6.2
opt-einsum==3.1.0
packaging==19.0
pandas==0.24.2
pandocfilters==1.4.2
parso==0.5.0
partd==1.0.0
path.py==12.0.1
pathlib2==2.3.4
patsy==0.5.1
pep8==1.7.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pkginfo==1.5.0.1
pluggy==0.12.0
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==2.0.9
protobuf==3.10.0
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.7
pyasn1-modules==0.2.7
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.3
pyflakes==2.1.1
Pygments==2.4.2
pylint==2.3.1
pyodbc==4.0.26
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyrsistent==0.14.11
PySocks==1.7.0
pytest==5.0.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.3.0
pytest-openfiles==0.3.2
pytest-remotedata==0.3.1
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1.1
pyzmq==18.0.0
QtAwesome==0.5.7
qtconsole==4.5.1
QtPy==1.8.0
requests==2.22.0
requests-oauthlib==1.2.0
rope==0.14.0
rsa==4.0
ruamel-yaml==0.15.46
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.3.0
seaborn==0.9.0
SecretStorage==3.1.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==1.9.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.8
Sphinx==2.1.2
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.2
spyder==3.3.6
spyder-kernels==0.5.1
SQLAlchemy==1.3.5
statsmodels==0.10.0
sympy==1.4
tables==3.5.2
tblib==1.4.0
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
tensorrt==6.0.1.5
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
toolz==0.10.0
tornado==6.0.3
tqdm==4.32.1
traitlets==4.3.2
uff==0.6.5
unicodecsv==0.14.1
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.4
widgetsnbextension==3.5.0
wrapt==1.11.2
wurlitzer==1.0.2
xlrd==1.2.0
XlsxWriter==1.1.8
xlwt==1.3.0
zict==1.0.0
zipp==0.5.1

**Comment by doomb007** [comment] 2019-11-13 01:55
@rmccorm4 @jinfagang 

I think this error **UffParser: Validator error: mrcnn_mask_deconv/add_1: Unsupported operation _AddV2** caused by wrong uff model **mrcnn_nchw.uff**. because my uff model was generated in the environment: TensorRT6.0+CUDA10.0+cuDNN7.6.3+Tensorflow1.15.0, It seems that the tensorflow1.15.0 is not suitable here.

After I regenerate the model ' **mrcnn_nchw.uff** ' use the script ' **mrcnn_to_trt_single.py** ' in the environment:TensorRT6.0+CUDA10.0+cuDNN7.6.3+Tensorflow1.14.0, and run `./sample_uff_maskRCNN`, this error disappeared. 

But another error has occurred: ' **[10/13/2019-09:20:08] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)** '.

**Comment by rmccorm4** [comment] 2019-11-13 02:15
You can watch your memory usage in a separate shell with something like: `watch -n 0.5 nvidia-smi`

I'm pretty sure I ran this sample in my earlier posts on an 8GB P4 GPU, so I think 8GB should be enough memory for this. Make sure you don't have other processes using up too much GPU memory.

**Comment by jinfagang** [comment] 2019-11-13 03:04
@doomb007 OK, seems tensorflow 1.14 needed here. You can have another test on a bigger memory GPU or shrink down batchsize, if you succeed, remember post some speed test (fps) here, I assume it can achieve 20 fps on GTX1080TI. If not, then too slow.

**Comment by doomb007** [comment] 2019-11-13 03:49
@rmccorm4 

I ran the sample on my personal computer, with a 2GB GPU(MX250), This may be the root of the error, I will try the sample on a workstation.

**Comment by rtrobin** [comment] 2019-11-13 03:51
@doomb007 try fp16 mode.

**Comment by doomb007** [comment] 2019-11-13 03:53
@jinfagang, OK

**Comment by doomb007** [comment] 2019-11-13 03:57
@rtrobin thanks for your advice.

when run the command `./sample_uff_maskRCNN --fp16`, the terminal display:

&&&& RUNNING TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN --fp16
[10/13/2019-11:52:11] [I] Building and running a GPU inference engine for Mask RCNN
[10/13/2019-11:52:14] [W] [TRT] Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
[10/13/2019-11:52:15] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
[10/13/2019-11:52:15] [E] [TRT] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)
&&&& FAILED TensorRT.sample_maskrcnn # ./sample_uff_maskRCNN --fp16

**Comment by rmccorm4** [comment] 2019-11-13 19:20
Hi @doomb007,

I'd be surprised if you'd be able to run any substantial workflow on a 2GB GPU, other than something like MNIST, even with `--fp16`.

Also, FYI:

> [10/13/2019-11:52:14] [W] [TRT] Half2 support requested on hardware without native FP16 support, performance will be negatively affected.

Only certain hardware platforms support FP16 acceleration, see the support matrix here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-support-matrix/index.html#hardware-precision-matrix

**Comment by doomb007** [comment] 2019-11-14 03:28
@rmccorm4 
 
OK, Will share details after ran the sample on my workstation, Thank you!

**Comment by hwh-hit** [comment] 2019-11-14 07:33
keras=2.1.3
tensorflow-gpu=1.12
I can convert h5 to uff successfully, but when i run 
make -j$(nproc)
in build folder,some error occurs:
TensorRT/samples/common/sampleDevice.h:79:60: error: ‘cudaLaunchHostFunc’ was not declared in this scope
         cudaCheck(cudaLaunchHostFunc(mStream, cudaSleep, ms));
but the error doen't matter maybe, because bin (sample_uff_maskRCNN) already generated successfully,
Speed:
1024x1024x3,1080gpu:98ms
512x512x3, 1080gpu : 46.1008ms

if someone can help me resolove the problem, that's would be great

**Comment by hwh-hit** [comment] 2019-11-14 07:35
forget to say that:
cuda 9.0 + cudnn 7.6.4

**Comment by doomb007** [comment] 2019-11-15 01:38
Hi @hwh-hit 

I have not encountered a similar situation as you. You can even run the program, this error should not matter. And you'd better consult **rmccorm4** if you want more professional advice.

**Comment by rmccorm4** [comment] 2019-11-15 01:50
The above issue is being tracked here: https://github.com/NVIDIA/TensorRT/issues/221

**Comment by doomb007** [comment] 2019-11-29 04:09
Hi @rmccorm4 

I can run the MaskRCNN sample on a workstation with a 1080Ti GPU now. yes, the performance of 2G GPU is not enough to run the sample. I will test the speed of MaskRCNN inference next step.

**Comment by sugger23** [comment] 2020-04-23 02:06
Hi @rmccorm4
I want to run this sample on windows10,  I have got the h5touff  file successfully,  when I run the  MaskRCNN sample ,some errors occurred,such as:
UffParser: Validator error: fpn_p3upsampled: Unsupported operation _ResizeNearest_TRT

then, I add the _ResizeNearest, SpecialSlice, PyramidROIAlign,ProposalLayer,DetectionLayer  plugins,
the code is here:
        initializePlugin<nvinfer1::plugin::DetectionLayerPluginCreator>(&gLogger.getTRTLogger(), "");
	initializePlugin<nvinfer1::plugin::ProposalLayerPluginCreator>(&gLogger.getTRTLogger(), "");
	initializePlugin<nvinfer1::plugin::PyramidROIAlignPluginCreator>(&gLogger.getTRTLogger(), "");
	initializePlugin<nvinfer1::plugin::ResizeNearestPluginCreator>(&gLogger.getTRTLogger(), "");
	initializePlugin<nvinfer1::plugin::SpecialSlicePluginCreator>(&gLogger.getTRTLogger(), "");

then I run the sample again,  the errors "Unsupported operation"  disappeared,  bug, when ,it run  function:parser->parse,  the program Downtime，and no any prompt,  can you give me some idea?
and can this sample run on window10?

**Comment by Apsu95** [comment] 2020-06-04 07:41
Hello all,

I successfully converted my model to UFF.

When I run the sample, I have this error:

&&&& RUNNING TensorRT.sample_maskrcnn # ./sample_maskRCNN -d /mnt/DTAA_data/DTAA/code/z662728/optimization/data/
[05/04/2020-09:24:19] [I] Building and running a GPU inference engine for Mask RCNN
[05/04/2020-09:24:21] [E] [TRT] UffParser: Validator error: mrcnn_detection_bboxes: Unsupported operation _SpecialSlice_TRT
&&&& FAILED TensorRT.sample_maskrcnn # ./sample_maskRCNN -d /mnt/DTAA_data/DTAA/code/z662728/optimization/data/

How did you solve it? @rmccorm4 @ShawnNew I would be very grateful if you could please help me :)

Config:
TF-gpu 1.14.0
CUDA 10.0
TensorRT: 6.0.1.5
Keras 2.1.3

Thanks!

**Comment by Apsu95** [comment] 2020-06-04 08:29
Hello all,

Another try with a different configuration:
I successfully converted my model to UFF. When I run the sample, I get the same error:

&&&& RUNNING TensorRT.sample_maskrcnn # ./sample_maskRCNN -d /mnt/DTAA_data/DTAA/code/z662728/optimization/data/
[05/04/2020-09:24:19] [I] Building and running a GPU inference engine for Mask RCNN
[05/04/2020-09:24:21] [E] [TRT] UffParser: Validator error: mrcnn_detection_bboxes: Unsupported operation _SpecialSlice_TRT
&&&& FAILED TensorRT.sample_maskrcnn # ./sample_maskRCNN -d /mnt/DTAA_data/DTAA/code/z662728/optimization/data/

How did you solve it? @gemmit  I would be very grateful if you could please help me :)

Config:
TF-gpu 1.9
CUDA 9.0
TensorRT: 6.0.1.5
Keras 2.1.3
python 3.6.10

Thanks!

**Comment by qualia0000** [comment] 2020-06-17 08:10
> Running up, I got the error：
> [08/19/2019-16:29:24] [I] Building and running a GPU inference engine for Mask RCNN
> [08/19/2019-16:29:34] [E] [TRT] UffParser: Validator error: fpn_p3upsampled: Unsupported operation _ResizeNearest_TRT
> 
> windows 10
> TensorRT 6.x zip install

Hello. May I know if you have solved the problem? I met the exact same error as yours under TRT6.x, Win10.

**Comment by pra-dan** [comment] 2021-08-30 09:46
I think I figured it out. The problem arises in the model conversion from `h5` to `uff`. When converted using Tf1.15-gpu, I got no such error.

A comparison between both methods: 

## undesired _AddV2
<img width="1115" alt="Screenshot 2021-08-30 at 3 14 15 PM" src="https://user-images.githubusercontent.com/46529961/131320655-f4206f15-231b-4bdd-9427-c3ab0e379561.png">

## _AddV2 converted to binary automatically by TF1.15 (I guess)
<img width="1189" alt="Screenshot 2021-08-30 at 3 15 04 PM" src="https://user-images.githubusercontent.com/46529961/131320651-d301c3f4-777a-4e63-b427-0d6b880e1d90.png">
