### ISSUE TITLE
Why does shuffle layer occur after argmax ?

### ISSUE THREAD

**Issue by lix19937** [NVIDIA/TensorRT#3030] opened 2023-06-01 15:45 UTC
## Description

I found **argmax** layer (when axis =1,  input shape is **nchw**) which will **auto generate a shuffle layer**, and sometime **no shuffle layer** occur after argmax.   See follow img:  

* layer info   
![shuffle](https://github.com/NVIDIA/TensorRT/assets/38753233/4bfacecd-9ce9-4c45-aa59-6184ae9d0502)

* time profile of each layer   
```
[05/11/2023-00:05:16] [I]                                                                                 ArgMax_727       42.12           0.3215      1.3
[05/11/2023-00:05:16] [I]                                                             (Unnamed Layer* 675) [Shuffle]        0.00           0.0000      0.0
[05/11/2023-00:05:16] [I]                                                                                 ArgMax_726       35.71           0.2726      1.1
[05/11/2023-00:05:16] [I]                                                             (Unnamed Layer* 673) [Shuffle]        3.41           0.0260      0.1
[05/11/2023-00:05:16] [I]                                                                                 ArgMax_725       41.94           0.3201      1.3
[05/11/2023-00:05:16] [I]                                                             (Unnamed Layer* 671) [Shuffle]        3.39           0.0259      0.1
[05/11/2023-00:05:16] [I]                                                                                 ArgMax_723       74.10           0.5657      2.3
[05/11/2023-00:05:16] [I]                                                             (Unnamed Layer* 667) [Shuffle]        3.58           0.0273      0.1
[05/11/2023-00:05:16] [I]                                                                          ConvTranspose_197       44.76           0.3417      1.4
[05/11/2023-00:05:16] [I]                                     Reformatting CopyNode for Input Tensor 0 to ArgMax_724       13.34           0.1019      0.4
[05/11/2023-00:05:16] [I]                                                                                 ArgMax_724       57.13           0.4361      1.8
[05/11/2023-00:05:16] [I]                                                             (Unnamed Layer* 669) [Shuffle]        3.54           0.0270      0.1
```

I guess argmax (axis =1) process flow:  permute (nchw -> nhwc)  --> argmax       
Why does shuffle layer occur after argmax, and sometimes not ? 

## Environment

**TensorRT Version**:v8410

**NVIDIA GPU**:Orin

**CUDA Version**:11.4

**CUDNN Version**:11.6

**Comment by zerollzeng** [comment] 2023-06-04 14:11
I think this should be the reason: https://github.com/onnx/onnx-tensorrt/blob/6ba67d3428e05f690145373ca87fb8d32f98df45/builtin_op_importers.cpp#L4572

@ttyio @kevinch-nv  Should we improve this? I remember this cause our ResNet50.onnx can not fully offload to DLA.

**Comment by zerollzeng** [comment] 2023-06-05 08:34
Wait, this should be a TopK Layer?

**Comment by lix19937** [comment] 2023-06-05 11:06
@zerollzeng  Yes, I am typo earlier, I means **argmax** op, see img.

**Comment by lix19937** [comment] 2023-06-12 11:26
@zerollzeng  Thanks for your reply, I upload a buildlog
[build_log.txt](https://github.com/NVIDIA/TensorRT/files/11722150/build_log.txt)
 (by trt8410)
,  and I found that if I use trt8510, there is no phenomenon of `shuffle layer occur after argmax`.

**Comment by zerollzeng** [comment] 2023-06-12 14:50
Looks like a fixed issue then, but still would be good if you can provide a reproduce so I can double-check it's also fixed in the latest codebase.

**Comment by lix19937** [comment] 2023-06-12 15:07
@zerollzeng    A TRT verbose log is  [build_log.txt](https://github.com/NVIDIA/TensorRT/files/11722150/build_log.txt)  here , you can find  `shuffle layer occur after argmax`.

**Comment by zerollzeng** [comment] 2023-06-16 02:00
https://user-images.githubusercontent.com/38753233/242655475-4bfacecd-9ce9-4c45-aa59-6184ae9d0502.png

Oh I think the shuffle here is a noop, afterall it's just a reshape, so it doesn't do anything here, @ttyio am I correct?

**Comment by ttyio** [comment] 2023-06-20 18:02
Yes. For `argmax` with `keepdims = 0`, we will also squeeze the dims see https://github.com/onnx/onnx-tensorrt/blob/6ba67d3428e05f690145373ca87fb8d32f98df45/onnx2trt_utils.cpp#L159, and in newer TRT version, this squeeze is optimized away since the memory layout not changed. Thanks.

**Comment by ttyio** [comment] 2023-06-20 18:04
closing since this is optimized away since TRT8.5, thanks all!

**Closed by ttyio** 2023-06-20 18:04 UTC
Labels: triaged
