### ISSUE TITLE
EfficientNMS_TRT not working on jetson nano (TensorRT 8.0.1)

### ISSUE THREAD

**Issue by mokpo4550** [NVIDIA/TensorRT#1538] opened 2021-10-07 09:32 UTC
## Description

An error occurred while converting the EfficientDet D0 512x512 model provided by TFOD2 to onnx and building with the trt engine.

## Environment

**TensorRT Version**: 8.0.1
**NVIDIA GPU**: Jetson Nano 4GB
**NVIDIA Driver Version**: 
**CUDA Version**: 10.2
**CUDNN Version**: 8.2.1
**Operating System**: Ubuntu 18.04
**Python Version (if applicable)**: 3.6.9
**Tensorflow Version (if applicable)**: 2.5.0+nv21.7
** ONNX Version (if applicable)**: 1.9.0
**Baremetal or Container (if so, version)**: 

## Relevant Files
Tensorflow 2 Object Detection Zoo : https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

Reference : https://github.com/pskiran1/TensorRT-support-for-Tensorflow-2-Object-Detection-Models

EfficientDet D0 512x512 saved_model : https://drive.google.com/file/d/17NAifAnnrumYmrQ1M-zByBYd0ftF9E87/view?usp=sharing
EfficientDet D0 512x512 onnx file (using EfficientNMS_TRT) : https://drive.google.com/file/d/1Rzvr6GYLltXq0KtXJ4URHFfBk9ARY9zH/view?usp=sharing
EfficientDet D0 512x512 onnx file (using BatchedNMS_TRT) : https://drive.google.com/file/d/1nSGWCRe9fKNo-kGkUlBuwp5fx4Gt1ku5/view?usp=sharing
EfficientDet D0 512x512 tensorrt file (using EfficientNMS_TRT, from Xavier NX) : https://drive.google.com/file/d/1bY6L1vaKUjQyDPfQ_gdDdauArbZGbLYi/view?usp=sharing

SSD MobileNet V2 (TFOD2) saved_model : https://drive.google.com/file/d/1ZTcg3dsiHwJYb1bF8qwnP_2SGjlDYqJ9/view?usp=sharing
SSD MobileNet V2 (TFOD2) onnx file (using EfficientNMS_TRT) : https://drive.google.com/file/d/1D3pZFfMQbIKo3ym1E8TNpj6CS8uvpU8-/view?usp=sharing

## Screenshot
[Jetson Nano]
![image](https://user-images.githubusercontent.com/32153007/136358382-6eba1986-451b-44ac-ad57-c2c91eda63d1.png)

[Jetson Xavier NX]
![image](https://user-images.githubusercontent.com/32153007/136358450-2232430c-09c1-4582-9989-b4c4498f3041.png)

## Steps To Reproduce

I downloaded the EfficientDet D0 512x512 model from TFOD2 Zoo and exported it in saved_model format.
<pre><code>python exporter_main_v2.py \
    --input_type image_tensor \
    --trained_checkpoint_dir efficientdet_d0_coco17_tpu-32/checkpoint \
    --pipeline_config_path efficientdet_d0_coco17_tpu-32/pipeline.config \
    --output_directory effdet_512x512_export
</code></pre>

Convert exported saved_model to onnx format.
<pre><code>cd samples/python/efficientdet/

python3 create_onnx.py \
    --input_shape '1,512,512,3' \
    --saved_model ./effdet_512x512_export/saved_model \
    --onnx ./model.onnx
</code></pre>
    
Run build_engine.py to convert the onnx model to the trt engine.

<pre><code>python3 build_engine.py \
    --onnx ./model.onnx \
    --engine ./model.trt \
    --precision fp16
</code></pre>

But when the build is almost finished, the following error is displayed.
(The same problem occurs when using other tools such as trtexec)
<pre>
[TensorRT] ERROR: 2: [pluginV2DynamicExtRunner.cpp::execute::115] Error Code 2: Internal Error (Assertion status == kSTATUS_SUCCESS failed.)
Traceback (most recent call last):
  File "build_engine.py", line 240, in <module>
    main(args)
  File "build_engine.py", line 212, in main
    args.calib_batch_size)
  File "build_engine.py", line 203, in create_engine
    with self.builder.build_engine(self.network, self.config) as engine, open(engine_path, "wb") as f:
AttributeError: __enter__
</pre>

What's even more strange is that it was built without any problems at Jetson Xavier NX. (same Jetpack, tensorrt version)

So, just in case, I tried an example of converting SSD MobileNet V2 (TFOD2) to TensorRT from another open source (using EfficientNMS_TRT), but the same symptom that the build did not work properly only in Nano was confirmed.

Reference : https://github.com/pskiran1/TensorRT-support-for-Tensorflow-2-Object-Detection-Models

This problem did not occur if BatchedNMS_TRT was used instead of EfficientNMS_TRT by giving the --legacy_plugins option when creating the onnx file in create_onnx.py.

<pre><code>python3 create_onnx.py \
    --input_shape '1,512,512,3' \
    --saved_model ./effdet_512x512_export/saved_model \
    --onnx ./model.onnx \
    --legacy_plugins
</code></pre>

Can anyone help with this problem?

**Comment by Berk183** [comment] 2021-10-11 06:34
Hi, I am getting similar error to yours. I created the trt engine but when I used that for inference I get (assertion status=kstatus_success failed) error.  Did you find any solutions to it ? Also, did you modify create_onnx.py file because on mine I it does not accepts any option like --legacy_plugins

**Comment by Berk183** [comment] 2021-10-11 06:34
Also I am using SSD_mobilenet v2 320x320 from tensorflow object detection model zoo

**Comment by thiemoToadi** [comment] 2021-11-02 10:30
Running into the same issues on my jetson with efficientdet_d0 when building the engine. Anyone got it working yet?

**Comment by Berk183** [comment] 2021-11-02 12:26
Nope, I don't know why but EfficientNMS plugin is not working on jetson nano. I just used Batched NMS plugin instead of that

**Comment by thiemoToadi** [comment] 2021-11-05 15:41
@Berk183 Did you get SSD_mobilenet V2 320x320 from tfod model zoo working? And if so how did you do it exactly?

**Comment by GreyZzzzzzXh** [comment] 2021-11-23 06:26
Has anyone found the root cause? I also encountered this error on TX2 (assertion status=kstatus_success failed), but there is no problem on both 1080 ti and 2080 ti.

**Comment by mezdahun** [comment] 2021-11-26 12:23
Did anyone find a solution? Running into the same error with ssd mobilenet v2 fpnlite 320x320!

Anyone have seen a fine tuned tf2 OD model successfully converted and built (saved_model -> onnx -> trt) on a jetson nano at all? If so, could you please let me know which model worked from the tf2 OD library?

**Comment by mezdahun** [comment] 2021-11-27 12:43
@Berk183 It looks like the  ´--legacy-plugins´ flag is provided in a modified ´create_onnx.py´ from the TensorRT repo (https://github.com/NVIDIA/TensorRT/blob/master/samples/python/efficientdet/create_onnx.py) according to this issue: https://forums.developer.nvidia.com/t/centernet-mobilenet-v2-from-tfod-failure-when-converting-onnx-to-trt/183972

might worth a try to create the converted onnx file with this one.  I check if it solves our rpoblem.

**Comment by mezdahun** [comment] 2021-11-27 16:04
https://forums.developer.nvidia.com/t/tf2od-on-jetson-nano-4gb-tf-onnx-trt-seemingly-not-supported-due-to-tensorrt-version/196389

**Comment by ntakouris** [comment] 2021-12-06 13:35
Using latest `nvcr.io/nvidia/pytorch:21.11-py3`, this breaks too (no `--legacy-plugins`)

**Comment by franferraz98** [comment] 2021-12-15 12:55
Hi! I've just run into this same issue. Has anyone been able to make a SSD Mobilenet V2 or Faster RCNN Inception V2 with TensorRT to work on Jetson Nano?

> Nope, I don't know why but EfficientNMS plugin is not working on jetson nano. I just used Batched NMS plugin instead of that

Can you explain how did you do this? I tried to combine [this code](https://github.com/NVIDIA/TensorRT/blob/master/samples/python/efficientdet/create_onnx.py) with [this code](https://github.com/pskiran1/TensorRT-support-for-Tensorflow-2-Object-Detection-Models/blob/main/create_onnx.py) so I could use the --legacy_plugins flag, but I'm failing to do so.

Thank you!

**Comment by ntakouris** [comment] 2021-12-20 14:44
It seems that on [Release 8.2.1](https://github.com/NVIDIA/TensorRT/releases/tag/8.2.1), the issue has been fixed.

The problem is that on nvidia container registry, most (if not all containers) have not been updated to the latest one (ex. pytorch).

Current version is `21.11-py3`. I suspect that this follows a monthly release schedule and a fix will be there with tag  `21.12-py3`. Or tag `22.01-py3` at january. 

I have not checked the tensorrt official container which could contain a latest version (or an easily upgradeable one) and I do not wish to switch to a tensorrt only container, installing torch etc from scratch.

**Comment by ntakouris** [comment] 2022-01-05 08:53
Update: It is indeed fixed with the `21.12-py3` release, but the efficient det samples are outdated, possible because google's checkpoints no longer contain old schemas of NMS subgraph -> graphsurgeon can't find some nodes and you get this error:
https://github.com/NVIDIA/TensorRT/issues/1705

**Comment by jinfagang** [comment] 2022-01-26 02:34
@ntakouris Am using efficientnms injected onnx converted to fp16 trt engine, the scores output are abnormal, while boxes and labels are right.

fp32 without any problem, why?

**Comment by mokpo4550** [comment] 2022-01-26 07:53
> @Berk183 Did you get SSD_mobilenet V2 320x320 from tfod model zoo working? And if so how did you do it exactly?

EfficientNMS_TRT was not available on Jetson Nano, so I decided to use BatchedNMS_TRT.

Tensorflow 2 Object Detection Zoo provides a training model called SSD MobileNet v2 320x320.
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md

You need to download this model and export it once in save_model format.
<pre><code>
python3 exporter_main_v2.py \
    --input_type image_tensor \
    --trained_checkpoint_dir "ssd_mobilenet_v2_320x320_coco17_tpu-8/checkpoint/ckpt-0" \
    --pipeline_config_path "ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config" \
    --output_directory "ssd_mobilenet_v2_320x320_coco17_tpu-8_export"
</code></pre>

Export the file created above as an onnx file. (Refer to the address below for the script)
https://gist.github.com/mokpo4550/eb019a674fb21af03f77381c3073d755
https://gist.github.com/mokpo4550/cb2f30bc448dbacb953184b6bf0e9f84
<pre><code>
python3 create_onnx.py \
    --saved_model ssd_mobilenet_v2_320x320_coco17_tpu-8_export/saved_model \
    --pipeline_config ssd_mobilenet_v2_320x320_coco17_tpu-8_export/pipeline.config \
    --onnx ./model.onnx
</code></pre>

Finally, convert onnx file to tensorrt.
<pre><code>
./trtexec --onnx=./model.onnx --saveEngine=./model.engine --verbose --fp16
</code></pre>

I confirmed that this method works on Jetson nano, xavier nx.
Jetpack versions tested with 4.4 (TensorRT 7) and 4.6 (TensorRT 8)

**Comment by arifftrigon** [comment] 2022-01-31 18:31
> > @Berk183 Did you get SSD_mobilenet V2 320x320 from tfod model zoo working? And if so how did you do it exactly?
> 
> EfficientNMS_TRT was not available on Jetson Nano, so I decided to use BatchedNMS_TRT.
> 
> Tensorflow 2 Object Detection Zoo provides a training model called SSD MobileNet v2 320x320. https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
> 
> You need to download this model and export it once in save_model format.
> 
> ```
> python3 exporter_main_v2.py \
>     --input_type image_tensor \
>     --trained_checkpoint_dir "ssd_mobilenet_v2_320x320_coco17_tpu-8/checkpoint/ckpt-0" \
>     --pipeline_config_path "ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config" \
>     --output_directory "ssd_mobilenet_v2_320x320_coco17_tpu-8_export"
> ```
> 
> Export the file created above as an onnx file. (Refer to the address below for the script) https://gist.github.com/mokpo4550/eb019a674fb21af03f77381c3073d755 https://gist.github.com/mokpo4550/cb2f30bc448dbacb953184b6bf0e9f84
> 
> ```
> python3 create_onnx.py \
>     --saved_model ssd_mobilenet_v2_320x320_coco17_tpu-8_export/saved_model \
>     --pipeline_config ssd_mobilenet_v2_320x320_coco17_tpu-8_export/pipeline.config \
>     --onnx ./model.onnx
> ```
> 
> Finally, convert onnx file to tensorrt.
> 
> ```
> /usr/src/tensorrt/bin/trtexec --onnx=./model.onnx --saveEngine=./model.engine --verbose --fp16
> ```
> 
> I confirmed that this method works on Jetson nano, xavier nx. Jetpack versions tested with 4.4 (TensorRT 7) and 4.6 (TensorRT 8)

this is a successful method using batchedNMS. but the kSTATUS_SUCCESS failed error code appear while im trying to do inference using detectnet. any idea why?

**Comment by wraveane** [comment] 2022-02-06 04:22
EfficientNMS should be available on Jetson. However, as was discovered in this issue, the first release unfortunately had an issue on Jetson Nano and Jetson TX1/TX2 -- but not on Jetson Xavier or Xavier NX.

The problem was related to a limit on older architecture devices regarding the maximum registers per thread block. There was already a fix for this problem committed to this repository last July:

https://github.com/NVIDIA/TensorRT/commit/3235cc2ffc04c7819482fe6a512d504843242ad8

I'm not sure when the updated plugin will appear on Jetpack (or if it already did), but you can always build this repository from source to use the latest version, and replace the resulting libnvinfer_plugin.so.8.x.x on your Jetson device.

**Comment by arifftrigon** [comment] 2022-02-07 11:32
> EfficientNMS should be available on Jetson. However, as was discovered in this issue, the first release unfortunately had an issue on Jetson Nano and Jetson TX1/TX2 -- but not on Jetson Xavier or Xavier NX.
> 
> The problem was related to a limit on older architecture devices regarding the maximum registers per thread block. There was already a fix for this problem committed to this repository last July:
> 
> [3235cc2](https://github.com/NVIDIA/TensorRT/commit/3235cc2ffc04c7819482fe6a512d504843242ad8)
> 
> I'm not sure when the updated plugin will appear on Jetpack (or if it already did), but you can always build this repository from source to use the latest version, and replace the resulting libnvinfer_plugin.so.8.x.x on your Jetson device.

I am a little new to this, can u give a clear explanation on how we can apply this fix and build the OSS repo?

**Comment by wraveane** [comment] 2022-02-07 20:02
> I am a little new to this, can u give a clear explanation on how we can apply this fix and build the OSS repo?

Sure. On your Jetson device, clone this repo recursively, build the plugin library, and install it:

```
git clone --recursive https://github.com/NVIDIA/TensorRT
cd TensorRT
mkdir build
cd build
cmake -DGPU_ARCHS=53 -DCMAKE_CUDA_ARCHITECTURES=53 -DCMAKE_C_COMPILER=gcc ..
make nvinfer_plugin
sudo cp -P -v libnvinfer_plugin* /usr/lib/aarch64-linux-gnu
```

Where the "53" in both arguments of the cmake command corresponds to the CUDA architecture of your Jetson device, i.e.:
Jetson Nano: 53
Jetson TX1: 53
Jetson TX2: 62
Jetson Xavier: 72

After you're done, make sure the library linking chain looks correct in /usr/lib/aarch64-linux-gnu:

```
ls -l /usr/lib/aarch64-linux-gnu/libnvinfer_plugin*

libnvinfer_plugin.so -> libnvinfer_plugin.so.8
libnvinfer_plugin.so.8 -> libnvinfer_plugin.so.8.2.3
libnvinfer_plugin.so.8.2.3
```

Where libnvinfer_plugin.so.8.2.3 should be the recently built and copied library.

If you get an error about the minimum cmake version, you will need to install a newer one. The last time I tried it, this procedure worked on Jetson, hopefully it's still valid:

```
cd /opt
sudo mkdir cmake
cd cmake
sudo wget https://github.com/Kitware/CMake/releases/download/v3.20.0-rc5/cmake-3.20.0-rc5-linux-aarch64.sh
sudo bash cmake-3.20.0-rc5-linux-aarch64.sh
# It will ask something about installation path, choose to install it directly in /opt/cmake instead of a subdirectory, or such
echo 'export PATH="/opt/cmake/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
```

**Comment by legalto** [comment] 2022-03-09 22:08
> > I am a little new to this, can u give a clear explanation on how we can apply this fix and build the OSS repo?
> 
> Sure. On your Jetson device, clone this repo recursively, build the plugin library, and install it:
> 
> ```
> git clone --recursive https://github.com/NVIDIA/TensorRT
> cd TensorRT
> mkdir build
> cd build
> cmake -DGPU_ARCHS=53 -DCMAKE_CUDA_ARCHITECTURES=53 -DCMAKE_C_COMPILER=gcc ..
> make nvinfer_plugin
> sudo cp -P -v libnvinfer_plugin* /usr/lib/aarch64-linux-gnu
> ```
> 
> Where the "53" in both arguments of the cmake command corresponds to the CUDA architecture of your Jetson device, i.e.: Jetson Nano: 53 Jetson TX1: 53 Jetson TX2: 62 Jetson Xavier: 72
> 
> After you're done, make sure the library linking chain looks correct in /usr/lib/aarch64-linux-gnu:
> 
> ```
> ls -l /usr/lib/aarch64-linux-gnu/libnvinfer_plugin*
> 
> libnvinfer_plugin.so -> libnvinfer_plugin.so.8
> libnvinfer_plugin.so.8 -> libnvinfer_plugin.so.8.2.3
> libnvinfer_plugin.so.8.2.3
> ```
> 
> Where libnvinfer_plugin.so.8.2.3 should be the recently built and copied library.
> 
> If you get an error about the minimum cmake version, you will need to install a newer one. The last time I tried it, this procedure worked on Jetson, hopefully it's still valid:
> 
> ```
> cd /opt
> sudo mkdir cmake
> cd cmake
> sudo wget https://github.com/Kitware/CMake/releases/download/v3.20.0-rc5/cmake-3.20.0-rc5-linux-aarch64.sh
> sudo bash cmake-3.20.0-rc5-linux-aarch64.sh
> # It will ask something about installation path, choose to install it directly in /opt/cmake instead of a subdirectory, or such
> echo 'export PATH="/opt/cmake/bin:$PATH"' >> ~/.bashrc
> source ~/.bashrc
> ```

Has anyone tried the above? I'm trying to convert efficientdet d0 from onnx to tensorrt? I built nvinfer_plugin from source as shown above, and then installed. When I run:

```
python3 build_engine.py --onnx effdet_d0_tf.onnx --engine effdet_d0_engine.trt 
```
I now get a segmentation fault.

**Comment by franferraz98** [comment] 2022-05-11 11:36
> > @Berk183 Did you get SSD_mobilenet V2 320x320 from tfod model zoo working? And if so how did you do it exactly?
> 
> EfficientNMS_TRT was not available on Jetson Nano, so I decided to use BatchedNMS_TRT.
> 
> Tensorflow 2 Object Detection Zoo provides a training model called SSD MobileNet v2 320x320. https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md
> 
> You need to download this model and export it once in save_model format.
> 
> ```
> python3 exporter_main_v2.py \
>     --input_type image_tensor \
>     --trained_checkpoint_dir "ssd_mobilenet_v2_320x320_coco17_tpu-8/checkpoint/ckpt-0" \
>     --pipeline_config_path "ssd_mobilenet_v2_320x320_coco17_tpu-8/pipeline.config" \
>     --output_directory "ssd_mobilenet_v2_320x320_coco17_tpu-8_export"
> ```
> 
> Export the file created above as an onnx file. (Refer to the address below for the script) https://gist.github.com/mokpo4550/eb019a674fb21af03f77381c3073d755 https://gist.github.com/mokpo4550/cb2f30bc448dbacb953184b6bf0e9f84
> 
> ```
> python3 create_onnx.py \
>     --saved_model ssd_mobilenet_v2_320x320_coco17_tpu-8_export/saved_model \
>     --pipeline_config ssd_mobilenet_v2_320x320_coco17_tpu-8_export/pipeline.config \
>     --onnx ./model.onnx
> ```
> 
> Finally, convert onnx file to tensorrt.
> 
> ```
> /usr/src/tensorrt/bin/trtexec --onnx=./model.onnx --saveEngine=./model.engine --verbose --fp16
> ```
> 
> I confirmed that this method works on Jetson nano, xavier nx. Jetpack versions tested with 4.4 (TensorRT 7) and 4.6 (TensorRT 8)

Hey,

How did you manage to install the TensorFlow Object Detection API? Both tensorflow-addons and tensorflow-text are not supported on Jetson, so I'm stuck on the first step, can't even export the model.

**Comment by wraveane** [comment] 2022-05-19 16:24
It might help to do all the TF Object Detection API tasks from a PC where you have TensorFlow fully installed, create the onnx file there as well. Then just copy the converted onnx file to your Jetson device and build the TensorRT engine on the jetson itself. That way, you don't need to install TensorFlow or any of its dependencies on the device.

**Comment by franferraz98** [comment] 2022-05-20 08:36
Hi @wraveane, 
Yes, I tried that and it worked. My issue now is that I can't run the model that is generated. I'm getting this error:
![image](https://user-images.githubusercontent.com/48053914/169488798-bed83193-35cc-447a-aa8c-4dacf30f0187.png)

Both when I run `inference.py` or `trtexec`. Any ideas on what might be happening?
Thanks!

**Comment by franferraz98** [comment] 2022-05-31 10:13
If anyone is interested in using Jetpack 4.6.1 and Docker, this solution has worked for me: https://forums.developer.nvidia.com/t/cant-execute-trt-engine-on-jetson-nano/214921/2

Thanks for the support!

**Comment by nvpohanh** [comment] 2022-06-15 09:14
closing this issue for now due to >14 days with no response. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-06-15 09:14 UTC
