### ISSUE TITLE
About tensorrt on tx2

### ISSUE THREAD

**Issue by faedtodd** [NVIDIA/TensorRT#16] opened 2019-06-27 04:57 UTC
how cani build tensorrt 5.1.5-open source on tx2

**Comment by xiaoxiaotao** [comment] 2019-06-29 10:53
Do you solve it,please?

**Comment by faedtodd** [comment] 2019-07-01 02:25
> Do you solve it,please?

mei a, xiong di, help

**Comment by rajeevsrao** [comment] 2019-07-01 18:44
This is a duplicate of https://github.com/NVIDIA/TensorRT/issues/9. We are working on it for upcoming release (soon).

**Comment by rmccorm4** [comment] 2020-01-26 00:13
Closing as dup of #9, which was solved: https://github.com/NVIDIA/TensorRT/issues/9#issuecomment-575106079

**Closed by rmccorm4** 2020-01-26 00:13 UTC
Labels: duplicate, hardware, jetson
