### ISSUE TITLE
Tensor (Unnamed Layer* 1022) [PluginV2]_output_0 is uniformly zero; network calibration failed.

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/TensorRT#521] opened 2020-04-29 20:40 UTC
## Environment

**TensorRT Version**: 
6.01
**GPU Type**: 
GeForce GTX 1080 Ti
**Nvidia Driver Version**: 
440
**CUDA Version**: 
10.2
**CUDNN Version**: 
N/A
**Operating System + Version**: 
ubuntu 18.04
**Python Version (if applicable)**: 
3.6.9
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
1.3.0a0+24ae9b5
**Baremetal or Container (if container which image + tag)**: 
nvcr.io/nvidia/pytorch:19.10-py3

## Steps To Reproduce

Applying optimizations and building TRT CUDA engine...
Half2 support requested on hardware without native FP16 support, performance will be negatively affected.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1022) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1025) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_0 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_0 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_2 is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 1026) [PluginV2]_output_2 copy is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 111) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 128) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 146) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 163) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 180) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 198) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 215) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 232) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 248) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 26) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 266) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 283) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 300) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 318) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 335) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 352) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 370) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 387) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 404) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 422) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 43) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 439) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 456) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 472) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 490) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 507) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 524) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 542) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 559) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 576) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 594) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 60) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 611) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 628) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 646) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 663) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 680) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 698) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 715) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 732) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 750) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 76) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 767) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 784) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 8) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 800) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 818) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 835) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 852) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 870) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 887) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 904) [Scale]_output is uniformly zero; network calibration failed.
Tensor (Unnamed Layer* 94) [Scale]_output is uniformly zero; network calibration failed.
Tensor 1004 is uniformly zero; network calibration failed.
Tensor 1019 is uniformly zero; network calibration failed.
Tensor 1033 is uniformly zero; network calibration failed.
Tensor 1047 is uniformly zero; network calibration failed.
Tensor 307 is uniformly zero; network calibration failed.
Tensor 322 is uniformly zero; network calibration failed.
Tensor 336 is uniformly zero; network calibration failed.
Tensor 350 is uniformly zero; network calibration failed.
Tensor 363 is uniformly zero; network calibration failed.
Tensor 378 is uniformly zero; network calibration failed.
Tensor 392 is uniformly zero; network calibration failed.
Tensor 406 is uniformly zero; network calibration failed.
Tensor 421 is uniformly zero; network calibration failed.
Tensor 435 is uniformly zero; network calibration failed.
Tensor 449 is uniformly zero; network calibration failed.
Tensor 464 is uniformly zero; network calibration failed.
Tensor 478 is uniformly zero; network calibration failed.
Tensor 492 is uniformly zero; network calibration failed.
Tensor 505 is uniformly zero; network calibration failed.
Tensor 520 is uniformly zero; network calibration failed.
Tensor 534 is uniformly zero; network calibration failed.
Tensor 548 is uniformly zero; network calibration failed.
Tensor 563 is uniformly zero; network calibration failed.
Tensor 577 is uniformly zero; network calibration failed.
Tensor 591 is uniformly zero; network calibration failed.
Tensor 606 is uniformly zero; network calibration failed.
Tensor 620 is uniformly zero; network calibration failed.
Tensor 634 is uniformly zero; network calibration failed.
Tensor 649 is uniformly zero; network calibration failed.
Tensor 663 is uniformly zero; network calibration failed.
Tensor 677 is uniformly zero; network calibration failed.
Tensor 690 is uniformly zero; network calibration failed.
Tensor 705 is uniformly zero; network calibration failed.
Tensor 719 is uniformly zero; network calibration failed.
Tensor 733 is uniformly zero; network calibration failed.
Tensor 748 is uniformly zero; network calibration failed.
Tensor 762 is uniformly zero; network calibration failed.
Tensor 776 is uniformly zero; network calibration failed.
Tensor 791 is uniformly zero; network calibration failed.
Tensor 805 is uniformly zero; network calibration failed.
Tensor 819 is uniformly zero; network calibration failed.
Tensor 834 is uniformly zero; network calibration failed.
Tensor 848 is uniformly zero; network calibration failed.
Tensor 862 is uniformly zero; network calibration failed.
Tensor 877 is uniformly zero; network calibration failed.
Tensor 891 is uniformly zero; network calibration failed.
Tensor 905 is uniformly zero; network calibration failed.
Tensor 920 is uniformly zero; network calibration failed.
Tensor 934 is uniformly zero; network calibration failed.
Tensor 948 is uniformly zero; network calibration failed.
Tensor 961 is uniformly zero; network calibration failed.
Tensor 976 is uniformly zero; network calibration failed.
Tensor 990 is uniformly zero; network calibration failed.
Writing to MAL_R50fpn_int8.plan...
root@667971367ba3:/workspace/dockerfold/retinanet-examples-mal_export#

**Comment by rmccorm4** [comment] 2020-05-05 23:33
Duplicate of https://github.com/NVIDIA/retinanet-examples/issues/188

Seems like a specific issue with that model. One possible way this could happen is if all inputs to a ReLU were negative, then you'd have all zeros.

**Closed by rmccorm4** 2020-05-05 23:33 UTC
