### ISSUE TITLE
Assertion failed : QTA onnx imported by tensorrt 8 get error 

### ISSUE THREAD

**Issue by Oldpan** [NVIDIA/TensorRT#1293] opened 2021-06-04 12:04 UTC
## Description

I used pytorch quantization to quantize the pytorch model and export to onnx with op-set 13.

This is onnx model's convtranspose op:

<img width="456" alt="WX20210604-195558@2x" src="https://user-images.githubusercontent.com/9389127/120798060-63b85a80-c56f-11eb-84de-8fc62b95095b.png">

When using Tensorrt8 to load the onnx, the parse failed with these. Seems conv is parsed without problem, but convtranspose will get:
```bash
[06/04/2021-11:25:40] [I] [TRT] ----------------------------------------------------------------
[06/04/2021-11:25:40] [E] [TRT] ModelImporter.cpp:738: While parsing node number 737 [ConvTranspose -> "1464"]:
[06/04/2021-11:25:40] [E] [TRT] ModelImporter.cpp:739: --- Begin node ---
[06/04/2021-11:25:40] [E] [TRT] ModelImporter.cpp:740: input: "1458"
input: "1463"
output: "1464"
name: "ConvTranspose_737"
op_type: "ConvTranspose"
attribute {
  name: "dilations"
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "group"
  i: 1
  type: INT
}
attribute {
  name: "kernel_shape"
  ints: 4
  ints: 4
  type: INTS
}
attribute {
  name: "pads"
  ints: 1
  ints: 1
  ints: 1
  ints: 1
  type: INTS
}
attribute {
  name: "strides"
  ints: 2
  ints: 2
  type: INTS
}

[06/04/2021-11:25:40] [E] [TRT] ModelImporter.cpp:741: --- End node ---
[06/04/2021-11:25:40] [E] [TRT] ModelImporter.cpp:744: ERROR: onnx2trt_utils.cpp:2044 In function convDeconvMultiInput:
[6] Assertion failed: (nChannel == -1 || C * ngroup == nChannel) && "The attribute group and the kernel shape misalign with the channel size of the input tensor. "
[06/04/2021-11:25:40] [E] Failed to parse onnx file
[06/04/2021-11:25:40] [E] Parsing model failed
[06/04/2021-11:25:40] [E] Engine creation failed
[06/04/2021-11:25:40] [E] Engine set up failed
```

Want to know the where the problem is, thanks!

## Environment

**TensorRT Version**: 8.0.0 EA
**NVIDIA GPU**: 2080TI
**NVIDIA Driver Version**: 450
**CUDA Version**: 11.0
**CUDNN Version**: 8.0.5
**Operating System**: 
**Python Version (if applicable)**: 
**Tensorflow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 
**Baremetal or Container (if so, version)**:

**Comment by ttyio** [comment] 2021-07-02 07:45
Hello @Oldpan , the message show: 

           The attribute group and the kernel shape misalign with the channel size of the input tensor. 

What the input tensor shape to the convTranspose, and what's the "group" for this node? thanks

**Comment by jiuzhuanzhuan** [comment] 2021-07-02 14:43
> Hello @Oldpan , the message show:
> 
> ```
>        The attribute group and the kernel shape misalign with the channel size of the input tensor. 
> ```
> 
> What the input tensor shape to the convTranspose, and what's the "group" for this node? thanks

I meet the same error. The input tensor shape is (1,3,768,512), group is 1. My nodule just have one conv2d layer and one deconv2d layer.  BTW，if i change the output channel of decon2d the same of input channel , did not meet this error.
```python
from torch import nn

from pytorch_quantization import quant_modules
quant_modules.initialize()
quant_nn.TensorQuantizer.use_fb_fake_quant = True


class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()

    self.conv_block_my1 = nn.Conv2d(3, 32, 3, stride=2, padding=1, bias=True)

    self.upconv_block_my1 = nn.ConvTranspose2d(32, 3, 3, stride=2, padding=1, groups=1, bias=True)

  def forward(self, x):  
    x = self.conv_block_my1(x)
    x = self.upconv_block_my1(x)
    return x
```

**Comment by Oldpan** [comment] 2021-07-05 02:36
@ttyio When input shape is [1,3,1024,1024], the shape of input tensor to the convTranspose is [1,512,32,32].
The group of this node is 1 which is a default value.
But I think this is a bug with quantize ? Because this model structure is right with other conversion.

**Comment by Oldpan** [comment] 2021-07-05 03:05
@ttyio There is another question, I remove the convTranspose of my model and the conversion is no problem, but the model with QAT(QuantizeLinear and DequantizeLinear) is not fast as I expect. 
The `quantize_scale_node` seems realy need some time to finish and I compare the QTA model(with QuantizeLinear and DequantizeLinear) and the FP32 model (with PTQ by TensorRT) . The PTQ TensorRT int8 calibration model is faster than QAT int8 model .
Here is the dumpProfile:
```
[07/01/2021-12:30:42] [I] === Profile (306 iterations ) ===
[07/01/2021-12:30:42] [I]                                                                                                                                   Layer   Time (ms)   Avg. Time (ms)   Time %
[07/01/2021-12:30:42] [I]                                                                                                    QuantizeLinear_2_quantize_scale_node       10.46           0.0342      0.4
[07/01/2021-12:30:42] [I]                      Reformatting CopyNode for Input Tensor 0 to conv1.weight + QuantizeLinear_7_quantize_scale_node + Conv_9 + Relu_11        6.42           0.0210      0.2
[07/01/2021-12:30:42] [I]                                                                  conv1.weight + QuantizeLinear_7_quantize_scale_node + Conv_9 + Relu_11       57.26           0.1871      2.2
[07/01/2021-12:30:42] [I]                                                                                                                              MaxPool_12       50.53           0.1651      1.9
[07/01/2021-12:30:42] [I]                                                                                                   QuantizeLinear_15_quantize_scale_node       17.05           0.0557      0.7
[07/01/2021-12:30:42] [I]                                                       layer1.0.conv1.weight + QuantizeLinear_20_quantize_scale_node + Conv_22 + Relu_24       13.61           0.0445      0.5
[07/01/2021-12:30:42] [I]  Reformatting CopyNode for Input Tensor 0 to layer1.0.conv2.weight + QuantizeLinear_32_quantize_scale_node + Conv_34 + Add_36 + Relu_37        8.48           0.0277      0.3
[07/01/2021-12:30:42] [I]                                              layer1.0.conv2.weight + QuantizeLinear_32_quantize_scale_node + Conv_34 + Add_36 + Relu_37       35.44           0.1158      1.4
[07/01/2021-12:30:42] [I]                                                                                                   QuantizeLinear_40_quantize_scale_node       17.54           0.0573      0.7
[07/01/2021-12:30:42] [I]                                                       layer1.1.conv1.weight + QuantizeLinear_45_quantize_scale_node + Conv_47 + Relu_49       13.96           0.0456      0.5
[07/01/2021-12:30:42] [I]  Reformatting CopyNode for Input Tensor 0 to layer1.1.conv2.weight + QuantizeLinear_57_quantize_scale_node + Conv_59 + Add_61 + Relu_62        8.42           0.0275      0.3
[07/01/2021-12:30:42] [I]                                              layer1.1.conv2.weight + QuantizeLinear_57_quantize_scale_node + Conv_59 + Add_61 + Relu_62       35.95           0.1175      1.4
[07/01/2021-12:30:42] [I]                                                                                                   QuantizeLinear_65_quantize_scale_node       17.32           0.0566      0.7
[07/01/2021-12:30:42] [I]                                                       layer1.2.conv1.weight + QuantizeLinear_70_quantize_scale_node + Conv_72 + Relu_74       14.01           0.0458      0.5
[07/01/2021-12:30:42] [I]  Reformatting CopyNode for Input Tensor 0 to layer1.2.conv2.weight + QuantizeLinear_82_quantize_scale_node + Conv_84 + Add_86 + Relu_87        8.40           0.0275      0.3
[07/01/2021-12:30:42] [I]                                              layer1.2.conv2.weight + QuantizeLinear_82_quantize_scale_node + Conv_84 + Add_86 + Relu_87       35.78           0.1169      1.4
[07/01/2021-12:30:42] [I]                                                                                                   QuantizeLinear_90_quantize_scale_node       17.66           0.0577      0.7
[07/01/2021-12:30:42] [I]                                                       layer2.0.conv1.weight + QuantizeLinear_95_quantize_scale_node + Conv_97 + Relu_99        8.66           0.0283      0.3
[07/01/2021-12:30:42] [I]                                                               layer2.0.conv2.weight + QuantizeLinear_107_quantize_scale_node + Conv_109       14.42           0.0471      0.6
[07/01/2021-12:30:42] [I]                                   layer2.0.downsample.0.weight + QuantizeLinear_118_quantize_scale_node + Conv_120 + Add_122 + Relu_123       14.13           0.0462      0.5
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_126_quantize_scale_node       15.00           0.0490      0.6
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_126_quantize_scale_node       10.13           0.0331      0.4
[07/01/2021-12:30:42] [I]                                                    layer2.1.conv1.weight + QuantizeLinear_131_quantize_scale_node + Conv_133 + Relu_135       11.58           0.0378      0.4
[07/01/2021-12:30:42] [I]                                          layer2.1.conv2.weight + QuantizeLinear_143_quantize_scale_node + Conv_145 + Add_147 + Relu_148       18.14           0.0593      0.7
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_151_quantize_scale_node       14.92           0.0488      0.6
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_151_quantize_scale_node       10.06           0.0329      0.4
[07/01/2021-12:30:42] [I]                                                    layer2.2.conv1.weight + QuantizeLinear_156_quantize_scale_node + Conv_158 + Relu_160       11.80           0.0386      0.5
[07/01/2021-12:30:42] [I]                                          layer2.2.conv2.weight + QuantizeLinear_168_quantize_scale_node + Conv_170 + Add_172 + Relu_173       18.55           0.0606      0.7
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_176_quantize_scale_node       15.17           0.0496      0.6
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_176_quantize_scale_node       10.04           0.0328      0.4
[07/01/2021-12:30:42] [I]                                                    layer2.3.conv1.weight + QuantizeLinear_181_quantize_scale_node + Conv_183 + Relu_185       11.48           0.0375      0.4
[07/01/2021-12:30:42] [I]                                          layer2.3.conv2.weight + QuantizeLinear_193_quantize_scale_node + Conv_195 + Add_197 + Relu_198       18.21           0.0595      0.7
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_201_quantize_scale_node       15.28           0.0500      0.6
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_201_quantize_scale_node       10.40           0.0340      0.4
[07/01/2021-12:30:42] [I]                                                    layer3.0.conv1.weight + QuantizeLinear_206_quantize_scale_node + Conv_208 + Relu_210        8.26           0.0270      0.3
[07/01/2021-12:30:42] [I]                                                               layer3.0.conv2.weight + QuantizeLinear_218_quantize_scale_node + Conv_220       13.55           0.0443      0.5
[07/01/2021-12:30:42] [I]                                   layer3.0.downsample.0.weight + QuantizeLinear_229_quantize_scale_node + Conv_231 + Add_233 + Relu_234        7.42           0.0242      0.3
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_237_quantize_scale_node        8.88           0.0290      0.3
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_237_quantize_scale_node        5.94           0.0194      0.2
[07/01/2021-12:30:42] [I]                                                    layer3.1.conv1.weight + QuantizeLinear_242_quantize_scale_node + Conv_244 + Relu_246       12.29           0.0402      0.5
[07/01/2021-12:30:42] [I]                                          layer3.1.conv2.weight + QuantizeLinear_254_quantize_scale_node + Conv_256 + Add_258 + Relu_259       16.12           0.0527      0.6
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_262_quantize_scale_node        8.96           0.0293      0.3
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_262_quantize_scale_node        5.72           0.0187      0.2
[07/01/2021-12:30:42] [I]                                                    layer3.2.conv1.weight + QuantizeLinear_267_quantize_scale_node + Conv_269 + Relu_271       12.38           0.0404      0.5
[07/01/2021-12:30:42] [I]                                          layer3.2.conv2.weight + QuantizeLinear_279_quantize_scale_node + Conv_281 + Add_283 + Relu_284       16.06           0.0525      0.6
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_287_quantize_scale_node        8.94           0.0292      0.3
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_287_quantize_scale_node        5.92           0.0193      0.2
[07/01/2021-12:30:42] [I]                                                    layer3.3.conv1.weight + QuantizeLinear_292_quantize_scale_node + Conv_294 + Relu_296       12.26           0.0401      0.5
[07/01/2021-12:30:42] [I]                                          layer3.3.conv2.weight + QuantizeLinear_304_quantize_scale_node + Conv_306 + Add_308 + Relu_309       16.00           0.0523      0.6
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_312_quantize_scale_node        8.75           0.0286      0.3
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_312_quantize_scale_node        5.87           0.0192      0.2
[07/01/2021-12:30:42] [I]                                                    layer3.4.conv1.weight + QuantizeLinear_317_quantize_scale_node + Conv_319 + Relu_321       12.04           0.0394      0.5
[07/01/2021-12:30:42] [I]                                          layer3.4.conv2.weight + QuantizeLinear_329_quantize_scale_node + Conv_331 + Add_333 + Relu_334       15.86           0.0518      0.6
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_337_quantize_scale_node        8.60           0.0281      0.3
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_337_quantize_scale_node       10.91           0.0357      0.4
[07/01/2021-12:30:42] [I]                                                    layer3.5.conv1.weight + QuantizeLinear_342_quantize_scale_node + Conv_344 + Relu_346       12.21           0.0399      0.5
[07/01/2021-12:30:42] [I]                                          layer3.5.conv2.weight + QuantizeLinear_354_quantize_scale_node + Conv_356 + Add_358 + Relu_359       16.10           0.0526      0.6
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_362_quantize_scale_node        8.65           0.0283      0.3
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_362_quantize_scale_node        5.79           0.0189      0.2
[07/01/2021-12:30:42] [I]                                                    layer4.0.conv1.weight + QuantizeLinear_367_quantize_scale_node + Conv_369 + Relu_371       10.44           0.0341      0.4
[07/01/2021-12:30:42] [I]                                                               layer4.0.conv2.weight + QuantizeLinear_379_quantize_scale_node + Conv_381       20.28           0.0663      0.8
[07/01/2021-12:30:42] [I]                                   layer4.0.downsample.0.weight + QuantizeLinear_390_quantize_scale_node + Conv_392 + Add_394 + Relu_395        5.08           0.0166      0.2
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_398_quantize_scale_node        5.38           0.0176      0.2
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_398_quantize_scale_node        4.24           0.0138      0.2
[07/01/2021-12:30:42] [I]                                                    layer4.1.conv1.weight + QuantizeLinear_403_quantize_scale_node + Conv_405 + Relu_407       16.48           0.0539      0.6
[07/01/2021-12:30:42] [I]                                          layer4.1.conv2.weight + QuantizeLinear_415_quantize_scale_node + Conv_417 + Add_419 + Relu_420       20.42           0.0667      0.8
[07/01/2021-12:30:42] [I]                                                      Reformatting CopyNode for Input Tensor 0 to QuantizeLinear_423_quantize_scale_node        5.27           0.0172      0.2
[07/01/2021-12:30:42] [I]                                                                                                  QuantizeLinear_423_quantize_scale_node        4.11           0.0134      0.2
[07/01/2021-12:30:42] [I]                                                    layer4.2.conv1.weight + QuantizeLinear_428_quantize_scale_node + Conv_430 + Relu_432       16.98           0.0555      0.7
[07/01/2021-12:30:42] [I]                                          layer4.2.conv2.weight + QuantizeLinear_440_quantize_scale_node + Conv_442 + Add_444 + Relu_445       20.34           0.0665      0.8
```

and the PTQ:
```
[07/01/2021-12:27:29] [I]                                                                                                       Layer   Time (ms)   Avg. Time (ms)   Time %
[07/01/2021-12:27:29] [I]                                                 Reformatting CopyNode for Input Tensor 0 to Conv_0 + Relu_1       19.98           0.0326      1.0
[07/01/2021-12:27:29] [I]                                                                                             Conv_0 + Relu_1       96.17           0.1569      4.8
[07/01/2021-12:27:29] [I]                                                                                                   MaxPool_2       31.84           0.0519      1.6
[07/01/2021-12:27:29] [I]                                                      Reformatting CopyNode for Output Tensor 0 to MaxPool_2       14.24           0.0232      0.7
[07/01/2021-12:27:29] [I]                                                                                             Conv_3 + Relu_4       26.07           0.0425      1.3
[07/01/2021-12:27:29] [I]                                                                                     Conv_5 + Add_6 + Relu_7       29.35           0.0479      1.5
[07/01/2021-12:27:29] [I]                                                                                             Conv_8 + Relu_9       26.61           0.0434      1.3
[07/01/2021-12:27:29] [I]                                                                                  Conv_10 + Add_11 + Relu_12       29.11           0.0475      1.5
[07/01/2021-12:27:29] [I]                                                                                           Conv_13 + Relu_14       26.57           0.0433      1.3
[07/01/2021-12:27:29] [I]                                                                                  Conv_15 + Add_16 + Relu_17       29.24           0.0477      1.5
[07/01/2021-12:27:29] [I]                                                                                           Conv_18 + Relu_19       16.11           0.0263      0.8
[07/01/2021-12:27:29] [I]                                                                                                     Conv_20       22.54           0.0368      1.1
[07/01/2021-12:27:29] [I]                                                                                  Conv_21 + Add_22 + Relu_23       10.99           0.0179      0.5
[07/01/2021-12:27:29] [I]                                                                                           Conv_24 + Relu_25       21.85           0.0356      1.1
[07/01/2021-12:27:29] [I]                                                                                  Conv_26 + Add_27 + Relu_28       22.78           0.0372      1.1
[07/01/2021-12:27:29] [I]                                                                                           Conv_29 + Relu_30       21.89           0.0357      1.1
[07/01/2021-12:27:29] [I]                                                                                  Conv_31 + Add_32 + Relu_33       22.76           0.0371      1.1
[07/01/2021-12:27:29] [I]                                                                                           Conv_34 + Relu_35       21.88           0.0357      1.1
[07/01/2021-12:27:29] [I]                                                                                  Conv_36 + Add_37 + Relu_38       22.56           0.0368      1.1
[07/01/2021-12:27:29] [I]                                                                                           Conv_39 + Relu_40       16.00           0.0261      0.8
[07/01/2021-12:27:29] [I]                                                                                                     Conv_41       22.54           0.0368      1.1
[07/01/2021-12:27:29] [I]                                                                                  Conv_42 + Add_43 + Relu_44        8.13           0.0133      0.4
[07/01/2021-12:27:29] [I]                                                                                           Conv_45 + Relu_46       23.47           0.0383      1.2
[07/01/2021-12:27:29] [I]                                                                                  Conv_47 + Add_48 + Relu_49       23.45           0.0383      1.2
[07/01/2021-12:27:29] [I]                                                                                           Conv_50 + Relu_51       23.78           0.0388      1.2
[07/01/2021-12:27:29] [I]                                                                                  Conv_52 + Add_53 + Relu_54       23.45           0.0383      1.2
[07/01/2021-12:27:29] [I]                                                                                           Conv_55 + Relu_56       23.30           0.0380      1.2
[07/01/2021-12:27:29] [I]                                                                                  Conv_57 + Add_58 + Relu_59       23.37           0.0381      1.2
[07/01/2021-12:27:29] [I]                                                                                           Conv_60 + Relu_61       23.21           0.0379      1.2
[07/01/2021-12:27:29] [I]                                                                                  Conv_62 + Add_63 + Relu_64       23.25           0.0379      1.2
[07/01/2021-12:27:29] [I]                                                                                           Conv_65 + Relu_66       23.25           0.0379      1.2
[07/01/2021-12:27:29] [I]                                                                                  Conv_67 + Add_68 + Relu_69       23.20           0.0379      1.2
[07/01/2021-12:27:29] [I]                                                                                           Conv_70 + Relu_71       19.42           0.0317      1.0
[07/01/2021-12:27:29] [I]                                                                                                     Conv_72       31.23           0.0509      1.6
[07/01/2021-12:27:29] [I]                                                                                  Conv_73 + Add_74 + Relu_75        7.59           0.0124      0.4
[07/01/2021-12:27:29] [I]                                                                                           Conv_76 + Relu_77       31.13           0.0508      1.6
[07/01/2021-12:27:29] [I]                                                                                  Conv_78 + Add_79 + Relu_80       32.20           0.0525      1.6
[07/01/2021-12:27:29] [I]                                                                                           Conv_81 + Relu_82       30.26           0.0494      1.5
[07/01/2021-12:27:29] [I]                                                                                  Conv_83 + Add_84 + Relu_85       31.42           0.0513      1.6
```
QTA model gets 4.6ms and PTQ gets 2.7ms.
I think about if I could the method you used in BERT(use y_scale to compute qMAX and set dynamic value manually) ?
Can this method make model faster and have QTA's accuray?
Thanks for your reply

**Comment by ttyio** [comment] 2021-07-06 01:19
Thanks @jiuzhuanzhuan for the repro, confirmed it is a bug and now fixed internally, hopefully we can merge it back to upstream in next monthly release. 

Hello @Oldpan, From your log, there are a lot of switch from FP32/FP16 to INT8 for the QAT path, but there is only 2 subgraph for the PTQ run. Could you share us both ONNX files? thanks!

**Comment by Oldpan** [comment] 2021-07-06 03:19
@ttyio Thanks for reply.
These are both ONNX files, one is [FP32 normal onnx](https://drive.google.com/file/d/1boifUNmL_GgGzTOPMUXYcneo0Qa48UMu/view?usp=sharing), another is [QTA onnx](https://drive.google.com/file/d/1krZUKCe7L8mneMNzRTfkUPHUDUTFFW3y/view?usp=sharing) with QuantizeLinear and DequantizeLinear

**Comment by ttyio** [comment] 2021-07-06 07:03
Thanks @Oldpan  for the model.

Could you try insert Q/DQ for all the conv residual ?

![image](https://user-images.githubusercontent.com/365590/124556586-07e13a00-de6b-11eb-8b94-db45930451ba.png)

You could follow sample code:
https://github.com/NVIDIA/TensorRT/blob/master/tools/pytorch-quantization/examples/torchvision/models/classification/resnet.py#L123

The reason for doing this is in https://github.com/NVIDIA/TensorRT/blob/master/tools/pytorch-quantization/docs/source/tutorials/quant_resnet50.rst#further-optimization

Thanks

**Comment by jiuzhuanzhuan** [comment] 2021-07-14 13:38
hi @ttyio:
As metion on <https://github.com/NVIDIA/TensorRT/issues/1293#issuecomment-873051351> ，after set the output channel of deconv same as input chandel, QTA onnx model converted to tensorrt smoothly.
But,
1. For Implement the operate of same padding on deconvolution, i set parameters as below in torch.  
```python
torch.nn.ConvTranspose2d(256, 256, 3, stride=2, padding=1, output_padding=1, bias=True)
```
[here](https://drive.google.com/file/d/1KxV2OAA-x5VBprp9IVeWVj2Q4BBgMOFG/view?usp=sharing) is my model. 
The result of inference onnx is correct, but i can't convert onnx to tensorrt. 
The opset  of convert torch to onnx  is 13. TensrtRt version is 8.0.0.3.， GPU are 2080 super.
If i set output_padding as zero, there will be no errors.
```
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +299, GPU +0, now: CPU 318, GPU 270 (MiB)
[TensorRT] VERBOSE: Registered plugin creator - ::GridAnchor_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::GridAnchorRect_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::NMS_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Reorg_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Region_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Clip_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::LReLU_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::PriorBox_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Normalize_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::ScatterND version 1
[TensorRT] VERBOSE: Registered plugin creator - ::RPROI_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::BatchedNMS_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::FlattenConcat_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::CropAndResize version 1
[TensorRT] VERBOSE: Registered plugin creator - ::DetectionLayer_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Proposal version 1
[TensorRT] VERBOSE: Registered plugin creator - ::ProposalLayer_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::PyramidROIAlign_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::ResizeNearest_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::Split version 1
[TensorRT] VERBOSE: Registered plugin creator - ::SpecialSlice_TRT version 1
[TensorRT] VERBOSE: Registered plugin creator - ::InstanceNormalization_TRT version 1
[TensorRT] VERBOSE: Adding network input: input with dtype: float32, dimensions: (1, 256, 48, 32)
[TensorRT] VERBOSE: Registering tensor: input for ONNX tensor: input
[TensorRT] VERBOSE: Importing initializer: upconv_block_my1.weight
[TensorRT] VERBOSE: Importing initializer: upconv_block_my1.bias
[TensorRT] VERBOSE: Parsing node: Constant_0 [Constant]
[TensorRT] VERBOSE: Constant_0 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_0 [Constant] outputs: [3 -> ()], 
[TensorRT] VERBOSE: Parsing node: Constant_1 [Constant]
[TensorRT] VERBOSE: Constant_1 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_1 [Constant] outputs: [4 -> ()], 
[TensorRT] VERBOSE: Parsing node: QuantizeLinear_2 [QuantizeLinear]
[TensorRT] VERBOSE: Searching for input: input
[TensorRT] VERBOSE: Searching for input: 3
[TensorRT] VERBOSE: Searching for input: 4
[TensorRT] VERBOSE: QuantizeLinear_2 [QuantizeLinear] inputs: [input -> (1, 256, 48, 32)], [3 -> ()], [4 -> ()], 
[TensorRT] VERBOSE: Registering tensor: 5 for ONNX tensor: 5
[TensorRT] VERBOSE: QuantizeLinear_2 [QuantizeLinear] outputs: [5 -> (1, 256, 48, 32)], 
[TensorRT] VERBOSE: Parsing node: Constant_3 [Constant]
[TensorRT] VERBOSE: Constant_3 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_3 [Constant] outputs: [6 -> ()], 
[TensorRT] VERBOSE: Parsing node: Constant_4 [Constant]
[TensorRT] VERBOSE: Constant_4 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_4 [Constant] outputs: [7 -> ()], 
[TensorRT] VERBOSE: Parsing node: DequantizeLinear_5 [DequantizeLinear]
[TensorRT] VERBOSE: Searching for input: 5
[TensorRT] VERBOSE: Searching for input: 6
[TensorRT] VERBOSE: Searching for input: 7
[TensorRT] VERBOSE: DequantizeLinear_5 [DequantizeLinear] inputs: [5 -> (1, 256, 48, 32)], [6 -> ()], [7 -> ()], 
[TensorRT] VERBOSE: Registering tensor: 8 for ONNX tensor: 8
[TensorRT] VERBOSE: DequantizeLinear_5 [DequantizeLinear] outputs: [8 -> (1, 256, 48, 32)], 
[TensorRT] VERBOSE: Parsing node: Constant_6 [Constant]
[TensorRT] VERBOSE: Constant_6 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_6 [Constant] outputs: [9 -> ()], 
[TensorRT] VERBOSE: Parsing node: Constant_7 [Constant]
[TensorRT] VERBOSE: Constant_7 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_7 [Constant] outputs: [10 -> ()], 
[TensorRT] VERBOSE: Parsing node: QuantizeLinear_8 [QuantizeLinear]
[TensorRT] VERBOSE: Searching for input: upconv_block_my1.weight
[TensorRT] VERBOSE: Searching for input: 9
[TensorRT] VERBOSE: Searching for input: 10
[TensorRT] VERBOSE: QuantizeLinear_8 [QuantizeLinear] inputs: [upconv_block_my1.weight -> (256, 256, 3, 3)], [9 -> ()], [10 -> ()], 
[TensorRT] VERBOSE: Registering layer: upconv_block_my1.weight for ONNX node: upconv_block_my1.weight
[TensorRT] VERBOSE: Registering tensor: 11 for ONNX tensor: 11
[TensorRT] VERBOSE: QuantizeLinear_8 [QuantizeLinear] outputs: [11 -> (256, 256, 3, 3)], 
[TensorRT] VERBOSE: Parsing node: Constant_9 [Constant]
[TensorRT] VERBOSE: Constant_9 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_9 [Constant] outputs: [12 -> ()], 
[TensorRT] VERBOSE: Parsing node: Constant_10 [Constant]
[TensorRT] VERBOSE: Constant_10 [Constant] inputs: 
[TensorRT] VERBOSE: Constant_10 [Constant] outputs: [13 -> ()], 
[TensorRT] VERBOSE: Parsing node: DequantizeLinear_11 [DequantizeLinear]
[TensorRT] VERBOSE: Searching for input: 11
[TensorRT] VERBOSE: Searching for input: 12
[TensorRT] VERBOSE: Searching for input: 13
[TensorRT] VERBOSE: DequantizeLinear_11 [DequantizeLinear] inputs: [11 -> (256, 256, 3, 3)], [12 -> ()], [13 -> ()], 
[TensorRT] VERBOSE: Registering tensor: 14 for ONNX tensor: 14
[TensorRT] VERBOSE: DequantizeLinear_11 [DequantizeLinear] outputs: [14 -> (256, 256, 3, 3)], 
[TensorRT] VERBOSE: Parsing node: ConvTranspose_12 [ConvTranspose]
[TensorRT] VERBOSE: Searching for input: 8
[TensorRT] VERBOSE: Searching for input: 14
[TensorRT] VERBOSE: Searching for input: upconv_block_my1.bias
[TensorRT] VERBOSE: ConvTranspose_12 [ConvTranspose] inputs: [8 -> (1, 256, 48, 32)], [14 -> (256, 256, 3, 3)], [upconv_block_my1.bias -> (256)], 
[TensorRT] VERBOSE: Convolution input dimensions: (1, 256, 48, 32)
Segmentation fault (core dumped)
```

2. Why deconvolution op did not speed up running on int8 compared with running on fp16 ? 
Ignore the error above, when i set output_padding to zero,  inferenced on tensorrt, the time of QTA int8 did not fast then fp16.

When set input shape as (1,256, 136,256), the inference time of int8 and fp16 are  0.0029042790499515833s, 0.002218980330042541s respectively. 
 
My timing code are：
```python
    tic = perf_counter() 
    for i in range(500):  
        context.execute_async_v2(bindings=bindings, stream_handle=stream.handle)
        stream.synchronize()
    toc = perf_counter()  
    print("speed: ", (toc-tic)/500)
```  
here is my [fp16 engine](https://drive.google.com/file/d/1HoLhd8NZ9WzImwUFyEeVd1UCEi-uRf8H/view?usp=sharing), [int8 engine](https://drive.google.com/file/d/1F8qLzBuJIAhA6hBo7eNI3mgFJ_lcpXs0/view?usp=sharing)
为什么没有变快呢，是我的操作有什么问题么? 还是对反卷积int8加速还不是很好? 卷积我测了int8比fp16快了百分之五十。

**Comment by ttyio** [comment] 2021-07-22 03:13
Hello @jiuzhuanzhuan , sorry for the delay response.

1. currently `convTranspose` in TRT has no support for asymmetric padding, and we are working on this.
2. this is because you only have single layer in your network, we need reformat before and after `convTranspose`, this is necessary when switch from/to int8 and fp32, and this overhead can be reduced in real network when more nodes run in INT8.
3. no, QAT in TRT8 currently designed for ONNX export from https://github.com/NVIDIA/TensorRT/tree/master/tools/pytorch-quantization
4. I believe they are arithmetic rounding issue, and DNNs are robust against perturbation by their nature most of the time. Could you evaluate the accuracy using real data and network benchmark? 

thanks!

**Comment by ttyio** [comment] 2021-09-10 05:52
Closing since no activity for more than 3 weeks, please reopen if you still have question, thanks!

**Closed by ttyio** 2021-09-10 05:52 UTC
Labels: Topic: QAT, triaged, Release: 8.x
