### ISSUE TITLE
TRT exec bug

### ISSUE THREAD

**Issue by tuoeg** [NVIDIA/TensorRT#2063] opened 2022-06-16 14:01 UTC
## Description

dynamic shape TRT execute loss of accuracy,but static shape TRT execute normal

## Environment

**TensorRT Version**: 8.2.3
**NVIDIA GPU**: GTX
**NVIDIA Driver Version**: 465.19.01
**CUDA Version**: 11.3 
**Operating System**: ubuntu
**Python Version**: 3.8.10
**PyTorch Version**: 1.11.0
**onnxruntime Version**: 1.11.0

## Relevant Files

dataset,onnx file,trt file and test script in this respository: https://github.com/tuoeg/issue_test ,please help me solve this problem

## Steps To Reproduce
steps to reproduce also in respository

**Comment by zerollzeng** [comment] 2022-06-16 14:35
BTW can you try TRT 8.4? it might be a fixed issue too.

**Comment by tuoeg** [comment] 2022-06-16 14:53
input shape are same



发自我的iPhone


------------------ Original ------------------
From: Zero Zeng ***@***.***&gt;
Date: Thu,Jun 16,2022 10:35 PM
To: NVIDIA/TensorRT ***@***.***&gt;
Cc: tuoeg ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [NVIDIA/TensorRT] TRT exec bug (Issue #2063)





 
Baidu net disk has a bad download speed, can you upload the dynamic shape onnx model to google drive?
 
Also, when you running your dynamic shape model? does the input shape the same as the static model? and does the input shape match the input shape that you set when you export the model from pytorch to onnx?

**Comment by tuoeg** [comment] 2022-06-16 14:54
Ok,I will try new version



发自我的iPhone


------------------ Original ------------------
From: Zero Zeng ***@***.***&gt;
Date: Thu,Jun 16,2022 10:36 PM
To: NVIDIA/TensorRT ***@***.***&gt;
Cc: tuoeg ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [NVIDIA/TensorRT] TRT exec bug (Issue #2063)





 
BTW can you try TRT 8.4? it might be a fixed issue too.

**Comment by tuoeg** [comment] 2022-06-17 03:00
> BTW can you try TRT 8.4? it might be a fixed issue too.

 we test TRT 8.4，there also have large loss of accuracy in our dynamic shape modle,our dynamic and static onnx modle in google driver：https://drive.google.com/drive/folders/1EjL-bpaDkBBVlhZTSZSSKmv-9_zLpjVH?usp=sharing

**Comment by tuoeg** [comment] 2022-06-17 03:02
> > BTW can you try TRT 8.4? it might be a fixed issue too.
> 
> we test TRT 8.4，there also have large loss of accuracy in our dynamic shape modle,our dynamic and static onnx modle in google driver：https://drive.google.com/drive/folders/1EjL-bpaDkBBVlhZTSZSSKmv-9_zLpjVH?usp=sharing

test script in respository: https://github.com/tuoeg/issue_test

**Comment by tuoeg** [comment] 2022-06-17 11:45
we use avilable small models, found that the small modle selected matmul operate tactic is different.

**Comment by BowenFu** [comment] 2022-06-20 08:26
Confirmed that the accurarcy issue will only happen when building engine without --noTF32 option.
With --noTF32, the max abs tolerance is within 1e-4.

**Comment by nvpohanh** [comment] 2022-06-24 05:54
@BowenFu Do you think this is a TRT issue? Or just TF32 tolerance issue?

@tuoeg Could you disable TF32 and see if the accuracy comes back?

**Comment by BowenFu** [comment] 2022-06-24 06:00
@nvpohanh More like a TF32 tolerance to me.

**Comment by nvpohanh** [comment] 2022-06-24 06:10
Cool. I guess the reason is that at BS=1, the BS is so small that FP32 tactics are chosen. While at BS=6, the BS is large enough for TF32 tactics to be chosen, and thus the accuracy drops. The solution is to disable TF32 from builder config setting. @tuoeg could you give it a try?

**Comment by BowenFu** [comment] 2022-06-24 06:13
@nvpohanh per offline discussion, they have resolved the issue with --noTF32.

**Comment by nvpohanh** [comment] 2022-06-24 06:50
cool! closing this

**Closed by nvpohanh** 2022-06-24 06:50 UTC
Labels: triaged, Accuracy
