### ISSUE TITLE
Cask Error in checkCaskExecError<false>: 7 (Cask Convolution execution)

### ISSUE THREAD

**Issue by aininot260** [NVIDIA/TensorRT#301] opened 2019-12-26 11:25 UTC
When I run my model in TensorRT,it get an error like this:
```
[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (245) - Cask Error in checkCaskExecError<false>: 7 (Cask Convolution execution)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
```

I wonder which condition may lead to this error?
Thanks.

**Comment by aininot260** [comment] 2019-12-26 11:28
I can provide some codes:
https://paste.ubuntu.com/p/qqWdwj28Pt/

**Comment by aininot260** [comment] 2019-12-26 11:36
```
        for binding in self.engine:
            size = trt.volume(self.engine.get_binding_shape(binding)) * \
                   self.engine.max_batch_size

            print('size',size)
            print('binding_shape',self.engine.get_binding_shape(binding))
            print('batch_size',self.engine.max_batch_size)
```
I print some debug infos:
```
[TensorRT] WARNING: TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
size 786432
binding_shape (3, 512, 512)
batch_size 1
size 16384
binding_shape (1, 128, 128)
batch_size 1
size 32768
binding_shape (2, 128, 128)
batch_size 1
size 32768
binding_shape (2, 128, 128)
batch_size 1
size 16384
binding_shape (1, 128, 128)
batch_size 1
size 32768
binding_shape (2, 128, 128)
batch_size 1
size 32768
binding_shape (2, 128, 128)
batch_size 1
```
The input size of network is 512*512*3.
The output size of network is 1*128*128 2*128*128 2*128*128 1*128*128 2*128*128 2*128*128

**Comment by aininot260** [comment] 2019-12-26 11:40
How I use the object is as follows:
```
trt_crossnet = Trtcross()

class CtdetDetector(BaseDetector):
  def __init__(self, opt):
    super(CtdetDetector, self).__init__(opt)

  def process(self, images, return_time=False):
    with torch.no_grad():
      
      output = trt_crossnet.detect(images)
      print(type(images))
      x = torch.from_numpy(output[-3]).sigmoid_()
      y = torch.from_numpy(output[-2])
      z = torch.from_numpy(output[-1])
```
The type of images is:
```
<class 'torch.Tensor'>
```

**Comment by aininot260** [comment] 2019-12-27 02:44
When I downgrade the TensorRT version to 5.1.5.0.It loged like this:
```
[TensorRT] ERROR: CUDA cask failure at execution for trt_maxwell_scudnn_128x128_relu_medium_nn_v1.
[TensorRT] ERROR: cuda/caskConvolutionLayer.cpp (355) - Cuda Error in execute: 400 (invalid resource handle)
[TensorRT] ERROR: cuda/caskConvolutionLayer.cpp (355) - Cuda Error in execute: 400 (invalid resource handle)
```

**Comment by rmccorm4** [comment] 2019-12-29 14:50
Hey @aininot260,

Can you share an ONNX model that reproduces this issue?

**Comment by aininot260** [comment] 2020-01-03 08:57
Sorry,The model is too big and it contains some sensitive infos.
**TensorRT Version**: 5.1.5.0
**GPU Type**: TITAN X Pascal
**Nvidia Driver Version**: 418.87
**CUDA Version**: 10.1
**CUDNN Version**: 7.5.1
**Operating System + Version**: Ubuntu18.04.3 LTS
**Python Version (if applicable)**: 3.6.9
**TensorFlow Version (if applicable)**: 
**PyTorch Version (if applicable)**: 1.2.0
**Baremetal or Container (if container which image + tag)**: 
Is there any other way to experiment?

**Comment by jkjung-avt** [comment] 2020-01-03 12:23
The last time I encountered a similar problem, it was because cuda context was initialized in one thread while TensorRT engine was executed in another thread.  The problem was solved once I moved all cuda init and TensorRT inference code into the same thread. 

Reference:

- https://jkjung-avt.github.io/speed-up-trt-ssd/
- https://devtalk.nvidia.com/default/topic/1056268/tensorrt-do_inference-error/

**Comment by rmccorm4** [comment] 2020-02-15 08:22
I agree with @jkjung-avt's answer above. Hard to say without a repro. It doesn't have to be your specific sensitive model, just any model + scripts that reproduce your error. That error is typically not related to the model itself, but how you're using it i.e. a bug in the inference code. similar to what's described in the previous comment.

Closing for now.

**Closed by rmccorm4** 2020-02-15 08:22 UTC
Labels: API: Python, Parser: ONNX

**Comment by higher127** [comment] 2020-06-04 06:14
I encountered this issue too, it disappeared when I reboot my computer and re-convert onnx model to trt model. But I do not know the root cause.

**Comment by nkhdiscovery** [comment] 2020-09-05 16:08
I faced the same issue, my code simply had a detector class, in the constructor I was creating the cuda context; you have to avoid using pycuda autoinit, and instead create your context separately like: 
`device = cuda.Device(0)
context = device.make_context()`
[see this: https://forums.developer.nvidia.com/t/tensorrt-do-inference-error/77055 , and you may also need a trt engine context too for doing the inference, making cuda context seems only making you able to use the cuda driver from that thread you are in]
I was also allocating buffers in the constructor, and then in another member function of my class, e.g. `inference`, I was doing the inference and faced this problem. The code was simple, I had a class, and in the main I was creating an instance of it and doing my inference, no threads, nothing else.

The solution was simply to move all cuda related stuff into my inference function! Seems the constructor of the class was actually running in somewhere else than the main thread or sth. Anyhow, moving the parts for creating the cuda context and trt engine context into my inference function solved the problem.

**Comment by sharoseali** [comment] 2020-12-17 15:37
> The last time I encountered a similar problem, it was because Cuda context was initialized in one thread while TensorRT engine was executed in another thread. The problem was solved once I moved all cuda init and TensorRT inference code into the same thread.
> 
> Reference:
> 
> * https://jkjung-avt.github.io/speed-up-trt-ssd/
> * https://devtalk.nvidia.com/default/topic/1056268/tensorrt-do_inference-error/

@jkjung-avt  I am working with yolo and implementing CPU base multithreading with tensor rt. I write the code in three separate threads preprocessing, inference, and postprocessing + drawing but when I run the code I get this error as mention  in the issue

`[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (245) - Cask Error in checkCaskExecError<false>: 7 (Cask Convolution execution)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
61.85924134269364
` 
I have to implement it at any cost, Can you guide me that how can I remove this error, You mentioned that the whole tensor RT inference code should be in one thread. If this is the point then, I to do **pre, post-processing**, and **drawing** in the other 2 threads and **inference** in 1 other thread that uses trt engine. I write the code by keeping in mind this thing but getting this error. 
Please guide..... thanks

**Comment by jkjung-avt** [comment] 2020-12-18 02:33
@sharoseali  Sorry, I don't have anything to add about the "Cask Error" besides what I've already posted.  And I'm not able to identify what the problem might be based on your description.

By the way, you could check out, say, https://github.com/jkjung-avt/tensorrt_demos/issues/213 and https://github.com/jkjung-avt/tensorrt_demos/issues/276.  Other people have adopted my [TensorRT yolov4/yolov3 implementation](https://github.com/jkjung-avt/tensorrt_demos#yolov4) and run the code in Flask or other multi-threaded applications.

**Comment by nhphuong91** [comment] 2021-03-04 09:50
I "accidentally" found a temporary fix for this issue. It happens when one added flask to their tensorRT proj which causes the situation that @jkjung-avt mentioned above. Here is a magic that I added to my script for fixing the issue:

> import tensorflow as tf
from tensorflow.python.keras.backend import set_session
sess = tf.compat.v1.Session()
set_session(sess)

**Comment by wduo** [comment] 2021-03-25 15:39
> I "accidentally" discovered a temporary fix for this issue. It happens when one added flask to their tensorRT proj which causes the situation that @jkjung-avt mentioned above. Here is a magic that I added to my script for fixing the issue:
> 
> > import tensorflow as tf
> > from tensorflow.python.keras.backend import set_session
> > sess = tf.compat.v1.Session()
> > set_session(sess)

For pytorch, how to fix this issue, please?

**Comment by nhphuong91** [comment] 2021-03-25 17:34
> > I "accidentally" discovered a temporary fix for this issue. It happens when one added flask to their tensorRT proj which causes the situation that @jkjung-avt mentioned above. Here is a magic that I added to my script for fixing the issue:
> > > import tensorflow as tf
> > > from tensorflow.python.keras.backend import set_session
> > > sess = tf.compat.v1.Session()
> > > set_session(sess)
> 
> For pytorch, how to fix this issue, please?

Did you try to add these dummy scripts to somewhere in your code? My project doesn't use anything from TensorFlow either. But by adding above scripts help fixing this issue (and slow down + consume quite amount of memory)
Just try adding it to somewhere within your project (at the beginning of your code) -> I know, it sounds stupid but it worked for me :))

**Comment by RocaPiedra** [comment] 2022-06-28 12:20
> The last time I encountered a similar problem, it was because cuda context was initialized in one thread while TensorRT engine was executed in another thread. The problem was solved once I moved all cuda init and TensorRT inference code into the same thread.
> 
> Reference:
> 
> * https://jkjung-avt.github.io/speed-up-trt-ssd/
> * https://devtalk.nvidia.com/default/topic/1056268/tensorrt-do_inference-error/

Everything in my code seems to point that my error is this but I'm defining the context and the engine in the same thread... Also, it used to work some time ago but I moved the project and recycled the code (did not change that part) and now it crashes. I probably do something wrong but I cannot realize what it is. This is how I declare the context and the engine, it is within a function that is executed in a posix thread:
```
// Creation of Runtime
IRuntime *runtime = createInferRuntime(gLogger);
// Deserialize the CUDA Engine
ICudaEngine *engine = getCudaEngine(THM_ENGINE_PATH, runtime);
// Create an execution context
IExecutionContext *context = engine->createExecutionContext();
```
After all the setup is done, the loop starts and I do the inference with:
```
doInference(*context, cudaStream, buffers, modelInput, output, BATCH_SIZE, INPUT_WIDTH * INPUT_HEIGHT * 3 * sizeof(float), OUTPUT_WIDTH * OUTPUT_HEIGHT * sizeof(float));
```

I did not try including the dummy code because I'm working in C++ (not sure if in a different language it would help) and I don't have available memory the libraries to import.
