### ISSUE TITLE
3 python processes for 3 GPUs could run, 4 processes for 4GPUs often stuck

### ISSUE THREAD

**Issue by troysung** [NVIDIA/TensorRT#1433] opened 2021-08-04 09:19 UTC
4 GPUs in my server.
In my python program,if 3 processes with same codes are spawned for 3 separate GPUs, things seemingly work fine,runs fast.

But if 4 processes for 4 GPUs each, sometimes stucked,and whole program runs much slower.
It`s related to python interpreter，or the tensorrt?
Hard to explain. Thanks for any reply!
and the code is like this:
   cuda.init()
    device = cuda.Device(gpuNum)
    cfx = device.make_context()

    runtime = trt.Runtime(TRT_LOGGER)
    f = open(trainedEngine, "rb")
    engineSeries = f.read()
    f.close()

    while True:
        engine = runtime.deserialize_cuda_engine(engineSeries)
        context = engine.create_execution_context()
        infer(cfx, engine, context)

**Comment by troysung** [comment] 2021-08-05 05:55
I believe it`s related to the communication between the hidden threads. Can anyone tell me how to debug it?Thanks!

**Comment by nvpohanh** [comment] 2022-06-15 09:44
It may be caused by the Python GIL: https://realpython.com/python-gil/

I would suggest trying with C++ implementation.

**Comment by nvpohanh** [comment] 2022-07-01 06:07
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-07-01 06:07 UTC
Labels: triaged
