### ISSUE TITLE
A little tip for segfault issue in custom_plugin initialize() .

### ISSUE THREAD

**Issue by dhkim0225** [NVIDIA/TensorRT#434] opened 2020-03-15 06:19 UTC
### This issue is just for sharing a tip.

Hello TRT users,

Recently, I had a issue with custom_plugin initialize() function. 
There was a segfault error with ```cudaMemcpy()```.
Segfault error means you have a host memory error.

And it was caused by my little(?) mistake.

#### build_engine.py
```python
def define_network(builder, args, cfg, plugins):
    explicit_batch = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    network = builder.create_network(explicit_batch)
    define_mbert(network, args, cfg, plugins)   # FOCUS
    return network

def main(args):
    cfg = load_config(args.config_file)
    builder = get_builder(args)
    plugins = get_plugins()
    network = define_network(builder, args, cfg, plugins)   # FOCUS
    profiles = get_profiles(builder, args, cfg)
    config = get_config(builder, profiles, args)
    engine = builder.build_engine(network, config)
    with open(args.out_engine_path, "wb") as f:
        f.write(engine.serialize())
```

#### model.py
```python
def define_mbert(net, args, cfg, plugins):
    w_dict = get_weights(args.weight_pth_file)   # FOCUS
    inps = _get_inputs(net, inp_len=cfg['max_position_embeddings'])
    embedded, inp_mask = embedding(net, w_dict, args, plugins, inps)
    enc_out = bert(net, w_dict, args, cfg, embedded, inps[2], plugins)
    net.mark_output(enc_out)
```

#### build_engine.py
```python
def define_network(builder, w_dict, args, cfg, plugins):
    explicit_batch = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)
    network = builder.create_network(explicit_batch)
    define_mbert(network, w_dict, args, cfg, plugins)   # FOCUS
    return network

def main(args):
    cfg = load_config(args.config_file)
    builder = get_builder(args)
    plugins = get_plugins()
    w_dict = get_weights(args.weight_pth_file)   # FOCUS
    network = define_network(builder, w_dict, args, cfg, plugins)   # FOCUS
    profiles = get_profiles(builder, args, cfg)
    config = get_config(builder, profiles, args)
    engine = builder.build_engine(network, config)
    with open(args.out_engine_path, "wb") as f:
        f.write(engine.serialize())
```

#### model.py
```python
def define_mbert(net, w_dict, args, cfg, plugins):
    inps = _get_inputs(net, inp_len=cfg['max_position_embeddings'])
    embedded, inp_mask = embedding(net, w_dict, args, plugins, inps)
    enc_out = bert(net, w_dict, args, cfg, embedded, inps[2], plugins)
    net.mark_output(enc_out)
```

Can you see?
Yup, in my case, segfault issue was caused by **lifetime of w_dict.** 
w_dict was deallocated automatically before builder::buildCudaEngine() call and segfault occured since **C 's void pointer also use same memory address.**

I hope this little tip helps someone.

Regards,
Anthony.

**Comment by rmccorm4** [comment] 2020-03-15 22:33
Thanks for sharing @dhkim0225!

Maybe that's related to this observation as well: https://github.com/NVIDIA/TensorRT/issues/238#issuecomment-598466238

Perhaps the issue is from the `PluginFieldCollection`s going out of scope, and a mishandling between the C++ / Python layers.

**Comment by kevinch-nv** [comment] 2020-08-25 21:00
Thanks @dhkim0225 for the tip. Closing this issue.

**Closed by kevinch-nv** 2020-08-25 21:00 UTC
Labels: API: Python, good-reference
