### ISSUE TITLE
Converting onnx to trt engine ("weights and output must be in same phylum")

### ISSUE THREAD

**Issue by dvirla** [NVIDIA/TensorRT#1963] opened 2022-05-02 08:59 UTC
## Description

I'm following the notebook for converting pytorch model into trt engine and getting the following error when trying trtexec:

[05/02/2022-11:31:38] [I] Finish parsing network model
[05/02/2022-11:31:38] [E] Error[2]: [constantNode.cpp::checkSanity::15] Error Code 2: Internal Error (Assertion phylum(params.weights.type()) == phylum(*outputs[0]) failed. weights and output must be in same phylum)
[05/02/2022-11:31:38] [E] Error[2]: [builder.cpp::buildSerializedNetwork::619] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
[05/02/2022-11:31:38] [E] Engine could not be created from network

This happens both with my wanted model but also with resnet50 as showed in the notebook.

## Environment

**TensorRT Version**: 8.4.0.6
**NVIDIA GPU**: RTX3090
**NVIDIA Driver Version**: 510.47.03
**CUDA Version**: 11.6
**CUDNN Version**:  8.4.0.27
**Operating System**: Ubuntu 20.04
**Python Version**: 3.8.10
**PyTorch Version**:  1.11.0+cu113

## Relevant Files

https://github.com/NVIDIA/TensorRT/blob/master/quickstart/IntroNotebooks/4.%20Using%20PyTorch%20through%20ONNX.ipynb

## Steps To Reproduce

Just following cell by cell in this notebook:
https://github.com/NVIDIA/TensorRT/blob/master/quickstart/IntroNotebooks/4.%20Using%20PyTorch%20through%20ONNX.ipynb

should reproduce my issue.

**Comment by dvirla** [comment] 2022-05-10 07:14
@ttyio @pbridger @aaronp24 @lukeyeager  Can anyone please assist?

**Comment by galagam** [comment] 2022-05-12 14:09
Was not able to reproduce on either TensorRT 8.2 or 8.4. 
Please attempt to reproduce using this shortened version of the linked notebook:

ONNX generation: 
`import torchvision.models as models
import torch
import torch.onnx

# load the pretrained model
resnet50 = models.resnet50(pretrained=True, progress=False).eval()

BATCH_SIZE=32

dummy_input=torch.randn(BATCH_SIZE, 3, 224, 224)


# export the model to ONNX
torch.onnx.export(resnet50, dummy_input, "resnet50_pytorch.onnx", verbose=False)
`
trtexec:
`$trtexec --onnx=resnet50_pytorch.onnx --saveEngine=resnet_engine_pytorch.trt  --explicitBatch --inputIOFormats=fp16:chw --outputIOFormats=fp16:chw --fp16`

**Comment by nvpohanh** [comment] 2022-07-01 06:36
Closing due to >14 days without activity. Please feel free to reopen if the issue still exists. Thanks

**Closed by nvpohanh** 2022-07-01 06:36 UTC
Labels: needs-info, Samples, Step: Builder, triaged, Release: 8.x
